### ISSUE TITLE
Set WM_URGENT on bell

### ISSUE THREAD

**Issue by dkasak** [kovidgoyal/kitty#1016]
Could kitty set X11's urgent bit for the window (`WM_URGENT`) when the bell character is displayed and `window_alert_on_bell` is set? I've noticed #51 but this issue seems to be about something else.

**Comment by kovidgoyal** [comment]
It requests attention already, see window_alert_on_bell in kitty.conf. I dont recall exactly what it does under X11, but it uses the glfwRequestWindowAttention function, you'll have to look at the glfw source code for what that does.

**Comment by dkasak** [comment]
Just in case someone finds this, `glfwRequestWindowAttention` appears to set `_NET_WM_STATE_DEMANDS_ATTENTION` which doesn't work for me for some reason on xmonad (while setting the urgent bit does).

**Comment by lierdakil** [comment]
A bit of necroposting, but I've run into this issue today.

Apparently, glfw expects an EWMH-compliant window manager and also it expects to see all `_NET_WM_*` atoms in supported atoms. XMonad's  [`ewmh` hook](http://hackage.haskell.org/package/xmonad-contrib/docs/XMonad-Hooks-EwmhDesktops.html) doesn't actually add `_NET_WM_STATE` and `_NET_WM_STATE_DEMANDS_ATTENTION`. Thankfully, it's XMonad, so it's easy enough to hack in.

Adding a call to this function to `startupHook` helps (notice: this _must_ be run _after_ ewmh startup hook -- if you're using `ewmh` function to set up ewmh hooks, it should be fine, since it prepends all its hooks to the config, but I think it bears mentioning none the less):
```haskell
fixSupportedAtoms :: X ()
fixSupportedAtoms = withDisplay $ \dpy -> do
    r <- asks theRoot
    a <- getAtom "_NET_SUPPORTED"
    c <- getAtom "ATOM"
    supp <- mapM getAtom [ "_NET_WM_STATE"
                         , "_NET_WM_STATE_DEMANDS_ATTENTION"
                         ]
    io $ changeProperty32 dpy r a c propModeAppend (fmap fromIntegral supp)
```
