### ISSUE TITLE
How to get warnings before closing multiple tabs of kitty?

### ISSUE THREAD

**Issue by aranmohyeddin** [kovidgoyal/kitty#1023]
I use awesome window manager and It has a shortcut windows+shift+c for closing an application and sometimes I issue that command without noticing what window has the view and then I close kitty with multiple tabs. how can I get a warning if I want to close a kitty instance with multiple tabs/windows? Like in firefox.

**Comment by kovidgoyal** [comment]
I'm afraid kitty has no such functionality, as I am not a fan of these warning popups. But I'll be happy to accept a patch to add an option for such a warning. It can use the same approach as the set_tab_title action to get input from the user via a kitten.

**Comment by kovidgoyal** [comment]
Well to be precise, I'm not particularly happy to accept a patch, since as I said, I dont like these kinds of popup dialogs, but since obviously my tastes are not universal, I am willing to accept such a patch. I dont keep issues open for things that have no clear path to implementation and that I am not a fan of.
