### ISSUE TITLE
Weird mouse support in htop

### ISSUE THREAD

**Issue by Askannz** [kovidgoyal/kitty#105]
Hello there !

Mouse support acts really odd when using htop in Kitty. It's like the terminal receives keypresses on the "F keys" (F1, F2, F3, etc) instead of mouse clicks. Here's a recording of the problem and a comparison with the expected behavior in xfce4-terminal :
[https://streamable.com/h6i4e](https://streamable.com/h6i4e)

OS is Linux Manjaro XFCE (latest version, stable branch, everything up-to-date). Kitty was downloaded through the AUR and its version is the latest one (0.2.7).

I haven't tested Kitty with other programs capable of mouse support (can't think of any right now).

Thanks for your work !

**Comment by NeoTheFox** [comment]
Can confirm this, same behaviour in htop with Arch Linux. 
Same weird mouse behaviour in ranger, this is what ranger receives:
[screenshot](http://i.imgur.com/5VxhN3O.png)

**Comment by kovidgoyal** [comment]
htop has generally pretty bad terminal support, and its author does not seem to be interested in fixing it. See for example: https://github.com/hishamhm/htop/issues/35

I'm guessing this is caused by htop not understanding SGR mouse codes, which are needed to support large screens and are the recommended way to handle mouse events in modern terminal programs. To see it in action use a program that supports it, such a vim (add set mouse=a to .vimrc) with kitty. 

It is probably using some obsolete protocol such as the urxvt protocol. I never use a mouse with htop, so I did not notice :) I'll take a look at it when I have a moment.
