### ISSUE TITLE
Integrating Kitty with another app

### ISSUE THREAD

**Issue by AndySomogyi** [kovidgoyal/kitty#1052]
Hi, 

I'm building an app (OSX, Linux, uses GLFW for UI), where I'd like to embed a Python interpreter, and provide a console where users could interactively enter and eval commands. 

My main thread runs the message pump loop, and I'd like a background thread to host a Python interpreter, and interact with a user. 

How hard do you suppose it would be to use Kitty as a lib to so that I could open a Kitty terminal window on the background thread?

**Comment by kovidgoyal** [comment]
Not sure why you'd need a lib for that. Simply use kitty as a complete app, and have it run a custom terminal program of your design to interact with the user instead of the normal shell. The program can forward the user input to your main process using sockets or similar IPC mechanisms.

The only constraint with this is that kitty will show up in a separate window, rather than embedded in your app. I dont know if that's a problem for you. 

You can see an example of doing something similar (using kitty to draw desktop panels) here https://sw.kovidgoyal.net/kitty/kittens/panel.html

As for using kitty as a lib, it's not really designed for that.
