### ISSUE TITLE
OSX ctrl cmd swapped - way to swap in kitty too?

### ISSUE THREAD

**Issue by viennaa** [kovidgoyal/kitty#1077]
Hi,

since I have ctrl and cmd swapped in the whole system I wonder, if there is the possibility to swap them in the kitty config as well (since I would need to use CMD+C in order to issue a Ctrl+C console behaviour). Haven't found anything so far. 

I tried remapping them directly with the glfw keys (swapped 0x2 and 0x8 here) without success.
on_key_input: glfw key: 347 native_code: 0x36 action: PRESS mods: 0x2 text: ''
on_key_input: glfw key: 341 native_code: 0x3b action: PRESS mods: 0x8 text: ''

Is this somehow possible
viennaa

**Comment by kovidgoyal** [comment]
You cannot remap modifiers in kitty, I'm afraid. The closest you can
come is mapping entire keypresses, which you will have to do for all
keypresses to have that affect. It should also be a fairly simple thing
to atch kitty to do what you need, see keys.c in the kitty source code

**Comment by sergei-dyshel** [comment]
FYI, I've made a simple patch to address this problem, see 056c124f

**Comment by flowchartsman** [comment]
@kovidgoyal, is there any way you would be able to take a look at the latest patch from @sergei-dyshel and see if there's a way to make this configurable? It does exactly what I want, and it would be amazing to offer it to everyone. https://github.com/kovidgoyal/kitty/commit/056c124f0fa3dc4872791998bba4b3fd5ac76e0b

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, sorry.
It might help if you explained the need for it.

**Comment by sergei-dyshel** [comment]
Here's my vision of why one would like to swap `Cmd` and `Ctrl` on Mac: 

On Linux (and Window) `Ctrl` and to lesser extent `Alt` are used as *application* modifiers (i.e. most application keybindings use combination of `Ctrl` and `Alt`), so one could call `Ctrl` the *primary* modifier and `Alt` a *secondary* one. On the other side `Windows`(aka `Super`) is mostly used as *global* modifier, i.e. for OS-level tasks, window management, global shortcuts.

On MacOS the situation is more complex, since `Ctrl` is also used for application-level bindings but there still seem to be a concept of `Cmd` being the *primary* modifier, `Option` (aka `Alt`) being the *secondary* modifier and `Ctrl` is used for *global* tasks but also for application.

So according to my "classification" `ctrl` and `cmd` already have swapped roles for one comming from Linux/Windows world and it might make sense to use `Cmd` as main modifier in terminal too, i.e. for the `Ctrl` key. 

But this is only my personal option and I understand that my patch is just a dirty hack and implementing this feature properly would require much more dev effort so I fully agree with @kovidgoyal's stance.

@flowchartsman
There is an app called Karabiner which allows to remap any keys on per-app basis so you might try this instead of patching Kitty's code. I would do that too but I just have this fetish of patching open-source software 😄

**Comment by flowchartsman** [comment]
@kovidgoyal Of course! I'm happy to explain. I feel the same way as @sergei-dyshel, but would like to give a few reasons of my own:

- Reason 1
  - It's a relatively common thing to do since they keys are in the same position and serve a similar function to `Ctrl` on other keyboards and in other operating systems.
- Reason 2
  - Different people prefer different hands to hit the modifier key. I (and probably many others) prefer the right hand due to years of muscle memory, and there is no corresponding `Ctrl` key on that side
- Reason 3
  - `Ctrl` is very awkward to hit on Apple keyboards; it is not the same priority as `cmd` for reasons @sergei-dyshel mentioned. It requires you to curl your thumb and lift your hand, and is very inconvenient, especially to people with years of experience hitting control. And I use it a lot as a heavy tmux / vim user

I hope that explains my rationale. iterm2 provides this ability for probably similar reasons, but I really like Kitty, and would like this option there. I think it would make a very useful configuration option. Of course I don't believe it should be on by default! :)

@sergei-dyshel: I'm aware of Karabiner, but that is way too heavy of a tool for this use, and I've had trouble getting it to work.

**Comment by sergei-dyshel** [comment]
BTW, I'd like to add that Karabiner rule would swap modifiers for system keybindings too, i.e. if you have `cmd+space` binding for Spotlight and you swap `ctrl` and `cmd` in Karabiner for kitty/iterm2, than you will have to press `ctrl+space` in those apps for Spotlight. Unfortunately iterm2 built-in modifier remapping works in the same manner (probably utilising same low-level mechanism).
This behaviour is very annoying.... So I would say that the remapping I did in kitty's code is the only proper solution existing on Mac terminals 😄

**Comment by kovidgoyal** [comment]
I'm fine with a patch adding such an (off-by-default) option, I'm just not motivated enough to come up with one myself.

**Comment by aste4** [comment]
@kovidgoyal, thank you for directing me to this issue

+1 to everything in this issue

**Comment by flowchartsman** [comment]
@kovidgoyal Understood. Would you be willing to provide a little direction on me or @sergei-dyshel integrating this the proper way? Anything we should be aware of? I'll take a crack at it.

**Comment by kovidgoyal** [comment]
Feel free to ask if you have questions, in general, this will need to be
done at the level of glfw, not kitty, since you will also have to remap
the cocoa global menu shortcuts. You define options in config_data.py
and state.[ch] and you will need to create a glfwinithint which the
kitty code in create_os_window() will need to set based onthe option
when creating the first window.

**Comment by ultrox** [comment]
I'm a very big fan of kitty, but unfortunately, lack of this feature on mac is preventing me to use it, I see a lot of people on blogs are struggling with this. I hope you change your mind @kovidgoyal.

**Comment by sergei-dyshel** [comment]
@ultrox 
You can use the patch I posted here earlier. It does the job pretty well.

**Comment by ultrox** [comment]
@sergei-dyshel will try that, thank you!

**Comment by aliher1911** [comment]
Can the same be applied to x11 version? Should the swapping be done inside x11_window.c?

**Comment by vaskozl** [comment]
After getting a Mac in addition to a Linux workstation the difference was driving me crazy. On the OS/QMK side I put "Control" on the same key as Mac "Command" as muscle memory is very strong. This makes pretty much all GUI apps equivalent. But terminals is the one place it's different due to the dedicated control key in Macs.

Since on Linux I don't use a DE that uses the super key, I'm now using @aliher1911 fork to remap Super and Control on linux kitty such that things match. The advantage of making Super the Control key in kitty, is that the real control can still be used for the normal shortcuts, just like MacOS.

E.g. once swapped, to make simple Control+C and Control+V do copy and paste:
```
kitty_mod super
```

Now we can have total parity between mac and linux from terminal to browser!

**Comment by ppwwyyxx** [comment]
I would hope to see an option to swap option and command key on mac.

AFAIK, option and command key are interpreted by kitty as "alt" and "super". However, on mac, option is on the left of command, but on a standard keyboard, alt is on the right of super.
The only way to address this inconsistencies so far seems to be to do a system-wide modifier swap on mac. But I hope to apply this swap only to kitty without affecting other apps.

**Comment by espenaf** [comment]
Created a new [patch](https://github.com/espenaf/kitty/commit/74b4f63d663e7aa617e149638861295e8772e43d) for command <-> control swap with the latest HEAD.

**Comment by sergei-dyshel** [comment]
@inv2004 
This commit https://github.com/kovidgoyal/kitty/commit/bde8691ea724be2ad9153616222a28e087e216e3 worked for me. It's based on fairly recent version of kitty. I assume it should work for latest version too, though I haven't checked that explicitly since I've moved to another terminal  already.

**Comment by inv2004** [comment]
sorry, still not clear. The comment mentioned swap ctrl<=>cmd https://github.com/kovidgoyal/kitty/issues/1077#issuecomment-1793153216 - is it some global change outside kitty?

Should I add something into kitty after the change or it is just kitty config?

**Comment by necauqua** [comment]
hey here's an updated version of that patch to swap ctrl and super that works as of now:

```diff
diff --git a/gen/key_constants.py b/gen/key_constants.py
index 7bf9a90d8..119eac65b 100755
--- a/gen/key_constants.py
+++ b/gen/key_constants.py
@@ -113,15 +113,15 @@
 raise_volume                XF86AudioRaiseVolume        -      -
 mute_volume                 XF86AudioMute               -      -
 left_shift                  Shift_L                     0x38   -
-left_control                Control_L                   0x3B   -
+left_control                Super_L                     0x3B   -
 left_alt                    Alt_L                       0x3A   -
-left_super                  Super_L                     0x37   -
+left_super                  Control_L                   0x37   -
 left_hyper                  Hyper_L                     -      -
 left_meta                   Meta_L                      -      -
 right_shift                 Shift_R                     0x3C   -
-right_control               Control_R                   0x3E   -
+right_control               Super_R                     0x3E   -
 right_alt                   Alt_R                       0x3D   -
-right_super                 Super_R                     0x36   -
+right_super                 Control_R                   0x36   -
 right_hyper                 Hyper_R                     -      -
 right_meta                  Meta_R                      -      -
 iso_level3_shift            ISO_Level3_Shift            -      -
diff --git a/glfw/cocoa_window.m b/glfw/cocoa_window.m
index 79e4104a1..16b50dd54 100644
--- a/glfw/cocoa_window.m
+++ b/glfw/cocoa_window.m
@@ -108,13 +108,13 @@
         case 0x4c: return GLFW_FKEY_KP_ENTER;
         case 0x51: return GLFW_FKEY_KP_EQUAL;
         case 0x38: return GLFW_FKEY_LEFT_SHIFT;
-        case 0x3b: return GLFW_FKEY_LEFT_CONTROL;
+        case 0x37: return GLFW_FKEY_LEFT_CONTROL;
         case 0x3a: return GLFW_FKEY_LEFT_ALT;
-        case 0x37: return GLFW_FKEY_LEFT_SUPER;
+        case 0x3b: return GLFW_FKEY_LEFT_SUPER;
         case 0x3c: return GLFW_FKEY_RIGHT_SHIFT;
-        case 0x3e: return GLFW_FKEY_RIGHT_CONTROL;
+        case 0x36: return GLFW_FKEY_RIGHT_CONTROL;
         case 0x3d: return GLFW_FKEY_RIGHT_ALT;
-        case 0x36: return GLFW_FKEY_RIGHT_SUPER;
+        case 0x3e: return GLFW_FKEY_RIGHT_SUPER;
 /* end vk to functional */
         default:
             return 0;
@@ -438,11 +438,11 @@ static void releaseMonitor(_GLFWwindow* window)
     if (flags & NSEventModifierFlagShift)
         mods |= GLFW_MOD_SHIFT;
     if (flags & NSEventModifierFlagControl)
-        mods |= GLFW_MOD_CONTROL;
+        mods |= GLFW_MOD_SUPER;
     if (flags & NSEventModifierFlagOption)
         mods |= GLFW_MOD_ALT;
     if (flags & NSEventModifierFlagCommand)
-        mods |= GLFW_MOD_SUPER;
+        mods |= GLFW_MOD_CONTROL;
     if (flags & NSEventModifierFlagCapsLock)
         mods |= GLFW_MOD_CAPS_LOCK;
 
@@ -1033,11 +1033,11 @@ - (NSTextInputContext *)inputContext
     if (flags & NSEventModifierFlagShift)
         mods |= shiftKey;
     if (flags & NSEventModifierFlagControl)
-        mods |= controlKey;
+        mods |= cmdKey;
     if (flags & NSEventModifierFlagOption)
         mods |= optionKey;
     if (flags & NSEventModifierFlagCommand)
-        mods |= cmdKey;
+        mods |= controlKey;
     if (flags & NSEventModifierFlagCapsLock)
         mods |= alphaLock;
 
@@ -1223,10 +1223,10 @@ - (void)flagsChanged:(NSEvent *)event
         case GLFW_FKEY_CAPS_LOCK:
             mod_name = "capslock";
             action = modifierFlags & NSEventModifierFlagCapsLock ? GLFW_PRESS : GLFW_RELEASE; break;
-        case GLFW_FKEY_LEFT_SUPER: action_for(super, NX_DEVICELCMDKEYMASK, NX_DEVICERCMDKEYMASK, NX_COMMANDMASK);
-        case GLFW_FKEY_RIGHT_SUPER: action_for(super, NX_DEVICERCMDKEYMASK, NX_DEVICELCMDKEYMASK, NX_COMMANDMASK);
-        case GLFW_FKEY_LEFT_CONTROL: action_for(ctrl, NX_DEVICELCTLKEYMASK, NX_DEVICERCTLKEYMASK, NX_CONTROLMASK);
-        case GLFW_FKEY_RIGHT_CONTROL: action_for(ctrl, NX_DEVICERCTLKEYMASK, NX_DEVICELCTLKEYMASK, NX_CONTROLMASK);
+        case GLFW_FKEY_LEFT_CONTROL: action_for(super, NX_DEVICELCMDKEYMASK, NX_DEVICERCMDKEYMASK, NX_COMMANDMASK);
+        case GLFW_FKEY_RIGHT_CONTROL: action_for(super, NX_DEVICERCMDKEYMASK, NX_DEVICELCMDKEYMASK, NX_COMMANDMASK);
+        case GLFW_FKEY_LEFT_SUPER: action_for(ctrl, NX_DEVICELCTLKEYMASK, NX_DEVICERCTLKEYMASK, NX_CONTROLMASK);
+        case GLFW_FKEY_RIGHT_SUPER: action_for(ctrl, NX_DEVICERCTLKEYMASK, NX_DEVICELCTLKEYMASK, NX_CONTROLMASK);
         case GLFW_FKEY_LEFT_ALT: action_for(alt, NX_DEVICELALTKEYMASK, NX_DEVICERALTKEYMASK, NX_ALTERNATEMASK);
         case GLFW_FKEY_RIGHT_ALT: action_for(alt, NX_DEVICERALTKEYMASK, NX_DEVICELALTKEYMASK, NX_ALTERNATEMASK);
         case GLFW_FKEY_LEFT_SHIFT: action_for(shift, NX_DEVICELSHIFTKEYMASK, NX_DEVICERSHIFTKEYMASK, NX_SHIFTMASK);
@@ -3113,11 +3113,11 @@ GLFWAPI GLFWColorScheme glfwGetCurrentSystemColorTheme(bool query_if_unintialize
     if (glfw_mods & GLFW_MOD_SHIFT)
         *cocoa_mods |= NSEventModifierFlagShift;
     if (glfw_mods & GLFW_MOD_CONTROL)
-        *cocoa_mods |= NSEventModifierFlagControl;
+        *cocoa_mods |= NSEventModifierFlagCommand;
     if (glfw_mods & GLFW_MOD_ALT)
         *cocoa_mods |= NSEventModifierFlagOption;
     if (glfw_mods & GLFW_MOD_SUPER)
-        *cocoa_mods |= NSEventModifierFlagCommand;
+        *cocoa_mods |= NSEventModifierFlagControl;
     if (glfw_mods & GLFW_MOD_CAPS_LOCK)
         *cocoa_mods |= NSEventModifierFlagCapsLock;
     return _glfwPlatformGetNativeKeyForKey(glfw_key);
```

**Comment by denialofsandwich** [comment]
I stumbled over the same problem and solved it by just manually remapping every key one-by-one. It works fine for me and only requires to change the config itself:
```
# Default key
kitty_mod cmd+shift

# Ctrl+Key fixes
map cmd+a send_text all \x01
map cmd+b send_text all \x02
map cmd+c send_text all \x03
map cmd+d send_text all \x04
map cmd+e send_text all \x05
map cmd+f send_text all \x06
map cmd+g send_text all \x07
map cmd+h send_text all \x08
map cmd+i send_text all \x09
map cmd+j send_text all \x0a
map cmd+k send_text all \x0b
map cmd+l send_text all \x0c
map cmd+m send_text all \x0d
map cmd+n send_text all \x0e
map cmd+o send_text all \x0f
map cmd+p send_text all \x10
map cmd+q send_text all \x11
map cmd+r send_text all \x12
map cmd+s send_text all \x13
map cmd+t send_text all \x14
map cmd+u send_text all \x15
map cmd+v send_text all \x16
map cmd+w send_text all \x17
map cmd+x send_text all \x18
map cmd+y send_text all \x19
map cmd+z send_text all \x1a
map cmd+left send_text all \x1bb
map cmd+right send_text all \x1bf
```

**Comment by bjohas** [comment]
Reviving this thread: A different angle on this that's worked well for me — offered in case it's of interest, though I realise it's narrower than the glfw-level Cmd/Ctrl swap discussed here.

Rather than swapping modifiers globally at the glfw level (which, as you noted, drags in the cocoa menu remap and affects kitty's own shortcuts), I added an (off-by-default) option that swaps a modifier pair **only for keys forwarded to the child program**, applied in `send_key_to_child()` *after* shortcut dispatch:

```conf
swap_modifiers hyper+ctrl
```

`Hyper+x` reaches the program as `Ctrl+x` and vice-versa, for every key — no per-key `map … send_key` enumeration.

**Why a terminal-side option and not the WM/OS.** Ctrl is context-dependent and only the terminal can tell the contexts apart: outside a terminal `Ctrl+C` is a GUI shortcut; inside, the terminal *encodes* Ctrl into control bytes for the program (`Ctrl+C`→SIGINT, `Ctrl+A`→`^A`) — encoding that lives in the terminal, below which a WM/xkb remap can't reach. And within one window Ctrl does double duty (kitty's own shortcuts *and* bytes to the child); a global/per-window OS remap relabels the physical key for both at once. Per-app OS remappers (xkeysnail/AutoKey/kinto by window class) only approximate it and are fragile (Wayland detection, stuck mods, no Hyper — kinto#562).

**The deliberate scope difference:** Because it runs after shortcut dispatch, kitty's own shortcuts and the macOS menu stay on the *physical* modifier and are unaffected — which sidesteps the cocoa-menu complexity that stalled the earlier patches, but is a genuine behaviour choice: some here (e.g. the `kitty_mod super` workflow above) instead *want* the swap to reach kitty's shortcuts. I went with child-only because it's the minimal, portable piece and leaves shortcut routing to the existing `kitty_mod`. (Happy to be told that's the wrong tradeoff!)

**Precedent / size.** It's the same class as the existing `macos_option_as_alt` (reinterpreting a physical modifier for the child), generalized. The mechanism is ~4 lines feeding the single `encode_glfw_key_event` choke point (legacy + kitty-protocol both covered):

```c
const int sm = OPT(swap_modifiers);
if (sm && (mods & sm) && (mods & sm) != sm) mods ^= sm;
```

plus an option (`to_modifiers`/`int`, like `kitty_mod`), a `kitty_tests/` test, and a docs line. Off by default.

**The need is already documented in this thread** (over 8 years): the ergonomics and muscle-memory reasons given in the comments above (preferring a right-hand modifier, Ctrl being awkward to reach on Apple keyboards), the primary/secondary/global modifier breakdown laid out earlier, the Mac↔Linux "same physical key" parity point, and a steady stream of +1s and personal-fork patches since 2018. My own case is the Linux variant of the same thing: cross-platform muscle memory with Ctrl moved onto Caps Lock/Hyper. I maintained a patched VTE build for it in GNOME Terminal, recompiled on every update (https://github.com/bjohas/gnome-terminal-vte, https://github.com/bjohas/Ubuntu-keyboard-map-like-OS-X), and would rather upstream it.

**Two questions before any PR:** (1) is this child-only scope of interest, or do you want the glfw-level "swap everything incl. menu" design instead? (2) if the former, do you prefer `swap_modifiers <a>+<b>` or a general one-directional `remap_modifier <from> <to>` (repeatable; composes to a swap; also covers super→ctrl)?

**Comment by kovidgoyal** [comment]
No, not really. Having keys behave differently depending on where they are routed is beyond confusing. It needs to be application wide aka at the glfw level. remap_modifier is preferable. You also need to be careful about ordering. Does remap_modifier affect previously declared mappings like kitty_mod? Does it affect kitty_mod? Is its position in kitty.conf significant? Also there needs to be output when using --debug-input indicating they have been swapped.

**Comment by bjohas** [comment]
Implemented as `remap_modifier <from> <to>`, repeatable, off by default, on top
of v0.48.1. Taking your questions in order.

1. It affects every mapping, wherever declared, because it is not a mapping: it
   rewrites the event in `key_callback()` before anything reads the config, so
   nothing in `kitty.conf` ever sees the physical modifier.

2. `kitty_mod` included — its value is read in post-remap terms like every
   `map`, so `remap_modifier ctrl super` moves the built-in `ctrl+shift+...`
   shortcuts onto the physical Super key unless you also set `kitty_mod`.

3. Not significant, except that the last declaration for a given source wins.
   Repeats compose as one simultaneous permutation applied once, so

   ```conf
   remap_modifier ctrl super
   remap_modifier super ctrl
   ```

   is a swap rather than two rewrites collapsing to the identity.

4. `--debug-input` prints `remap_modifier: mods: hyper -> mods: ctrl`, and also
   reports when a modifier key's own identity was rewritten.

It applies in `mouse_button_callback()` and `scroll_callback()` too, so
`mouse_map` agrees with `map`. Only shift, alt, ctrl, super, hyper and meta can
be named; anything else is rejected with an error. A modifier key's own press
reports the destination key, so a program using the full keyboard protocol does
not see ctrl reported together with `LEFT_HYPER`.

On macOS `get_cocoa_key_equivalent()` inverts the remap so an accelerator lands
on the physical key. That inverse can fail — two sources onto one modifier, or
hyper/meta, which `glfwGetCocoaKeyEquivalent()` has no flags for and would
silently reduce to a key equivalent with no modifiers at all, turning
`map super+q quit` into a bare `q`. It declines to install rather than guess.

Tests are parser cases in `kitty_tests/options.py` plus a script that drives a
real window with xdotool and asserts the encoded bytes, including a 3-cycle that
a sequentially-applied implementation would fail.

Unrelated, but noticed while doing this: `translateState()` in `x11_window.c`
drops Mod3, so hyper never reaches mouse events on X11 at all.

I have no way to test macOS — that path compiles clean in isolation but has
never run. Is it acceptable to review on that basis?

**Comment by kovidgoyal** [comment]
Yes, that's fine I have a mac (I keep one old one just for testing kitty and
calibre) and can test on that.

**Comment by bjohas** [comment]
Thank you @kovidgoyal - I'd be pretty confident in saying this is the first terminal-style programme that has this feature! THANK YOU!

**Comment by kovidgoyal** [comment]
Eh I hardly did anything it was your PR!
