### ISSUE TITLE
Double/triple click does not take position into account

### ISSUE THREAD

**Issue by mninja** [kovidgoyal/kitty#1093]
The double/triple click to select word/line feature does not take position into account. For example:

```
line A
line B
line C
```
If you click on `line` on each line in quick succession in kitty, you will select `line` on B and then all of line C.

The expected behavior (e.g. as standard in other terminals, browsers) is that you would have to double/triple click without moving the cursor for the selection to work.

**Comment by martinetd** [comment]
I had noticed this, it's not part of what I intended to fix with the rework.
If the solution is just "click again without changing cells" it's not too difficult, but I've actually come to appreciate this a bit and would like it to work as long as the next click is still within the selection (e.g. second click would work if in same cell, and the third click would work as long as it is inside 'line' in the second click) -- that's more work and would be better after I'm done. . . on which note I'm really sorry for the delay, should get back to it around next week ish; I stumbled on some issues and have been delaying doing a proper fix but I should just get on with it.

I guess we can do the easy way in `mouse.c` now and the rest later if it's annoying folks, up to others.

**Comment by kovidgoyal** [comment]
I certainly would not expect double/triple clicking to work without moving the cursor at all. That would be very painful since the cursor can often move accidentally while clicking, expecially with touchpads or sensitive mice. 

What actual problem does this behavior cause? If you move the mouse on multiple lines while double clicking, the worst thing that happens is you get a wrong selection. In other terminals you get no selection. In either case you have to go back and fix the selection.

**Comment by martinetd** [comment]
I can agree it's annoying when you don't expect it to, e.g. click once on the wrong line by mistake, move up a line then click twice to get a word and you didn't get what you expected to.

"Not moving at all" could very easily be same cell with the current code, I'd think that's fine even with sensitive touchpads/mice ?
I was talking of 'within selection' earlier, technically what I would consider ideal is "within where the selection would be extended with one more click", so within word on 2nd click or line on 3rd click, but I don't think that's worth the hassle of computing where selection would end up and discard the result if cursor was too far...

**Comment by kovidgoyal** [comment]
The mouse code has access to OSWindow which has fonts_data which has cell width and cell height. I'd probably choose some multiple of cell height, maybe 1.5 or similar. Hard to say without trying out a few numbers.

**Comment by michaelkix** [comment]
Just adding here - I'm a new kitty user/fan but have run into this issue several times.

An example of when this might happen: I double click to select a word but miss. Then I reposition the cursor and double click again, but I get triple click behavior instead.

I support the sensitivity radius idea and think it can be configurable (because why not). Something like double_click_threshold or multi_click_threshold.

**Comment by maximbaz** [comment]
Agree, here's a demo of extreme case (double click, move cursor, single click):

![kitty-selection2](https://user-images.githubusercontent.com/1177900/48001698-9674ea80-e109-11e8-9672-5492307deeae.gif)

And this is quite a realistic scenario that was already mentioned above (double click, notice wrong word is selected, reposition cursor, another double click):

![kitty-selection-3](https://user-images.githubusercontent.com/1177900/48001803-e94ea200-e109-11e8-9049-5191688be81c.gif)

Not sure if the radius here is the actual issue, or simply the waiting interval for the third click being too large.

**Comment by kovidgoyal** [comment]
Feel free to adjust the wait interval to whatever you like, it is in
kitty.conf IIrC called click_interval
