### ISSUE TITLE
Menu(?) bar not working on macOS 10.12.5

### ISSUE THREAD

**Issue by VincentBurke** [kovidgoyal/kitty#111]
Hey everyone, I have configured kitty to my liking and almost everything is working. I am having an issue where in the top menu bar whenever I press kitty nothing happens(seen in the picture below). Also not sure if this is related but none of the keyboard shortcuts work either(ctrl q to quit etc). Here's some debug info:
<img width="719" alt="problem" src="https://user-images.githubusercontent.com/5258253/29377010-0dbde7ac-8280-11e7-8d03-38ae37f34db2.png">
` ❯ brew info python3
python3: stable 3.6.2 (bottled), HEAD
Interpreted, interactive, object-oriented programming language
https://www.python.org/
/usr/local/Cellar/python3/3.5.2_3 (3,663 files, 55.0MB) *
  Poured from bottle on 2016-11-16 at 21:54:25
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/python3.rb`
`❯  brew info glfw
glfw: stable 3.2.1 (bottled), HEAD
Multi-platform library for OpenGL applications
http://www.glfw.org/
/usr/local/Cellar/glfw/3.2.1 (14 files, 286.6KB) *
  Poured from bottle on 2017-08-16 at 12:31:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/glfw.rb`
Thanks!

**Comment by kovidgoyal** [comment]
kitty has no menu entries. So pressing the menu bar will have no effect. And the keyboard shortcut to quit is not Ctrl+Q, it is Ctrl+Shift+Q (which closes the current tab and will close kitty if the current tab is the last tab). All kitty keyboard shortcuts start with Ctrl+Shift so that they dont interfere with shortcuts for programs running in the terminal.
