### ISSUE TITLE
Scroll by pixels, not by lines, and support acceleration

### ISSUE THREAD

**Issue by maximbaz** [kovidgoyal/kitty#1123]
Extracting https://github.com/kovidgoyal/kitty/issues/1112#issuecomment-435876514 in a separate thread.

I noticed that sakura terminal scrolls by pixels:

![sakura-scroll](https://user-images.githubusercontent.com/1177900/48001263-58c39200-e108-11e8-86a0-07a099be5a1d.gif)

While kitty is only able to scroll by lines:

![kitty-scroll](https://user-images.githubusercontent.com/1177900/48001306-7d1f6e80-e108-11e8-9b0f-0e02655bead3.gif)

Scrolling by pixels feels a lot smoother, plus `sakura` has acceleration, which helps a lot. 

-------

Kitty doesn't seem to have acceleration, so if I set `wheel_scroll_multiplier 1` in config, scrolling will be very slow even if I violently move my fingers on touchpad — the absence of acceleration prevents me from permanently setting `wheel_scroll_multiplier` to `1`.

**Comment by kovidgoyal** [comment]
Given the way kitty renders supporting pixel scrolling is way too much work. As for acceleration, not a fan personally, but pull requests are welcome. Note that on high resolution scrolling devices such as touchpads on macOS or with proper drivers in linux, there should be no need to implement acceleration, since it is automatic. You'd only needeeeed it for touchpad device that dont have propeer drivers or wheel mice, and at least personally, I dont wat acceleration for wheel mice.

**Comment by maximbaz** [comment]
Pixel scrolling - OK, I anyway expected this answer 😄 

Acceleration - definitely not wanted for wheel mice, but it doesn't work work for me on laptop. If you run linux on laptop, does acceleration work for you?

Acceleration works everywhere else for me, so I'm really surprised that it might be a driver issue, did all other apps truly re-implemented acceleration?

**Comment by maximbaz** [comment]
Is there a place I can maybe add some debug prints to prove that my touchpad doesn't produce accelerated values?

**Comment by Luflosi** [comment]
I would _**really**_ love to have smooth and precise scrolling in kitty as I know of no terminal emulator on macOS that supports it and only two on linux. I might make a wip pull request to attempt to start implementing this in the near future. Here is a great article that goes into great detail about many problems, solutions and more when implementing something like this for anyone interested: https://pavelfatin.com/scrolling-with-pleasure/.
@maximbaz what do you mean by acceleration? https://pavelfatin.com/scrolling-with-pleasure/#scrolling-acceleration or https://pavelfatin.com/scrolling-with-pleasure/#kinetic-scrolling? IMHO ideally both of those things should be done by the driver or some other piece of software outside of applications. It should "just work" for applications to provide a consistent user experience across different applications. And are you using X11 or Wayland?
@kovidgoyal how does rendering when scrolling currently work? Do you render specific lines at the bottom or top and shift the rest of the rendered lines over? Or do you render every line on the entire screen again? And how are images from the graphics protocol rendered? I imagine it to work a bit differently than the other stuff.

**Comment by maximbaz** [comment]
I've seen that article before and I absolutely agree with it 🙂 

I was referring to "scrolling acceleration", where depending on the speed of moving fingers on touchpad I can get more or less lines scrolled for the same distance. However, I spent the last hour trying different things and reading on internet, it seems there's simply no such thing in `libinput` as "scrolling acceleration". So I understood that in sakura I was experiencing something different, and I'll try to explain it without using some fancy terms.

In kitty, with `wheel_scroll_multiplier 1` I can scroll up by approximately 60 lines if I use all available touchpad height, regardless of how fast I move my fingers on touchpad (no acceleration). So I can go as slowly as line by line and a total of as high as 60 lines in the scrollback history. I can go more if I increase parameter `wheel_scroll_multiplier`, but I lose the fidelity and cannot scroll by one line anymore.

Sakura, on the other hand, allows me to scroll as slow as pixel by pixel (for now treat this as "by one line" for comparison with kitty) and yet as much as 380 lines if I scroll by using all available touchpad height. There's no acceleration involved, but somehow sakura allows me to scroll much more smoothly.

I'm on X11, i3 with Arch.

**Comment by kovidgoyal** [comment]
you need to set Xft.dpi if you want glfw and therefore kitty to use high DPI rendering. This is generally true for all applications, tough the "big" toolkits/desktops often have their own DPI mechanisms. I know Qt for instance respects Xft.dpi if its preferred mechanism is not present.

**Comment by kovidgoyal** [comment]
In high precision scrolling, the OS reports the number of pixels your finger has moved. Applications can use that directly and there is therefore no need to implement it per application. On X11 I am pretty sure the driver situation is horrible which means your touchpad likely is not being treated as a high precision input device by glfw. I have no idea if that is a bug in glfw/x11 drivers or something else.

**Comment by kovidgoyal** [comment]
@Luflosi rendering is always full screen at a time (code is in shaders.c). images are rendered ina  separate shader call and are positioned with respect to lines (code is mostly in graphics.c and shaders.c)

**Comment by egmontkob** [comment]
Currently Kitty doesn't seem to scroll by single lines, it scrolls by 5 lines at a time for me.

Whereas per-pixel scrolling is indeed a bit cumbersome to implement, I guess it could be a low hanging fruit to scroll by 1 line each time the touchpad reports a cumulated 0.2 unit of movement, rather than by 5 lines at once when 1 unit (corresponding to 1 "click" of the mouse wheel) is reached. Same for the synthesized up/down keypresses on alternate screen.

In VTE (Sakura and friends) we did this improvement first ([710426](https://bugzilla.gnome.org/show_bug.cgi?id=710426)), and I loved it so much that eventually further improved it to per-pixel scrolling ([746690](https://bugzilla.gnome.org/show_bug.cgi?id=746690)).

**Comment by egmontkob** [comment]
VTE (thus Sakura) has neither acceleration nor kinetic scroll implemented in itself. If this behavior is experienced, it comes from an underlying layer (not sure if GTK+ can do any of these, or X11/Wayland, or driver). So I believe Kitty and VTE should both work the same way in this regard.

(I, for one, don't seem to have acceleration in either, while have kinetic scrolling in both.)

**Comment by maximbaz** [comment]
> Currently Kitty doesn't seem to scroll by single lines, it scrolls by 5 lines at a time for me.

You need to add `wheel_scroll_multiplier 1` to `kitty.conf`, the default value is `5` indeed. But when you do this, scrolling feels much slower comparing to sakura or chromium, I'm wondering why.

**Comment by maximbaz** [comment]
> scroll by 1 line each time the touchpad reports a cumulated 0.2 unit of movement

This is the problem here, it looks like kitty doesn't receive fractional units of movement for me, neither with `libinput` nor with `synaptics` drivers. I added some debug logs and was watching what happens when I slowly move my finger, kitty receives nothing, nothing, and then boom, one event, `1` line moved.

sakura / chromium on the other hand are much more precise, they react on tiniest possible movements of my finger on the touchpad.

**Comment by maximbaz** [comment]
I've just remembered that one year ago I was helping to debug [this exact issue in alacritty](https://github.com/jwilm/alacritty/issues/721#issuecomment-321888010), and when I was monitoring their debug logs, alacritty was able to register fractional units. Since other terminals work fine under the same driver and X11, the problem is definitely in glfw.

**Comment by egmontkob** [comment]
> But when you do this, scrolling feels much slower comparing to sakura or chromium, I'm wondering why.

Because that's exactly what you configured :), slowed down scrolling speed by a factor of 5.

VTE's (Sakura's) scrolling factor isn't 1, it's 3–5-ish (depending on the window height, that's a nasty pending issue), e.g. effectively it might scroll by 5 lines per 1 traditional unit of the input device. It just does it in finer steps, but with the same (or similar) overall speed as Kitty's default.

Unfortunately I cannot comment on the input driver / glfw side of the story.

**Comment by maximbaz** [comment]
> Because that's exactly what you configured :), slowed down scrolling speed by a factor of 5.
> VTE's (Sakura's) scrolling factor isn't 1, it's 3–5-ish (depending on the window height, that's a nasty pending issue), e.g. effectively it might scroll by 5 lines per 1 traditional unit of the input device. It just does it in finer steps, but with the same (or similar) overall speed as Kitty's default.

Aaaah, I see what you mean!

I've just confirmed that the problem is in glfw, contrary to `cocoa_window.m` (which has some logic around "precision scrolling"), `x11_window.c` has nothing like that, the code for X11 plain simple: Button4 key received -> +1 to the offset. There is "high precision" mode in X11 since 2011, but it is not implemented in glfw.

**Comment by kovidgoyal** [comment]
you'll likely have to wait a long time for glfw to fix it. Should not be hard to make the requisite changes in glfw/x11_window.c yourself.

**Comment by maximbaz** [comment]
I was looking into this today, I wish it was [as easy as for macOS](https://github.com/glfw/glfw/pull/95/files), but for X11 I'm afraid the patch will be quite large. I was searching for some examples on how to even start approaching this, and found [this patch](https://sourceforge.net/p/xdvi/mailman/message/32179998/) which seems to be implementing more or less the same functionality, but it is adding something like a 1000 new lines 😕 

I would be happy to be proven wrong, but at a first glance all of those changes seem to be necessary: detect if smooth scrolling is available, detect which of the potentially multiple pointer devices are currently active and switch between them on the fly, handle mistakenly large scroll delta if user was scrolling in some other window, etc.

Not sure I'll be able to pull this off by myself, @Luflosi are you using kitty on Linux and how are your C skills? Maybe we can join forces on this one, if you are also interested in getting a better scrolling experience on X11?

**Comment by Luflosi** [comment]
I mostly use Linux on servers but I occasionally use Linux as a desktop OS but only with Wayland. I could probably set up a virtual machine though. My C skills should be more than good enough. I would be more worried about my X11 skills since I've never done any programming involving X11.

**Comment by maximbaz** [comment]
How's the situation under Wayland, by the way? I don't see anything about scrolling at all in `wl_window.c`, I assume kitty also has no smooth scrolling? 

With this X11 example I'm primarily scratching my head around how to integrate that with glfw, assuming this is a good example and we will be able to simply copy-paste the majority of the code. But just to confirm, since you aren't using X11, is this something you want to pursue or shall we drop this idea for now? I've also never done any X11 programming before, and my C skills are on the level of "I understand the syntax, but have never written any actual code besides maybe small examples".

**Comment by Luflosi** [comment]
kitty under Wayland can see precise scrolling events, in my testing even less than one pixel. macOS "only" seems to report scrolling events with pixel-precision. Under X11, kitty does not see precise scrolling events, only line-by-line.

I'd be happy to try to help you out extending glfw with the help of the example code.

**Comment by maximbaz** [comment]
> kitty under Wayland can see precise scrolling events

Huh, give me a day or two, I would like to explore Wayland first, more and more people use Wayland so maybe it's time for me to migrate away from X11 as well, and then this work will be a wasted effort 🙂

**Comment by maximbaz** [comment]
@Luflosi are you sure-sure precise scrolling works under Wayland? I've tried `weston` and `sway`, scrolling is definitely not smooth, not in kitty, not even in sakura or chromium. Which one do you use? Gnome, maybe? I've seen mentions that Gnome is way ahead of others in Weston, that it's the only one that has decent support for HiDPI for example (in sway everything is so blurry 😕)

**Comment by egmontkob** [comment]
In GNOME + Wayland I do have smooth (per-pixel) scrolling in VTE – both with native Wayland apps like gnome-terminal or sakura (over which xmag, xwininfo etc. don't work), and with XWayland compatibility ones like guake (over which these tools work as usual).

**Comment by Luflosi** [comment]
@maximbaz I'm sorry, if I wasn't clear enough, I didn't say, I could scroll with more precision than one line, kitty doesn't support that yet. I only said, that kitty gets high precision scroll events under Wayland and macOS but not X11. That does not mean, that kitty can actually increase smoothness because it doesn't really use the high precision. Currently the only advantage (I can think of) is, that scrolling is more consistent with other applications and at different font sizes because kitty only scrolls by a line when the height of the line was scrolled in pixels. All I did, was put a printf statement in `scroll_event` in mouse.c and print whether `is_high_resolution` is true or not and also print the value of `yoffset`. Under Wayland and macOS `is_high_resolution` was true and under X11 it was false. Under Wayland the values could be less than one pixel, under macOS the values had an accuracy of one pixel and under X11 the values had an accuracy of one line. I didn't notice any difference in scrolling between sway and Gnome.

**Comment by maximbaz** [comment]
Got it, thanks to both of you for confirming, I'll look more into this.

**Comment by maximbaz** [comment]
A small update, under Wayland my touchpad is indeed recognized as "high resolution" and `viewport_y_ratio` is detected as `2`.

Multiplying `yoffset` by `20` (totally hand-crafted value) makes the scrolling feel just awesome. Thus, for Wayland I submitted #1129.

I'm still not sure if I stay with Wayland or try to come up with a patch for X11 next...

**Comment by maximbaz** [comment]
I give up on the patch for X11, unfortunately it's beyond my abilities for the time I can dedicate for this 🙁. Hope someone else chips in, or we all finally migrate to Wayland one day.

**Comment by Luflosi** [comment]
I would like to try to start implementing pixel-precise scrolling. I have an idea of how it could work in theory but I don't know how to do it in practice. Here is my current plan:

- Create a new (third) buffer, which is slightly (at least one line) larger than the other two
- Instead of rendering to one of the other buffers, render to this new buffer
- Just before swapping the two other buffers with `swap_window_buffers(os_window)`, copy the correct block of image data from the new buffer to one of the other buffers. This should be fairly fast with bit blit

Only minor changes should be needed to be made to the actual render code since we still only render a few lines into some buffer. Obviously the scroll code needs to also be adjusted so it can actually scroll by pixels and not just by lines.

Please tell me if anything is wrong with what I said.

How and where do I create this new buffer? And where do you create the other buffers?

**Comment by kovidgoyal** [comment]
There are no buffers allocated by kitty, except in the case of
interleaved graphics rendering. OpenGL rendering happens into system
provided framebuffers. If you want to allocate your own buffers you
would need to use FBOs (frame buffer objects, render into those and then
copy using a shader).

**Comment by Luflosi** [comment]
What does "interleaved graphics rendering" mean and when is it used? And do you know where the best place to create an FBO is? In `init_cell_program()` in `kitty/shaders.c`?

**Comment by kovidgoyal** [comment]
Interleaved grphics rendering is when the images are rendered under the text in separate layers. Look for draw_cells_interleaved_premult in
shaders.c. You create FBOs during rendering on demand and store them,
see that function for an example.
