### ISSUE TITLE
Can't map kitty_mod+plus to zoom in

### ISSUE THREAD

**Issue by daniel-pfeiffer** [kovidgoyal/kitty#1140]
On a german keyboard I set
```
kitty_mod ctrl+alt
map kitty_mod+plus change_font_size all +2.0
```
which doesn't work but gives me
```
Press scancode: 0x23 clean_sym: plus composed_sym: plus mods: ctrl+alt glfw_fallback_key: 93 (RIGHT BRACKET) xkb_key: 93 (bracketright)
on_key_input: glfw key: 93 native_code: 0x5d action: PRESS mods: 0x6 text: '' state: 0 handled as shortcut
```
apparently mapping to US keyboard.  No matter whether I switch to US layout or replace my 2nd line with or add
```
map kitty_mod+bracketright change_font_size all +2.0
```
It doesn't help.  I then get
```
Press scancode: 0x23 clean_sym: bracketright composed_sym: bracketright mods: ctrl+alt glfw_key: 93 (RIGHT BRACKET) xkb_key: 93 (bracketright)
on_key_input: glfw key: 93 native_code: 0x5d action: PRESS mods: 0x6 text: '' state: 0 handled as shortcut
```
but still no zoom.

Note 1: besides not being mnemonic, I can't type `kitty_mod+equal` on a german keyboard, because = is shift-0 and unless I switch to US layout the american = key doesn't work either.

Note 2:  I assume you haven't implemented this yet, but I'd love to map zooming to `ctrl+mouse4` & `ctrl+mouse5`

**Comment by Luflosi** [comment]
I'm using a german keyboard layout too and I'm using this for changing the font size:
```
map kitty_mod+RIGHT_BRACKET change_font_size all +0.5
map kitty_mod+MINUS         change_font_size all -0.5
map kitty_mod+0             change_font_size all 0
```
I can't remember how I figured out that I need to use `RIGHT_BRACKET`.

Instead of `kitty_mod+equal`, you can use `kitty_mod+shift+0`. @kovidgoyal Maybe there is some room for improvement to allow something like `kitty_mod+equal` or `kitty_mod+=` to work too? I don't know how difficult this would be to implement. Or maybe it is already possible and I'm just missing something.

@kovidgoyal needs to say something to note 2 as I have no idea (and also not a mouse with enough buttons).

**Comment by kovidgoyal** [comment]
there is no way to get the same shortcuts to work across all keyboard layouts, since the modifier keys needed to press a particular key vary by layout, not to mention that some layout simply dont have some keys. Use the appropriate shortcut for your layout in kitty.conf. In you case as luflosi said, it appears to be right_bracket

As for mapping scroll wheel to font size changing, not something I am interested in. (making mouse button mappings configurable in general -- which is the only way this would fly) is a fairly large task for relatively little return, there aren't that many mouse buttons to configure.

**Comment by timokau** [comment]
I feel like there may have been a misunderstanding. The issue is that in order to get kitty to increase the font size when I hit the keys "ctrl" and "+" (according to their label), I have to create the mapping `map ctrl+RIGHT_BRACKET change_font_size all +2.0`. Is that really intended? It sounds like you understood the issue as "I want to bind functionality to a keyboard position irrespective of the layout" instead.

**Comment by sachaz** [comment]
What is the configuration parameter to map mouse wheel to change font size ?
