### ISSUE TITLE
Glitch on first start. 

### ISSUE THREAD

**Issue by imjustpeachy** [kovidgoyal/kitty#1148]
Only on first start kitty has a graphical glitch. I tried to disable the compositor but the problem persists. I use i3-gaps with Compton. Distro: Arch Linux.

**Comment by imjustpeachy** [comment]
![videotogif_2018 11 17_12 06 27](https://user-images.githubusercontent.com/45119870/48660420-63afe800-ea61-11e8-8112-d102d5460a33.gif)

**Comment by maximbaz** [comment]
Wow, just out of curiosity try disabling transparency and see if it reproduces.

I don't know for sure, but I think this is caused by your graphics driver, I have a different glitch that is visible on resize and because it also reproduces in alacritty I think it's caused by my driver:

![kitty-resize](https://user-images.githubusercontent.com/1177900/48660616-e4241800-ea64-11e8-88ae-0c65b082c781.gif)

**Comment by imjustpeachy** [comment]
I tried ti disable the compositor and then trasparency but It persists. I use ATI Radeon drivers any ideas?

**Comment by kovidgoyal** [comment]
sorry no idea what could cause the glitch on startup. It certainly looks like an environment related issue either graphics drivers or window manager or some combination of the two. That said the recent fix for #1104 might be relevant, so you can try running from master.

@maximbaz that is expected behavior on resize, to avoid wasting CPU cycles kitty does not redraw itself on consecutive resize events but instead debounces them and only redraws when the resize is finishe/paused.

**Comment by Luflosi** [comment]
That black "background" which can be seen in @maximbaz's recording, is there is a way to change that colour? It would look better if it was the normal background colour, not black. But maybe it's just not worth the effort.

**Comment by kovidgoyal** [comment]
@luflosi, it is not worth the effort to me, but patches are welcome.
