### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1150]
Basically a duplicate of #778. The latest release (0.12.3) was released on 2018-09-29. That's almost two months or 50 days. There have been quite a few useful new features and bug-fixes since then. In #139 you mentioned that you release whenever you deem the time "suitable". Would "soon" be a suitable time? And how much work is required on your side to make a new release? I understand that you're a bit busy with other stuff and I'm sorry to bother you if you don't currently have the time to make a new release.

**Comment by kovidgoyal** [comment]
basically, I need to finish off the stuff mentioned at the end of #974 for the double scrollback system from @martinetd. I also would ideally like to wait for the release of wayland-protocols 1.17 since kitty now requires them for its wayland backend. Strangely enough wayland-protocols is released on the github project but not on its main website. Other than that, kitty is good to go.
