### ISSUE TITLE
Feature request: Allow embedding kitty in to other apps

### ISSUE THREAD

**Issue by diamond-lizard** [kovidgoyal/kitty#1151]
It would be great if kitty supported embedding, like xterm's -into feature.  To quote from xterm's man page:
```
-into windowId
      Given an X window identifier (an integer, which can be
      hexadecimal, octal or decimal according to whether it begins
      with "0x", "0" or neither), xterm will reparent its top-level
      shell widget to that window.  This is used to embed xterm within
      other applications.
```

This is used by [yeahconsole](http://phrat.de/yeahtools.html), for instance, to embed xterm and allow it to be used as a drop-down console.

To do this, yeahconsole will run something like:
```
xterm -b 0 -into 37748742 -name yeahconsole
```

I'd like to use kitty instead of xterm in yeahconsole, but without this feature I don't think it's possible.

**Comment by kovidgoyal** [comment]
Not something I am interested in personally, but patches are welcome. It
would be a little complicated, because unlike xterm, kitty is designed
to run on multiple platforms not just X11. THat means lower level stuff
is abstracted by a toolkit (glfw) and as far as I know glfw has no
support for X embedding. So you'd need to add that to glfw first and
then kitty could make it available.
