### ISSUE TITLE
Ignores space in escape sequences

### ISSUE THREAD

**Issue by egmontkob** [kovidgoyal/kitty#1153]
ECMA-48's

    8.3.121 SL - SCROLL LEFT
    Representation: CSI Pn 02/00 04/00

is incorrectly interpreted as

    8.3.64 ICH - INSERT CHARACTER
    Representation: CSI Pn 04/00

Similarly,

    8.3.130 SPD - SELECT PRESENTATION DIRECTIONS
    Representation: CSI Ps1;Ps2  02/00 05/03

is misinterpreted as

    8.3.147 SU - SCROLL UP
    Representation: CSI Pn 05/03

and so on for presumably many more.

Probably Kitty doesn't implement any of these escape sequences with a space inside, otherwise this bug would have been noticed earlier. Still, ideally the parser should be changed so that these escape sequences are silently ignored, rather than doing something else.

**Comment by kovidgoyal** [comment]
kitty does implement escape codes with spaces inside, for example the set cursor style escape code. I just have not bothered with filtering out CSI codes with invalid start or end modifiers, since these aren't actually seen in the wild. Space is just one case of a end modifier. Whenever I come across some program that actually generates these, I filter them out.
