### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by Luflosi** [kovidgoyal/kitty#1155]
Does kitty support reproducible builds? If so, I didn't find any mention of it on the website. If not, I think it should be supported. https://reproducible-builds.org might be helpful.

**Comment by maximbaz** [comment]
[It's not reproducible right now](https://tests.reproducible-builds.org/archlinux/community/kitty/kitty-0.12.3-1-x86_64.pkg.tar.xz.html), I'll have a look if I can fix this.

**Comment by maximbaz** [comment]
By the way, this issue should really be brought up with package maintainers, there's almost zero chance that anything will need to be changed in source code. Unless you are requesting provided binary releases to be reproducible, in which case I'd say it won't happen, that's something next to impossible to achieve because you'd have to precisely reproduce Kovid's environment and just doesn't worth the effort.

I'm looking into making Arch Linux package reproducible.

**Comment by maximbaz** [comment]
Turns out no python app can be reproducible today: https://bugs.python.org/issue29708

**Comment by Luflosi** [comment]
Yeah, I meant the binary releases in https://github.com/kovidgoyal/kitty/releases. But the packages of distributions would also be nice.
The python non-reproducibility is a bummer although the first comment in that issue says, that the `.py` files have to be touched for the issue to occur, so maybe it's not as bad as you might have thought. Would it be possible to not have the `.pyc` files in the binary release? Python would create them when kitty is run, right? But I guess there is some reason against doing that since many people don't seem to do that.

**Comment by martinetd** [comment]
If the pyc non-reproductible part is only the timestamp that can be worked around, distros like debian touch all the files to the date of the changelog entry in the package when building so all timestamps should be using that date.

However, looking at @maximbaz's build diff, I think we're falling into that other problem (from his issue link):
```
For what it's worth, in Endless OS we still saw slight variations between builds
in the .pyc files, even with all the source files' mtimes set to the epoch (ie.
equivalent to setting & supporting SOURCE_DATE_EPOCH, I believe). Looking at the
contents of the file suggested it was just reordering of class fields; indeed, we
only saw this on Python versions where hash randomization is enabled by default,
and disabling hash randomization made the output reproducible.
```

Apparently, setting `PYTHONHASHSEED` might help; haven't tested.

**Comment by maximbaz** [comment]
I confirmed locally that Arch Linux build is not reproducible, so I guess touching files is not necessary. In my case, the difference was due to different hash seeds - although it is possible to disable randomization, I'm afraid the general state of this is that Python is not reproducible yet. However I'll confirm with others tomorrow what they think we should do with Arch package

**Comment by kovidgoyal** [comment]
Probably just need to turn on https://www.python.org/dev/peps/pep-0552/

**Comment by kovidgoyal** [comment]
As for the original issue, making the binary builds reproducible, that is really not worth the effort. If you care about that, build kitty from source yourself.

**Comment by maximbaz** [comment]
Unfortunately https://github.com/kovidgoyal/kitty/commit/9991dd6ce440b9d38da566a533ff5a54caae4a8e doesn't help, so far only defining `PYTHONHASHSEED` makes my local reproducibility tests pass (setting it to any number, e.g. to `0`).

**Comment by kovidgoyal** [comment]
I dont really understand why field order needs to be randomized for classes in python. But yeah, this is not an issue that can be solved in kitty, it needs to be solved in python.
