### ISSUE TITLE
The `--program` option on the hints kitty yields silent failure

### ISSUE THREAD

**Issue by briandunn** [kovidgoyal/kitty#1171]
```kitty.conf
map kitty_mod+p>shift+c kitten hints --type path --program foo
```

foo is in my path once my dotfiles have loaded. I've also tried an absolute path, and for a moment it seemed to be working, but I can't reproduce. I've appended logging to the script every time it is executed. My program is not executed.

What additional steps should I take to diagnose?

MacOS 10.14.1
Kitty 0.12.3

**Comment by kovidgoyal** [comment]
remember that the PATH kitty sees is not the PATH you will have inside the shell, since you likely have code in your shell startup files tomanipulate PATH. So use an absolute path for your program and you should be fine.

If you want to debug, simply run kitty from inside a terminal and it will print errors to stdout or use console.app
