### ISSUE TITLE
vim reading send_text [left_arrow] and [left_arrow] differently

### ISSUE THREAD

**Issue by dermoumi** [kovidgoyal/kitty#1172]
Hello,

    map alt+h send_text all \x1b[D
Allows me to navigate through almost everything in kitty using hjkl-style keys except for vim.

I think that vim reads the `\x1b` (`^[`) part the same as ESC, leaves insert mode, and sends the rest as normal mode mappings.

Not sure i how I can overcome this, and why vim reads `\x1b[D` differently when sent through alt+h and through the left key.

I have also noticed that this doesn't happen in ssh and tmux sessions. Probably has something to do with key latency?

Thank you.

**Comment by kovidgoyal** [comment]
Not sure what you expect kitty to do about this? kitty simply sends bytes to the client. How they are interpreted is entirely up to the client. Also since vim anyway uses hjkl not sure why you need this there. 

Note that the bytes that the left arrow key sends depends on the current keyboard mode, which terminal programs can change. You should really be using something like:

```
map alt+h send_text normal \x1b[D
map alt+h send_text application \x1bOD
```

**Comment by dermoumi** [comment]
Thanks, the keyboard mode is apparently exactly what I needed!
