### ISSUE TITLE
Xterm/Urxvt style tab complete behavior?

### ISSUE THREAD

**Issue by ssbothwell** [kovidgoyal/kitty#1177]
This is really specific and I wouldn't expect anyone to put in work to change this if there isn't already a way to do it, but i thought I would ask just in case..

In XTerm and Urxvt the tab completion dialogue isn't triggered until you release the tab key. With Kitty, this happens immediately when you press the tab key.

Is there any way to change this behaviour? I use xcape to bind my tab key as a super key when it iscombined with other keys and the autocomplete dialogue causes problems.

**Comment by kovidgoyal** [comment]
I dont see this behavior in either urxvt or xterm. In fact I dont see how that behavior is possible. Traditional terminals such as xterm/urxvt dont have any way of reporting key release events at all. Each keypress/keyrelease combo generates only a single key event. And that key event cannot be on release, since if it was, key repeats would not work.

So I doubt the problem is with key release vs press.
