### ISSUE TITLE
glyph rendering different between installs

### ISSUE THREAD

**Issue by MeisterTea** [kovidgoyal/kitty#1194]
Hi, I think my issue is related to this one : https://github.com/kovidgoyal/kitty/issues/220

I have 2 computers, both on arch running kitty. Same kitty config for both.
One is displaying the glyphs as it should and the other is minimizing my prompt.
Any idea  (I have read the FAQ)?
Too small prompt >
![image](https://user-images.githubusercontent.com/19970734/49334789-94a22800-f5de-11e8-9301-2955798df53b.png)
okay prompt
![image](https://user-images.githubusercontent.com/19970734/49334795-bb605e80-f5de-11e8-8a1f-e192be8365d0.png)

**Comment by kovidgoyal** [comment]
Not sure what the problem is? are you saying th efont size is too small on one computer? If so font size is a function of the specified size in kitty.conf and the monitor DPI. If you mean that the prompt is different on the two computers, then the prompt is drawn by the shell, not kitty, you will need to check your shell rc files.

**Comment by kovidgoyal** [comment]
if the window size is not an exact multiple of the cell size, then you will get margins around the content, since kitty does not draw partial cells. as for glyph sizes being different, I have no idea, it could be because they are loaded froma  different font, or at a different cell size, etc. Use --debug-font-fallback to check for the former and adjust_line_height fo rthe latter.

**Comment by MeisterTea** [comment]
Thank's, the problem was that on the faulty install I had the mono version of DejaVuSans and it was used as a fallback. Removing it so it can use the other version fixed my issue.
