### ISSUE TITLE
Any screencast or video? + can't test the binary

### ISSUE THREAD

**Issue by BarbzYHOOL** [kovidgoyal/kitty#1204]
I'm trying to install the binary but it's not working

```
./kitty                                                                                                                            37ms|21:24:41
Traceback (most recent call last):
  File "python3.6/runpy.py", line 280, in run_path
  File "python3.6/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 96, in <module>
  File "kitty/__main__.py", line 89, in main
  File "kitty/main.py", line 10, in <module>
  File "kitty/borders.py", line 8, in <module>
ImportError: /tmp/kitty-0.11.0-x86_64/bin/../lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates

python -V                                                                                                                          27ms|21:24:55
Python 3.6.7
```

So instead I wanted to see some videos to see how good it is but I can't find any video o_0 this is crazy

**Comment by Luflosi** [comment]
One of your libraries is too old, see #992, #1125 and #595. You need to update it somehow.
I think I once found one video about kitty on youtube :/
But kitty is still my favourite terminal emulator :)

**Comment by erf** [comment]
Maybe add a svg screencast like [this](https://github.com/sharkdp/fd/pull/223) ?

**Comment by SolitudeSF** [comment]
its a terminal emulator, what is there to screencast?

**Comment by BarbzYHOOL** [comment]
> update to the next LTS ubuntu release. Or install freetype by hand

k was expected, so no I can't try it and a video would be nice

**Comment by Luflosi** [comment]
I wanted a faster terminal since my last terminal emulator (iTerm2) was too slow for me and kitty was on the first google search results page when I searched. I also found a few mentions of kitty in a few other places. So I'm surprised that you didn't find kitty earlier.
I highly recommend to try kitty out. I've installed freetype by hand on at least one machine before and it wasn't too difficult.
Here is what you need to do (haven't tested but should work):
- Go to https://download.savannah.gnu.org/releases/freetype/
- Find the latest version, that seems to be 2.9.1 at the moment
- Download `freetype-2.9.1.tar.bz2` or `freetype-2.9.1.tar.gz`
- Optionally verify the signature
- Unpack the file
- Read the installation instructions in `docs/INSTALL.UNIX`

**Comment by kovidgoyal** [comment]
whether you find kitty searching depends on the search terms. Usually searches for fast terminals will find it. As for creating a video -- maybe someday -- I really hate creating videos :( 

but yeah you just need to update freetype and the binaries will run. chances are somebody has created updates freetype packages for whatever distro you are on, just install those and you should be fine (freetype is pretty backwards comapt)

**Comment by erf** [comment]
@SolitudeSF perhaps features/settings of Kitty you won't find in other terminal emulators, performance comparisons to other terminals etc.

**Comment by SolitudeSF** [comment]
@erf https://sw.kovidgoyal.net/kitty website contains all relevant info

**Comment by erf** [comment]
@SolitudeSF not in a visual / animated way, but hey, just a suggestion ..
