### ISSUE TITLE
Is it possible to map a shortcut to new_os_window with a different startup_session?

### ISSUE THREAD

**Issue by nerdrew** [kovidgoyal/kitty#1219]
I'd like to have a shortcut that opens a new OS window but uses a different startup_session.

Something like:

```
map cmd+shift+p      new_os_window session=production-session.conf
```

Is that possible right now?

**Comment by kovidgoyal** [comment]
just run a new kitty instance. sessions are really only supported at starttup. Something like:

```
map f1 pipe none none kitty --detach --session whatever
```

the disadvantage is of course that you now have two kitty instances instead of a new window in one.

The other approach is to use the kitty remote control api with which you can duplicate the functionality of sessions. https://sw.kovidgoyal.net/kitty/remote-control.html
