### ISSUE TITLE
Resizing is slow/laggy when ﻿﻿background_opacity < 1

### ISSUE THREAD

**Issue by erf** [kovidgoyal/kitty#1227]
Resizing ( by dragging a corner with touchpad ) a window in kitty if `background_opacity` < 1, is very slow/laggy on macOS.

Resizing is fast, as expected, on an opaque background.

I'm on kitty version 0.13.1. ( empty kitty.conf except background_opacity )

**Comment by kovidgoyal** [comment]
I cannot reproduce. There is no perceptible difference resizing with or
without background_opacity. Indeed, while resizing on macos the only
difference between opaque and non-opaque is that kitty clears the window
when not opaque. This is because if it does not, macOS draws nothing
(see lines 121 onwards in glfw.c)

The only way resizing could be laggy is if your system cannot handle even
blanking the window in real time -- that would be pretty unusual. Given
that you have other artifacts with transparent windows that I cannot
reproduce, I'm guessing this is something specific to your system.
