### ISSUE TITLE
slightly wrong library name

### ISSUE THREAD

**Issue by pjz** [kovidgoyal/kitty#1235]
On starting kitty on Ubuntu 18.04 I get:
```
Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 216, in init_startup_notification
    return init_startup_notification_x11(window_handle, startup_id)
  File "/usr/bin/../lib/kitty/kitty/utils.py", line 201, in init_startup_notification_x11
    return init_x11_startup_notification(display, window_handle, sid)
OSError: Failed to load libstartup-notification-1.so with error: libstartup-notification-1.so: cannot open shared object file: No such file or directory
```
It seems the actual library is named `libstartup-notification-1.so.0`.  So that might be a thing to add to the search for which library to load.  I worked around by adding a symlink, but adding a search for a trailing `.0` would save other people some worries.

**Comment by kovidgoyal** [comment]
The actual library name is libstartup-notification-1.so.0.0.0
libstartup-notification-1.so.0 should just be a symlink to it and libstartup-notification-1.so
another symlink to that. For some reason the symlink is missing on your
system, that is really a bug in the system. However, since it is trivial
to also search for the alternate names, I can have kitty do that.

**Comment by pjz** [comment]
```
# ls -al libstartup*
lrwxrwxrwx 1 root root    30 Dec 14 11:10 libstartup-notification-1.so -> libstartup-notification-1.so.0
lrwxrwxrwx 1 root root    34 Dec 17  2017 libstartup-notification-1.so.0 -> libstartup-notification-1.so.0.0.0
-rw-r--r-- 1 root root 34744 Dec 17  2017 libstartup-notification-1.so.0.0.0
```
I added the first link to quiet down the error message I posted above.  The others already existed but that error message still showed up.

**Comment by pjz** [comment]
FWIW, it looks like on Ubuntu and Debian (maybe others - I only had those two handy to easily check), the `.so` file for libraries only exists if the `-dev` package is installed - otherwise there are only `.so.MAJOR` links and the  `.so.MAJOR.MINOR.PATCH` files that they point to.

**Comment by jamessan** [comment]
> FWIW, it looks like on Ubuntu and Debian (maybe others - I only had those two handy to easily check), the `.so` file for libraries only exists if the `-dev` package is installed

Yes, that's expected.  The plain `.so` file is installed only when building something, since _that_ name stays the same over time, even though ABI changes may make the runtime name change.

When building an object that links against the `.so` file, the linker records the SONAME in the object's dynamic section via a NEEDED entry.  At runtime, the dynamic loader searches for all the NEEDED libraries and loads them.  That's safe to do because they are the same ABI (if normal SONAME conventions are followed).

For dynamically opened libraries (not dynamically loaded), the library lookup is done manually in KiTTY's code and doesn't have the knowledge of what SONAME to expect when trying to load the library.  This can be problematic if something else has caused a different version of the library, with a different ABI, to also be loaded.

It would be better to build kitty/desktop.c (and whatever other necessary code) into a private module that kitty loads which _is_ linked against libstartup-notification.  This would ensure that the correct linker information is determined at build time for the private module, but KiTTY could still gracefully fail if the private module fails to `dlopen()` (e.g., due to libstartup-notification not being available).
