### ISSUE TITLE
Cannot correctly print ( ͡° ͜ʖ ͡°)

### ISSUE THREAD

**Issue by eepp** [kovidgoyal/kitty#1237]
kitty does not seem to be able to correctly print `( ͡° ͜ʖ ͡°)`.

More specifically, the eyebrows and smile are not printed:

![image](https://user-images.githubusercontent.com/1816705/50025261-e1a8d580-ffb2-11e8-85e1-6431eed5aaf2.png)

This is whatever the font and `adjust_line_height` I choose.

This is with Terminator:

![image](https://user-images.githubusercontent.com/1816705/50025374-52e88880-ffb3-11e8-9c6a-de32ca4adc3d.png)

**Comment by kovidgoyal** [comment]
This is never really going to work in kitty. In fact it does not work in terminator either. The correct rendering of it can be seen in chrome in the bug report title. The combining diacritic U+0361 should be over the space and the degree mark and the lower one should be under the nose, not to the left.

I will note that even chrome gets it wrong in the actual bug report when using monospaced fonts.

As for kitty, because of the way rendering in kitty works, complex, multi-character diacritics like U+361 are not going to work in kitty, as rendering is single cell based (with the exception of some ligatures).

**Comment by eepp** [comment]
ʕ  ͡° ʖ̯ ͡°ʔ
