### ISSUE TITLE
macOs Mojave can't open preferences

### ISSUE THREAD

**Issue by softinio** [kovidgoyal/kitty#1277]
When installing the binary on macOs Mojave I can't access the preferences at all. When I do `COMMAND+,` I screen shows for 1 second and then disappears.

Is this a known issue? 

Thanks

**Comment by liocer** [comment]
Does your original terminal go away too? I'm getting this with 0.13.1 from both Binary and compiled from latest sourcecode. Closing any window causes Kitty to segfault as does opening the configuration file with CMD+,

**Comment by kovidgoyal** [comment]
Works for me. You likely dont have an editor in the PATH used by macOS
launch services. Add a full path to an editor such as vim in kitty.conf
and you will be fine. Something like

editor /usr/bin/vim


Assuming vim exists and that is the editor you want to use.

**Comment by garymm** [comment]
Are there any requirements on the path pointed to by `editor`?
I have this in my kitty.conf. The script it points to works as an editor when I manually invoke it on kitty.conf and also works fine as git's editor.

```
editor /Users/garymm/bin/editor.sh
```

**Comment by page-down** [comment]
@garymm
> Are there any requirements on the path pointed to by editor?

Absolute paths need to be configured in version 0.25.2 and earlier, `~` will be supported in a future release.

> ... doesn't work for editing kitty's preferences.

Please elaborate. My guess is that a window opens and closes immediately.

The reason is the same as stated above your reply.
The environment variables inherited by the editor run directly by kitty are not the same as those run in a shell, unlike what you might expect.

https://sw.kovidgoyal.net/kitty/faq/#things-behave-differently-when-running-kitty-from-system-launcher-vs-from-another-terminal

Most likely the PATH is different and you want this:
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path

Or make sure that the path to the program executed in the editor shell script is correct (e.g. absolute path).

**Comment by garymm** [comment]
Ah yes the PATH was not what I expected when the editor script was invoked. Thanks!
