### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by geordieF** [kovidgoyal/kitty#13]
Kitty is nice at the moment, but is pretty daunting and gtk2 window frames are ugly. It would also fix the previous resize issue entirely, just by using GTK events instead of the current system.
I made a quick mockup in glade.
[TermMockup.zip](https://github.com/kovidgoyal/kitty/files/691608/TermMockup.zip)

**Comment by kovidgoyal** [comment]
kitty does not use GTK. Indeed kitty does not draw any window frames at all. It does draw a simple window border when you use a tiling layout, but that can be turned off in the configuration.

**Comment by geordieF** [comment]
No, GTK would be to contain the GL context
![Quic Screenshot](https://cloud.githubusercontent.com/assets/10172736/21743670/2954b9ae-d507-11e6-997c-2a2f44ad2e56.png)

**Comment by kovidgoyal** [comment]
Yeah, one of the design goals of kitty is to not use any GUI toolkits, thereby being a simple and dependency light, portable as possible. Also (while this is entirely a matter of taste) I like the fact that the tabbar in kitty is drawn exactly like a UI from a terminal program, rather than the typical GUI toolkit tabbar/scrollbars which I find out of place in a terminal. There is not doubt that this makes kitty a little less new user friendly, but that is a price I am willing to pay -- kitty is not really meant for someone that just occassionally uses a terminal but for a someone that lives in one.

**Comment by geordieF** [comment]
Right. I might make a fork of this, as I like having a hardware accellerated terminal, with a 4K display it is noticable.

**Comment by kovidgoyal** [comment]
Sure, feel free to do so. I can certainly understand that not everyone shares my tastes.
