### ISSUE TITLE
Us international keyboard: can't write á é í ó ú ñ

### ISSUE THREAD

**Issue by ggsalas** [kovidgoyal/kitty#1311]
Hi, I have configured my keyboard as US-international. With this configuration if I press `'` and then `a` the result is `á` but on kitty is `<00c3><00a1>`.  Similar issue I have to write ñ. 

I think there is a problem with locale and macos Mojave. Maybe I can set manually the locales on kitty. 

I have try to set a different locale on macos config:
![image](https://user-images.githubusercontent.com/8403993/51259779-9c017300-198b-11e9-8c39-48c87e1a8016.png)

If I select "Unite states" on my region, Kitty not display a locale error, but the issue persist:
![image](https://user-images.githubusercontent.com/8403993/51259991-06b2ae80-198c-11e9-85f2-2e2749eed687.png)

This is my keyboard config
![image](https://user-images.githubusercontent.com/8403993/51256830-12e73d80-1985-11e9-8d66-960161807c68.png)

I have read  https://github.com/kovidgoyal/kitty/issues/90 and https://github.com/kovidgoyal/kitty/issues/1233 but I haven't found a fix for my issue.

Also, on macos terminal is working well, but on Hyper-terminal I have same issue that I have with Kitty: 
![image](https://user-images.githubusercontent.com/8403993/51260199-8b053180-198c-11e9-8692-786c530a8a2e.png)

Thanks.

**Comment by kovidgoyal** [comment]
The way unicode input works on macOS is by pressing the option key and then another key to generate the accented text. You can enable that in kitty by setting macos_option_as_alt no in kitty.conf

**Comment by ggsalas** [comment]
I can do that on macos terminal app, for example with the ñ. But on kitty gives error (I can hear the error). I have try with and without ` macos_option_as_alt yes` option on kitty.conf

**Comment by kovidgoyal** [comment]
I cannot replicate on my mojave machine with us keyboard layout and
macos_option_as_alt=no pressing option+n and then n gives me ñ

**Comment by kovidgoyal** [comment]
Oh never mind, I think I misunderstood the issue. You can type the character, it just shows up as unicode escapes in your shell. Run cat instead of a shell and you will see that kitty is sending the correct utf-8 bytes for the key presses (set the shell to cat in kitty.conf). As for why your shell is mis-behaving, you will need to ask your shell's developers. Switch to using a different shell and you should be fine.

As for setting locale, you need to do it system wide, in the macOS preferences for it to have any effect on kitty.

**Comment by kovidgoyal** [comment]
I cannot reproduce, pressing option+` followed by s gives me s as expected.

**Comment by ggsalas** [comment]
The US international keyboard not requires to press option key, only `'a`  or `'s`

**Comment by kovidgoyal** [comment]
Or do you mean you want it to give you `s not just plain s? Dont really see why, if you wanted to type `s why would you press the option key in the first place?

**Comment by ggsalas** [comment]
to test this you need use this keyboard 
![image](https://user-images.githubusercontent.com/8403993/51294099-3abfbb00-19f0-11e9-8bd8-f2543766db86.png)

**Comment by kovidgoyal** [comment]
> The US international keyboard not requires to press option key, only `'a` or `'s`

ah ok, I was using plain US keyboard.

**Comment by lucasalencar** [comment]
I was having a similar issue where the unicode characters were not showing at all. Instead it was rendering an underline in place.

![image](https://user-images.githubusercontent.com/366659/52476743-ca3b3280-2b86-11e9-80f3-2675b8f3a9a0.png)

**Setting at my `.zshrc` `export LANG="en_US.UTF-8"` worked.** 
Without setting `LANG` and running `kitty --version` it returns the following warning:

```
$ kitty --version
[039 09:46:06.160191] Failed to set locale with LANG: en_BR.UTF-8
kitty 0.13.3 created by Kovid Goyal
```

Because my current locale is en_BR (BR because I am from Brazil), kitty couldn't find out the characters I guess.

I am using MacOS Mojave BTW.
