### ISSUE TITLE
Feature request: implement vt510 left and right scrolling regions

### ISSUE THREAD

**Issue by aaronduino** [kovidgoyal/kitty#1356]
The relevant ANSI sequences are [DECLRMM](https://vt100.net/docs/vt510-rm/DECLRMM.html) and [DECSLRM](https://vt100.net/docs/vt510-rm/DECSLRM.html).

This would allow programs to quickly scroll columns of text.

Without left & right scrolling region margins, I cannot think of anything faster than wiping the relevant portion of the screen and redrawing shifted text, which is *very* slow.

**Comment by kovidgoyal** [comment]
Those control sequences are fairly poorly designed/limited. They interact with other control sequences in undefined ways, and are mode (i.e. internal state) dependent. It would be far better to simply create new escape sequences that allow you to scroll text in arbitrary regions of the screen in a state independent, orthogonal fashion. That is you use a single escape sequence that specifies the region and amount to scroll at once, and does not otherwise rely on internal state in any way. Something for the new terminal-wg to ponder, I think.

And I will note that at least in kitty, redrawing the entire screen is not slow. This was one of the reasons I wrote kitty in the first place.
