### ISSUE TITLE
Bug with yank / redrawing output inplace

### ISSUE THREAD

**Issue by nickgronow** [kovidgoyal/kitty#1386]
I am sure this is not just with [yank](https://github.com/mptre/yank), but am including it for reference.  Yank allows you to yank the selected text to your clipboard.  It does this by allowing you to select the output that is piped to it from a previous command.  The issue is that it places this at the top of the window rather than drawing it in place like it does for other terminals.

This is how it is behaving in Kitty:

![image](https://user-images.githubusercontent.com/2894717/52868912-7a261800-3112-11e9-859a-59f0745d20aa.png)

As you can see, it is redrawing the selection of the piped output to the top of the window, right over previously rendered output.  In other terminals, such as Gnome, it behaves as expected:

![image](https://user-images.githubusercontent.com/2894717/52869123-f4ef3300-3112-11e9-861d-71909eaea784.png)

**Comment by kovidgoyal** [comment]
Sorry, I dont really have the time/interest to debug whatever the issue is with yank. Most likely, it is making some assumption about terminal behavior that does not apply to kitty, instead of using terminfo.

If you want to select arbitrary text from the terminal screen using the keyboard use the hints kitten, which is a lot more powerfulk than yank. https://sw.kovidgoyal.net/kitty/kittens/hints.html
