### ISSUE TITLE
Nemo "Open in Terminal" opens home dir instead

### ISSUE THREAD

**Issue by Strum355** [kovidgoyal/kitty#1412]
Related issue in https://github.com/gnunn1/tilix/issues/162#issuecomment-199329035

**Comment by Luflosi** [comment]
Could you provide a bit more information please? Which kitty and OS version? And how is kitty being executed by Nemo? On my machine with macOS, if I open a terminal, change the directory (cwd) and then start kitty from that terminal, kitty keeps the directory and doesn't open with the home dir. So kitty does not seem to have the same bug that was fixed in the issue you linked.

**Comment by Strum355** [comment]
Ah i believe this may be because of https://github.com/fish-shell/fish-shell/issues/5647, `pwd` shows the right directory in bash

**Comment by Luflosi** [comment]
Did updating fish fix your issue?

**Comment by Strum355** [comment]
it did, 3.0.2 fixes this issue :+1: thanks for your help
