### ISSUE TITLE
environ issues on macOS

### ISSUE THREAD

**Issue by dedelala** [kovidgoyal/kitty#1448]
using `kitty 0.13.3`  and `osx 10.13.6`
I can't repro this on my linux machine.

Run `kitty @ new-window sh`
`PATH` and other env are not set correctly.

This can be worked around by running `kitty @ new-window sh --login` _however_, in my real use case I am invoking `kitty @ new-window kak`, `kak` is in `/usr/local/bin`, which is not in the `PATH` in the new window.

Result: :crying_cat_face: no such file or directory.

It seems reasonable to expect that any program in my `PATH` can be invoked in a new window.

**Comment by kovidgoyal** [comment]
If you set your PATH in your shell rc files rather than system-wide, then
obviously, that PATH will not show up when running programs other than
your shell or the shell in non login mode. 

Set your PATH system-wide and you will be fine. I'm not a macOS user so
I dont recall the exact procedure for this, but it will likely involve
futzing with launchd.
