### ISSUE TITLE
feature request: when scrolled back, do not clear selection in response to new output

### ISSUE THREAD

**Issue by eldentyrell** [kovidgoyal/kitty#148]
Hi, I often open tons of terminal windows that are watching logs (tail -F).  Many times I will scroll back in these windows and copy some text.

The MacOS Terminal.app (which I am trying to use Kitty to replace) will let me copy text even while more log output is being appended, including newlines.  This is one thing Terminal.app does really well.

Unfortunately kitty clears the selection whenever new text (or perhaps just additional lines) are appended to the terminal.  Is there a way to disable this behavior?

I looked into implementing this myself but there's a lot that isn't clear about how selection is handled.  In particular, what notion of "dirtiness" does is_dirty refer to?  Are the coordinates in SelectionBoundary with respect to the current scrollback position (and therefore invalidated by scrolling) or absolute (and therefore invalidated by additional newlines being sent to the terminal)?

**Comment by kovidgoyal** [comment]
I just use Ctrl+Shift+h when I want to copy from a window generating content continuously. That opens the current content + scrollback buffer in a new window (in the kitty sense of window) under a pager (by default less) allowing for comfortable copying/searching/etc. of the text.

Currently the selection is cleared when there is any change to the window contents. This is the most performant design. Otherwise, you have to track and update the selection area on scroll. You also have to resend the selection area to clipboard every time any change occurs (on platforms such a X11 where there is a primary selection). It should not be particularly hard to implement updating the scroll area on newlines, but I personally prefer using ctrl+shift+h

If you do want to implement it, you would need to add some code to INDEX_UP and INDEX_DOWN macros to update the selection boundaries. Screen->is_dirty is set to true when any change occurs so you cannot use it anymore to clear selections. I suppose you would then have to clear selections only on click and screen clear/reset.

**Comment by eldentyrell** [comment]
> That opens the current content + scrollback buffer in a new window (in the kitty sense of window) under a pager (by default less) allowing for comfortable copying/searching/etc. of the text.

Yes but if the scrollback buffer is huge you will have to go find (in your editor in the new tab) the line you were looking at in the original tab.  If the log output consists of lots of nearly-identical lines this is a big time-waster no?

> If you do want to implement it, you would need to add some code to INDEX_UP and INDEX_DOWN macros to update the selection boundaries. Screen->is_dirty is set to true when any change occurs so you cannot use it anymore to clear selections. I suppose you would then have to clear selections only on click and screen clear/reset.

Thanks for this insight.  Could you respond regarding the interpretation of the selection coordinates in my original question?  An intermediate solution I was thinking of is to clear the selection whenever the character cells it encompasses are modified.  This would preserve the current high performance design while allowing stable selection so long as you've scrolled back at least one line (which prevents new lines added to the terminal from shifting all the char cells upwards).  But whether or not it works depends on if the selection boundary coordinates are relative to the displayed char-grid or relative to the bottom of the scrollback buffer.

**Comment by kovidgoyal** [comment]
On Thu, Oct 19, 2017 at 05:45:43AM +0000, eldentyrell wrote:
> Yes but if the scrollback buffer is huge you will have to go find (in your editor in the new tab) the line you were looking at in the original tab.  If the log output consists of lots of nearly-identical lines this is a big time-waster no?

Not really, I am in the habit of using ctrl+shift+h whenever I want to
explore the scrollback buffer. I find exploring the buffer in a
pager/editor far more comfortable than in a terminal directly.

> 
> > If you do want to implement it, you would need to add some code to INDEX_UP and INDEX_DOWN macros to update the selection boundaries. Screen->is_dirty is set to true when any change occurs so you cannot use it anymore to clear selections. I suppose you would then have to clear selections only on click and screen clear/reset.
> 
> Thanks for this insight.  Could you respond regarding the interpretation of the selection coordinates in my original question?  An intermediate solution I was thinking of is to clear the selection whenever the character cells it encompasses are modified.  This would preserve the current high performance design while allowing stable selection so long as you've scrolled back at least one line (which prevents new lines added to the terminal from shifting all the char cells upwards).  But whether or not it works depends on if the selection boundary coordinates are relative to the displayed char-grid or relative to the bottom of the scrollback buffer.

Tracking cell level changes is a much worse performance hit than simply
updating the buffer. The problem is that there are all sorts of command
codes that can alter cell contents, such as erase line, erase screen,
erase from cursor, etc.

The selection object stores the x, y and scrolled by values for the
start and end of the selection. The x and y values are relative to the
stored scrolled by value. Therefore when translating the selection into
actual co-ordinates in the line buffer, you modify the y co-ord by the
difference between the stored scrolled by and the current scrolled by.

**Comment by wjakob** [comment]
I'm not sure if this is related -- I'm having difficulties copying text when scrolling back, even when there is *no* shell output in the meantime. What seems to happen is that ``kitty`` is off by one line, which causes it to copy the wrong text (even though the visual selection is in the right place). Copying from the same screen (i.e. without having used ``scroll_page_up``) works without problems.

**Comment by kovidgoyal** [comment]
update, this was fixed a while ago.

**Comment by toonn** [comment]
Does `S-C-h` work with curses programs, like irssi? Terminology from the enlightenment project actually does this really well, much better than Terminal.app, kitty, gnome-terminal, any other terminal I've used.
It'd be great if kitty could copy that behavior.

**Comment by kovidgoyal** [comment]
I dont see how S-C-h or indeed anything, could possibly do that with full screen applications, as there is no scrollback buffer there. When in alternate screen mode, you cannot scroll using the terminal's scroll features.

**Comment by kovidgoyal** [comment]
While it is not a direct fix that commit fixes the underlying reason for this feature request, namely that opening the scrollback buffer in less after already being scrolled means you have to scroll all the way back to find your place. That is no longer the case.

**Comment by toonn** [comment]
Well, if you'd check terminology's behavior in something like irssi you'd see what I mean. The selection scrolls along with the text, even while you're selecting.

**Comment by kovidgoyal** [comment]
I dont know about irssi, but that works fine in full screen applications that have mouse support in kitty as well, for example, vim.

**Comment by toonn** [comment]
Why doesn't terminology require an irssi plugin for this behavior though?

**Comment by kovidgoyal** [comment]
Are you sure it doesnt? On my system running irssi inside terminology and dragging witht he mouse does not scroll.

**Comment by toonn** [comment]
That's not what I meant. When I select something in irssi and a new line comes in, kitty clears the selection, which makes copying something quite uncomfortable. Terminology on the other hand has the selection move up along with the text even while you're still dragging, it's like the cursor moves up along with the text as long as you're dragging. (Not a very clear explanation and it may not sound useful/simple but it's actually really nice UX.) This means I can easily select something and then copy it to the clipboard while in kitty I currently have to race to select-and-copy before anything else is said.

**Comment by kovidgoyal** [comment]
Umm, that's what this whole issue was about. As I said before, simply press C-S-h and copy peacefully to your hearts content, it works fine with irssi as well.

**Comment by toonn** [comment]
That's not as convenient though. And not at all discoverable behavior.
Should I open a new issue as a feature request for this?

**Comment by kovidgoyal** [comment]
Oh and let me elaborate on why I think kitty's solution is much superior:

1) It is much harder to select text precisely when the text is moving/changing under you
2) It is much easier to search/scroll/navigate the scrollback buffer from a pager. For instance you dont have to hold down ctrl+shift to scroll. You can search for the text you want to copy.
3) A solution like terminology lies about what has been copied. Try the following experiment:

Run `sh -c 'printf bad; sleep 5s; printf "\rgood"'`

select bad with the mouse, wait five seconds, bad will change to good. Now middle click somewhere else to paste. Even though godd is selected, bad will be pasted.

**Comment by toonn** [comment]
Actually, the selection is cleared when overwritten and the primary contains the most recently selected text so that's perfectly logical and expected imo.

It's not harder to select the text when it's moving in terminology because the selection moves up with the text, even though your cursor does not. So scrolling text doesn't automatically mean extra text is selected if you don't move the cursor (this is a brilliant feature ime).

Opening the pager, selecting and then closing the pager is a lot less streamlined than just dragging a selection imo. I understand performance is one of kitty's main concerns but imo that shouldn't come at the cost of usability, I'd much rather have the machine waste cycles than me.

**Comment by maximbaz** [comment]
This debate is pointless, it was already mentioned a few times that PR will be accepted, it's now only a matter of finding a person who is interested enough in this feature to submit the PR 🙂

> it is on my TODO list to replace less with a custom pager that allows selecting directly using keyboard shortcuts for movement, like in vim.

Oh that would be so cool! Shortcuts for movement, selection and yank 🙂

**Comment by toonn** [comment]
I'm still not convinced you've seen the terminology behavior in action because the point at which you want to stop moving the mouse doesn't change, that's the whole point of the feature. You should really check it out in a busy irc channel in irssi in terminology if you want to see what I'm talking about.

Alternatively, being able to copy links with a right-click would relieve part of the inconvenience for me. Kitty already makes it easy to select urls but the selection is cleared when a message comes up so the usefulness is limited (for my use case specifically). Should I open a new feature request for this?

**Comment by toonn** [comment]
@maximbaz I'm fine with that but I want to make sure kovid really understands the feature so he can make a better judgement on whether or not he wants to implement it. Being the maintainer and original author of kitty it'd be much easier for him to implement this than anyone else.
So as long as kovid doesn't end the discussion I don't see a problem continuing it.

**Comment by kovidgoyal** [comment]
I have seen it, and I'm afraid I am not convinced.

As for selecting URLs, I'm confused, the moment you select it, it is already copied regardless of whether it is cleared later or not. So what's the problem? Though if you want to really copy URLs fast, use the hints kitten, it doesn't get faster than that.

**Comment by toonn** [comment]
I never use the primary selection for copy-paste, too easily changed by accident and it's not available on mac os.
Didn't know kitty had hints, that's useful. Don't know how to activate them though, is there online kitty documentation? My kitty, installed with brew, doesn't come with a man page.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/

And kitty has a setting to make selection copy to clipboard on macOS

**Comment by toonn** [comment]
Thank you, two more questions I don't have a more appropriate place to ask.

`C-S-p nor C-S-f nor C-S-p>f` seem to work for me to enter path hinting mode, am I reading the shortcut wrong?

Found `C-S-u` by accident trying to enter the one above but I can't navigate the 'Search by' categories because mac os maps the function keys to things like brightness and I can't figure out how to pass the literal Fkey trhrough. Is there another way to change the "tab"?

**Comment by kovidgoyal** [comment]
You need to press C-S-p then leave all keys. Then press f. 

You should be able to generate function key presses by pressing some modifier on your mac, typically a key named fn.

**Comment by kovidgoyal** [comment]
Yes, that is correct.

**Comment by maximbaz** [comment]
Thank you for making this happen in https://github.com/kovidgoyal/kitty/commit/d72098bdf82fee8a788aa1b59d9c162545b7606e @kovidgoyal, although Ctrl+Shift+H is usually superior, sometimes just selecting stuff with the mouse is all we need. Works perfectly!

**Comment by kovidgoyal** [comment]
You're welcome :)

**Comment by CMCDragonkai** [comment]
I have a similar request to this. But it's more that I can usually select text, move my cursor to the top edge of the screen, and have the terminal scroll up to get back my text so I can select and copy larger than a terminal size. However this doesn't seem to be possible. Even if I use `Ctrl+Shift+H`, the less pager has no notion of clipboard either. It could probably be done if the pager used was vim instead though. But this seems like it is more difficult than it should be.

**Comment by kovidgoyal** [comment]
You can simply drag with the mouse to select text off the top edge of the screen.

**Comment by Ekats** [comment]
I fixed it in my kitty-meow fork
