### ISSUE TITLE
macOS emoji picker

### ISSUE THREAD

**Issue by adamyonk** [kovidgoyal/kitty#1508]
Is it possible to enable this emoji picker (`⌃ ⌘ ␣`) inside of kitty on macOS?

Screenshot of iTerm:
<img width="880" alt="Screen Shot 2019-03-28 at 10 17 03 AM" src="https://user-images.githubusercontent.com/33258/55169417-bea9c800-5142-11e9-95a1-5130e8998221.png">

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/kittens/unicode-input.html

**Comment by Luflosi** [comment]
While the unicode input kitten also allows entering unicode characters, it's not the native macOS unicode input, which works in most other applications. How does IME input work on macOS? It might be similar.

**Comment by kovidgoyal** [comment]
Sorry, I'm not interested in supporting platform specific emoji pickers.

**Comment by Luflosi** [comment]
Fair enough.

**Comment by adamyonk** [comment]
👍 Thanks for the info!

**Comment by zharmany** [comment]
I noticed that in macOS, [#8195](https://github.com/kovidgoyal/kitty/pull/8195) also enabled the use of the native macOS emoji picker. For better or worse, I had been using `ctrl-cmd-space` as a sort of leader or prefix key for Kitty since it explicitly did not support the emoji picker. 

I was able to work around this by reassigning the "Emoji & Symbols" menu item to a different keyboard shortcut, which allowed me to continue to use `ctrl-cmd-space` in Kitty.
