### ISSUE TITLE
Why do some python files use `#!/usr/bin/env python` and others use `#!/usr/bin/env python3`?

### ISSUE THREAD

**Issue by nerdrew** [kovidgoyal/kitty#1512]
I built kitty for mac os `make app` and it doesn't have `/usr/local/bin` on the path, so it can't find my homebrew installed python3, which seems to be required for my custom kittens. I added `/usr/local/bin` to the `PATH` by setting it in `LSEnvironment` in `Info.plist`, but it is confusing that kitty boots at all if it can't find python3 on my system.

**Comment by nerdrew** [comment]
FWIW: This is the change I made to get my kittens to work:

```
--- a/setup.py
+++ b/setup.py
@@ -719,7 +719,10 @@ Categories=System;TerminalEmulator;
             NSHighResolutionCapable=True,
             NSSupportsAutomaticGraphicsSwitching=True,
             LSApplicationCategoryType='public.app-category.utilities',
-            LSEnvironment={'KITTY_LAUNCHED_BY_LAUNCH_SERVICES': '1'},
+            LSEnvironment={
+                'KITTY_LAUNCHED_BY_LAUNCH_SERVICES': '1',
+                'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'
+                },
```

**Comment by kovidgoyal** [comment]
If you want to run kitty from source, you should have python (and ideally python3) in your PATH already. Otherwise, the kitty binaries ship with their own copy of python.

You should add /usr/local/bin to your path system-wide, or simply create symlinks to python/python3 from some directory already in your PATH. Of course modifying LSEnvironment will also do the trick, but this is not a general solution because it would override the system PATH with a hardcoded value.
