### ISSUE TITLE
macOS: v0.4.1 Keymap control codes seem to be QWERTY-only

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#153]
I'm using version 0.4.1 from the github releases page.

Any `control+key` sequence seems to type `control + (whatever the qwerty version of the key is)`

I've tested this by observing what control codes are typed in `cat` on these keyboards:

- QWERTY
- Colemak
- Dvorak
- Belarussian

This issue doesn't appear with `alt+key`. It appears in v0.4.0 as well, but not v0.3.0

**Comment by kovidgoyal** [comment]
As far as I know, kitty has never supported exotic keyboard layouts. See for example #74 

GLFW, the graphics toolkit kitty uses has pretty poor keyboard handling. Look at the get_localized_keys() function in keys.c That is where kitty tries to work around glfw's lack of proper key handling. Basically the key code reported by glfw is passed to glfwGetKeyName which is supposed to give the keyboard layour dependent name. That is then used instead of the original key code. Presumably, for some reason it si failing on your system. Stick some printf() statements in there and see what is happening.
