### ISSUE TITLE
Pushing the limits of Kitty's reliability

### ISSUE THREAD

**Issue by atomsymbol** [kovidgoyal/kitty#1552]
_Originally posted by @kovidgoyal in https://github.com/kovidgoyal/kitty/issues/1546#issuecomment-485441960_

>> I believe you are living in a fantasy world that isn't the real world: #1551

> Are you high?

No. Are you?

> Even if it was an actual bug, how would it cause you to lose work?

At some point in the discussion a rational person would have realized that I am talking about the quality of Kitty in general, instead of still talking about the specific issue that was mentioned earlier.

You are starting to make unnecessary mistakes and are starting to be irrational when faced with opposition that is telling you that the testing procedures of your software are insufficient.

You are closing bugs that are reported against the git-tip version of Kitty. An interesting question is how it is possible that **your testing and verification procedures allow you to commit code of questionable quality**.

Thank you for developing Kitty. I appreciate it and strongly believe that you will make Kitty more reliable in the future.

Try harder.

Sincerely
Jan

https://en.wikipedia.org/wiki/Availability
https://en.wikipedia.org/wiki/Graphical_user_interface_testing
https://en.wikipedia.org/wiki/Random_testing
https://en.wikipedia.org/wiki/Robustness_(computer_science)

**Comment by atomsymbol** [comment]
Closing.

**Comment by Luflosi** [comment]
I agree that kitty is not very well tested at all besides manual testing. That seems to have worked mostly ok til the latest release. There have been some somewhat large changes to certain internals recently and some of those seem to cause some issues, as you noticed. That's why it has been 93 days since the last release (0.13.3), the longest ever as far as I can tell from `docs/changelog.rst`. The second longest time between two releases was from 0.12.3 to 0.13.0 with 63 days. I'm trying to track down a bug where kitty freezes (might be macOS only) myself but since it can take several days for that to happen, it takes a very long time to bisect which commit causes the freezes. You're also free to bisect the commits yourself and find which commit causes a certain issue. I'm sure @kovidgoyal would also be happy to have some more automatic tests. A couple months ago I wrote a super simple fuzzer since I heard a university lecture about fuzzers and found a couple bugs, that were then fixed. I should probably develop that fuzzer some more but I didn't have much time and motivation to do so.

IMHO some of your comments came across a little rude, like
> Reopen this issue -- or choose to remain in the fantasy world.

But that's just my opinion.
I'm sure that you didn't mean to be rude.
I can understand if you were frustrated, that your issue #1551 was marked as a duplicate of #1550 and not immediately fixed. #1550 itself was closed because it is a known issue reported in https://github.com/kovidgoyal/kitty/issues/461#issuecomment-483083324, which is likely caused by the event loop refactoring described in https://github.com/kovidgoyal/kitty/issues/461#issuecomment-483091044. I'm sure @kovidgoyal experiences this issue himself so he won't forget it despite no open issues as far as I can tell. @kovidgoyal wants to investigate and the issues with the event loop and believes, that doing so will cause #1550 and #1551 to be fixed as well. If you still have the same issues after that fix, you can leave a comment on those issues describing that. In the meantime, you can just wait for that to happen, investigate the issue yourself or use an earlier version that doesn't have the issue yet.
You have to also understand, that kitty had no 1.0 release yet and thus is not considered completely "stable" (please correct me if I'm wrong, @kovidgoyal). You're also using the latest master, which has a higher chance of being unstable that the latest 0.13.3 release.

All that said, this is a project on GitHub, so if you think that the testing code is insufficient and want to improve it, feel free to open a pull request to improve it. kitty is also free and open source software, so if you want to do something, that @kovidgoyal doesn't want to incorporate into the main codebase, you can just create your own fork and do it there.
