### ISSUE TITLE
Memory blowup when resizing window on i3

### ISSUE THREAD

**Issue by TheJJ** [kovidgoyal/kitty#1557]
Some of my kitty windows with much output in them eat really a lot of ram (3GiB).
```
scrollback_lines 262144
```

I've noticed that the memory consumption is somehow correlated with window resizing. My window resizing happens instantly (with i3), not gradually (by mouse). The 3GiB window now uses 2.5GiB after I've halfed its width and restored it afterwards. Something is going on there :)

I think I've had this behavior since I use kitty, so this issue probably predates v0.8.0.

Any suggestions how I can narrow this down further?

**Comment by kovidgoyal** [comment]
The scrollback buffer's size depends on the window size, since the length of each line in the buffer depends on the width of the window. If you wish to store large amounts of scrollback, you should instead use the scrollback_pager_history_size option which stores scrollback history more efficiently.

As for the change in memory it is most likely just malloc not returning freed memory to the OS immediately, but if you wish to debug the memory allocations, the relevant code is in screen.c and history.c

**Comment by TheJJ** [comment]
Thanks, I'll see what I can figure out :)
Assuming all scrollback lines are in use, that would mean that my kitty roughly uses use:

```
3*1024**3 / 262144 = 12KiB
```

I doubt that 12 KiB _per line_ is the intended storage need.

**Comment by kovidgoyal** [comment]
Well, IIRC a single cell takes about 24 bytes (there are three 4 byte colors, two four byte unicode characters, and misc other attributes. So if your line is approx 500 cells long, then 24 * 500 = 12KB

**Comment by TheJJ** [comment]
Hm that would actually make sense, thank you. I think we can close this, I'll report back if I actually get proof some of leaking memory.
