### ISSUE TITLE
feature request: clipboard over mosh

### ISSUE THREAD

**Issue by stites** [kovidgoyal/kitty#1558]
Thanks so much for writing and maintaining kitty! I noticed that the clipboard works over ssh but not [mosh](https://mosh.org/) -- which has a few nice benefits over vanilla ssh. I'd like to make a feature request for this support.

If you think this would be a cut-and-dry request, I would love to add this feature myself! I would probably need a bit of hand-holding, however.

**Comment by kovidgoyal** [comment]
kitty supports OSC 52, which is an escape sequence that can be used by
terminal programs to read/write the clipboard. This support is not
specific to ssh/mosh or any other program. If it is not working in 
mosh it is likely mosh is filtering it out for some reason. This would
need to be fixed in most itself.

**Comment by glensc** [comment]
Found this commit from mosh repo:
- https://github.com/mobile-shell/mosh/commit/4b240ac033db29de4349a4fe9658ff13b54f5960
