### ISSUE TITLE
remote set-background-opacity affects only one window of the instance

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#1581]
I'm running kitty with multiple main windows in one instance and listening on UNIX socket (`--single-instance --listen-on unix:/tmp/mykitty`) and trying to control it remotely (`@ --to unix:/tmp/mykitty`) from outside. I noticed the following inconsistency when running remote commands: `set-font-size` changes font in ALL windows but `set-background-opacity` only affects one window (I guess the first one opened).

When sending remote command from *inside* one of the windows, `set-font-size` affects ALL windows and `set-background-opacity` affects only *current* window.

**Comment by kovidgoyal** [comment]
That's because you cannot set font size independently in kitty windows.
You can in top-level OS windows, but not in windows inside a top level
window. And even that ability is relatively new, it wwas added after that
command was created.

I could add an option to that command to have it apply only to
the active top-level window and all it's sub-windows.

**Comment by sergei-dyshel** [comment]
Thank's for quick response :smile:
Now `set-font-size` and `set-background-opacity` behave consistently.
