### ISSUE TITLE
Box drawing characters are offset by a pixel

### ISSUE THREAD

**Issue by vlisivka** [kovidgoyal/kitty#16]
Box drawing characters are inconsistent in mc: horizontal line is not continuous, some vertical characters are offset by 1 pixel. Run mc and look at bottom right corner.

**Comment by kovidgoyal** [comment]
Yes, but unfortunately I know of no easy way to fix this. The problem is that rendering is done by freetype using whatever unicode font has those symbols on your system, I  know of no way to force freetype to align those symbols -- whether they are aligned or not seems to depend on how they are defined in the font and the font size the font is rendered at (rasterization algorithm in freetype depends on font size).

So this will take some investigation. For anyone interested, the rendering code is in freetype.py and you can use the test_rendering() function, like this:

```
kitty -c "from kitty.fonts.freetype import *; test_rendering(text='some test text', sz=20, family='whatever font you are using')"
```

**Comment by kovidgoyal** [comment]
After investigating this issue a bit, I think the best approach is to directly draw the box drawing characters rather than using freetype. That way, it will work consistently on all system regardless of the availability of fonts, font rendering engine, hinting, anti-aliasing, etc.

**Comment by vlisivka** [comment]
Box drawing characters can be drawn without freetype, directly, like in other unicode terminals. They are just lines. This will eliminate any problems with them.

**Comment by kovidgoyal** [comment]
That's what I said in my previous post
