### ISSUE TITLE
Full screen kitty minimizes after it loses focus to another application

### ISSUE THREAD

**Issue by Keyframe** [kovidgoyal/kitty#1602]
Gnome3/PopOS setup with multiple monitors. This is extremely annoying - is there something one can do about it?

**Comment by kovidgoyal** [comment]
No idea. kitty does not control what happens to it after it loses focus, that's up to the window manager. Not ethat in kitty fullscreen mode is native fullscreen which means it takes over theentire screen for maximum preformance. You might be refering to fake fullscreen mode, where the window manager just maximizes a window and hised the chrome fo the rest of the desktop. If so use the keyboard shortcut for fullscreen provided by your window manager rather than the kittynative one.

**Comment by Keyframe** [comment]
which one is ctrl+shift+f11? It might be due to how glfw sets itself up.

**Comment by Luflosi** [comment]
I experienced something similar and also used <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f11</kbd> (I think) but since I rarely use Linux with a graphical interface and I never used any other program in fullscreen (and still haven't), I assumed this was normal.

**Comment by kovidgoyal** [comment]
As I said use whatever mechanism your window manager has for fullscreen and you should be fine. ctrl+shif+f11 will takeover the screen it corresponds to the "native fullscreen" it wil lbypass your window manager.

**Comment by marcelroed** [comment]
> Gnome3/PopOS setup with multiple monitors. This is extremely annoying - is there something one can do about it?

Did you figure this out @Keyframe? I'm having the same issue with Wayland multi-monitor GNOME 3.40.
