### ISSUE TITLE
Strange mouse behavior in ncmpcpp

### ISSUE THREAD

**Issue by maksbotan** [kovidgoyal/kitty#167]
Hi! Sorry for another strange issue from me :)

I use `ncmpcpp` MPD client as my music player. Here on the screenshot you can see progress bar of the current song in the bottom:

![screenshot-12-03](https://user-images.githubusercontent.com/275614/32697445-95b8b13a-c7a1-11e7-8342-0ee8b96f2bd4.png)

`ncmpcpp` allows to click with mouse on this bar in any position to scroll the song to that position -- very handy. But when I try to do this in kitty, I suddenly get to `ncmpcpp`'s search engine, as if I pressed `3` on the keyborad, and of course no scrolling hapens. At the same time, `ncmpcpp` in `xterm` reacts correctly to the click.

How can I debug the issue and provide you additional information? I'm running kitty from master commit 8431eef970afb84d10ca5a29052c08417d780f26 with `glfw` from master as well (to get clipboard without `xsel`).

**Comment by kovidgoyal** [comment]
This will be a mismatch between mouse event  encoding in kitty and ncmcpp. The problem is that there are several existing mouse protocols. I know the oldest and newest work as they are used by htop and vim respectively and I use them myself in kitty. Probably ncmcpp is using one of the middle ones. Simplest way to debug is to first run kitty with --dump-commands and then look for the command that sets the mosue protocol version. Then write a small script that simply sets that protocol version and outputs any bytes received from the terminal so you can see the difference between xterm and kitty. And then finally fix the problem in encode_mouse_event() in mouse.c (or you can skip the --dump-commands part and just insert some printf() in encode_mouse_event() to see which protocol is being used).

**Comment by maksbotan** [comment]
Adding this `printf`:

```c
printf("MOUSE %d\n", screen->modes.mouse_tracking_mode);
```

I see output "`MOUSE 1`". So if I understand the code correctly, `UTF8_PROTOCOL` is used.
By the way, when I click in `ncmpcpp`, i get __two__ "`MOUSE 1`" lines in the output, as if there were two mouse events. And in fact, before it shows search screen I see a fast flash of some other screen which I can't identify.

**Comment by kovidgoyal** [comment]
There are all sorts of mouse events, move/press/release/drag. So the number should not matter. I have never tested the UTF8_PROTCOL, so it's quite possible there is a bug in there.

**Comment by maksbotan** [comment]
Can you give me some directions on how to debug this? Description of protocol for example or how to write that simple script you mentioned.

**Comment by kovidgoyal** [comment]
Protocol documentation is all at http://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking

Your script would send the command to turn on mouse tracking and switch to UTF8_PROTOCOL. Then it would simply output the bytes it receives on stdin. You click and see what bytes it generates. Presumably they will be different in xterm and kitty, that should tell you what needs fixing.

**Comment by maksbotan** [comment]
Okay, thanks, will try. By the way, when I launch `ncmpcpp` I get the following error from `kitty`:

`[PARSE ERROR] CSI s in private mode not supported`

**Comment by kovidgoyal** [comment]
That's a device status query -- it might be used internally in ncmcpp to try to detect terminal emulators. Should be harmless to ignore.

**Comment by kovidgoyal** [comment]
And here is a script (python2)
```py
import sys

sys.stdout.write(b'\033[?1000h\033[?1005h')
sys.stdout.flush()
print(repr(raw_input()))
```

**Comment by maksbotan** [comment]
Please see my PR. There's also a bug in URXVT protocol :)
