### ISSUE TITLE
Shell prompt duplicated on every window resize

### ISSUE THREAD

**Issue by valentjedi** [kovidgoyal/kitty#170]
Hi, I use Arch Linux and i3wm. Kitty works great, but there is one annoying issue - shell prompt doubles every time window is resized either by opening some other application or by resizing kitty when in float mode. So it looks like this after a couple of resizing:

![image](https://user-images.githubusercontent.com/7038954/32702119-87629be6-c82d-11e7-8834-63cdbf0e9108.png)

Of course, `clear` clears window correctly, but I wonder if there is a simple solution for this.

Btw thanks for an awesome job

**Comment by kovidgoyal** [comment]
Not that I know of. After a resize the cursor moves to the next line, and the shell redraws the prompt. Which is what causes an extra prompt to appear. If the cursor did not move tot he next line, then in the case when the terminal was not at a shell prompt it could result in the last line of text being overwritten. Since the terminal has no way of know whether it is at a shell prompt or not, there is no good solution to this.

Of course, maybe I am wrong, in which case patches are welcome !

**Comment by kovidgoyal** [comment]
On second thoughts, maybe if before resizing kitty checks if the cursor is on the last content line and if so, puts it on the last content line after resizing, it will do the trick. Iill look into it when I have some time.

**Comment by valentjedi** [comment]
Cool, thanks! I was a bit surprised that you think that there is no good solution because AFAIK no other terminals have this issue (no one I'm aware of). I've checked at least on termite, alacritty and upterm.
