### ISSUE TITLE
cat pubring.kbx reproducably causes unexpected freeze

### ISSUE THREAD

**Issue by YoloClin** [kovidgoyal/kitty#1714]
Shell appears to 'freeze', mashing c-z and c-c seems to fix the issue.

File is a public key file from Gentoo (/etc/portage/gpg/pubring.kbx).

Don't ask why I was catting a binary file :P

[pubring.kbx.txt](https://github.com/kovidgoyal/kitty/files/3289801/pubring.kbx.txt)

**Comment by kovidgoyal** [comment]
catting binary files can always freeze terminals, this is because they
can contain terminal escape codes, so the terminal will start reading
one and any further key presses will be interpreted as part of the
escape code, until some bytes arrive that terminate the escape code or
the limit for the code size is reached.

**Comment by Luflosi** [comment]
Is there something like a "secure cat" that filters terminal escape codes?

**Comment by Luflosi** [comment]
Such a program could also prevent something like https://www.youtube.com/watch?v=QZkRw2bik9Q.

**Comment by kovidgoyal** [comment]
Must be one around, though,I think just using ``cat -v`` will do the
trick.
