### ISSUE TITLE
Slow Mac Startup

### ISSUE THREAD

**Issue by FHaine** [kovidgoyal/kitty#1715]
Hello folks,
First of all, thanks for ur work, kitty is great.
The only issue i have is that is quite slow on start up (even single-instance) on my Mac (about ~ 4 seconds)
I've searched already but i didn't find solution.
Here's my console, if u need more infos i can provide everything.
Thanks anyway. :)

(Mac OS Mojave 10.14.5 MBP late 2013 single integrated iris pro)

That what i found on Console 
<img width="1658" alt="Schermata 2019-06-14 alle 16 02 32" src="https://user-images.githubusercontent.com/45208075/59514812-f44a8b80-8ebd-11e9-9c14-3e05f1e4eadd.png">

(Side note: running *locale* returns me that lang is it_IT.UTF-8, that what my .profile says)

edited for typos

**Comment by Luflosi** [comment]
I can confirm that kitty is not exactly fast to start on macOS.

**Comment by kovidgoyal** [comment]
And what does the following output:

```
time kitty +runpy 1
```

**Comment by FHaine** [comment]
creating a new window with ctrl+shift+n is almost instant!
`time /Applications/kitty.app/Contents/MacOS/kitty +runpy 1`
returns
`/Applications/kitty.app/Contents/MacOS/kitty +runpy 1  0,02s user 0,01s system 94% cpu 0,027 total`
(but it didn't open anything)
Curious 'cause 
`time /Applications/kitty.app/Contents/MacOS/kitty`
returns
`/Applications/kitty.app/Contents/MacOS/kitty  2,64s user 0,32s system 50% cpu 5,860 total`

(promise, i'll create an alias for *kitty* asap)

**Comment by kovidgoyal** [comment]
You dont need an alias, run those from within kitty and they work because kitty inserts itself into PATH.

Now coming to your issue, definitely something strange going on. All single instance does is open a socket, write to it and exit. kitty reads from the socket and opens a new window with the specified parameters. I dont see why that would be noticeably slower than ctrl+shift+n

You will need to get into kittys code to debug further. Are you willing to do that?

**Comment by FHaine** [comment]
I can def try if it helps the project!

(mmmm strange, i've to insert a simple alias in my .zshrc to have *kitty* in order to work)

**Comment by kovidgoyal** [comment]
I dont know if it will help the project since a 4 sec startup time for single instance is definitely not normal, but it might help you :) You will find the code that sends the single instance command in kitty main.py look around line 255 for where it starts. First check that that code is working fast, it should all complete in under a second.

**Comment by FHaine** [comment]
Oh god, i've got very basic python knowledge.


But it seems it loops from line 11 to line 18 of main.py

> ""No module named '__main__.borders'; '__main__' is not a package""

and so on for .boss, .child, .cli.. etc.

And then STRANGELY again from the start?

But maybe I'm doing something wrong. (Also tried with Pdb, same loop)

(Python 3.7.3, from homebrew, maybe something broken with that version?)

**Comment by kovidgoyal** [comment]
How are you running kitty? Did you follow the instructions at
https://sw.kovidgoyal.net/kitty/build.html

**Comment by FHaine** [comment]
I followed exactly that manual.
But still.
(even without _make app_ )

`kitty (git)-[master] % time python3 .`
`python3 .  2,72s user 0,32s system 72% cpu 4,183 total`


i run also your test.py but 70/70 tests are OK.

**Comment by kovidgoyal** [comment]
The idea is to modify the code I pointed out earlier to insert some
print statements and check wherethe slowdown is occurring.

**Comment by kovidgoyal** [comment]
No followup

**Comment by FHaine** [comment]
Hi kovidgoyal,
I've tried some test (like running on new clean user environment), and tried to bypass some parts of the code to check where was the problem, but everything seems ok, and still slow on opening.
I still didn't find nothing, but i haven't got so much free time lately.
I'll keep you uptodate :)

**Comment by kovidgoyal** [comment]
sure, no rush.

**Comment by victorkashirin** [comment]
Hi guys, and thank you Kovid for the Kitty, I'm really enjoying it.

I also experience initial instance startup taking 4 seconds on MBPro 2015, which made me curious, since for the rest it's blazing fast. 

I ran MacOS instruments to profile the startup of kitty, here is result from one of the runs: 

![image](https://user-images.githubusercontent.com/345522/74587242-78768500-4ff0-11ea-9fd6-15b4d7d04d24.png)

Seeing that, my only guess was that the startup is slowed down by the large collection of fonts, which Kitty scans on first instantiation. As an additional proof to that: the time it takes Kitty to list available monospaced fonts is about same four seconds:
```bash
~ $ time kitty list-fonts > /dev/null

real	0m3.950s
user	0m3.134s
sys		0m0.186s
```

Indeed, I have quite big library of monospaced fonts (JetBrains Mono, Fira Code, iA Writer, IBM Plex Mono, Hack, Input Mono, Iosevka, Knack, Roboto Mono etc.) and non-monospaced as well. Most of them have multiple font-weights, some have tons of ligatures, so it adds up to a big variety of shapes.  By moving part of the fonts out of `~/Library/Fonts` the startup time was cut down to ~2 seconds.

This might be an explanation to this issue and perhaps #330. I guess one solution to this without dumping the fonts might be a configurable option to scan fonts collection only once and cache the results in form of paths to the selected fonts. Fonts don't change every day, and when they do, they could be rescanned with the same `kitty list-fonts`. In case when Kitty won't be able to find previously selected fonts, it might do full scan of the library to find fallback, thus not breaking application start for the user.

**Comment by kovidgoyal** [comment]
kitty uses CoreText APIs for fonts. I would assume they are already
using cached data, but maybe that's not true. At least on linux with
which I am more familiar the equivalent APIs from fontconfig do indeed
use cached data.

**Comment by tbsmn** [comment]
I came here with the same Problem. I can confirm that the Start-Up slowed down after I used the `kitty list-fonts` command the first time. Before that it was blazingly fast.

Is there a way to get back?

**Comment by kovidgoyal** [comment]
I'm afraid, I dont see how running list-fonts could possibly change the startup time.

**Comment by kovidgoyal** [comment]
And I suggest use --single-instance as a way to have kitty read fonts
only once per boot. You can specify command line options on macOS as
described in the FAQ

**Comment by tbsmn** [comment]
That's so sad. I was so amazed by the speed and now that i configured it. The speed is gone.
I'am already using the `--single-instance` option, but that does not help...

**Comment by kovidgoyal** [comment]
How could single instance possibly not help? You are not doing what you
think you are doing.

**Comment by tbsmn** [comment]
im starting kitty from iterm with this command.
maybe this output could help
`kitty --single-instance
[099 10:00:59.787925] No render frame received in 0,25 seconds, re-requesting at: 2,211340
[099 10:00:59.802503] No render frame received in 0,25 seconds, re-requesting at: 2,225922
[099 10:00:59.802866] No render frame received in 0,25 seconds, re-requesting at: 2,226286
[099 10:00:59.841376] [PARSE ERROR] Unknown OSC code: 7
[099 10:01:00.198434] [PARSE ERROR] Unknown OSC code: 7
[099 10:01:00.198455] No render frame received in 0,25 seconds, re-requesting at: 2,621850`

**Comment by kovidgoyal** [comment]
That will start the first instance of kitty which will be slow. All subsequent instances started like that will be instant.

**Comment by tbsmn** [comment]
Thank you! This worked. I changed the settings to not quit when the last window is closed. And now the Speed is back. Thanks for the help

**Comment by tigger04** [comment]
I had exactly the same issue. Have a look in ~/Library/Fonts, turns out there were 2.2GB of fonts in there, 1.9GB of which were there for just one font family - Noto from Google. Removing this font family has cut my kitty startup from over 4s to about 1.1s

**Comment by tbsmn** [comment]
Thanks for this tip! I just gave it a try but my ~/Library/Fonts Folder is just about 150 MB and I don't have the Noto Font from Google installed. It must be something else.

**Comment by nguyenvukhang** [comment]
I know this is an old thread, but I recently fixed this so I wanted to share it here anyway.

I found that it was `xcodebuild` that was causing first launch to be slow, and in order to stop it from running, you have to use a non-apple distributed version of git.
So to solve the slow start up, simply install git with homebrew `brew install git` (or any other method), and restart your device. First load of kitty after startup should be significantly faster.

**Comment by Frank-Mayer** [comment]
I had the same issue and found out that it wasn't kitty. The root problem was oh my zsh. I played around with the settings, and now it is much faster.
It went from four seconds to one my changing some settings. This is ok for me.

[My `.zshrc` is in my dotfiles repo](https://github.com/Frank-Mayer/dotfiles/blob/main/.zshrc).
