### ISSUE TITLE
Alt no longer works for keybindings

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#1723]
Update from 0.14 to 0.14.2 yesterday. Alt now works as in other places on Mac OS, like a sort of compose key. This is keeping me from using it in keybindings for irssi/ranger and other TUI programs.

How do I troubleshoot this further? The muscle memory makes this more than a little annoying : x

**Comment by Luflosi** [comment]
See the first change of 0.14.0: https://sw.kovidgoyal.net/kitty/changelog.html#id3
@kovidgoyal The anchors in the changelog are not ideal as they will point to different versions when a new version is released.

**Comment by toonn** [comment]
Thank you, I couldn't find anything while searching through issues but didn't check the changelog. Yeah, this changelog shows version 0.14 but everything still worked with that version.

Is there a way to eat my cake and have it too, i.e., remap the normal option+key unicode input to a different modifier cmd+option for example?

**Comment by Luflosi** [comment]
Its very strange, that this still worked with 0.14.0 as I'm very sure that the changelog is correct. I changed the default value of that option in #1323 because I wanted to cause less confusion for new users. It was merged in  0833697, which is part of the 0.14.0 release.
Follow the link in that changelog entry, it takes you to the configuration docs. The config option allows you to have different behaviors for the two <kbd>alt</kbd> keys.

**Comment by toonn** [comment]
Oh, great. The option docs are a little hard to find though. Only a search on the site led me there. Doesn't mention the default "yes" though so I guess they're incomplete. For some reason I don't have a manpage where I'd normally go to look it up and the comment in the config doesn't mention the options either.

Thanks for the patience and the help! : )

**Comment by Luflosi** [comment]
The default is `no`, not `yes`. The docs mention `both`, which does the same as `yes` but is much more descriptive IMO. The docs also mention the other two available options `left` and `right`. Your `kitty.conf` is probably from a time when `yes` and `no` were the only two available options, which is why the comment in it doesn't mention the other ones.
If you're building from source, you can build the man pages with `make man`.

**Comment by toonn** [comment]
Not building from source, install kitty through nix or homebrew. Guess I'll diff my config with the one that comes with kitty, must be on the system somewhere.

The default was probably different back then, that line was commented out but did have "yes" rather than "no."

**Comment by Luflosi** [comment]
Yes, the default was changed in 0.14.0 as mentioned in the changelog.

**Comment by Luflosi** [comment]
@kovidgoyal did you see my comment https://github.com/kovidgoyal/kitty/issues/1723#issuecomment-502797741 above?

**Comment by kovidgoyal** [comment]
Well that's what sphinx generates, I dont know of a way to change it to something more permanent.
