### ISSUE TITLE
Difference in unicode symbol heights

### ISSUE THREAD

**Issue by mhartington** [kovidgoyal/kitty#174]
Hi there! I've been using kitty for a week or so and have noticed some small differences in font rendering with patched fonts (powerline/nerd-fonts)

On the left is Kitty and on the right is iTerm

<img width="1109" alt="screen shot 2017-11-19 at 5 34 57 pm" src="https://user-images.githubusercontent.com/2835826/32996414-773b0082-cd50-11e7-86de-089afe9ce9c8.png">

The `TS` symbol in the vim completion menu for some reason is rendered at a different size.
It's not just custom symbols in patched fonts that seem to be rendered differently, but any non-asci symbols too. 

`Ⓛ` in this case in the statusline

<img width="319" alt="screen shot 2017-11-19 at 5 41 51 pm" src="https://user-images.githubusercontent.com/2835826/32996489-6bc1dc34-cd51-11e7-989e-2cc910552311.png">

Is there anyway this can be adjusted?

**Comment by kovidgoyal** [comment]
Glyphs are rescaled if they are too wide to fit. The most common cause of that is using fonts that have a different character width than the main font, or using characters that are "wide characters" but for which wcwidth() returns that they are narrow. For unicode characters that can often be fixed by using use_system_wcwidth=no in your kitty.conf. Note that this can cause other problems because now kitty and the application running in kitty have different ideas about how many cells a character should take.

I have no idea why iterm is rendering your wide characters in two cells instead of one (they appear to be powerline characters, which means they come from the unicode private use area and have wcwidth=1) but kitty will only do that is wcwidth() says that the character is a wide character. I typically use powerline glyphs that fit in a dingle cell to avoid this issue. Probably iterm simply bleeds wide characters into the next cell, which will cause overwritten characters if one of these symbols is followed by something other than a space. 

And note that you can use the symbol_map feature in kitty to avoid the need for patched fonts for powerline.
