### ISSUE TITLE
[Website] Better highlight install/download steps

### ISSUE THREAD

**Issue by muhammad-saleh** [kovidgoyal/kitty#1752]
Thank you for the amazing project
Just a really small comment on the website, I guess it will be much better if you could highlight the steps to download or install Kitty

and maybe make this in a separate section with it's own link in the menu

Feel free to close this if you don't agree :)

**Comment by Luflosi** [comment]
Did you see the links to the installation instructions on https://sw.kovidgoyal.net/kitty/ under the Quickstart section?

**Comment by kovidgoyal** [comment]
The steps are the very first thing under the Quickstart section, not sure
what more highlighting is required.
https://sw.kovidgoyal.net/kitty/#quickstart

**Comment by muhammad-saleh** [comment]
Thank you guys, just wanted to say that people who want to use a specific product they usually don't want to go over multiple steps they just quickly scan the page for CTAs or download links

anyway in case you wanted to revisit this here are some examples of what a better UX in my opinion would look like (which I think will help Kitty as well)

![image](https://user-images.githubusercontent.com/1510608/60190841-9b6ee180-9833-11e9-98e8-f0bed5953269.png)

![image](https://user-images.githubusercontent.com/1510608/60191023-ec7ed580-9833-11e9-801c-43c75fc83110.png)

![image](https://user-images.githubusercontent.com/1510608/60191052-f99bc480-9833-11e9-83ac-1180421b9a51.png)


Compared to Kitty:
![image](https://user-images.githubusercontent.com/1510608/60191090-0b7d6780-9834-11e9-8417-c8024b257d39.png)



Anyway it's nothing major and I just hope it would be considered in the future

Thanks!

**Comment by Luflosi** [comment]
I agree the Website design could be improved but since it is currently generated from the source code and rot files, it would require a fair amount of work to make the website look as good as the others. The benefit of making the website better is relatively small compared to the required investment of time. Therefore this is not going to be a very high priority to change the website.
I do however hope that we get a better website at some point in the future.

**Comment by muhammad-saleh** [comment]
Totally understand! best of luck!
