### ISSUE TITLE
Custom binary install error

### ISSUE THREAD

**Issue by vaskark** [kovidgoyal/kitty#1784]
I'm trying to install the binary to a custom location and receive this error:

```
$ sudo curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin dest=/usr/local/bin                                       01:58 pm
Using python executable: /usr/bin/python3
Checking for latest release on GitHub...
Will download and install kitty-0.14.2-x86_64.txz
Downloaded 8761432 bytes 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 225, in script_launch
  File "<string>", line 201, in main
  File "<string>", line 168, in linux_install
  File "/usr/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.7/shutil.py", line 429, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'kitty'
```
I do have write permissions to this location.
I'm on Ubuntu 19.04 using latest 0.14.2 release.
Thanks.

P.S. Is there any reason why there isn't the standard install model of ./configure, make, and make install? Just curious.

**Comment by kovidgoyal** [comment]
That's a permission denied error, and given that you are trying to
install to /usr/local/bin that's hardly surprising, since user accounts
dont have permission to make changes to that directory typically. You
need to add sudo to both parts of the pipeline in the install caommadn
notjust the first.

And ./configure;make; make install is not a standard, it's an
abomination. If you want to build and install kitty from source, you can
certainly do that, https://sw.kovidgoyal.net/kitty/build.html

**Comment by Luflosi** [comment]
The instructions on the website to build kitty from source are currently out of date. The latest instructions are here: https://github.com/kovidgoyal/kitty/blob/master/docs/build.rst
