### ISSUE TITLE
Terminal cursor remains active when window not focused

### ISSUE THREAD

**Issue by sebosp** [kovidgoyal/kitty#18]
Expected behavior:
When the terminal is not being focused, the cursor should lose its internal color and only its border should be visible to denote inactivity.

What actually happens:
Cursor remains filled as if active window.

Thanks!

**Comment by kovidgoyal** [comment]
Because kitty supports multiple windows and only one of those windows can display a cursor, I find this less useful as an indicator of focus, instead I usually rely on my window manager to provide focus indicators (which is, after all, the job of the window manager).

That said, I have no objection to this being implemented, patches are welcome! The cursor drawing code is in char_grid.py and boss.py
