### ISSUE TITLE
new_os_window_with_cwd through ssh

### ISSUE THREAD

**Issue by kovasap** [kovidgoyal/kitty#1826]
Anyone know of a way to set up kitty so that I can run the new_os_window_with_cwd through an ssh session?  The use case is me working over ssh on a remote machine and hitting a keyboard shortcut that spawns a new OS kitty window.  This window right away runs ssh to get to my remote machine and cd to get to the same directory where I am on that machine.

**Comment by kovidgoyal** [comment]
Since there is no way that I know of to query ssh for what the remote
CWD is, no. The closest you can come is the kitty remote control
facility, https://sw.kovidgoyal.net/kitty/remote-control.html 

You can setup an alias/script on your servre that runs
kitty @ new-window ssh -c "cd $PWD; $SHELL"

or something similar.
