### ISSUE TITLE
F5 to F12 input tilde

### ISSUE THREAD

**Issue by MobiTobi** [kovidgoyal/kitty#1827]
Pressing the function keys from F5 upwards yields `~`. Hence F11 cannot be used  to enter full screen.
This only happens using kitty, in the default gnome terminal this behaviour is absent.

I found issue #726 and compared the outputs of `showkey -a`  for various function keys between kitty and the gnome terminal. The output was identical.

I am using kitty 0.14.2 on Ubuntu 18.04.2 LTS with a vanilla kitty config file.

Can someone help me to obtain normal function key behaviour?

**Comment by kovidgoyal** [comment]
kiity and gnome-terminal produce the exact same bytes for function keys.
Therefore if you are seeing function keys not working, the problem is in
whatever software you are running inside kitty. Either you have changed
the value of TERM or the kitty terminfo files are missing orthe software
in question hardcodes terminal detection instead of using terminfo.
