### ISSUE TITLE
Bell is now droplet sound in Arch (kitty version 0.14.3-1)

### ISSUE THREAD

**Issue by grahampfau** [kovidgoyal/kitty#1866]
Doing an action that would previously make my PC speaker beep with a bell code now causes a  droplet sound to be played though my headphones.

Is there a way I can configure it to go back to using the PC speaker?

**Comment by kovidgoyal** [comment]
No, but you can configure the default sound to be whatever you like.
Bell sounds are now played via libcanberra which uses the system sound
theme, which you can override by putting some files in your home
directory, see http://0pointer.de/public/sound-theme-spec.html

**Comment by qazip** [comment]
How can I disable the sounds from kitty alltogether @kovidgoyal?

**Comment by kovidgoyal** [comment]
Look in kitty.conf

**Comment by qazip** [comment]
For posterity sake: https://sw.kovidgoyal.net/kitty/conf.html?highlight=bell#terminal-bell

**Comment by cuppajoeman** [comment]
For anyone who wants to use a custom bell sound, here is a solution. Find your sound, then convert it to a file named `bell.oga`, for example I did: `ffmpeg -i CB.WAV -acodec libvorbis bell.oga`.
Then I overwrote the default bell sound (if you want to have the default again at any point, make a backup of it somewhere) by moving it to `/usr/sounds/freedesktop/stereo`, and I had my custom bell.

**Comment by ctrlcctrlv** [comment]
You shouldn't need to overwrite anything if you follow Kovid's advice and make a new sound theme in your home directory. Overwriting may break upgrades.

**Comment by durka** [comment]
Can you elaborate on how to override the sound theme? The linked 0pointer.de page is vague, full of broken links and does not specify how to identify, change, or modify the theme in any way.

**Comment by Bug-Reaper** [comment]
@durka is a lifesaver. 

I simply created the path `~/.local/share/sounds/freedesktop/stereo/bell.oga` (where bell.oga is your desired audio file). Kitty picked up on it easily w/o even required to restart.

Not sure why this is closed... There should really be an option in the conf file to set an arbitrary path for your sound effect(s). Seems really jenky otherwise.

**Comment by bitwombat** [comment]
`bell_path`

**Comment by wind0204** [comment]
> I simply created the path `~/.local/share/sounds/freedesktop/stereo/bell.oga` (where bell.oga is your desired audio file). Kitty picked up on it easily w/o even required to restart.

I also needed to add `~/.local/share/sounds/__custom/index.theme`, possibly because the theme was not freedesktop or I'm using version `0.32.1`. --Using the theme directory name __custom is convenient since the default value of `linux_bell_theme` of kitty is `__custom`
```
cat <<EOF > ~/.local/share/sounds/__custom/index.theme
[Sound Theme]
Name=foobar
Comment=mine
Directories=stereo

[stereo]
OutputProfile=stereo
EOF
```

> 
> Not sure why this is closed... There should really be an option in the conf file to set an arbitrary path for your sound effect(s). Seems really jenky otherwise.

There is one in the more recent versions of kitty: `bell_path` like @bitwombat hinted above.
