### ISSUE TITLE
Symbol map problem

### ISSUE THREAD

**Issue by vaskark** [kovidgoyal/kitty#1948]
I'm using this line in kitty.conf to specifiy certain unicode characters for a certain script I have:

`symbol_map U+E087,U+E103,U+E104,U+E08D,U+E146 Typicons`

And here's the screenshot showing extra character squares: [link](https://i.imgur.com/RXp7b35.png)
Those squares don't show on other terminals configured to use the Typicons set, like st.

I'm on Ubuntu 19.04, kitty 0.14.4.
Thanks.

**Comment by Luflosi** [comment]
This may be the same issue as #1225.

**Comment by kovidgoyal** [comment]
Those are private use unicode codepoints, make sure they are followed by two space characters and you should be fine.

**Comment by vaskark** [comment]
@kovidgoyal Can you explain further?

`symbols_map U+E087 U+0020 U+0020, ...`

Is this what you mean? I've tried a bunch of things and none are working.

**Comment by Luflosi** [comment]
He meant that you need to have the spaces after the actual character where it is printed in your terminal. You may need to add a space to `symbols_map` too for it to work, not sure though (`symbol_map U+E087,U+E103,U+E104,U+E08D,U+E146,U+0020 Typicons`).
But if you look in #1225, you can see that this should be fixed in the latest master. To use the fix, either build from source or wait until the next version is released. If you're using Arch Linux, you can also install kitty-git from the AUR.

**Comment by vaskark** [comment]
@Luflosi Thanks so much. I built from master and the problem is solved.
