### ISSUE TITLE
Kitty Only uses Dark colors

### ISSUE THREAD

**Issue by Xiaoming94** [kovidgoyal/kitty#197]
Hello I have set custom value to all color0 -- color15 but it kind of feels like only the dark colors are being picked.

Just like in this screenshot:
![2017-11-29-21 02 30-screenshot](https://user-images.githubusercontent.com/6448975/33396524-0dce2240-d549-11e7-9674-be7f006e712f.png)

The terminal to the left are Termite

Here is the config files for the terminals:
kitty: https://github.com/Xiaoming94/PersonalRepo/blob/master/myConfigs/kitty/kitty.conf
termite: https://github.com/Xiaoming94/PersonalRepo/blob/master/myConfigs/termite/config

OS: Arch Linux

**Comment by kovidgoyal** [comment]
I doubt that has anything to do with color configuration. More likely whatever you are using to generate that particualr text output is incorrectly using bold formatting for bright colors. kitty does not support that. Instead bold formatting is used for, actual bold text (assuming the font you choose has a bold variant). 

Tell whoever maintains that application that they should be using the aixterm colors (SGR color codes 90-97m) for bright colors instead.

**Comment by wez** [comment]
Please consider adding an option to enable the use of bright when bold is enabled.  Many terminal emulators provide such an option; there's a lot of software out there that can't easily be changed to use the more correct sequences and it isn't especially feasible to tell kitty users to request those changes, especially because the appearance to them is that kitty is the software that doesn't "correctly" render (for example) bold+black as dark grey like the other terminals do, and where it instead appears to not render that text at all.

**Comment by wez** [comment]
eg: this renders as dark grey in most other terminals, but is black in kitty.  Kitty could definitely be argued to have the correct behavior, but when it is the odd one out, then it appears to be the one that is wrong:

`echo -e "\e[0;30;1mboo\e[0m\n"`

**Comment by kovidgoyal** [comment]
As I've said before. Using bold for bright colors is a very, very bad decision. It means that no software can use bold fonts, since bold now has no well defined meaning. I am not going to perpetuate this bad decision.   See for example #135

**Comment by simoniz0r** [comment]
Ya'know this is something users have come to expect as normal behavior in a terminal.  `kitty` is the ***only*** terminal I've ever used that displays bold text using the dark color without any sort of configuration option.

For something relatively simple for you to add, you're basically throwing a little hissy fit and making your terminal unusable for many people.

I am not going to perpetuate this bad decision by using kitty.

**Comment by RedKugelblitz** [comment]
To each their own, but i have to back up kovidgoyal here. Don't touch me bold text cyka

**Comment by rndusr** [comment]
Nobody is arguing for hardcoding bold=bright or even to make it the default. We're asking to make it opt-in.

I've just switched to kitty and noticed that all my daily drivers (emacs, git, man pages, etc) lost 50% of their colors. That's a dealbreaker for me.

I agree that diverging from standards is a bad idea, but breaking user experience is also a bad idea. Which one is worse is debatable, but it's also irrelevant in this case because the issue can be solved for everyone by adding an option.

**Comment by simoniz0r** [comment]
> I dont know what is so hard to grasp about the concept that by asking for an option to do this you are making it impossible for people that write terminal programs to rely on terminals having bold formatting.

Damn, I wonder how they're able to do this with the terminals out there that do provide this option... :thinking:

**Comment by kovidgoyal** [comment]
> Damn, I wonder how they're able to do this with the terminals out there that do provide this option... :thinking: 


Many of them do not, precisely because of the broken-ass behavior you are
advocating for.

**Comment by kovidgoyal** [comment]
Oh and @simoniz0r kindly take your hissy fit elsewhere. Since you have already stated you dont want to use kitty, I have no interest in your opinions.

**Comment by kovidgoyal** [comment]
In fact, I think I have wasted enough time repeating myself. This thread is now closed.
