### ISSUE TITLE
Build Failed: No such file or directory: 'build/kitty/fast_data_types.so' -> 'kitty/fast_data_types.so'

### ISSUE THREAD

**Issue by anoduck** [kovidgoyal/kitty#1987]
Kitty looks incredible. In my experience, I cannot fathom a reason for it not to have compiled correctly and run without a hitch. But just when all seemed to run smoothly, it hit an error. 

```
  ➜ gmake      
  python3 setup.py 
  CC: cc (4, 2)
  wayland-protocols >= 1.17 is required, found version: not found
  Disabling building of wayland backend
  [59/59] Compiling kitty/gl-wrapper.c ... done
  [4/5] Linking kittens/diff/diff_speedup ...Traceback (most recent call last):
  File "setup.py", line 1024, in <module>
    main()
  File "setup.py", line 1004, in main
    build_launcher(args, launcher_dir=launcher_dir)
  File "setup.py", line 654, in build_launcher
    args.compilation_database.build_all()
  File "setup.py", line 444, in build_all
    parallel_run(items)
  File "setup.py", line 404, in parallel_run
    wait()
  File "setup.py", line 388, in wait
    compile_cmd.on_success()
  File "setup.py", line 518, in on_success
    os.rename(dest, real_dest)
  FileNotFoundError: [Errno 2] No such file or directory: 'build/kitty/fast_data_types.so'   -> 'kitty/fast_data_types.so'
  gmake: *** [Makefile:9: all] Error 1
```

Any suggestions? Running OpenBSD 6.6 CURRENT 64

**Comment by Luflosi** [comment]
Which version of kitty are you trying to compile? The latest master version compiled fine on FreeBSD for me. But maybe there is some important difference between FreeBSD and OpenBSD.

**Comment by kovidgoyal** [comment]
No followup

**Comment by kovidgoyal** [comment]
They are generated by the build system to record what commands were used to compile each file. This allows automatic re-compilation when compile flags change and is also used for completion via clang-complete.

**Comment by jesselucas** [comment]
@Luflosi thank you, removing the options from the python setup allowed it to compile but when running the launcher it returns

```
kitty$ ./kitty/launcher/kitty
Failed to read /proc/self/exe
```

**Comment by Luflosi** [comment]
Try changing `#elif defined(__FreeBSD__)` in `launcher.c` to something like `#elif defined(__FreeBSD__) || defined(__OpenBSD__)`.

**Comment by jesselucas** [comment]
Looks like KERN_PROC_PATHNAME doesn't exist on OpenBSD. I'm not sure how to find the path on OpenBSD so might need to wait for someone with more knowledge than me to give it a try :)

**Comment by Luflosi** [comment]
I went to the trouble of installing OpenBSD in a VM and trying to compile kitty myself. There are no VirtualBox guest Additions, so working in the VM was a bit of a pain, no copy and paste in and out of the VM, no shared folders, needing to capture mouse and keyboard, etc. .
I got kitty mostly working with this patch:
```diff
diff --git a/glfw/glfw.py b/glfw/glfw.py
index 90f8a73f..624042ce 100755
--- a/glfw/glfw.py
+++ b/glfw/glfw.py
@@ -36,7 +36,7 @@ def init_env(env, pkg_config, at_least_version, test_compile, module='x11'):
     if module in ('x11', 'wayland'):
         ans.cflags.append('-pthread')
         ans.ldpaths.append('-pthread')
-        ans.ldpaths.extend('-lrt -lm -ldl'.split())
+        ans.ldpaths.extend('-lm'.split())
         at_least_version('xkbcommon', 0, 5)
 
     if module == 'x11':
diff --git a/launcher.c b/launcher.c
index 253bcc73..6d7ca7a6 100644
--- a/launcher.c
+++ b/launcher.c
@@ -143,6 +143,14 @@ read_exe_path(char *exe, size_t buf_sz) {
     return true;
 }
 
+#elif defined(__OpenBSD__)
+
+static inline bool
+read_exe_path(char *exe, size_t buf_sz) {
+    if (!safe_realpath("/home/u/kitty/kitty/launcher/kitty", exe, buf_sz)) { fprintf(stderr, "Failed to read /home/u/kitty/kitty/launcher/kitty\n"); return false; }
+    return true;
+}
+
 #else
 
 static inline bool
diff --git a/setup.py b/setup.py
index 257727cb..76ab42fb 100755
--- a/setup.py
+++ b/setup.py
@@ -98,9 +98,7 @@ def cc_version():
         if is_macos:
             cc = 'clang'
         else:
-            if shutil.which('gcc'):
-                cc = 'gcc'
-            elif shutil.which('clang'):
+            if shutil.which('clang'):
                 cc = 'clang'
             else:
                 cc = 'cc'
@@ -272,10 +270,6 @@ def kitty_env():
     ans.ldpaths += pylib + font_libs + gl_libs + libpng
     if is_macos:
         ans.ldpaths.extend('-framework Cocoa'.split())
-    else:
-        ans.ldpaths += ['-lrt']
-        if '-ldl' not in ans.ldpaths:
-            ans.ldpaths.append('-ldl')
     if '-lz' not in ans.ldpaths:
         ans.ldpaths.append('-lz')
```
One has to use `gmake` instead of `make` to compile kitty or just execute `setup.py` directly.
While OpenBSD has gcc, the version is super old (the last version licensed under GPLv2 apparently) and doesn't know options like `-Wfloat-conversion`, `-stdc=11` and `-flto`.
I figured I wouldn't even try to compile kitty without C11 support from the compiler, so I wanted to use clang instead of gcc.
I couldn't figure to how to uninstall it, so I just modified kitty's build system to never use gcc.
The version of clang they are using apparently doesn't know `-lrt` and `-ldl`. I'm not sure what these options do but I got kitty to mostly work without them so...
OpenBSD apparently doesn't allow reading the path to the current executable. `/proc` doesn't exist and the `sysctl()` used for FreeBSD also doesn't exist, so I just hardcoded the path for now. Maybe we can just use `argv[]` to read that path somehow.
When I start kitty with `kitty/launcher/kitty`, it prints
```
xkbcommon: ERROR: couldn't find a Compose file for locale "C.UTF-8"
[...] [glfw error 65544]: Failed to create XKB compose table for locale C.UTF-8
```
When executing `export LANG='en_US.UTF-8'`, kitty just prints the same error with the new locale.
The shell inside kitty complains as well:
```
/bin/ksh: No controlling tty (open /dev/tty: Device not configured)
/bin/ksh: warning: won't have full job control
```
but otherwise it seems to work fine.

@jesselucas Can you try my patch and see how it works? (replace "/home/u/kitty/kitty/launcher/kitty")
@kovidgoyal any remarks?

**Comment by kovidgoyal** [comment]
I'm fine with hardcoding clang on openbsd just as it is on macOS.

You cant get path to executable reliably from argv since it can contain anything.
https://stackoverflow.com/questions/31494901/how-to-get-the-executable-path-on-openbsd

If OpenBSD does not have a working xkbcommon then I dont see what we can
do about it.

The controlling tty stuff is just probably some mising ioctl that
openbsd needs the terminal emulator to execute on tty devices.


On Fri, Oct 25, 2019 at 04:35:58PM -0700, Luflosi wrote:
> I went to the trouble of installing OpenBSD in a VM and trying to compile kitty myself. There are no VirtualBox guest Additions, so working in the VM was a bit of a pain, no copy and paste in and out of the VM, no shared folders, needing to capture mouse and keyboard, etc. .
> I got kitty mostly working with this patch:
> ```diff
> diff --git a/glfw/glfw.py b/glfw/glfw.py
> index 90f8a73f..624042ce 100755
> --- a/glfw/glfw.py
> +++ b/glfw/glfw.py
> @@ -36,7 +36,7 @@ def init_env(env, pkg_config, at_least_version, test_compile, module='x11'):
>      if module in ('x11', 'wayland'):
>          ans.cflags.append('-pthread')
>          ans.ldpaths.append('-pthread')
> -        ans.ldpaths.extend('-lrt -lm -ldl'.split())
> +        ans.ldpaths.extend('-lm'.split())
>          at_least_version('xkbcommon', 0, 5)
>  
>      if module == 'x11':
> diff --git a/launcher.c b/launcher.c
> index 253bcc73..6d7ca7a6 100644
> --- a/launcher.c
> +++ b/launcher.c
> @@ -143,6 +143,14 @@ read_exe_path(char *exe, size_t buf_sz) {
>      return true;
>  }
>  
> +#elif defined(__OpenBSD__)
> +
> +static inline bool
> +read_exe_path(char *exe, size_t buf_sz) {
> +    if (!safe_realpath("/home/u/kitty/kitty/launcher/kitty", exe, buf_sz)) { fprintf(stderr, "Failed to read /home/u/kitty/kitty/launcher/kitty\n"); return false; }
> +    return true;
> +}
> +
>  #else
>  
>  static inline bool
> diff --git a/setup.py b/setup.py
> index 257727cb..76ab42fb 100755
> --- a/setup.py
> +++ b/setup.py
> @@ -98,9 +98,7 @@ def cc_version():
>          if is_macos:
>              cc = 'clang'
>          else:
> -            if shutil.which('gcc'):
> -                cc = 'gcc'
> -            elif shutil.which('clang'):
> +            if shutil.which('clang'):
>                  cc = 'clang'
>              else:
>                  cc = 'cc'
> @@ -272,10 +270,6 @@ def kitty_env():
>      ans.ldpaths += pylib + font_libs + gl_libs + libpng
>      if is_macos:
>          ans.ldpaths.extend('-framework Cocoa'.split())
> -    else:
> -        ans.ldpaths += ['-lrt']
> -        if '-ldl' not in ans.ldpaths:
> -            ans.ldpaths.append('-ldl')
>      if '-lz' not in ans.ldpaths:
>          ans.ldpaths.append('-lz')
> ```
> One has to use `gmake` instead of `make` to compile kitty or just execute `setup.py` directly.
> While OpenBSD has gcc, the version is super old (the last version licensed under GPLv2 apparently) and doesn't know options like `-Wfloat-conversion`, `-stdc=11` and `-flto`.
> I figured I wouldn't even try to compile kitty without C11 support from the compiler, so I wanted to use clang instead of gcc.
> I couldn't figure to how to uninstall it, so I just modified kitty's build system to never use gcc.
> The version of clang they are using apparently doesn't know `-lrt` and `-ldl`. I'm not sure what these options do but I got kitty to mostly work without them so...
> OpenBSD apparently doesn't allow reading the path to the current executable. `/proc` doesn't exist and the `sysctl()` used for FreeBSD also doesn't exist, so I just hardcoded the path for now. Maybe we can just use `argv[]` to read that path somehow.
> When I start kitty with `kitty/launcher/kitty`, it prints
> ```
> xkbcommon: ERROR: couldn't find a Compose file for locale "C.UTF-8"
> [...] [glfw error 65544]: Failed to create XKB compose table for locale C.UTF-8
> ```
> When executing `export LANG='en_US.UTF-8'`, kitty just prints the same error with the new locale.
> The shell inside kitty complains as well:
> ```
> /bin/ksh: No controlling tty (open /dev/tty: Device not configured)
> /bin/ksh: warning: won't have full job control
> ```
> but otherwise it seems to work fine.
> 
> @jesselucas Can you try my patch and see how it works? (replace "/home/u/kitty/kitty/launcher/kitty")
> @kovidgoyal any remarks?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/kovidgoyal/kitty/issues/1987#issuecomment-546544568

-- 
_____________________________________

Dr. Kovid Goyal 
https://www.kovidgoyal.net
https://calibre-ebook.com
_____________________________________
