### ISSUE TITLE
Window always has light theme title bar when launching kitty from command line in MacOS, even in dark mode

### ISSUE THREAD

**Issue by gotgenes** [kovidgoyal/kitty#1992]
When launching kitty from the command line on MacOS, the title bar always renders with the "light theme" colored title bar, even when "dark theme" (a.k.a. "dark mode") is selected in the "Appearance".

Steps to reproduce:

1. Go to System Preferences, General, and select "Dark" under Appearance
2. Open kitty from Applications and observe title bar has dark theme coloring
3. In the kitty terminal window, type `kitty` and hit enter to run kitty from the command line
4. Observe the new terminal window has a light theme coloring

If you want, you can explicitly pass a config file that has only the following contents
```
macos_titlebar_color system
```
but `system` is already the default value for this setting.

My system

* MacOS 10.14.6
* kitty 0.14.4 installed via Homebrew cask

**Comment by Luflosi** [comment]
I can reproduce the problem with kitty 0.14.5 installed via Homebrew cask or directly from the kitty releases page but weirdly enough not kitty 0.14.5 compiled by myself.
When executing `kitty` installed via Homebrew, `kitty` is `/usr/local/bin/kitty`, which is a symlink to `/Applications/kitty.app/Contents/MacOS/kitty`. I'm guessing the problem was introduced in 9b58317fb11c0f7c6d798563f7ac392a9e60e77b but without being able to reproduce the issue with kitty compiled by myself, it's hard to say for sure. What I can say for sure is that 9b58317fb11c0f7c6d798563f7ac392a9e60e77b did change some behaviour when executing kitty via symlink because the icon in the dock is just a white sort of rectangle (the icon for a symlink).

@gotgenes Please verify that `kitty` is `/usr/local/bin/kitty` by executing `type kitty`. You should be able to work around the problem by executing `/Applications/kitty.app/Contents/MacOS/kitty` instead of `kitty` or by adding `/Applications/kitty.app/Contents/MacOS` in front of the `PATH` environment variable.

**Comment by kovidgoyal** [comment]
kitty itself does not do anything to titlebar colors. Cocoa lacks an API
to control them. As is noted in the docs for macos_titlebar_color it
only works using a hack, setting the overall window background color and
making the titlebar transparent. 

Also given that Apple tries very hard to prevent GUI apps from having a
command line interface, i am guessing this is caused simply by some
cocoa sub-system that launch services sets up that is not setup
automatically when launching an app directly. Sadly, I have no idea what
that might be.  Patches are welcome. In the meantime run kitty using
open instead of directly as a workaround. Or alternately, use
--single-instance which will create windows in already running kitty
instance.

**Comment by gotgenes** [comment]
@Luflosi Thanks for your recommendations. Here are my answers.

>@gotgenes Please verify that kitty is `/usr/local/bin/kitty` by executing `type kitty.`

```
$ type kitty
kitty is /usr/local/bin/kitty
$ ls -l /usr/local/bin/kitty 
lrwxr-xr-x  1 chris  admin  44 Sep 13 22:00 /usr/local/bin/kitty -> /Applications/kitty.app/Contents/MacOS/kitty
```

You're correct. It's a symlink from `/usr/local/bin`

>You should be able to work around the problem by executing `/Applications/kitty.app/Contents/MacOS/kitty` instead of `kitty` or by adding `/Applications/kitty.app/Contents/MacOS` in front of the `PATH` environment variable.

You're correct, again. Launching with `/Applications/kitty.app/Contents/MacOS/kitty` caused the title bar to respect the dark theme setting.
