### ISSUE TITLE
"Outer padding" is inconsistent (window borders don't always align)

### ISSUE THREAD

**Issue by sunaurus** [kovidgoyal/kitty#1994]
I've noticed that in some layouts, with some specific amounts of windows open, the outer borders of my windows don't align, which can look rather messy: 

![kitty](https://user-images.githubusercontent.com/5356547/65449104-f324e500-de42-11e9-8d59-432c5b9ca902.png)

Is this intentional?

**Comment by kovidgoyal** [comment]
It is unavoidable since window sizes have to be multiples of cell_height
which means, unless you set margins and borders to zero two windows
wont line up with one large window.

**Comment by sunaurus** [comment]
What about an option to add some additional padding to the end of the large window in cases like this? If it's a choice between slightly inconsistent padding and slightly misaligned borders, I would certainly choose the inconsistent padding. 

I'm not familiar with the code of this project yet, but if you think that this option might be interesting, I could try to create a PR for this over the weekend.

**Comment by kovidgoyal** [comment]
Sure feel free to create such an option.

**Comment by danrot** [comment]
I would also be interested in an option for that, since I totally agree with @sunaurus. I guess this could be an option in the `placement_strategy` configuration, right? What would be a good value? `center-align-border`? Not sure I am able to implement that within a reasonable amount of time, but if I find some time I could imagine trying at somewhen in the future.

**Comment by kovidgoyal** [comment]
placement_strategy has nothing to do with this. THe proposed fix is dynamically adding padding to a large window to make it match the neighboring small windows. placement_strategy simply controls how the entire set of windows is aligned inside the OS window.

**Comment by danrot** [comment]
Ah, I see, my idea would have been a slightly different one. I would have adjusted the margins between the windows in order to align them. In my specific setup the problem is that the larger window is higher than all smaller windows combined as shown in the attached screenshot.
<img width="752" alt="image" src="https://github.com/kovidgoyal/kitty/assets/405874/16e47839-b5dd-40f6-bd90-57d59a75cd34">

Here I would prefer to have them aligned and would accept a bigger margin between the 3 smaller windows.

Or am I mixing something up, and this is a different problem altogether?

**Comment by kovidgoyal** [comment]
Its the same issue. My point was simply that placement_strategy is not the answer, since it controls overall alignment. You would need a separate option to have layouts automatically adjust margins and/or padding to have things line up.
