### ISSUE TITLE
Kitty no longer increases font size when using Programmer Dvorak layout

### ISSUE THREAD

**Issue by sssilver** [kovidgoyal/kitty#2020]
Hi,

I use the [Programmer Dvorak](https://www.kaufmann.no/roland/dvorak/) keyboard layout, where the `+` sign is on the _lower register_ of the physical keyboard's `9`/`(` key.

![image](https://user-images.githubusercontent.com/619878/66156153-bdbc8c00-e5e6-11e9-9da4-fd726163d5a1.png)

In previous versions of Kitty, I would increase the font size by pressing Ctrl+Shift+physical `9`/`(`. Recently, that has stopped working. Neither does pressing Ctrl+Shift+physical `=`/`+`. Effectively, in order to increase my font size, I have to toggle back to the QWERTY layout.

Is this a regression or am I now doing something wrong?

**Comment by Luflosi** [comment]
I recently added a bunch of keyboard keys that were previously not properly recognised on non-QWERTY keyboard layouts. I think you just need to adjust which keys you need to press in your `kitty.conf`. The default is
```
map kitty_mod+equal     change_font_size all +2.0
map kitty_mod+minus     change_font_size all -2.0
map kitty_mod+backspace change_font_size all 0
```
You probably need to change `equal` to `plus`. If that doesn't work `kitty --debug-keyboard` should tell you which keys kitty thinks are being pressed.

**Comment by sssilver** [comment]
Ah, yes -- `=` certainly works!

I almost feel like Kitty should operate on a lower level of abstraction when it comes to shortcuts, so that it maps shortcuts to physical keys on the keyboard rather than symbols that those keys print. In other words, it should map zoom in to the physical key of `=` rather than the key that happens to print the `=` character with the current keyboard layout.

**Comment by Luflosi** [comment]
Do you mean that `map kitty_mod+= change_font_size all +2.0` worked for you? Or is that a typo?

I don't think the idea with the physical keyboard keys would work that well. I have a german keyboard with a german keyboard layout and so all the keys are labeled correctly with what they would print despite being a little different than the standard US keyboard layout. How would kitty know what the text key caps have written on them when the OS tells kitty that the layout is a certain way but the physical keyboard is actually different? It is also theoretically possible to swap some key caps. The OS would then have no way to know about that.
But maybe you meant that kitty should just treat the key as whatever it would be on the standard US keyboard. This might also not work well because the keyboard keys can be in different positions on different keyboards/layouts. For example my keyboard has an enter key shaped like the one in the image above but I know that some keyboards have a long rectangular one. This causes the surrounding keys to be in different positions. I'm sure there are more examples.

**Comment by sssilver** [comment]
I didn't add any mappings, I just pressed Ctrl+Shift+`6` (which is the `=` sign on programmer dvorak).

What I mean by saying "physical key" is that a keyboard has physical keys, and the keys are fixed. Regardless of what's printed on them, the keys do not change their positions. For what it's worth, it doesn't even matter what function they are bound to -- they're just keys. It's the OS's job to map these keys to particular letters or actions. In other words, the OS has an abstraction layer that has a map like:

"The physical Escape key on the top row" => "Esc"
"The physical plus key" => "+".

The values on the right change depending on what keyboard layout you choose. The values on the left never change -- they are the constant set of all the keys on the physical keyboard.

It looks like Kitty maps its own shortcuts from the values on the right. What I propose is that Kitty (like many video games) should map its shortcuts from the values on the left.

**Comment by Luflosi** [comment]
> I didn't add any mappings, I just pressed Ctrl+Shift+6 (which is the = sign on programmer dvorak).

Oh, ok. Feel free to remap the key so you don't need to change your habit.

> What I propose is that Kitty (like many video games) should map its shortcuts from the values on the left.

I would find that really annoying. For example to map <kbd>y</kbd> on my german keyboard, I'd have to put `z` in my `kitty.conf`. I would have to look up which physical keys correspond to which key in kitty for every single keyboard shortcut.
If you prefer this behaviour, this is already possible in a very similar way using the scan code reported by the OS:
Start kitty with `kitty --debug-keyboard`. In the new kitty instance press whatever key you would like to use. In the debug output look for `scancode: 0x26` or similar. Then put something like `map kitty_mod+0x26 change_font_size all +2.0` into your `kitty.conf`.

**Comment by kovidgoyal** [comment]
Mapping by physical keys does not really work in non-games, kitty actually started out with something close to that thanks to using glfw whichis designed for games. Read the long history of keyboard issues that resulted in me having to basically re-write the glfw keyboard handling code fromscratch.

**Comment by Luflosi** [comment]
Did the scan code solution work for you?
