### ISSUE TITLE
Weird Rendering of `/` in Vim

### ISSUE THREAD

**Issue by Abu-ZaydAbdullah** [kovidgoyal/kitty#205]
I am getting some weird font-rendering on my comments which start "//".

This is what it looks like in kitty.
<img width="271" alt="screen shot 2017-11-30 at 11 57 57 am" src="https://user-images.githubusercontent.com/20071707/33446619-3a3ddcbc-d5c6-11e7-8f24-250cc8cf7194.png">

And here is what it looks like on iTerm2 & Alacritty
<img width="308" alt="screen shot 2017-11-30 at 11 58 41 am" src="https://user-images.githubusercontent.com/20071707/33446628-4548a7c2-d5c6-11e7-9d63-362a02240e7f.png">

**Comment by kovidgoyal** [comment]
This is because that character is much wider in the italic variant of Operator Mono than in the normal variants. Which means it is rendered truncated. You can work around it by adding the following to your kitty.conf 

```
symbol_map U+002f Operator Mono Book
```

which will always use the / glyph from the Operator Mono Book font, even in the italic and bold variants.

The other terminals dont show this because they let large glyphs bleed into neighboring cells. You can see that in your screenshot where the bottom left of the / character bleeds onto the left gutter, in the non-kitty terminals. Probably the top right also bleeds, but you cannot see that since the next cell has no content in that area.
