### ISSUE TITLE
Flashing screen on autocomplete in nvim.

### ISSUE THREAD

**Issue by karambaq** [kovidgoyal/kitty#207]
![gif](https://imgur.com/a/Hw2VM)

**Comment by kovidgoyal** [comment]
Your attached image does not display. And I use YouCompleteMe for autocomplete in vim all day long, with no flashing screens in kitty.

**Comment by karambaq** [comment]
@kovidgoyal https://imgur.com/a/EQSlq

**Comment by kovidgoyal** [comment]
I tried exactly the example from your screenshot in nvim, editing a path with completion from YCM and I get no flashing. The only thing I can think of, if you see this flashing only in kitty and not other terminals is that kitty is fast enough that it renders the YCM menu being redrawn while other terminals dont, so you see the flickering only in kitty. Of course the real bug is why is your YCM menu being redrawn constantly. 

Two things you can check:

1) Run kitty with --dump-commands and you should see the commands being issued to redraw the menu

2) You can try increasing the input_delay and repaint_delay in kitty.conf and see

Other that that, I dont have any ideas, sorry.
