### ISSUE TITLE
Wrong vertical alignment with Sudo font

### ISSUE THREAD

**Issue by franciscod** [kovidgoyal/kitty#2086]
Something's wrong with the alignment using the [Sudo Font](https://github.com/jenskutilek/sudo-font):

![2019-10-23_01-45-18](https://user-images.githubusercontent.com/726447/67358440-c7c31200-f536-11e9-8afd-27e2ea5654df.png)

```

 AÁA
 EÉE
 IÍI
 OÓO
 UÚU

```

Initially I blamed the font, but [termite](https://github.com/thestinger/termite) seems to render this just fine.

Is there additional information that I can provide? Any experiments that I could make?

**Comment by kovidgoyal** [comment]
That looks like characters are coming from a different fallback font, see --debug-font-fallback

**Comment by franciscod** [comment]
Hmm should I see any additional output?

Just launched kitty like this:
```
$ kitty --debug-font-fallback 
[296 02:36:07.632494] Preloaded font faces:
[296 02:36:07.632548] normal face: /usr/share/fonts/sudo-font/SudoVariable.ttf:0
[296 02:36:07.632602] bold face: /usr/share/fonts/sudo-font/Sudo-Bold.ttf:0
[296 02:36:07.632639] italic face: /usr/share/fonts/sudo-font/Sudo-Italic.ttf:0
[296 02:36:07.632671] bi face: /usr/share/fonts/sudo-font/Sudo-BoldItalic.ttf:0
```

and did `cat weird` on that instance, but nothing new appears.

**Comment by kovidgoyal** [comment]
If you are not seeing anything then no fallback font is being used.

**Comment by kovidgoyal** [comment]
Someday if I have time I will look into what's going on with that font,  but I suggest just use a different one, there are dozens of them.

**Comment by franciscod** [comment]
Okay, thanks! Meanwhile I've asked in the font repo too.

**Comment by ctrlcctrlv** [comment]
Hello:

I have no interest in the font, to me its aesthetics are bad, (apologies to its author,) but I believe Ican confirm for you that it is *their problem* and not our (kitty's) problem.

Observe:
![2020-01-07-134100_552x237_scrot](https://user-images.githubusercontent.com/838783/71871141-3cc7e000-3153-11ea-8c8a-fe8eba516ad3.png)

I achieved this by going to &laquo;Element&rarr;Font Info&rarr;Grid Fitting&raquo;, hit &laquo;Default&raquo;, then re-generated the TTF.

The reason its author @jenskutilek could not reproduce it, I suspect, is due to DPI. We're both using it at high DPI, he's at low.

**Comment by franciscod** [comment]
Thanks for folllowing up, ctrlcctrlv! I've noticed it depends on font size, so changing font scale can expose it too.

**Comment by jenskutilek** [comment]
@ctrlcctrlv Could you send me your modified font? (Just attach it here) Because I'm not sure what this FontForge setting does.

I tested the font in ftview (FreeType viewer) and the problem is not visible there either, no matter what settings & sizes I try …

![Bildschirmfoto 2020-01-07 um 15 28 57](https://user-images.githubusercontent.com/3185950/71902516-8835ba80-3162-11ea-8f1b-1b3262c8d150.png)

**Comment by ctrlcctrlv** [comment]
We give FontForge away for free you know :-)

Jokes aside, here you go:

[Sudo-Regular.zip](https://github.com/kovidgoyal/kitty/files/4031065/Sudo-Regular.zip)

**Comment by jenskutilek** [comment]
Yes, I know, but different installations, settings, etc. may give different results…

I have diffed the two fonts, and it seems FontForge writes back the instruction tables from the original fonts. There are no differences in the instructions of your regenerated fonts, except for the composite flags. 0x1000 UNSCALED_COMPONENT_OFFSET is set by FontForge which should not influence this, as the components in accented letters don't have any offset in this font.

![Bildschirmfoto 2020-01-07 um 16 03 43](https://user-images.githubusercontent.com/3185950/71904902-4eb37e00-3167-11ea-9bca-7b172066dee1.png)

(Tables with differences are marked red in the right hand (modified) font)

What I've noticed now is that @franciscod is using the variable font instead of the Regular TTF. Maybe that is the reason for this behaviour? In the latest versions I have given the variable font a different family name (Sudo Variable) so the variable and static fonts are not mixed accidentally. Francisco, can you try using the latest static fonts only?

**Comment by ctrlcctrlv** [comment]
This doesn't have anything to do with TrueType instructions. FontForge has other interfaces for editing those (including a complete TT debugger). No, the difference is the `gasp` table. I don't know whether OP is using variable font, but before making my post I verified the issue with the regular font.

**Comment by ctrlcctrlv** [comment]
By the way. Kitty uses HarfBuzz. So it will never be enough to just use ftview

**Comment by jenskutilek** [comment]
Sorry to report that the whole FontForge thing was just a distraction. I tested the original font and the modified font by @ctrlcctrlv on Debian, normal DPI, font size 34, and both fonts show the original problem.

![Bildschirmfoto 2020-01-13 um 12 30 31](https://user-images.githubusercontent.com/3185950/72252878-82c3ee80-3600-11ea-82d5-2016c698733a.png)

I now believe it may have something to do with the vertical metrics … the ascender and descender values are set tightly so the line height does not become too tall for normal ASCII text. The accents go beyond those vertical metrics. Maybe the whole accented letter is drawn at the wrong position, i.e. beginning from the ascender value, even though the top of the accent is above the ascender value?

**Comment by ctrlcctrlv** [comment]
So why is my screenshot correct?

**Comment by jenskutilek** [comment]
Maybe because the phenomenon is not visible at every font size? I had to try several sizes to trigger the error. For me, it appears at 34 points. (Also at smaller sizes, I think e.g. 16 points, but it is not as noticeable.)

**Comment by ctrlcctrlv** [comment]
If your theory is correct you should be able to fix it just by generating a version of your font with a higher ascender. Does this work? (I tried it so I doubt it.)

**Comment by jenskutilek** [comment]
Yes, I can fix it by enlarging the ascender metrics. I'm not really happy with that because it changes the default line spacing … Anyway here is a new version with this and other changes: [Sudo version 0.41](https://github.com/jenskutilek/sudo-font/releases/tag/v0.41).
