### ISSUE TITLE
Status bar refresh frequently

### ISSUE THREAD

**Issue by zgpio** [kovidgoyal/kitty#2094]
# Environment
- macos 10.14.5
- kitty 0.14.6

# Reproduce Step
1. nvim -u NONE
2. hold key `j`, status bar refresh frequently, it annoys me.
I also tested it on alacritty, it didn't flash.
The status bar I mean shown as below:
![image](https://user-images.githubusercontent.com/19503791/67551581-db8b9580-f73b-11e9-886d-b5d71565d009.png)

**Comment by Luflosi** [comment]
I cannot reproduce the issue. Tested on macOS 10.14.6, kitty 0.14.6 compiled from source, NVIM v0.4.2.
Do you mean the menu bar flickers? That doesn't happen for me.
In any case, you can turn off the title in the menu bar, see https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.macos_show_window_title_in.

**Comment by zgpio** [comment]
This may be caused by my hackintosh. Thanks anyway.
Closed.

**Comment by Luflosi** [comment]
Did disabling the text in the menu bar with that config option provide an acceptable workaround?

**Comment by zgpio** [comment]
The `Kitty` and `Window` menu item still annoy me.

**Comment by Luflosi** [comment]
Since I can't reproduce the problem and I have no idea why it is happening it is impossible for me to fix this.
You could try the following patch (and keep the `macos_show_window_title_in` set to `window` or `none`!) as a possible workaround:
```diff
diff --git a/kitty/glfw.c b/kitty/glfw.c
index e7f680eb..c4419422 100644
--- a/kitty/glfw.c
+++ b/kitty/glfw.c
@@ -591,9 +591,6 @@ create_os_window(PyObject UNUSED *self, PyObject *args) {
         PyObject *ret = PyObject_CallFunction(load_programs, "O", is_semi_transparent ? Py_True : Py_False);
         if (ret == NULL) return NULL;
         Py_DECREF(ret);
-#ifdef __APPLE__
-        cocoa_create_global_menu();
-#endif
 #define CC(dest, shape) {\
     if (!dest##_cursor) { \
         dest##_cursor = glfwCreateStandardCursor(GLFW_##shape##_CURSOR); \
```
It removes as much of the menu bar as I think is possible. This has the unfortunate side-effect, that some keyboard shortcuts like <kbd>cmd</kbd>+<kbd>Q</kbd> won't work anymore. The kitty item remains but has no sub-items.
If your issue is very annoying, this might me worth trying for you.
