### ISSUE TITLE
Regression re editor for preferences

### ISSUE THREAD

**Issue by toonn** [kovidgoyal/kitty#2096]
My `EDITOR` var got set to nano for some reason, not sure why but that's beside the point. It did make me notice that kitty doesn't properly use the `VISUAL` variable to open up the preferences. This seems to be a regression because it used to open up in vim for me.

Current values:
```
VISUAL=vim
EDITOR=nano
```

`Cmd-;`, to open up preferences, opens up `kitty.conf` in a new kitty window inside *nano*.
This suggests to me that kitty's running `${EDITOR} kitty.conf` while accepted behavior is `${VISUAL:-${EDITOR}} kitty.conf`. Because no one uses non-visual editors (like ed) anymore anyway at least not to edit config files afaik.

Note that a "visual editor" is an editor like nano or vim. It has nothing to do with GUI editors which aren't guaranteed to work properly when set as either of `EDITOR` and `VISUAL`.

**Comment by Luflosi** [comment]
kitty will use the editor specified in `kitty.conf`. If the option is set to the default value `.`, kitty will try to load the environment variable `EDITOR`. Since by default it's not set on macOS, that won't work either. If that happens, kitty will start a shell and read the `EDITOR` environment variable from there. We try to avoid starting a shell because that makes kitty start quite a bit slower.
To work around kitty not respecting `VISUAL`, either set the editor in `kitty.conf`, see https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.editor or change `EDITOR` to `vim` in your `.bashrc` or similar.
@kovidgoyal should we try to read `VISUAL` as well before reading `EDITOR`?

**Comment by toonn** [comment]
The only reason to read `EDITOR` at all is that most people configure it wrong. It's a remnant from when line-based editors as opposed to visual editors were common.

**Comment by kovidgoyal** [comment]
@Luflosi: Sure I dont mind. I never use VISUAL myself since the original
rationale for it was that EDITOR is supposed to work on dumb terminals,
while VISUAL works on full screen "modern" terminals. Since I have never
used a terminal not capable of running VISUAL in the last decade it
seems highly redundant and far less intuitive than EDITOR. But ok, I
wont refuse a PR to prefer VISUAL over EDITOR is both exist.
