### ISSUE TITLE
Backspace not working properly in German keyboard layout

### ISSUE THREAD

**Issue by kmplngj** [kovidgoyal/kitty#2111]
Hi,

backspace is not working correct for me. I makes a space instead a backspace.

Setup:

Kitty on macOS (German keyboard layout) connecting via ssh to CentOS or Fedora
Local is no problem (without ssh).

Is this a Kitty bug? I don't have this problem with iTerm.

Thanks a lot
Jan

**Comment by Luflosi** [comment]
See https://sw.kovidgoyal.net/kitty/faq.html#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer.
The terminfo file is not present on the remote machine. Use `kitty +kitten ssh myserver` instead of `ssh myserver` once, it will automatically copy the file.

**Comment by kmplngj** [comment]
Nice. I only have this to do once for a server. Am I right?

**Comment by SolitudeSF** [comment]
unless you install terminfo system-wide, once per user per server.

**Comment by kmplngj** [comment]
Thanks for your help!
