### ISSUE TITLE
macOS: a very long terminal title will fill up all the menubar

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#2132]
In the window title I think it's fine to take up all the space but it looks a bit strange in the menubar:

<img width="1440" alt="Screenshot 2019-11-14 at 00 21 36" src="https://user-images.githubusercontent.com/3632883/68813075-f71bf900-0674-11ea-824b-b8231c2ad9e2.png">

Perhaps some limit (64 chars?) followed by `...`?

**Comment by kovidgoyal** [comment]
Whats wrong with taking up the space, if needed? Does it prevent something being used in the menubar?

**Comment by minusf** [comment]
i think a limit would be useful as i have a lot of information in my menubar: battery, clock, sound, cpu load, disk activity, etc.  as you can see in the screenshot the full title still didnt fit, so it's cut off  at some point anyway.

**Comment by kovidgoyal** [comment]
Yeah what I am asking is, does the long title push off this information? I would have thought coca would truncate menu items that dont fit before they interfere with other widgets on the menu bar.

**Comment by Luflosi** [comment]
macOS removes the items on the right until the stuff on the left fits. But I'm not sure truncating the information is a good idea because we don't know how long it should be. There can be arbitrarily many items on the right and unless there is some way to query how much space those items take up, it's difficult deciding on one particular length that works for everybody.

**Comment by minusf** [comment]
as you can see on the screenshot, it fills it up to the edge.  the screenshot is from "wall to wall". i was also suprised that the OS gives up all this place for the menubar :}

> macOS removes the items on the right until the stuff on the left fits. But I'm not sure truncating the information is a good idea because we don't know how long it should be. There can be arbitrarily many items on the right and unless there is some way to query how much space those items take up, it's difficult deciding on one particular length that works for everybody.

the information is already truncated as it simply does not fit in this example.  the menubar is normally for menu items and not variable length information items like this and while i like the way it is being abused, i think it would be more useful to have a maximum width with an ellipsis (which already happens at the edge in this example).  i personally would not expect more information to be shown than what is shown with a "standard" 80x24 terminal window title, which depending on the text (not monospace font) is around 60-90 characters.

**Comment by kovidgoyal** [comment]
Well one could theoretically use NSStatusItem instead of a menu item to
display the title. This means cocoa will auto hide it if it is too long.
Sadly, it does not auto truncate it instead.

**Comment by minusf** [comment]
i also see that it is not being updated correctly all the time when an external monitor is attached. even if a different terminal is active, the previous active terminal's title is shown in the menubar...

**Comment by minusf** [comment]
(for the record i have now switched to `macos_show_window_title_in window` and i am happy with it)

**Comment by wyuenho** [comment]
Now that we are in 2022, I just want to say, on the M1 Pro MBPs, any command line longer than a couple of words will be shifted entirely to the right of the screen due to the notch, so the end result is neither the space can be filled up nor the command line on the menu visible lol.

I'd glad there's a configuration for it tho, it should be the default on M1 Pro MBPs.

**Comment by Techcable** [comment]
For some reason, this appears fixed for my as of the latest commit (43ceaf0b7e85422d7d97502c2407e94337b5a50d).

I didn't change my config files or anything. It just appears on the left of the menu bar now (right next to "Shell", "Window", "Help").

![screenshot](https://user-images.githubusercontent.com/4615889/152246112-4a2bb1b4-853b-4309-8493-cde6af01f65a.png)

Can someone else please confirm this is fixed on the latest nightly?

**Comment by toonn** [comment]
@techcable, do you mean to the left of the notch? Because that's the issue described by wyuenho.

I'm on a rather large display so I appreciate there not being a hardcoded limit. If a limit is decided upon I'd like to request it be configurable.

**Comment by Techcable** [comment]
> @techcable, do you mean to the left of the notch? Because that's the issue described by wyuenho.

No. I mean it's gone from the right side of the screen to the left side. I have "kitty. Shell", "Window", "Help", <name of the window> on the left side.

Then I have a large space, then I have the items normally in my right menu bar.

This change seems to come between 0.24.1 and 0.24.2. I did not edit my config at all. It just moved.

> I'm on a rather large display so I appreciate there not being a hardcoded limit. If a limit is decided upon I'd like to request it be configurable.

I don't know if they added any sort of limit. For me the problem has effectively gone away because the window name has moved.
