### ISSUE TITLE
Fontconfig issue

### ISSUE THREAD

**Issue by tobia** [kovidgoyal/kitty#214]
I'm having a strange bug. I have configured my new system (Arch Linux) to use sub-pixel anti-aliasing in my `~/.config/fontconfig/fonts.conf`

Every app I have tried so far follows those rules (Firefox, Chromium, Leafpad...) except Kitty, which uses a default grey anti-aliasing, no matter what I specify.

Using `strace` I can see that it opens the same FontConfig library as the other programs: `/usr/lib/libfontconfig.so.1` and that it sources my local config file correctly. But then it seems to just ignore it. Or maybe it turns the glyphs into monochromatic after the font has been rendened? I dunno.

I'm using the Sway window manager, which is Wayland-based. Could that be it?

**Comment by kovidgoyal** [comment]
In kitty all glyphs are rendered as 8bit alpha masks stored on the GPU for performance. So there can be no sub-pixel antialiasing. In order to implement it one would no longer be able to store prerendered glyphs since to implement sub-pixel rendering you have to know the foreground and background colors at glyph render time. This is a huge performance hit for not much gain. On newer high DPI displays, there is not much point in sub-pixel rendering anyway.

**Comment by parthsdoshi** [comment]
While I agree that it's not needed on newer hidpi displays, I would argue that most people still use their "older" monitors that are probably not hidpi. Would you be opposed to sub-pixel rendering being an optional feature either chosen in run-time or compile-time?

**Comment by kovidgoyal** [comment]
In order to do sub-pixel rendering one would have to render to an offscreen buffer first (in order to do correct alpha blending), this has significant performance implications and code complication implications. As such I'm not really in favor of it. But you are welcome to send a PR and I will review it, and might merge it if it has no negative performance implications when disabled and reasonable code complication overhead.

**Comment by tobia** [comment]
As the OP, I have to say I agree with @kovidgoyal. Sub-pixel rendering would substantially lower the efficiency of Kitty's rendering. Also, if you have a low-res screen, there's less reason to use an OpenGL-based terminal emulator. Traditional rendering techniques were and still are good enough.

In fact, on low-res screens I still prefer uRxvt with my favorite hand-drawn bitmap font, [GohuFont 14px](http://font.gohu.org/), no anti-aliasing at all. It looks so much sharper than any kind of anti-aliasing.

**Comment by parthsdoshi** [comment]
I would agree with you but I think there are a lot of people out there who have a hidpi laptop but connect the laptop to a non-hidpi monitor. I'd like to be able to use the same terminal seamlessly wherever I am without having to switch.

But of course, if the performance hit is as drastic as you say; I can see why someone wouldn't want it to be added.

**Comment by slavoutich** [comment]
Pity. This is a great terminal emulator, but fonts look really ugly on my 1920x1080 15 inch.

**Comment by strange** [comment]
Yes, it's a pity. Looks like a very nice project, but the font rendering is awful compared to urxvt on my setup (Arch, dual Dell 27" 2560x1440, Deja Vu Sans Mono at 11pt). But it's hard to argue with the reasons outlined by @kovidgoyal . Will keep an eye on the project, keep up the great work!

**Comment by pkazmier** [comment]
Maybe it’s years of using a Mac, but I love the look of “thicker” fonts. I, too, am struggling with the awesomeness of Kitty with the ugliness of my fonts (Pragmata Pro). Every time I think I’ve come to grips with it, I accidentally open up iTerm and realize that I’m kidding myself - I just prefer the sub-pixel aliasing. I must be in the minority though as I never understood why iTerm and other programs (VS Code) give options to disable it. Nonetheless, thanks for a fantastic terminal! Your level of support is outstanding!

**Comment by kovidgoyal** [comment]
I can totally appreciate that, once you get used to a certain look, it is very hard to adapt to a change. I have this issue all the time when I am forced to work temporarily on third party computers, I just cant get used to how the fonts look :)

As I said, I am willing to merge a patch that has no overhead when disabled and reasonable levels of code complication.

**Comment by slice** [comment]
I attempted this by tweaking the `render_glyphs` function: https://github.com/kovidgoyal/kitty/blob/master/kitty/core_text.m#L364-L365

I tried various combinations of function calls:

* `CGContextSetShouldSmoothFonts`
* `CGContextSetAllowsFontSmoothing`
* `CGContextSetAllowsAntialiasing`
* `CGContextSetAllowsFontSubpixelQuantization`
* `CGContextSetAllowsFontSubpixelPositioning`
* `CGContextSetShouldSubpixelQuantizeFonts`
* `CGContextSetShouldAntialias`

However, disabling and enabling a variety of these CoreText APIs had no effect.

I did more research into how terminal emulators like iTerm2 and Alacritty did "thin stroke" rendering. Both of those emulators have options to enable and disable thin strokes. It turns out that there is a semi-private (?) smoothing style API:

```c
extern void CGContextSetFontSmoothingStyle(CGContextRef, int);
extern int CGContextGetFontSmoothingStyle(CGContextRef);
```

This API is also used in WebKit, which is how people found out about it.

Passing `16` (`2 << 3`) into `CGContextSetFontSmoothingStyle` would enable thin strokes. But this isn't useful to us as the strokes are already thin.

I tried some other smoothing styles, but they didn't appear to revert back to the thick strokes.

* Alacritty: https://github.com/jwilm/alacritty/pull/277/files#diff-91c8eb5607beecf6f1ff9718907e2df6R408
* iTerm2: https://github.com/gnachman/iTerm2/blob/5661e5681f1d19aad28a33a30b9b1380b48962a2/sources/Metal/Support/iTermCharacterSource.m#L266

Kitty's font rendering mechanics might be forced to thin strokes because of how the views are backed, maybe? It doesn't seem that tweaking the CoreGraphics context may help, but maybe I just didn't try hard enough...

I hope this helps!

**Comment by kovidgoyal** [comment]
Yeah tweaking coregraphics parameters will have no effect. Unlike most (all?) other terminals kitty achieves its performance (partly) by storing alpha masks of each character on the GPU. So every character is rendered only once. A render in kitty just means sending the indices for each apha mask to the GPU. This alpha mask is then blended with the foreground color, background color, and any negative z-index graphics and drawn to screen.

So to enable sub-pixel rendering, you have to first:

1) Generate three-channel alpha masks
2) Render the background and any negative z-index graphics to an offscreen buffer
3) Blend the three channels onto that buffer, with gamma correction
4) Render positive z-index graphics on top
5) Done

**Comment by kovidgoyal** [comment]
Just FYI, Apparently Apple agrees with me, they are removing sub-pixel antialias completely in 10.14 https://infinitediaries.net/removed-in-macos-10-14-mojave/

**Comment by karambaq** [comment]
@kovidgoyal and that's really sucks :(

**Comment by kovidgoyal** [comment]
@karambaq Shouldn't that comment be directed at Apple, not me? In any case, just to note, the procedure I described above for adding sub-pixel rendering to kitty would work regardless of any changes Apple makes. So if you love sub-pixel rendering so much, feel free to implement it.

**Comment by darthdeus** [comment]
Probably not the right place to ask, but I'm not sure where to ask. Do you guys have any suggestions what to use instead for external monitors?

I've been playing with kitty, but now that I'm looking at it on my 27" monitor, I just don't feel like I could get used to it. It looks so pretty on the retina display, but so ugly on the monitor :(

**Comment by MattWalston** [comment]
@darthdeus looks great on my high dpi monitor.

**Comment by tobia** [comment]
@darthdeus See my comment above (6th from the top)

**Comment by tbodt** [comment]
I have a patch for Mac that renders glyphs using subpixel antialiasing in three channel color, then averages the color values to create an alpha mask. It looks pretty good, especially on dark colorschemes, but it's not real subpixel antialiasing, and I'm not sure if I know enough to implement three-channel blending on the GPU.

```diff
diff --git a/kitty/core_text.m b/kitty/core_text.m
index 6a369900..e752b9fc 100644
--- a/kitty/core_text.m
+++ b/kitty/core_text.m
@@ -356,9 +356,9 @@ render_color_glyph(CTFontRef font, uint8_t *buf, int glyph_id, unsigned int widt

 static inline void
 ensure_render_space(size_t width, size_t height) {
-    if (render_buf_sz >= width * height) return;
+    if (render_buf_sz >= width * height * 4) return;
     free(render_buf);
-    render_buf_sz = width * height;
+    render_buf_sz = width * height * 4;
     render_buf = malloc(render_buf_sz);
     if (render_buf == NULL) fatal("Out of memory");
 }
@@ -366,16 +366,23 @@ ensure_render_space(size_t width, size_t height) {
 static inline void
 render_glyphs(CTFontRef font, unsigned int width, unsigned int height, unsigned int baseline, unsigned int num_glyphs) {
     memset(render_buf, 0, render_buf_sz);
-    CGColorSpaceRef gray_color_space = CGColorSpaceCreateDeviceGray();
-    CGContextRef render_ctx = CGBitmapContextCreate(render_buf, width, height, 8, width, gray_color_space, (kCGBitmapAlphaInfoMask & kCGImageAlphaNone));
-    if (render_ctx == NULL || gray_color_space == NULL) fatal("Out of memory");
+    CGColorSpaceRef color_space = CGColorSpaceCreateDeviceRGB();
+    CGContextRef render_ctx = CGBitmapContextCreate(render_buf, width, height, 8, 4 * width, color_space, kCGImageAlphaPremultipliedFirst | kCGBitmapByteOrder32Host);
+    if (render_ctx == NULL || color_space == NULL) fatal("Out of memory");
+    // render against a black background (rather than a transparent background)
+    CGContextSetRGBFillColor(render_ctx, 0, 0, 0, 1);
+    CGContextFillRect(render_ctx, CGRectMake(0, 0, width, height));
     CGContextSetShouldAntialias(render_ctx, true);
     CGContextSetShouldSmoothFonts(render_ctx, true);
-    CGContextSetGrayFillColor(render_ctx, 1, 1); // white glyphs
+    CGContextSetRGBFillColor(render_ctx, 1, 1, 1, 1); // white glyphs
     CGContextSetTextDrawingMode(render_ctx, kCGTextFill);
     CGContextSetTextMatrix(render_ctx, CGAffineTransformIdentity);
     CGContextSetTextPosition(render_ctx, 0, height - baseline);
     CTFontDrawGlyphs(font, glyphs, positions, num_glyphs, render_ctx);
+    // convert to greyscale
+    for (size_t i = 0, j = 0; i < width*height; i++, j += 4) {
+        render_buf[i] = (render_buf[j] + render_buf[j+1] + render_buf[j+2]) / 3;
+    }
 }

 static inline bool
```

**Comment by tbodt** [comment]
Investigating further, it seems almost impossible to have CoreText render a glyph with three alpha channels. Has anyone found a way to do this? @kovidgoyal

**Comment by kovidgoyal** [comment]
No idea, sorry. I'm not a CoreText expert. II suspect that itis deliberate since to do proper sub-pixel rendering you have to know the background color. I assume Apple didn't bother with making such an API since if you know the background color already, it's easier to just render both in one pass.

**Comment by tbodt** [comment]
@kovidgoyal Would you merge this patch under an option called something like `fake_subpixel_antialiasing`?

**Comment by kovidgoyal** [comment]
Doesn't seem workable to me.

1) It is not sub-pixel antialiasing since subpixels are not actually being individually colored
2) I suspect it wont look good if your background color is not similar to the hard coded bg. Think of full screen applications that change background colors/ use menus/text boxes that are often light while the main background is dark. Given the architecture of kitty there is no way to adjust characters for different background colors on the CPU, only the GPU and that requires using alpha masks
3) It would probably make text look worse on retina displays

What you can do is use FreeType instead of CoreText to render. I know FreeType supports generating sub-pixel alpha masks. Of course, chances are you (by that I mean the metaphorical you) wont like the way text rendered with freetype will look

**Comment by tbodt** [comment]
Hmm, maybe I could render the glyph in black on a red, green, and blue background, then extract and invert the red/green/blue channel to use as the alpha channel? Not 100% sure that would give the correct result.

**Comment by kovidgoyal** [comment]
Dunno, there are a lot of moving parts here: You'd have to extract the alpha masks using some sort of hack, then you'd have to change the OpenGL code to render to a framebuffer and change the shaders to to alpha blending of the framebuffer color and the foreground color using the alpha masks with propoer gamma correction. It will be very hard to say at which point in this pipeline things are going wrong. There's a reason Apple is dropping sub-pixel AA :)

That said, feel free to try, as I said before, I am willing to merge a patch that does all that, as long as it does not impact the no-subpixel AA use case.

**Comment by tbodt** [comment]
It's also possible to do what the other GPU-accelerated terminals do, and key the glyph cache with the foreground and background color in addition to the glyph. That's probably a whole lot easier than implementing the whole subpixel antialiasing pipeline.

**Comment by kovidgoyal** [comment]
That would be a huge increase in memory consumption for  the glyph cache is you use colored text. It would probably increase cache size by an order of magnitude for anyone using applications such as vim. or colored ls etc. There is a reason kitty is so much less resource intensive than other GPU accelerated terminals. Not to mention that it wont work with the graphics support in kitty at all (remember text in kitty can be overlaid over graphics).

If you like thicker fonts, why not just use a font with a thicker stem size? It seems backwards to me to get the font rendering subsytem to jump through hoops just to thicken your fonts. Different typefaces have different design characteristics and IMO it should be the job of the rendering system to render them as accurately as possible. Otherwise font designers will never be able to rely on rendering systems to get rendering right.

**Comment by renatofdds** [comment]
@kovidgoyal i totally understand your position on the matter, but please could you keep this issue open so someone else can implement this as an optional feature (off by default) ? 

I tested kitty and is such a great project and i really would like to use it but without sub pixel anti-aliasing is a deal breaker for me on 1080p and i believe for many people too because the font render quality is just too low. 

Perhaps another option is you consider adding a section on the readme to explain your position (which is totally understandable) but encourage anyone to code it as an optional flag in a way that doesn't change anything (performance/resource wise) when it's off ? Surely higher DPI is here but i think many people will still be stuck with 1080p for quite some time.

**Comment by kovidgoyal** [comment]
Sorry, I dont keep issues open that have no well defined path to implementation and that I dont think are a good idea. As I have already stated, i am willing to merge a patch that has no ill-effects for the non-subpixel use case, but that does not mean I actually think such a patch is a good idea.

**Comment by renatofdds** [comment]
I understand, thank you for your consideration.

**Comment by tbodt** [comment]
The insane hack used to get subpixel antialiasing in the Metal renderer in iTerm 2 is documented here: https://docs.google.com/document/d/1vfBq6vg409Zky-IQ7ne-Yy7olPtVCl0dq3PG20E8KDs/edit#!

**Comment by kovidgoyal** [comment]
I was not suggesting there was back and forth in your technique, I was just pointing out that there wasn't any in mine, either. Yeah, CoreText not creating per-channel masks is a big problem on macOS.

**Comment by joewarrenmeeks** [comment]
Another voice.. I love kitty on my macbook pro laptop monitor, but moving a window onto my external 27" display, the fonts look ragged and hard to read.

I'll follow the project in the mean time and hope for a solution.

Good luck!

**Comment by tbodt** [comment]
I've figured out how to use kCGTextFillStroke to unconditionally add a bit of weight to the font, which is a good enough workaround for me. Here's the patch, in case anyone wants to use it:

```diff
diff --git a/kitty/core_text.m b/kitty/core_text.m
index 6a369900..ea119560 100644
--- a/kitty/core_text.m
+++ b/kitty/core_text.m
@@ -372,10 +372,14 @@ render_glyphs(CTFontRef font, unsigned int width, unsigned int height, unsigned
     CGContextSetShouldAntialias(render_ctx, true);
     CGContextSetShouldSmoothFonts(render_ctx, true);
     CGContextSetGrayFillColor(render_ctx, 1, 1); // white glyphs
-    CGContextSetTextDrawingMode(render_ctx, kCGTextFill);
+    CGContextSetGrayStrokeColor(render_ctx, 1, 1);
+    CGContextSetLineWidth(render_ctx, 0.75);
+    CGContextSetTextDrawingMode(render_ctx, kCGTextFillStroke);
     CGContextSetTextMatrix(render_ctx, CGAffineTransformIdentity);
     CGContextSetTextPosition(render_ctx, 0, height - baseline);
     CTFontDrawGlyphs(font, glyphs, positions, num_glyphs, render_ctx);
+    CGContextRelease(render_ctx);
+    CGContextRelease(gray_color_space);
 }
```

**Comment by kovidgoyal** [comment]
@tbodt that patch I'd be willing to merge under an option named macos_thicken_fonts or similar.

**Comment by tbodt** [comment]
#950

**Comment by beelze** [comment]
As for me, Kitty is the best terminal. There are a lot of nice features which I need – in one place. But it seems the only way to not hurt my eyes with Kitty is to use 4K display device? I'm using 2× 27'' 2K monitors and tried some bitmap fonts too but my eyes still aren't pleased with it.

**Comment by David-Else** [comment]
I spent the day comparing Kitty to Gnome Terminal, and Kitty wins in every way apart from the single most important thing, the readability of the text. Without sub-pixel rendering on a 1080p display the fonts look blurry in comparison. I would buy a 4k monitor, but my graphics card doesn't support 4k, so back to Gnome Terminal until this is fixed.

**Comment by cultureamp-brucew** [comment]
Use 
```
macos_thicken_font 0.75
```
now it's more readable on a 24" 1080p display

Ref: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_thicken_font

**Comment by number5** [comment]
Use 
```
macos_thicken_font 0.75
```
now it's more readable on a 24" 1080p display

Ref: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.macos_thicken_font

**Comment by trathborne** [comment]
> Without sub-pixel rendering on a 1080p display the fonts look blurry in comparison.

wezterm does sub-pixel rendering: https://wezfurlong.org/wezterm/config/lua/config/freetype_load_target.html

**Comment by kovidgoyal** [comment]
Except, as noted above, CoreText does not actually give you a mask with three channels. And that's not even going into the issues you will have doing sub-pixel alpha blending on non-transparent backgrounds. See #1604

**Comment by Isopod** [comment]
Apple abandoned subpixel antialiasing in modern versions of their OS, there is probably nothing that can be done about that and I wouldn't bother. But for other operating systems it would still be useful. Drawing onto transparent backgrounds is always a problem with subpixel rendering. Most implementations just give up at that point and fall back to grayscale antialiasing. Is that the only problem with that MR?

**Comment by kovidgoyal** [comment]
No idea, the OP never responded so I never actually reviewed it. And
that will need refactoring after #5423 so I suggest you wait till that
is merged

**Comment by bluenote10** [comment]
For me personally, this is not limited to 1080p. I'm working at 1440p (at 27"), and it still makes a pretty huge difference in terms of font legibility. Considering that human eyesight varies a lot across individuals, I guess it is expected that some users would happily trade-off some rendering performance for better readability.

**Comment by rulatir** [comment]
> kitty does not support sub-pixel rendering. Supporting it would require both a performance hit (all cached glyph images would become three times larger and alpha blending would require three separate per-channel calculations) and also a fair bit of code complication. Given that on newer high DPI displays, there is not much point in sub-pixel rendering anyway, I am not interested in implementing it.

So is kitty for people with high DPI displays, or for boomers on 1024×768 CRTs aka "terminal power users"?

**Comment by rosinflower-studios** [comment]
I would like kitty to obey my freetype settings. I don't care how much of a “performance hit” I would take; clearly it isn't that much since it's enabled for the entire rest of my computer, and the rest of my computer runs just fine.

As a “terminal afficianado”, I [“spend all day staring at text, so getting text rendering just right is very important.”](https://sw.kovidgoyal.net/kitty/changelog/#variable-font-support-0-36)

**Comment by fkjldjfo9iour** [comment]
Almost 10 years later, and lol, even now mid range laptops are being sold with low DPI screens. Not to mention the millions if not billions of people rocking old PCs/laptops. Really unfortunate that this basic feature is not supported.
