### ISSUE TITLE
Looks like icon width smaller than need.

### ISSUE THREAD

**Issue by karambaq** [kovidgoyal/kitty#215]
![image](https://user-images.githubusercontent.com/14233969/33622270-73411286-d9fe-11e7-916c-a255cc7e1054.png)

**Comment by kovidgoyal** [comment]
There is no such thing as an icon width. That symbol is presumably coming from a font whose metrics are different from whatever font you have chosen as the main font. In such a case, if the symbol is greater than 133% of the available width kitty will auto-resize it to fit, otherwise it will truncate it as you see there.
