### ISSUE TITLE
0.15.0 fails to build with musl

### ISSUE THREAD

**Issue by SolitudeSF** [kovidgoyal/kitty#2169]
I'm not an expert, but here are relevant logs https://travis-ci.org/void-linux/void-packages/jobs/617596821#L545

**Comment by kovidgoyal** [comment]
It's likely it requires some macro such as _POSIX_SOURCE defined for
time.h to include clock_gettime(). But because monotonic.h is included
all over the place defining the macro inside it is not going to work.
Which means it needs to be defined globally as a compiler flag and that
could break something else, so somebody with some experience of musl
needs to figure out the best way to get time.h to include
clock_gettime()
