### ISSUE TITLE
macos kbd shortcut issue

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#2183]
I am a bit confused by the macos specific keyboard shortcuts listed on https://sw.kovidgoyal.net/kitty/#other-keyboard-shortcuts

These are my settings from the config file:
```
map kitty_mod+equal     change_font_size current +1.0
map kitty_mod+minus     change_font_size current -1.0
map kitty_mod+backspace change_font_size current 0
```

I have added a "works" column as there is an interesting matrix of what works and what doesnt for me:

Action | Shortcut | works | macos specific | works 
-- | -- | -- | -- | --
Increase font size | ctrl+shift+equal | yes | (also ⌘++ on macOS) | no
Decrease font size | ctrl+shift+minus | yes | (also ⌘+- on macOS) | yes
Restore font size | ctrl+shift+backspace | no | (also ⌘+0 on macOS) | yes

- neither `⌘++` (`cmd+shift+=`) and/or `⌘+=` increase the font size for me.

- the `cmd` based keys always use hardcoded `change_font_size all`.  I think it would be nice if this was explicitly mentioned, esp as there is functionality to do this for all windows or just the current one.

kitty 0.15.0
macos 10.14.6 Mojave

**Comment by Luflosi** [comment]
If you want to use <kbd>cmd</kbd>+<kbd>shift</kbd>+<kbd>=</kbd>, you have to specify it with the <kbd>shift</kbd> key and the <kbd>=</kbd> key in the config file because that is different from <kbd>cmd</kbd>+<kbd>+</kbd>. This is a known limitation of the keyboard handling.
What you described as "hardcoded" is probably just the original keyboard shortcut, which wasn't overwritten because your keyboard shortcuts were different from the original. You can remove keyboard shortcuts by mapping them to `no-op` or by using `clear_all_shortcuts yes` before the shortcuts.
What is your `kitty_mod` set to? You may want to use `kitty_mod cmd` to use the command key.

**Comment by minusf** [comment]
my config:

```
kitty_mod ctrl+shift
```

i have not cleared out the default kbd shortcuts, and this ticket is first and foremost about 2 things:

1. `cmd++` does not work for me as per documentation. (it's just extra confusion for me that `+` is `shift+=`)

2. `ctrl+shift+backspace` i do override in my config to reset only the current window, and this shortcut does nothing for me. to reset the font size i always have to use `cmd+0` which resets every window, not just the current one.

**Comment by minusf** [comment]
hm.  `ctrl+shift+backspace` works correctly.  not sure what happened, probably my fault.  only `cmd++` remains, but it's not a binding i actually set, so...

**Comment by Luflosi** [comment]
I suppose we should document this limitation of the keyboard handling...
