### ISSUE TITLE
Can only drag icon on Ubuntu

### ISSUE THREAD

**Issue by TurkeyMcMac** [kovidgoyal/kitty#2190]
When I open kitty with `kitty --detach`, the icon appears on the sidebar, as it should. When I click it, it opens, as it should. The icon responds correctly the first time I drag it. However, after that first dragging, I cannot click it to bring it into focus; instead, I always just end up dragging the icon. I can also sometimes bring up the right-click options "All Windows" and "Quit" by clicking on it. However, I am forced to use ALT+TAB to bring kitty into focus.

Here is the output of `kitty --debug-config`:
```
kitty 0.13.0 (460c353898) created by Kovid Goyal
Linux TurkeyMcMac 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64
Running under: X11
Ubuntu 18.04.3 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
Loaded config files: <$HOME>/.config/kitty/kitty.conf

Config options different from defaults:
adjust_line_height 1
font_family        Bitstream Vera Sans Mono
font_size          8.0
```

**Comment by bew** [comment]
What do you mean by "dragging the icon" ?

**Comment by kovidgoyal** [comment]
Since kitty has nothing to do with Ubuntu and its desktop chrome (which
I think is GNOME these days), I dont see why this is a kitty issue.
kitty does not create the taskbar entry nor does it manage window focus
when the entry is clicked on.

I suggest rather than dragging the icon to create a launcher, simply
create one manually as described here:
https://sw.kovidgoyal.net/kitty/binary.html#desktop-integration-on-linux

Then add that to the taskbar or whatever it is called in GNOME. As far
as I know that should work fine.
