### ISSUE TITLE
xterm-256color redrawing issues

### ISSUE THREAD

**Issue by minusf** [kovidgoyal/kitty#2192]
recently i have switched from `screen-256color` to `xterm-256color` on my remote openbsd servers.

```
local$ grep xterm .config/kitty/kitty.conf
term xterm-256color

remote$ echo $TERM
xterm-256color
remote$ grep term .tmux.conf
set -g default-terminal xterm-256color
remote$ mutt -v |grep ncurse
ncurses: ncurses 5.7.20081102 (compiled with 5.7)
```

while using kitty and ssh-ing in, i get rendering glitches in mutt where the previous email parts still show up in the current one.  the reason why i think this might be kitty related is because i cannot reproduce the same in iTerm.  it's not much, i know.  is there a way to track this down?  there are too many moving parts here...

**Comment by kovidgoyal** [comment]
Read the entry about SSH in the kitty FAQ.

**Comment by minusf** [comment]
i have read the FAQ and i dont see how it applies here.

**Comment by kovidgoyal** [comment]
Dont use zterm-256color kitty is not xterm. Use xterm-kitty and make
sure the terminfo/termcap definitions are available on the server.

**Comment by minusf** [comment]
are you saying that `xterm-kitty` is the only `TERM` supported?

**Comment by Luflosi** [comment]
Yes. The terminfo file tells programs which escape sequences to use for doing things like moving the cursor and adding color. If you change which terminfo file is used, other programs will use the wrong escape sequences which can lead to corrupted text, as you experienced. You should not change the `term` setting in `kitty.conf`. Read https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.term.
Unfortunately tmux poses a bit of a problem here. If you use `xterm-256color` inside tmux, programs will not be able to use all features of kitty, such as the full keyboard protocol. On the other hand, if you use `xterm-kitty` inside tmux, programs may output the wrong escape sequences for tmux. Nevertheless @kovidgoyal recommends doing the latter. With `xterm-kitty` inside tmux, I experienced a few glitches with htop. I recommend trying both and seeing which works best.

**Comment by minusf** [comment]
nah, sorry, this is way too much hassle.  the terminfo/termcap thing is a mess to begin with and the last thing i want to do is messing with it on all the servers where i login, that's just not sustainable.  there is a perfectly fine widely used `TERM` and it's called `xterm-256color`. if `xterm-kitty` is not compatible with it it should clearly say so in the docs/config file and not make `term` changeable in the first place...

**Comment by kovidgoyal** [comment]
It does clearly say so in the docs and config file. There is even a joke about not believing whatever crap advice you read on StackOverflow about changing TERM. And there is nothing "fine" about xterm-256color. using it means every terminal is forever a slave to whatever mistakes xterm continues to make. And finally, if you had read the FAQ entry properly you would note that it includes a way to automatically copy terminfo files to servers when you ssh into them.

**Comment by minusf** [comment]
```
#: The value of the TERM environment variable to set. Changing this
#: can break many terminal programs, only change it if you know what
#: you are doing, not because you read some advice on Stack Overflow
#: to change it. The TERM variable if used by various programs to get
#: information about the capabilities and behavior of the terminal. If
#: you change it, depending on what programs you run, and how
#: different the terminal you are changing it to is, various things
#: from key-presses, to colors, to various advanced features may not
#: work.
```

i am sorry but i dont read this as "kitty works only with xterm-kitty, no other values are supported".

i am sure i dont know as much about terminals as you do, but i have never heard the advice to use `xterm-256color`/`screen-256color` to be jokes, or that you need a license to kill to set them.

automating the copying is not the core issue for me.  making all the terminal based programs work correctly with exotic termcaps is. i use these terms because despite their issues/bugs/quirks they are the most supported with all the terminal programs.  you have started your own and that is nice but it seems like an uphill battle to me.

**Comment by kovidgoyal** [comment]
On Thu, Dec 12, 2019 at 06:06:52PM +0000, minusf wrote:
> ```
> #: The value of the TERM environment variable to set. Changing this
> #: can break many terminal programs, only change it if you know what
> #: you are doing, not because you read some advice on Stack Overflow
> #: to change it. The TERM variable if used by various programs to get
> #: information about the capabilities and behavior of the terminal. If
> #: you change it, depending on what programs you run, and how
> #: different the terminal you are changing it to is, various things
> #: from key-presses, to colors, to various advanced features may not
> #: work.
> ```
> 
> i am sorry but i dont read this as "kitty works only with xterm-kitty, no other values are supported".

Let me quote the relevant section for you:

The value of the TERM environment variable to set. Changing this
can break many terminal programs, only change it if you know what
you are doing, not because you read some advice on Stack Overflow
to change it.

If you dont read that as strong advice not to change TERM I dont know
what to say to you.

> 
> i am sure i dont know as much about terminals as you do, but i have never heard the advice to use `xterm-256color`/`screen-256color` to be jokes, or that you need a license to kill to set them.

Probably because you have only read about terminals on generalised
programming advice sites. Those tend to have typically, extremely
superficial advice. NEVER change TERM unless you REALLY know what
you are doing.


> 
> automating the copying is not the core issue for me.  making all the terminal based programs work correctly with exotic termcaps is. i use these terms because despite their issues/bugs/quirks they are the most supported with all the terminal programs.  you have started your own and that is nice but it seems like an uphill battle to me.

Terminfo is a database that describes what escape sequences client
programs have to send to the terminal emulator to achieve certain
functions. A value of TERM being supported by a client application in
meaningless. The way it works is the client application is supposed to
read TERM and then lookup the corresponding escape codes in the terminfo 
database. Therefore clients do not support particular TERM values at
all. It is simply a key to lookup in a database.

I'm not going to get into badly coded clients (usually shell scripts)
that dont lookup terminfo and instead play games with pattern matching
on TERM, it is for such badly behaved clients that I chose to give kitty
a TERM value starting with xterm- rather than just "kitty".

So again, DO NOT change TERM.

**Comment by Luflosi** [comment]
Do the programs work correctly when you don't change `term` in `kitty.conf` (restart kitty for changes in the config to take effect) and don't use tmux? Verify that `TERM` is set to `xterm-kitty` with `echo $TERM` as you did at the top. If they do, we can work from there. If they don't, they don't behave correctly.

**Comment by minusf** [comment]
> Changing this can break many terminal programs

this is a generic advice true also outside kitty...  so how about making it really explicit?

"Changing this can break many terminal programs, __and the only supported value is
xterm-kitty__."

> only change it if you know what you are doing

who qualifies for this then?  if no other value is supported what kind of advice is this? what values are accepted here if i "know what i am doing"?

> So again, DO NOT change TERM.

may i ask what TERM have you used before `kitty` existed?


and no, not using tmux is not an option for me.  if tmux is not supported it should be also clearly stated in the docs.

**Comment by kovidgoyal** [comment]
On Thu, Dec 12, 2019 at 10:27:34AM -0800, minusf wrote:
> who qualifies for this then?  if no other value is supported what kind of advice is this? what values are accepted here if i "know what i am doing"?

There is no question of values being "supported", whatever that means.
When you change TERM you are lying to client applications about what
terminal emulator you are running. When you do that, things *will*
break. Why is this such a hard concept to grasp? 

> 
> > So again, DO NOT change TERM.
> 
> may i ask what TERM have you used before `kitty` existed?

Whatever TERM value was native to the terminal I used at the time.

> 
> 
> and no, not using tmux is not an option for me.  if tmux is not supported it should be also clearly stated in the docs.

I know nothing about tmux, other than that I would not touch it with a
10 foot barge pole. The entire concept is totally wrong headed.  If it
requires setting TERM to some specific value, then it is its responsibility
to translate the resulting escape codes to something the host terminal
understands. If it fails to do that, then that is a bug in tmux, not the
host terminal. Although I vaguely recall that tmux itself suggests using
some tmux specific TERM, but dont quote me on that.

**Comment by minusf** [comment]
> There is no question of values being "supported", whatever that means.
When you change TERM you are lying to client applications about what
terminal emulator you are running. When you do that, things *will*
break. Why is this such a hard concept to grasp?

it's not hard.  only confusing: why offer the possibility of changing it, if other values are not compatible with how kitty works?  and if someone changes it -- to any other value -- simply telling them "dont change it!". what is the logic behind this? don't you find this confusing?

> I know nothing about tmux, other than that I would not touch it with a
10 foot barge pole. The entire concept is totally wrong headed.

the concept of what?  windows and panes inside 1 terminal window and/or keeping the programs running even if the process parent (the terminal window) is closed?

kitty itself offers windows and panes inside 1 terminal window and it's a kind of "poor man's tmux".

> host terminal. Although I vaguely recall that tmux itself suggests using
some tmux specific TERM, but dont quote me on that.

tmux advises in its man page to use `screen` or `tmux` or a "derivative of them". `tmux` does not work well in my experience with programs like mutt, but `screen` and it's derivative `screen-256color` works well.

**Comment by kovidgoyal** [comment]
On Thu, Dec 12, 2019 at 03:07:30PM -0800, minusf wrote:
> > There is no question of values being "supported", whatever that means.
> When you change TERM you are lying to client applications about what
> terminal emulator you are running. When you do that, things *will*
> break. Why is this such a hard concept to grasp?
> 
> it's not hard.  only confusing: why offer the possibility of changing it, if other values are not compatible with how kitty works?  and if someone changes it -- to any other value -- simply telling them "dont change it!". what is the logic behind this? don't you find this confusing?

You can change TERM values trivially in your shell startup script. By offerring it in
kitty.conf at least I can detect it easily via --debug-config for
bug reports. And no, I dont find it confusing.

> 
> > I know nothing about tmux, other than that I would not touch it with a
> 10 foot barge pole. The entire concept is totally wrong headed.
> 
> the concept of what?  windows and panes inside 1 terminal window and/or keeping the programs running even if the process parent (the terminal window) is closed?
> 
> kitty itself offers windows and panes inside 1 terminal window and it's a kind of "poor man's tmux".

The concept of adding a whole extra, badly implemented, terminal between
the client program and the terminal, just to offer windows and tabs,
which should be properly implemented in the terminal. tmux literally
means that every single byte has to be interpreted twice, a complete
waste of resources. And thanks to its existence terminal developers just
punt on adding proper window/tab management to their implementations,
meaning the entire world wastes resources unnecessarily just to get
windows and panes. And it acts like a drag on the whole terminal
ecosystem, making it much harder to create new features because tmux
breaks them, willy nilly. And there is nothing "poor" about kitty's
windows management. About the only significant feature of tmux it is
missing is persistence, and that can be achieved in a dozen different
ways, and will eventually be achievable in kitty natively as well.

**Comment by minusf** [comment]
you have some very strong opinions about tmux for someone claiming "I know nothing about tmux". 

you certainly dont seem to be in the need of ssh-ing into dozens of servers, doing multiple things at the same time from a variaty of computers and devices as part of your day job, because for me tmux doesnt offer "just windows and tabs".  nobody would make elaborate window and tabs setups if a broken/closed connection would destroy them...

the "only significant feature" you mention as the very last thing makes tmux the single most useful program in any sysadmin's toolbelt.  i have been using it practically since it exists (and `screen` before that -- and tmux is a breath of fresh air compared to screen's features, config language and documentation), and it has __always__ enchanced my terminal experience and not downgraded it.  whether i am on windows, bsd, linux or even a smartphone, and no matter which terminal emulator i use, i will always have my sessions exactly as i left them.  kitty will never be able to do that, unless it implements the very same horrible "concept".

it doesnt matter that kitty has windows and tabs or what `terminal.app` can do, or what the dozen other terminal apps can or cannot do because i learnt them once with tmux and i dont care about their implementation, quirks, bugs, idiosynchrasies. tmux might squander resources in your view but it certainly doesnt squander my muscle memory and sanity.

do programs have sometimes issues with terminal capabilities and features?  do both terminals and applications have drawing bugs? sure.  but that was all true before terminal multiplexers as well and will be true after kitty as well.

if anything tmux has made the whole terminal ecosystem much better for me.  YMMV.

**Comment by kovidgoyal** [comment]
On Fri, Dec 13, 2019 at 12:14:43AM -0800, minusf wrote:
> you have some very strong opinions about tmux for someone claiming "I know nothing about tmux". 

My strong opinions are about terminal multiplexers, of which I know a
lot. tmux in particular is just the latest iteration of a bad idea, that
I have never bothered to familiarise myself with, because I have better
things to do with my time.

> 
> you certainly dont seem to be in the need of ssh-ing into dozens of servers, doing multiple things at the same time from a variaty of computers and devices as part of your day job, because for me tmux doesnt offer "just windows and tabs".  nobody would make elaborate window and tabs setups if a broken/closed connection would destroy them...

I used to be sysadmin for the High energy particle physics and Quantum
Computing groups at Caltech, so I'll thank you to keep your assumptions
about my day job to yourself. And I never felt the need for a terminal
multiplexer, even once, in all that time.

> 
> the "only significant feature" you mention as the very last thing makes tmux the single most useful program in any sysadmin's toolbelt.  i have been using it practically since it exists (and `screen` before that -- and tmux is a breath of fresh air compared to screen's features, config language and documentation), and it has __always__ enchanced my terminal experience and not downgraded it.  whether i am on windows, bsd, linux or even a smartphone, and no matter which terminal emulator i use, i will always have my sessions exactly as i left them.  kitty will never be able to do that, unless it implements the very same horrible "concept".

Yes it will, since the horrible concept becomes a lot less horrible when
implemented by a terminal program's libraries, that can maintain its own
internal state machine, that matches the one in the underlying terminal,
so escape code translation does not need to be done. You are comparing
the efficiency of translating from English to Latin and Back to English
to doing no translation at all. Lost in translation, and all that.

> 
> it doesnt matter that kitty has windows and tabs or what `terminal.app` can do, or what the dozen other terminal apps can or cannot do because i learnt them once with tmux and i dont care about their implementation, quirks, bugs, idiosynchrasies. tmux might squander resources in your view but it certainly doesnt squander my muscle memory and sanity.

Instead you need to care about how tmux breaks terminal programs and how
the entire terminal ecosystem stagnates because of its malign influence.

> 
> if anything tmux has made the whole terminal ecosystem much better for me.  YMMV.

Yeah, it most definitely does VARY.


In any case, with regards to this issue. The cure is simple, use
TERM=xterm-kitty and make the terminfo available. I am done wasting my
time arguing with you. No terminal is ever going to guarantee
functionality when you mis-identify it as another incompatible terminal
and the expect things to work.
