### ISSUE TITLE
Using kittens outside of kitty

### ISSUE THREAD

**Issue by watzon** [kovidgoyal/kitty#2197]
I know that it's possible to write kittens in Python, and that's awesome, but what if you want to write and actual python library with some kitty specific functionality? For instance write now I'm trying to wrap the terminal graphics protocol into an easy to use package, but since I can't actually import the existing tui and icat kittens I'm having to write a lot of stuff from scratch.

**Comment by Luflosi** [comment]
Similar to #746 but I totally agree with you.

**Comment by kovidgoyal** [comment]
I'm not sure what you are asking for? A kitten has to be executed using kitty. So your library simply has to depend on kitty. And be executed by kitty instead of by the python interpreter. So for example, if you write a python file some_program.py, you would run it with

kitty +launch some_program.py

And inside some_program.py you can import everything from kitty or kittens or tui or whatever.

**Comment by watzon** [comment]
So the problem is this is a library that's not kitty specific. It's a terminal based reddit browser, which I'm trying to get to support the terminal graphics protocol, as well as other backends like w3m. I did a basic implementation of the graphics protocol, but to do that I had to rewrite a lot of things that I could've otherwise just imported from `tui` and `icat`.

**Comment by kovidgoyal** [comment]
Well, tui shares lots of code with kitty internals that would need to be
re-implemented to split it out, such as wcswidth(), extended keyboard
mode key parsing, various bit of native code used for speeding up
things, interfacing with the system., etc. I dont think that is really
worth splitting from kitty, it would just slow down and complicate a lot
of kitten development. Someday it might be worth it to write a truly
modern library to replace curses that can serve as a foundation for
building terminal applications, but that is a pretty large project, that
I personally dont have a lot of motivation for, given that I only ever
write terminal applications for kitty itself.

As for the graphics protocol, yes having a standalone library
implementing it seems useful. Since you have already done the work for
it, I am happy to collaborate on publishing/improving it, if you need
assistance. I can certainly add links to it in the kitty graphics
protocol docs, so people can discover it easily.

**Comment by kovidgoyal** [comment]
Am closing this at it is not a kitty issue per se, but feel free to continue the discussion.
