### ISSUE TITLE
100% CPU use when screen is locked.

### ISSUE THREAD

**Issue by jpotier** [kovidgoyal/kitty#224]
![htop](https://framapic.org/ZfHlpbspYEGL/lopz5qnram6g.png)

When I lock my screen (I run `i3lock-fancy`) then some (not all) of my kitty instances just use 100% CPU. It sometimes happen when they are unfocused for some time.

I'm running XMonad on Nixos-17-09. Here's the kitty derivation (build instruction) that was used to get a binary: https://github.com/NixOS/nixpkgs/blob/8bc0bf6785797e01b8c91d5201950b870b87c921/pkgs/applications/misc/kitty/default.nix

Ideas? Should I upgrade to 5.1?

**Comment by kovidgoyal** [comment]
100% CPU usage would imply some kind of continuous event delivery, causing the main loop to run continuously. You can stick a print statement into the main_loop function in child-monitor.c to test. And since this is likely to be related toX11 I doubt updating kitty will make a difference, but it cannot hurt to try.

**Comment by kovidgoyal** [comment]
You could try running kitty from master (it budles an updated version of glfw, the windowing toolkit) so it might help.

**Comment by jpotier** [comment]
Ok, I'll try that as soon as I can (most probably this evening)

**Comment by kovidgoyal** [comment]
no followup

**Comment by jpotier** [comment]
Yeah, weird thing is, after a full revamp of my `xmonad.hs` it hasn't been happening anymore. So it might no be related to kitty.
