### ISSUE TITLE
Primary selection does not work in Wayland

### ISSUE THREAD

**Issue by tim77** [kovidgoyal/kitty#2254]
- Description of problem:
When try to use the primary selection (highlight string to copy, middle button to paste), it does now work

- How reproducible:
Always, by trying to copy and paste using primary selection

- Steps to Reproduce:
1. highlight a text to copy a string
2. use the middle button to paste the string

- Actual results:
content is not copy and pasted

- Expected results:
content is copy and pasted

- Original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1787287

It used to work on 0.14.6 and not works on 0.15.0, 0.15.1.

**Comment by Luflosi** [comment]
I couldn't get the primary selection to work correctly but in 0.15.0 I got an error message, that didn't happen in 0.14.6:
```
Wayland: Cannot copy no primary selection device available
```
I bisected this and the first commit in which this error message occurs is f476c56f9198052f08927cad4a5dacbd471826e9.
@tim77 please check that this is indeed the first commit that causes your problem by building from source from f476c56f9198052f08927cad4a5dacbd471826e9 and 474688888d119aa65d4db24e852a1891d10b156a. See https://sw.kovidgoyal.net/kitty/build.html.

@kovidgoyal Is this expected behaviour?

**Comment by kovidgoyal** [comment]
What wayland compositor is this on? If your compositor is only supporting the obsolete gtk_primary_selection then yes, it wont work. gtk_primary_selection has been deprecated and replaced by wp_primary_selection_device_manager. If and when the compositor you are using adds support for it primary selection will work again.
