### ISSUE TITLE
Unable to paste text from clipboard in wayland

### ISSUE THREAD

**Issue by vianpl** [kovidgoyal/kitty#2288]
Hi I'm running kitty 0.15.1 on openSUSE tumbleweed. When pasting I get this error when running kitty with WAYLAND_DEBUG=1:

`[glfw error 65545]: X11: Failed to convert selection to string`

Any ideas?

**Comment by kovidgoyal** [comment]
That indicates you are running the X11 backend not wayland and probably XWayland is having issues. You can set linux_display_backend=wayland in kitty.conf to force it to use wayland, but most likely the reason it didn not use wayand is because you are on gnome and gnome does not support server side window decorations under wayland, so kitty defaults to X11.
