### ISSUE TITLE
exit command hangs the terminal after using pass to copy password to clipboard

### ISSUE THREAD

**Issue by nicodebo** [kovidgoyal/kitty#229]
Hi,

First, thanks you for kitty, it's an amazing terminal.

# issue
Executing the ```exit``` command after copying a password to the clipboard from [pass](https://www.passwordstore.org/), hangs the terminal.

# steps to reproduce
1. Open kitty
2. Copy a password to the clipboard: ```$ pass -c "$path_to_password"```
3. Exit the kitty: ```$ exit```
(4. Opening a new instance of kitty and executing ```$ pass -c "$path_to_password"``` unhang the previous instance and successfully close it)

# expected behavior
The terminal should exit right after running ```exit```.

# misc info
* kitty version: kitty 0.5.1 created by Kovid Goyal
* I could not reproduce this issue with [termite](https://github.com/thestinger/termite/)

**Comment by kovidgoyal** [comment]
That's presumably because pass hangs around waiting to clear the clipboard after 45 seconds and does not close its stdout/stdin/stderr file descriptors. You can test that by running ps aux | grep pass in another window.

kitty will not quit until the pipe used to communicate with the child process is closed (i.e. until *all* processes using that pipe are closed, not just the first one). Note that kitty is not hung. You can always tell kitty to quit by either using your window manager's close window functionality or pressing ctrl+shift+w which is the default kitty close window shortcut.

I dont know why other terminals close even though there is still a running child process holding the pipe open, that seems like a bug in those terminals. But maybe I am wrong and there is some obscure corner of unix arcana that says terminals should close when the first child process closes even though there are other processes still using the pipe. If so please point me to some documentation that says so.

**Comment by kovidgoyal** [comment]
Oh and I should add that this can be easily fixed in pass. It just needs to close its stdout/stderr/stdin file descriptors, like any well behaved program that want to run a daemon should do. IIRC pass is a shells cript, so it probably uses disown instead of nohup. That will mean that its clipboard clearning feature will not work if the controlling terminal is closed. You should probably notify its developer to change that. 

https://unix.stackexchange.com/questions/3886/difference-between-nohup-disown-and
