### ISSUE TITLE
Inverted cursor option

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#234]
AFAIK currently kitty only allows fixed cursor color. It also draws character under cursor using dark foreground color (background color?). While this is enough for 99% of uses, there are some cases where one would prefer block cursor to be draw by just inverting foreground and background colors of current character. For example if one changes terminal background between light and dark (e.g. using color setting escape sequences), then default light cursor color will not be visible on light background.

Alacritty implements this feature really well (proper inverted colors and non-blinking cursor). Gnome Terminal just uses text foreground color for cursor so the character under cursor is visible only between "blinks", which is not good IMO.

UPD: Issue was updated after a more thorough playing with different terminals.

**Comment by kovidgoyal** [comment]
Really, these terminals actually change cursor color as you move around between differently colored characters? That would IMO be horrible. Not to mention that it means the escape sequences to set cursor color would no longer work. Which is incidentally the correct solution to the problem of changing terminal colors via escape sequences. You also change the cursor color at the same time. 

So I am not going to implement this. That said I wont refuse a PR to implement an option to turn it on. It should be pretty easy, since kitty already uses a partial reverse video effect for block cursors (the cursor color is fixed, but the foreground color is changed to background when the cursor is over the character).

**Comment by maximbaz** [comment]
It is actually quite pleasing to the eye, but maybe requires getting used to it 🙂

I'm not sure how alacritty handles the escape sequences to set cursor color, but I would assume these sequences take priority over the default behavior.

![alacritty-cursor](https://user-images.githubusercontent.com/1177900/38518672-db7abd74-3c3d-11e8-8e04-66947a02a29b.gif)

**Comment by blueyed** [comment]
base16-shell uses this also, via the escape sequence `printf '\033]12;7\033\\'`.

> It should be pretty easy, since kitty already uses a partial reverse video effect for block cursors (the cursor color is fixed, but the foreground color is changed to background when the cursor is over the character).

Any additional pointers would be appreaciated.

I've found https://github.com/kovidgoyal/kitty/blob/5b6038db358417a1625168a6a8fea869727e1e14/kitty/cursor.c#L96-L99, but also `printf '\033]12;9\033\\'` does not seem to have any effect.

Is it related to this code?
https://github.com/kovidgoyal/kitty/blob/5b6038db358417a1625168a6a8fea869727e1e14/kitty/line.c#L489-L492 or rather `line_apply_cursor`?

What is the purpose of `CURSOR_TO_ATTRS`?

**Comment by kovidgoyal** [comment]
All the actual cursor drawing happens in an OpenGL shader. cell_vertex.glsl look for cursor_color the background is set to that color. You would need to instead swap the background and foreground colors for the cursor cell to achieve reverse video. 

Once you have it working, to avoid an unneccessary branch in the shader (branching is very expensive in shaders) use #ifdef with the corresponding define based on an option implemented in load_shader_programs in window.py
