### ISSUE TITLE
Underline not drawn with adjust_line_height=0

### ISSUE THREAD

**Issue by sergei-dyshel** [kovidgoyal/kitty#236]
With default setting `adjust_line_height 0` many fonts don't draw underline. The default font on my Fedora installation, DejaVu Sans Mono, works Ok, it is also the font which is used by default when setting `font_family monospace`. Example of font which doesn't work properly is [Nerd Font Inconsolata](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Inconsolata/complete/Inconsolata%20Nerd%20Font%20Complete%20Mono.otf) or any other Nerd Font I've tried. Some other monospace fonts which are installed by default, such as Liberation Sans Mono, don't work.

However after setting `adjust_line_height 1`, all fonts draw underline without problems, but this setting increases line spacing, which is not desirable for me.

Is is a bug or feature? Can I somehow (by patching a code maybe) make Kitty draw underlines without increasing line spacing?

**Comment by parity3** [comment]
Not sure what the solution/explanation for this, but I almost switched back to terminator because of this. It'd be nice to see *some* explanation here, or that it's a fact with all font systems and adjust_line_height is here precisely to combat this issue, and is the blessed solution in this case, etc etc. Using the default font for Linux Mint 19.1 MATE, probably a somewhat well known use case.

**Comment by kovidgoyal** [comment]
Umm this issue was fixed a while ago.

**Comment by kovidgoyal** [comment]
And if you ar talking about underscores not underlines, then that was also fixed a while ago, see #690

**Comment by parity3** [comment]
Oh, I stand corrected, yes this was an underscore situation, not an underline.
