### ISSUE TITLE
Command-, not launching a shell, pyenv

### ISSUE THREAD

**Issue by bs** [kovidgoyal/kitty#2373]
Noticed that command-, (launching the config editor) had VIM complaining at not being able to locate python3.

pyenv injects the proper paths by evaluating "$(pyenv init -)" in the shell. Since one can't run this from kitty.conf to get the proper env variable set higher in the stack, suggestions?

**Comment by kovidgoyal** [comment]
Setup your system environment correctly, so that your default editor is
useable. That means the environment variables needed should be setup in
launchd not shell startup scripts. 
Or change the editor in kitty.conf to be a wrapper script that does it for you.
Or change it to something like bash --login -c "vim" if you want to
re-use your shell startup scripts.

**Comment by bs** [comment]
I bring it up as many editors set in EDITOR will depend on variables set there (correct or not), so I imagine others will run into the same.

Fixed for vi and pyenv, in my case! Thanks for your work!
