### ISSUE TITLE
"resize_draw_strategy size" to display size throughout the resize

### ISSUE THREAD

**Issue by dottedmag** [kovidgoyal/kitty#2423]
"size" resize draw strategy draws the window contents after 1s of inactivity. This is useful, but it also hides the current size that was drawn during the mouse movement.

Would it be possible to overlay the current size over the window contents instead of hiding it until the mouse button is released?

P.S: I've tried to hack something quickly but was only able to remove repainting completely, not drawing the current size on top of the content of the terminal. Admittedly I only tried for several minutes before filing this enhancement request.

**Comment by kovidgoyal** [comment]
You cant do that because there is no guarantee you will get the mouse
release event. In theory, the window manager *should* guarantee you get
it, but I am not comfortable relying on it, since if it fails, it means
the window will be stuck in resize mode, with a snapshot of the
contents.

Note that if you want to see the current size of the terminal, simply
run

tput lines; tput cols;

**Comment by dottedmag** [comment]
My intention was to resize the terminal window back to 80x25 exactly if it was resized by whatever means.

Maybe there is a more straightforward way to do so?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/remote-control.html 

see resize-window

**Comment by kovidgoyal** [comment]
Actually never mind you are talking about resizing OS windows, not kitty windows. Use whatever facilities your window manager offers for resizing windows precisely for that.
