### ISSUE TITLE
Opening Kitty 0.6.0 fails with LSOpenURLsWithRole() error message

### ISSUE THREAD

**Issue by Alok** [kovidgoyal/kitty#245]
I'm running macOS 10.11.6.

I run `open -a /Applications/kitty.app` after downloading the latest macOS release.

I get the following error message: `LSOpenURLsWithRole() failed for the application /Applications/kitty.app with error -10825`, and kitty doesn't open.

This doesn't appear in kitty 0.5.1.

**Comment by kovidgoyal** [comment]
dup of #241

**Comment by kovidgoyal** [comment]
Read the first post, paying special attention to the version of OS X, then read #241 and it should be perfectly obvious how it is a duplicate.

**Comment by specious** [comment]
I'm running kitty 0.6.1 on macOS 10.13.2.  I don't think it's a duplicate.

For some reason which I cannot fathom, I'm no longer getting this error and `open -a kitty` works fine.  I'm not sure what I did, other than maybe reinitializing my shell since installing kitty with brew cask, but if I figure it out I'll report back.

**Comment by sharanraj124** [comment]
The same error happens my mac
os version: 10.12.6
```
open -a /Applications/kitty.app/
LSOpenURLsWithRole() failed for the application /Applications/kitty.app with error -10810.
```
please help for this issue, I don't know how to fix this
