### ISSUE TITLE
color4 is not enough

### ISSUE THREAD

**Issue by sheerluck** [kovidgoyal/kitty#2453]
`color4` is used for both completely different tasks:
* background of `mc` and `far manager`  (it usually should be darker)
* names of directories after `ls --color=auto` (it usually should be brighter)

If I set `color4` a little brighter, I like names of directories but I can't tolerate `mc` or `far manager`.

If I set `color4` a little darker, I like how `mc` and `far manager` looks, but I can not see names of directories after `ls --color=auto`

`Konsole`, on the other hand,  use two differect colors for there tasks:
* `Color4` for `mc` and `far manager` (it's dark)
* `Color4Intense` for names of directories (it's bright)

I don't exactly know what I wanted to ask to change in `kitty`.
I just know that single `color4` for two different tasks is not enough :(

**Comment by kovidgoyal** [comment]
kitty support 24bit colors, that 16 million colors, you just need to convince whatever softwre
you are running in it to use them. Look in the settings of that software
or ask the creators of the software for help.

**Comment by trygveaa** [comment]
Just to explain the reason it's different in kitty and konsole. Some terminals (including konsole) prints bold text in a brighter color, while kitty prints it as bold in the same color. `ls --color=auto` uses bold blue text for directories by default, which is why you see it as brighter in konsole.

The colors `ls` uses are configurable and supports 24bit, so you can change this yourself to whatever you want. See e.g. http://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors for how to do it.

**Comment by sheerluck** [comment]
Thank you @trygveaa 
So I solved my problem with
1) open /etc/DIR_COLORS
2) find line with `DIR 01;34`
3) replace it with `DIR 38;2;84;84;255` as "38;2;R;G;B;"
and now I can have dark `color4` (`#1818b2`) with bright dirs (`#5454ff`)

**Comment by sheerluck** [comment]
I did the same thing in /etc/bash/bashrc with `PS1`:
I have replaced `\033[01;34m` with `\033[38;2;84;84;255m`
