### ISSUE TITLE
SSH kitten not opening directly a shell

### ISSUE THREAD

**Issue by BlueskyFR** [kovidgoyal/kitty#2475]
Hello!

When opening a connection to a new server (e.g. which has not yet the Kitty's terminfo), I have to use `kitty +kitten ssh myserver` to copy the terminfo on it.

To avoid looking at the FAQ every time, I aliased `ssh='kitty +kitten ssh'.
However, the downside to this is that the kitten is not opening directly a shell on connection, which means that the MOTD is not displayed.

I absolutely **DO NOT** want to have like two commands (one to copy terminfo and the other to normally connect), I just want ssh to always display motd while not carrying about the terminfo anymore on any future server I will connect to.

Can you please help me?

**Comment by kovidgoyal** [comment]
The ssh kitten most definitely does open a shell on connection. I
frankly have no interest in debugging why your MOTD does not display.

**Comment by BlueskyFR** [comment]
@kovidgoyal I don't understand: you are in contradiction with yourself. See https://github.com/kovidgoyal/kitty/issues/1791#issuecomment-510037625.

The problem comes from you ssh kitten.

Also, this is really annoying to have to copy the terminfo files to all the servers I connect to, and after doing so some root commands still don't work using ssh.
Is there anything I can do to simplify that copy process?

**Comment by kovidgoyal** [comment]
Yes, it doesn't run a shell directly, since if it did there would be no
way to copy the terminfo file. But, it does run a shell, which is
obvious, since you end up in one. 

And no there is nothing I can magically do to make copying terminfo
files while preserving the MOTD or whatever else you need happen.
Understand how these things work, and then perhaps you will not feel the
need to ask for impossibilities. The ssh kitten is about 200 lines of
code, read it.

**Comment by kovidgoyal** [comment]
For posterity, when you log into a system via ssh, sshd displays the MOTD for you, using various configurable mechanisms. But sshd only does this if you are logging in "interactively". The ssh kitten has to log in non-interactively in order to first copy over the terminfo file and then start the shell, converting the session into an interactive one. There exists no mechanism to tell sshd to print the MOTD for an non-interactive session, hence the impossibility.

**Comment by DaVarga** [comment]
@diaz-esparza While this works, whats is the benefit setting this up vs setting up terminfo on the remote?
