### ISSUE TITLE
Using the shell option doesn't set SHELL

### ISSUE THREAD

**Issue by BlueDrink9** [kovidgoyal/kitty#2495]
When using the shell option, for example `shell zsh`, the `$SHELL` variable is unchanged.

Minimal reproduction (OSX, user shell is bash)

kitty.conf:

`shell zsh`

.zshrc:

`echo $SHELL`

> `/bin/bash`

Two workarounds would be:

* manually set SHELL in kitty.conf. Downside is this won't respect `which zsh`, reducing portability.
* Manually set SHELL in .zshrc. No downsides, but means each user has to do this.

My understanding is setting SHELL is the responsibility of the terminal emulator, forgive me if I'm wrong

**Comment by kovidgoyal** [comment]
On Sun, Mar 29, 2020 at 05:18:13PM -0700, BlueDrink9 wrote:
> My understanding is setting SHELL is the responsibility of the terminal emulator, forgive me if I'm wrong

Not as far as I know. Note that you dont even have to execute a shell in
kitty. You could directly execute vim, for example. From what I recall,
in traditional unix, SHELL was set by login. And these days on Linux at
least SHELL is set by the shell startup files. 

That is what your reproduction case indicates as well. The system shell
startup files are setting SHELL to /bin/bash which is the shell
specified for your user account. If you change your shell using chsh
rather than in kitty.conf, that should be automatically fixed. 

Using chsh is preferable anyway since it changes your shell everywhere,
for instance when sshing into the machine as well. The shell setting in
kitty mostly exists to change how the shell is invoked, not so mucg for
changing shells.

**Comment by BlueDrink9** [comment]
That's fair. I wanted only kitty to use zsh, since then I know it has powerline fonts

**Comment by ashebanow** [comment]
As an FYI, there are a lot of folks on the red hat side who are arguing that you shouldn't need to ever change your shell, because you can start whatever shell you want in the terminal emulator (zsh, fish, etc). They've gone so far as to remove the chsh command from some of  the atomic distros (silverblue, kinoite, etc), and then the ublue distros that derive from them (bluefin, bazzite, etc. See [this article](https://tim.siosm.fr/blog/2023/12/22/dont-change-defaut-login-shell/) by a redhat engineer.

Of course this is easy enough to workaround, as the article alludes. But given the rising popularity of Silverblue and Bazzite, it would be good if there was an easier way to do this in kitty.

**Comment by kovidgoyal** [comment]
That has got to be one of the dumbest articles I have read in a while. That person is advocating for completely fragmenting the setting of the user's preferred shell, because he doesn't like setuid binaries, which is a completely orthogonal issue. If he doesnt want to maintain the user's preferred shell in /etc/passwd he should do the work to come up with an alternative way to manage that preference that actually works with things like ssh as well instead of expecting users to have to configure their shell in multiple places. 

Regardless, the existence of chsh is irrelevant. SHELL should still be set by the shell's rc files, the shell is the one that is best placed to know what the value of  SHELL should be. And if you really want to do this in kitty it's trivial enough, needing just a single additional line in kitty.conf

```
env SHELL=whatever
```

will set SHELL for you.

**Comment by ashebanow** [comment]
I definitely do not agree with their point of view. Purists are gonna
purist.

But the atomic stuff is really nice in the big picture, so I put up with it.
