### ISSUE TITLE
"No render frame received in 0.25 seconds" log spam on sway

### ISSUE THREAD

**Issue by Hello71** [kovidgoyal/kitty#2509]
happens every few seconds when kitty is on an inactive workspace. as I understand, render events are only sent approximately once per second to hidden windows with wlroots, and this is allowed by the protocol specification, so either the max wait should be increased significantly, or the message should be removed entirely.

**Comment by Hello71** [comment]
kitty 0.17.2, sway 1.4, wlroots 0.10.0

**Comment by kovidgoyal** [comment]
What log is it spamming? It prints to stderr, if you dont want to see
those and other messages redirect stderr to /dev/null

**Comment by Hello71** [comment]
it seems excessive to print that many messages. redirecting stderr to /dev/null hides other messages.

**Comment by kovidgoyal** [comment]
Excessive for what?? Printing out one lines every quarter second is
certainly not excessive in terms of resource usage.  What is it these
messages are preventing you from doing? And where are you seeing them
anyway?

**Comment by akobel** [comment]
If sway is started as a systemd unit, any stderr output of direct children of the window manager is redirected to the journal, on the wm's unit. Which is completely sane; otherwise it would be hard to get any feedback of those processes on actual errors.
But it means that this very message is indeed fairly obtrusive. From the last three days with this setup, and with little screen time, `journalctl | grep 'No render frame received' | wc -l` already gives me a whopping 16913, and counting.
Entirely redirecting stderr to /dev/null is something I tend to avoid, because it means that I cannot get hints and report useful info if something serious breaks. A workaround is to replace the kitty call by the messy and somewhat arcane invocation `{ kitty 2>&1 1>&3 | grep -v 'No render frame received' 1>&2; } 3>&1`, at the mild expense of a subshell that clutters up pstree and the like. But I second @Hello71 that it would be nice to have this line optional, e.g. as part of `--debug-gl` (which is extremely sparse in comparison, as far as I can tell).

**Comment by kovidgoyal** [comment]
On Tue, Apr 14, 2020 at 09:47:05AM -0700, Alexander Kobel wrote:
> If sway is started as a systemd unit, any stderr output of direct children of the window manager is redirected to the journal, on the wm's unit. Which is completely sane; otherwise it would be hard to get any feedback of those processes on actual errors.
> But it means that this very message is indeed fairly obtrusive. From the last three days with this setup, and with little screen time, `journalctl | grep 'No render frame received' | wc -l` already gives me a whopping 16913, and counting.
> Entirely redirecting stderr to /dev/null is something I tend to avoid, because it means that I cannot get hints and report useful info if something serious breaks. A workaround is to replace the kitty call by the messy and somewhat arcane invocation `{ kitty 2>&1 1>&3 | grep -v 'No render frame received' 1>&2; } 3>&1`, at the mild expense of a subshell that clutters up pstree and the like. But I second @Hello71 that it would be nice to have this line optional, e.g. as part of `--debug-gl` (which is extremely sparse in comparison, as far as I can tell).

This is not debugging OpenGL, its debugging Wayland compositors. And 16K
lines is what 0.5MB?? Over three DAYS. 

And just FYI redirecting the stderr/stdout of all child programs of the
graphical session into a global log file is about 40 years old now.
Nothing special about wayland/systemd, other than that it likes to throttle
render frames a lot, unlike the other systems kitty runs on.

Anyway, I dont really care that much. If it bothers you so much send a
PR to hide it behind --debug-gl and while you are at it, rename
--debug-gl to --debug-rendering. This will involve renaming the option
internally in the code as well as the actual option used on the CLI.

**Comment by akobel** [comment]
It doesn't bother me that much, but since I raised my voice... PR done.
It's not about the MB/day, but about the spam in journalctl and me filtering it by eye instead of tools, if anything.
