### ISSUE TITLE
Certain symbols not colorized in macOS

### ISSUE THREAD

**Issue by pallavagarwal07** [kovidgoyal/kitty#252]
Thanks so much for this awesome terminal!
I just got a new MacBook Air (macOS Sierra) and after installing Kitty with my usual zsh config, I noticed that certain symbols are not colorized on the terminal (This does *not* happen in Linux with Kitty).

![screen shot 2017-12-24 at 8 21 43 pm](https://user-images.githubusercontent.com/9394044/34327374-c603bf8e-e8e8-11e7-9fdc-fd66b3534268.png)

In the above screenshot, the black terminal is kitty, and the white one is the in-built terminal. Notice that the tick mark should be red, but is white instead in kitty.

- Changing font size does not affect behavior.
- Changing the font itself does not affect behavior.

**Comment by kovidgoyal** [comment]
That will be because that symbol is an emoji (as per the unicode 10.0 standard). As of kitty 0.6 all emoji are rendered using a colored font, so their color comes from the font, not from the foreground color. You can create exceptions for individual symbols by using symbol_map to have kitty render them from a non-emoji font.
