### ISSUE TITLE
Some UTF8 bold characters are not properly displayed

### ISSUE THREAD

**Issue by ondrejj** [kovidgoyal/kitty#2554]
Some characters, specially slovak "ď" are not properly displayed. They are very small. Some others like "Š" are a bit lower like other characters. Look at this

![Screenshot](https://user-images.githubusercontent.com/7007507/79339034-88471280-7f28-11ea-9620-1c954837ec4a.png)

At left there is kitty, at right gnome-terminal. Trying to change font, but still same problem.
Partial solution is to use non bold font for "bold_font". :-)

Setting adjust_line_height=2 fixes "S" characters, but don't fix "d".

Testing text: `echo $(tput bold) ďalšie ŠSSŠSSS $(tput sgr0)`

**Comment by kovidgoyal** [comment]
That will be because the metrics of the bold font dont fit in the cell
size of the normal font, so kitty has to resize them, causing the
alignment issues. Use a font with a properly designed bold face
that has compatible metrics and you will be fine.

Or use symbol_map in kitty.conf to remap those particular characters
from a non bold font.

**Comment by ondrejj** [comment]
All fonts I have tried on my system has similar problems. May be it's a problem of this character which should be wider, no other characters have this problem.

Looks like a better solution is to use:
```
adjust_column_width 1
adjust_line_height 2
```
in kitty.conf.

1 added pixel is not visible and font is displayed properly.

**Comment by kovidgoyal** [comment]
Yeah using the adjust cell size settings is another alternative, of
course.
