### ISSUE TITLE
tmux pane switching does not clear status line

### ISSUE THREAD

**Issue by alexciarlillo** [kovidgoyal/kitty#265]
When switching between panes with tmux enabled, it looks like the last status line does not get cleared from the pane that was switched from. I have also noticed if you escape out of the command sequence (ctrl+a, then ESC) the status line is not cleared. Here are some visual examples:

![2018-01-04-115721_3840x1080_scrot](https://user-images.githubusercontent.com/656039/34575006-2d4848fc-f147-11e7-8483-6e72c1e76c32.png)
![2018-01-04-115739_3840x1080_scrot](https://user-images.githubusercontent.com/656039/34575008-2f94eb92-f147-11e7-815e-03a5f0abb937.png)
![2018-01-04-115805_3840x1080_scrot](https://user-images.githubusercontent.com/656039/34575009-311a1384-f147-11e7-9d95-36129a2922fd.png)

**Comment by kovidgoyal** [comment]
I'm not a user of tmux, but I'd guess it is because tmux is incorrectly using background color erase which kitty declares it does not support in its terminfo. You can test that by changing your color scheme to not have a background color. Also make sure you have not changed the value of TERM, it should be xterm-kitty

For background on why kitty does not supprot it, see: https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc#setting-text-styles-colors-in-arbitrary-regions-of-the-screen


If it is not background color related feel free- to update this bug report.
