### ISSUE TITLE
Monospace fonts not available

### ISSUE THREAD

**Issue by novcn** [kovidgoyal/kitty#2739]
Hi, I read the [related FAQ](https://sw.kovidgoyal.net/kitty/faq.html#kitty-is-not-able-to-use-my-favorite-font) and a number of other similar closed issues but still have a problem.

There are a number of monospaced fonts I have installed on my system which I cannot use with kitty. I'll use [Cozette](https://github.com/slavfox/Cozette) as an example.

![2020-06-05-154956_1124x283_scrot](https://user-images.githubusercontent.com/48640573/83928317-378fb100-a744-11ea-996e-abb3953d6c6e.png)

Based on the info I read, kitty will load fonts with a spacing of 100 or 90. In my situation, this appears not to be the case.

**Comment by Luflosi** [comment]
Unfortunately kitty does not support bitmap fonts because they can't be resized. See #97 for some context and see https://github.com/kovidgoyal/kitty/issues/97#issuecomment-579094656 for a workaround (that I haven't tested) if you really want bitmap fonts in kitty.
That said, I installed the latest versions of Cozette and CozetteVector on my Mac and they show up in `kitty list-fonts`. Which version of Cozette are you using? Try the latest version from https://github.com/slavfox/Cozette/releases.
Which other monospace fonts are you using? I'd like to try to make a small patch for people who _really_ want to use these fonts.

**Comment by colingabrielson-okta** [comment]
@Luflosi thanks for the info on this. The FAQ should probably be updated to indicate this since it implies kitty will load any of these fonts listed via ```fc-list : family spacing | grep -e spacing=100 -e spacing=90```

I'm using `cozette-otb 1.8.2-1` from AUR. I'll try to install it another way to see if I can get it to render.

I was planning to try out cozette or [cherry](https://github.com/turquoise-hexagon/cherry) for something new.

**Comment by Luflosi** [comment]
I quickly hacked together a patch. Try building kitty from source from https://github.com/Luflosi/kitty/tree/allow_bitmap_fonts. It might work for you but I haven't actually tested it besides the font showing up in `kitty list-fonts`.

**Comment by colingabrielson-okta** [comment]
Thanks for the patch @Luflosi 

I can confirm that I was able to list the desired fonts. Here was the behavior when I tried to use them:

 ```bash
λ › ./kitty/launcher/kitty -o=font_family=cherry                                                                          src/kitty-bitmap allow_bitmap_fonts
[157 19:37:04.339980] Cell height invalid after adjustment, ignoring adjust_line_height
[157 19:37:04.340008] Line height too small: 1
λ › ./kitty/launcher/kitty -o=font_family=Cozette                                                                         src/kitty-bitmap allow_bitmap_fonts
[157 19:37:09.609287] Cell height invalid after adjustment, ignoring adjust_line_height
[157 19:37:09.609314] Line height too small: 0
```

I followed an example from the thread you linked me by adjusting the the `font_size` and `line_length` to 32

Cherry loaded cleanly - although too small which isn't surprising giving my laptops high dpi
![2020-06-05-195306_345x189_scrot](https://user-images.githubusercontent.com/48640573/83934501-6fa7eb80-a766-11ea-8afb-ecbc758e67f4.png)

Cozette loaded as well, although less clean (looks like pixels on the right are cutoff)
![2020-06-05-195335_298x199_scrot](https://user-images.githubusercontent.com/48640573/83934526-a67e0180-a766-11ea-81a9-8c96650065a9.png)

**Comment by ctrlcctrlv** [comment]
For Cozette, probably all you need to do is add some padding.

**Comment by Luflosi** [comment]
I booted up my Linux container with a GUI and got Cozette to work with
```
kitty -o=font_family=Cozette -o adjust_line_height=13
```
![screenshot](https://user-images.githubusercontent.com/15217907/84071961-ae3fdf00-a9ce-11ea-9a45-a51c9eba4e49.png)
This looks correct, right?
Note, that the Browser may interfere with the crispiness of the image.

**Comment by CyberShadow** [comment]
@ctrlcctrlv You [wrote](https://github.com/kovidgoyal/kitty/issues/97#issuecomment-579094656) (sorry for replying here, the original thread got locked):

> As a contributor to FontForge project, I know for a fact that I can fashion fonts with embedded bitmaps which Kitty will not reject. Let me demonstrate.

Thank you for posting that workaround. I'm trying to apply it to the 7x13 Xorg Misc/Fixed font. However, upon trying to use it in kitty, there is a problem with the glyphs' vertical alignment:

![](https://dump.cy.md/eced8e53cc639a0cfb0fe1fa07c761d2/16%3A22%3A24-upload.png)

This is with `font_size 13.0` and `adjust_line_height 13`. I notice that if I set `adjust_line_height` to `18`, the glyphs are correctly vertically aligned, but each line is of course 18 pixels tall.

Would you happen to know what went wrong?

**Comment by ctrlcctrlv** [comment]
Would you mind uploading the original font? Does only 18 and above work or did you try numbers between 14 and 18 as well?

**Comment by CyberShadow** [comment]
Apologies, upon retracing my steps I realized that the font file I was using in the above test was converted using fonttosfnt and not FontForge. (I did do [a FontForge conversion after the pango 1.44 disaster](https://gitlab.gnome.org/GNOME/pango/-/issues/386#note_574494) but I guess it was lacking in some way so I looked for other tools, possibly because the original font is broken up across 45 files.) In case of fonttosfnt, kitty needs the fonts to be **converted with the `-c` option ("do not crop glyphs")**, I guess some part of its or its dependants' font machinery is not respecting the glyph bounds that cropping sets. With uncropped glyphs, the font now looks fine in kitty.

To answer your questions either way, the original font files are in `/usr/share/fonts/misc/7x13*.pcf.gz`, and at least in Arch Linux, in the [xorg-fonts-misc package](https://www.archlinux.org/packages/extra/any/xorg-fonts-misc/download/). Any number above 18 seems to work, with numbers between 18 and 13 bringing the glyphs gradually less mispositioned.

Thanks again.

**Comment by airtonix** [comment]
```shell
> ls -al ~/.fonts | grep cozette                                  
-rw-r--r--. 1 zenobius zenobius  309925 Sep 17 20:27 cozette.bdf
-rw-r--r--. 1 zenobius zenobius   91880 Dec 10 15:36 cozette_bitmap.dfont
-rw-r--r--. 1 zenobius zenobius   88976 Sep 30 10:47 cozette_bitmap.ttf
-rw-r--r--. 1 zenobius zenobius    4083 Sep 17 20:27 cozette.fnt
-rw-r--r--. 1 zenobius zenobius   88476 Sep 17 20:26 cozette.otb

> kitty +list-fonts | grep cozette                                

x kitty +list-fonts | grep Cozette  

x kitty -v
kitty 0.26.5 created by Kovid Goyal

```

Unsure what to do here?
