### ISSUE TITLE
DCS pending mode char parsing looks to incorrect

### ISSUE THREAD

**Issue by mawww** [kovidgoyal/kitty#2764]
While trying to understand display issues between Kakoune and Kitty, I came accross `Unrecognized DCS` errors. That led me to look at Kitty's code and I found this line in parser.c:824 (on latest git)

```
if (screen->parser_buf_pos > 2 && (screen->parser_buf[1] == '1' || screen->parser_buf[2] == '2') && screen->parser_buf[2] == 's') {
```

It looks like there is a typo in `screen->parser_buf[2] == '2'` which should be `screen->parser_buf[1] == '2'` as `screen->parser_buf[2] == '2' && screen->parser_buf[2] == 's'` is obviously always false.

My current understanding of this is that currently kitty never parses screen_stop_pending_mode there and relies on some timeout to actually do the redraw.

**Comment by kovidgoyal** [comment]
That is indeed a typo, however, it will not cause any ill-effect other than the report of an unknown DCS, instead of the report of an unmatched stop pending mode. The actual parsing of stop_pending_mode happens in _queue_pending_bytes() at 1171

**Comment by kovidgoyal** [comment]
Note that my fix just means you will get a new error message rather than unknown DCS code. THe underlying issue of why kitty is not in pending mode when kakoune expects it to be remains. While debugging you might find kitty --dump-commands and kitty --replay-commands useful. As well as --dump-bytes.
