### ISSUE TITLE
man prints warnings

### ISSUE THREAD

**Issue by bradlyatc** [kovidgoyal/kitty#277]
Having a problem with Kitty sending some warnings when using man. This doesn't happen on any other terminal.  I googled and there is lots of info about other terms with these problems from time to time.  IDK if the others have a workaround or what, but here is the output:
 man cat
bzip2: I/O or other error, bailing out.  Possible reason follows.
bzip2: Broken pipe
           Input file = /usr/share/man/man1p/cat.1p.bz2, output file = (stdout)

man works, just those warnings always come up only with kitty.  Love this terminal by the way. Awesome work!

**Comment by kovidgoyal** [comment]
I use man in kitty dozens of times a day, never seen any warnings. But then my system uses gz for man files not bz2. I dont know what the terminal could possibly have to do with I/O errors reading bz2 files. But if someone has any bright ideas, I'll be happy to hear them. You can try using strace -f on man and see if it shows anything suspicuous

**Comment by kovidgoyal** [comment]
I looked into this a little, and as far as I can tell, its an issue in bzip2. Basically, when bzip2 outputs to stdout and stdout is connected to a program and that program terminates before reading all of the data in the pipe, bzip2 will receive SIGPIPE which will cause it to print that error. This is a bug in bzip2, well behaved programs that write to stdout should not print errors on SIGPIPE, since you could pipe their output into programs such a head, to see only the first few lines of output. The reason it happens in some terminals some of the time is that it is timing based, it depends on the size of the pipe buffer, the exact timing of when the output program quits, which in turn depends on terminal performance.

**Comment by shrdlu68** [comment]
That may be the case, but I don't see the error when I use either xterm or urxvt on my system, only kitty does this. What could explain the difference?

**Comment by Arnaudv6** [comment]
Thanks @RPigott.
@kovidgoyal is it relevant to fix if as it was fixed in sway?
https://github.com/swaywm/sway/commit/1dd6df6a5df3924d42a25bd17dab0ef8beecad61

**Comment by kovidgoyal** [comment]
Not sure what you are asking? kitty already sets SIGPIPE to SIG_DFL when running child programs. See line 108 in child.c

**Comment by Arnaudv6** [comment]
OK, that's what I meant. Thanks, I should have checked.

**Comment by teika-kazura** [comment]
@OP: 
See also this gentoo bugzilla:
https://bugs.gentoo.org/409745

If you are using gentoo, re-emerging all related packages, or 
``$ emerge -uDNav @world``
may fix the issue.

Thanks a lot for developping kitty.
Best regards.
