### ISSUE TITLE
Flickering when using fzf.vim

### ISSUE THREAD

**Issue by yanzhang0219** [kovidgoyal/kitty#2807]
OS: macOS 10.15.5
Kitty version: 0.18.1

Hi,

I am using fzf.vim in neovim. When I start fzf by :Files and then move the cursor up and down, there are two abnormal flashing things (GIF attached below). One is a flashing cursor on the right-hand side (i.e., the preview part) of the fzf window. Another flashing is the number column (on the leftmost, like the line number) of the fzf window.

Thank you very much.

![83828714-3011ce80-a696-11ea-87fa-d97f8f264408](https://user-images.githubusercontent.com/11582667/85929195-b1105000-b867-11ea-9cad-0e1dd350b6dc.gif)

**Comment by kovidgoyal** [comment]
This isn't a terminal emulator bug. It's likely just that kitty is
redrawing the screen fast enough that you can see the flicker. THe
correct way to fix it is for fzf.vim to:

a) hide the cursor while it is redrawing
b) Use the atomic screen redraw facility that many terminals implement

I dont know how possible this is for a vim plugin to do however, since
vim abstracts away terminal interaction.

Finally, you can probably workaround the issue in kitty by adjusting the
input_delay value in kitty.conf to give you a poor man's version of (b)
above

**Comment by yanzhang0219** [comment]
Got it. Thank you.
