### ISSUE TITLE
Support scratchpad overlay and tabbed layout

### ISSUE THREAD

**Issue by wirtsi** [kovidgoyal/kitty#2828]
**I3 has some useful features that would also work nicely with kitty**
I am switching between i3 on Linux and my Mac and I would love to have two things that I like in i3 implemented in kitty

**Describe the solution you'd like**
https://i3wm.org/docs/userguide.html#_scratchpad

You can take a container and turn it into a scratchpad ($Mod-Shift-<Minus>) ... the window will be shown as a centered overlay on top of the other containers. You can use $Mod-<Minus> to show/hide the scratchpad. I find this really nice for showing compilation output. So something that you don't need to see all the time but it's handy to have it in access quickly (and it doesn't eat away at the screen real estate)

https://i3wm.org/docs/userguide.html#_changing_the_container_layout

i3 has tabbed and stacked layout. Both show one large container that takes all space and list all other containers in vertical/horizontal tabs on top of the window. You can use $Mod-<left|right> to switch between them.

The difference to the kitty stack layout would be that you can still see the other windows as tabs (like in a browser). Please note, I am not talking about the tabs at the bottom of the screen, this is about a layout view not about creating a new kitty window in a tab.

Just some thoughts from my side ... thanks for providing kitty by the way, it is truly the best terminal program out there :-)

**Comment by kovidgoyal** [comment]
I believe macOS has tiling window managers as well, such as chunkwm,
yabai, etc. 

If you turn on remote control in kitty, you can easily
write a short script that implements scratchpad, basically use
detach/attach of windows. detach a window that you want to be the
scratchpad, and when you want to see it, switch layout to stack, attach
it. And when you want to hide it, detach it and switch layout back to
the previous layout. Or alternately write a kitten that does this
sequence of steps.

As for showing the list of windows in stacked layout as tabs, am not a
fan of the concept, indeed, I run a patched version of i3 that removes
those tabs in stacked layout. If I want to see windows in a tabbed
layout rather than a stacked layout, I use actual tabs. You can do the
same in kitty, and in fact using the same attach/detach functionality
you can write a kitten to gather all the windows in tabs into a single
tab with some layout and disperse them into new tabs for tabbed layout.

**Comment by kovidgoyal** [comment]
And that said, it is on my todo list to make kitty window management
even more powerful with docked windows, and overlay windows that can
overlay an entire layout. See #2391
