### ISSUE TITLE
no_op action still captures key binding

### ISSUE THREAD

**Issue by cdosborn** [kovidgoyal/kitty#285]
In readline/bash ctrl+shift+minus allows you to undo. Kitty binds this sequence to an action. I would like this key sequence to be forwarded to bash. When I used `no_op` i expected this behavior, but bash never receives it.

**Comment by kovidgoyal** [comment]
This has nothing to do with no-op, no-op works fine. In general terminal programs cannot use ctrl+shift+X because there is no way to encode the shift modifier. Some terminals add special override mappings that cause ctrl+shift+X to act like ctrl+(shifted X) for some (widely varying between different terminal emulators, values of X). This is because the meaning of (shifted X) depends on your keyboard layout. You can do the same thing in kitty by adding the following to your kitty.conf

```
map ctrl+shift+- send_text all \x1f
```

It's perhaps an open question whether it is worthwhile to survey the most common such overrides used by terminal emulators and ship them out of the box in kitty.

**Comment by cdosborn** [comment]
:bowing_man: So responsive! Thanks

**Comment by kovidgoyal** [comment]
You are welcome :)
