### ISSUE TITLE
Kitty uses 100% CPU when Wayland compositor is killed / restarted

### ISSUE THREAD

**Issue by maciekmm** [kovidgoyal/kitty#2867]
**Describe the bug**
After restarting Sway kitty uses 100% CPU 

**To Reproduce**
1. Start kitty
2. Restart / Kill the compositor (sway)
3. Run `ps u | grep kitty` 
4. The kitty process is using 100% cpu

**Expected behavior**
Kitty closes or stays idle

**Screenshots**

**Environment details**
OS: Archlinux 5.7.9 with Wayland

```
kitty 0.18.1 created by Kovid Goyal
Linux beekeeper 5.7.9-arch1-1 #1 SMP PREEMPT Thu, 16 Jul 2020 19:34:49 +0000 x86_64
Arch Linux \r (\l)
Running under: Wayland
 
Config options different from defaults:
```

Kitty debug rendering:
```
[201 13:56:23.567600][glfw error 65544]: Wayland: fatal display error: Broken pipe
[201 13:56:23.567605][glfw error 65544]: Wayland: fatal display error: Broken pipe
[201 13:56:23.567610][glfw error 65544]: Wayland: fatal display error: Broken pipe
... infinite loop
```

**Comment by st3r4g** [comment]
This was introduced in a recent (maybe latest?) release, didn't happen before

**Comment by kovidgoyal** [comment]
I cannot replicate this on master, steps I trieed:

1) Start sway
2) Run kitty in sway
3) run pkill sway in the newly opened kitty

the kitty process exits. IIRC there were some fixes related to this in
master, so run from master and you should be fine.

**Comment by oscarcp** [comment]
I can confirm that this happens under the specified circumstances. I usually switch between GNOME/Hikari/Sway and if I have opened a kitty instance it does not close after exiting the compositor and entering another.

Usually the outcome is a zombie headless kitty instance using 100% CPU (which in my case is a problem given the kind of hardware that I run and the thermal limits) and there is no way to "recover" it.

The only solution so far is to kill every single instance of kitty that is running on the computer. New kitty instances do not have that problem. It seems that it happens only when kitty loses control over the graphical environment.

Let me clarify again, **it only happens if you don't manually close the kitty instance**. It happens when you exit the compositor without closing the application.

❯ kitty --version                                                 
kitty 0.18.1 created by Kovid Goyal
❯ uname -a                                      
Linux ironclad 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux

**Comment by bonnefoa** [comment]
I can confirm. I had the same issue with 0.18.1 but running master is fine.
