### ISSUE TITLE
Heavily loaded tab makes rest of the tabs janky

### ISSUE THREAD

**Issue by Avamander** [kovidgoyal/kitty#2868]
**Describe the bug**
When there's heavy output in one of the tabs, it makes rest of the tabs janky

**To Reproduce**
1. Run for example `cat /dev/urandom` (this can happen with other output-heavy software, I had it with a spammy service)
2. Open new tab
3. Hold down any key, for example the `s` key
4. See the jankiness of the cursor

**Expected behavior**
It remains smooth

**Environment details**
Kitty: 0.15.0
```
Linux Avam 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64
Ubuntu 20.04 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04 LTS"
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/avamander/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
background            Color(red=32, green=32, blue=32)
font_size             9.0
update_check_interval 0.0
```

**Comment by kovidgoyal** [comment]
I cannot replicate this with tabs, running cat -v /dev/urandom
as the hidden tab is not rendered it does not cause jank in the visible
tab. Note that if you leave off the -v you will get jank, because then
all sorts of escape codes come through, especially commonly the terminal
bell, since that is played even with the tab hidden, it will cause jank.

If however, you run the cat in a side-by-side kitty window in say the
tall layout, it will cause jank, this is because all windows are
rendered in the same thread. That, I'm afraid is not going to change,
as it is not possible to fix without fundamentally changing the
design of kitty. Currently all input is handled in a single thread and
all rendering happens in another thread. To fix this every child would
need its own thread and so would every window for all rendering short of 
actual GPU communication.
