### ISSUE TITLE
Mappable commands list

### ISSUE THREAD

**Issue by gaydenko** [kovidgoyal/kitty#2889]
Hi! Probably I have missed something obvious, but have not found a way to list all commands I can map keyboard shortcuts to. Would be great to get them.

**Comment by kovidgoyal** [comment]
There is no such list. Basically, pretty much any method on the Boss,
Window, and Tab classes can be mapped. Of course, calling many of them
will not actually do anything useful/meaningful. All the intentional
ones are documented in the help in various places, but not as a single
list.

You are better off looking for what specific task you want to perform.
That will lead you to the functions you need, assuming they exist.

**Comment by Tyilo** [comment]
This would be nice to have.

**Comment by kovidgoyal** [comment]
Contributions are most welcome. To get started, list out all the methods
for the Tab, Window and Boss classes, the set of mappable actions is a
subset.
