### ISSUE TITLE
Cannot switch to alternate file in vim

### ISSUE THREAD

**Issue by korsmakolnikov** [kovidgoyal/kitty#2898]
**Describe the bug**
Using vim in kitty (other terminals are working) can't switch to alternate file. 
Normally ctrl+6 or ctrl+^ are bound to do this. In kitty, nothing happens and if I try `showkey -a` nothing is printed.
I've tried to bind ctrl+^ to a send_text like this:
```
map ctrl+^ send_text all \x36
```
but nothing happens. You can observe what the keys as supposed to do executing the command `:b#`

**To Reproduce**
1. open kitty, then vim
2. open two files
3. press ctrl+6 or ctrl+^

**Environment details**
OS: popos! latest

**Comment by linsomniac** [comment]
What version?  I just tried it on 0.18.2 and it works for me.  I did: "vi /etc/services /etc/protocols", then ":n" then "ctrl+^" and was back at /etc/services.

**Comment by kovidgoyal** [comment]
There's no such thing as ctrl+^. There is ctrl+shift+6 and if you want
and traditional terminal keyboard protocols such as what vim uses cannot
represent ctrl+shift+6. So many terminal just strip out the shift, kitty
does not. If you want kitty to do that, map ctrl+shift+6 to send the
same bytes as ctrl+6. Or just use ctrl+6 since there is absolutely no
point pressing the additional shift key.

**Comment by srustamo** [comment]
> map ctrl+shift+6 to send the same bytes as ctrl+6.

Sorry if I'm resurrecting a closed post.

How do I do the quoted above mapping? I see in the `kitty.conf` Keyboard shortcut section, but it doesn't show sending raw codes.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Send-arbitrary-text-on-key-presses

**Comment by srustamo** [comment]
Thanks. 

`map ctrl+shift+6 send_text ctrl+6` 

does the trick.
