### ISSUE TITLE
Provide "titeinhibit" / disable altscreen

### ISSUE THREAD

**Issue by linsomniac** [kovidgoyal/kitty#2900]
**Is your feature request related to a problem? Please describe.**
One feature of xterm that I really like is that I can disable the altscreen via the "titeinhibit" option.

**Describe the solution you'd like**
Having a configuration option to disable altscreen, like xterm and others "titeInhibit" would be great.  Or a second terminfo file that has no "rmcup" entry, for a TERM setting of like "xterm-kitty-titeinhibit"?  Having a config option would allow for not distributing terminfo across my fleet and instead just using "TERM=xterm".

**Describe alternatives you've considered**
Currently I'm building a custom terminfo file and packaging it and installing it on my fleet.

**Additional context**
A lot of terminal options do not provide this feature, and I guess it is something that is somewhat fringe.  But I find it interferes with my workflow to have something on my screen and then have that go away so that I can no longer reference it.

I realize that many individual programs can be configured to disable the altscreen, like the -X option to less, configuring vim, configuring screen.  But there always seems to be another program that I'd like to be able to see context on when I exit it (orpie, htop, mtr), and on top of that I manage 100 machines, and prefer not to have to add ansible settings for every little program to disable them across multiple accounts, etc.  Sure, I can live with it across them, because I use them much less frequently than I use my handful of primary machines.  It is very nice to have the ability to disable altscreen in the terminal though.

**Comment by kovidgoyal** [comment]
I'm afraid I dont think this is a useful feature. If you want to
preserve the altscreen, kitty can already do that by piping it to less
in an overlay or new window/tab, just like it does for the browse
scrollback feature. See
https://sw.kovidgoyal.net/kitty/launch.html#cmdoption-launch-stdin-source

And if you do want this feature I will accept a patch for adding an
option, however, not one that inhibits the alternate screen, since the
alternate screen has important semantics the main screen lacks, and it is
not good for the ecosystem for applications to not be able to rely on
those semantics. Instead have an option that will simply dump the
contents of the alternate screen into the main screen after switching,
so it will be available in the scrollback.

**Comment by linsomniac** [comment]
Thank you for the consideration.  Your idea of scrolling the alt screen onto the main screen at switch sounds like it'd work.  I'm afraid I don't have the expertise to be able to make that happen.

I understand what you are saying about disabling the alternative screen being problematic for things that rely on it.  I'd note that I've been running xterm with titeInhibit for over 30 years, in a terminal-centric workflow, and can't say that I've ever notice any programs that have a problem with it.  Just a data-point.

At the moment I've taken the terminfo and removed smcup/rmcup and that seems to resolve it for me in my testing.  I'll push that .deb out to my fleet and continue my testing.  I built a custom package anyway since our platform only has 0.15 available in the upstream packages.
