### ISSUE TITLE
Regognize wrapped links running other software like Vim

### ISSUE THREAD

**Issue by Brixy** [kovidgoyal/kitty#2927]
```
MacOS Catalina
kitty 0.18.3
tested with kitty --config NONE: yes
```

On the command itself kitty recognizes wrapped URLs (see #272), yet it does not when kitty runs other software, e.g. Vim or mutt.

I just tested this in iterm2; iterm2 recognizes wrapped links running Vim or mutt. So this might be a kitty issue?!

Thank you very much!

![sc](https://user-images.githubusercontent.com/1643010/90633696-c5007e80-e226-11ea-929f-aa7c85b2bb83.png)

**Comment by kovidgoyal** [comment]
I dont see how it is possible to detect hyperlinks across hard line
breaks in a non-broken way, which is what vim and mutt do. They insert
hard line breaks at the end of every line, the terminal emulator cannot
know if that hard line break is to be ignored or not. If it ignored it,
it would mean that for hyperlinks that happen to end at a line edge and
are followed by a hard newline naturally will then be misdetected as
continuing onto the next line.

One could argue that this breakage is acceptable, but then for most vi
setups that include a gutter line, even that would not work.

**Comment by trygveaa** [comment]
kitty already recognizes urls with hard line breaks as long as the line exactly fills the width of the terminal.

As long as you don't configure line wrapping in mutt it should work fine (does for me). In your screenshot from vim the line breaks before the last column, so that will not be recognized by kitty. If you want, you can configure vim to fill the line by running `set nolinebreak`. Recognizing urls will only work if you don't have any sidebars in vim like numbers or signs though.

**Comment by Brixy** [comment]
Thank you @trygveaa. I had played with `set nolinebreak` before, but I had forgotten to turn line numbers off.
