### ISSUE TITLE
Add nerd font unicode to unicode search list

### ISSUE THREAD

**Issue by Jake-Gillberg** [kovidgoyal/kitty#2972]
It would be nice to see the unicode characters I have installed (nerd font) searchable from the unicode input selector

**Describe alternatives you've considered**
Using the unicode vim selector (which also looks unsupported currently https://github.com/chrisbra/unicode.vim/issues/39)

**Additional context**
Looks like there is a way to get a text list of nerd font characters: https://github.com/ryanoasis/nerd-fonts/issues/448

**Comment by kovidgoyal** [comment]
Generate a text file of the form:

code point in hex symbol name

for example

eb1d  right triangle

and post it here and I will take a look.

**Comment by Jake-Gillberg** [comment]
https://gitlab.com/jake.gillberg/nerd-fonts-glyph-list/-/raw/master/glyph-list.txt

**Comment by Jake-Gillberg** [comment]
Thanks! <3

**Comment by Finii** [comment]
There is now a glyph name list in Nerd Fonts
* https://github.com/ryanoasis/nerd-fonts/pull/1137
* https://github.com/ryanoasis/nerd-fonts/blob/master/glyphnames.json

which reflects the latest icon additions and will also reflect the drop of the offending glyphs in the Arab and CJK blocks with the next release.

**Comment by page-down** [comment]
@Finii
Thanks for the heads up.

I recently updated the list of symbol names in kitty to nerd fonts 2.3.3.
Since you informed about another way to get the names, I compared the data in that JSON and found some issues.

- Missing `U+E323 weather night alt rain mix`. This is a completely different symbol from `U+E236`, but has the same name. So it is overwritten by the latter one.
- The correct codepoint for `oct device desktop` is `U+F4A9`, not the incorrect one in JSON: `U+F67C` (mdi comment alert).

There are many icons in there that are similar, and I would prefer to use Unicode codepoint instead of Unicode characters in JSON to make it easier to distinguish.

**Comment by Finii** [comment]
Thanks for the input!

Changed the script to include the codepoints like this (unless you have a better idea):

```json
{
  "METADATA": {
    "website": "https://www.nerdfonts.com",
    "development-website": "https://github.com/ryanoasis/nerd-fonts",
    "version": "2.3.3",
    "date": "2023-03-12 18:51:14+00:00"
  },
  "cod-account": {
    "char": "",
    "code": "eb99"
  },
  "cod-activate_breakpoints": {
    "char": "",
    "code": "ea97"
  },
```

Tackling the issue over there.
