### ISSUE TITLE
Kitty too dark

### ISSUE THREAD

**Issue by danielmain** [kovidgoyal/kitty#3027]
Problem:
The contrast is too low in comparison with iTerm2

Possible solution:
Make a setting that allows set the brightness/contrast

Screenshot showing two terminal emulators using the same vim-colorscheme and same font:
- Background: Kitty
- Front: iTerm2

As you can see Kitty seems to be darker and has lower contrast.
![image](https://user-images.githubusercontent.com/4303099/95861899-65c07580-0d62-11eb-883a-29301b91797f.png)

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf.html#color-scheme

**Comment by ingjieye** [comment]
I've had the same problem, did you solved it?

**Comment by page-down** [comment]
I don't know what your problem is. But I see that you have configured the theme color hex value via kitty config file.
Then there is one possible reason: other terminals modified the color of the bold text to make it brighter.
kitty renders the correct color and you can compare it with your theme's color hex value by using a color picker.

**Comment by yurenchen000** [comment]
I know themes can affect color display,
but is it possible to change brightness globally?
// feel `kitty` colors little brighter than `gnome-terminal` or `terminator` 

it'll be nice if posible change terminial brightness (like change opacity) to meet other windows (web page, editor, IDE.. etc)
