### ISSUE TITLE
How to exit when main process ended leaving subprocess

### ISSUE THREAD

**Issue by andresmrm** [kovidgoyal/kitty#307]
Hello! Thanks for Kitty!

In xterm (and most terminals), if you run `( inkscape & ); exit`, it will close the terminal leaving inkscape open. But in kitty, it will open inkscape and wait it to finish before closing the terminal. Is there a way to configure this behavior?

**Comment by kovidgoyal** [comment]
No there is no such option, and I dont really see the point. Closing the terminal automatically while there is still some process connected to it is just bad behavior. If you want to close the terminal at any time simple press ctrl+shift+w

So instead of typing: inkscape & exit

Type: inkscape & <ctrl+shift+w>

Or if you want to do it via a command use:

```
nohup inkscape & disown; exit
```

**Comment by kovidgoyal** [comment]
Oh and just for completeness, before somebody complains that using nohup means typing a lot, you can define the following in your zshrc/bashrc

```sh
function launch {
    nohup $1 >/dev/null 2>/dev/null & disown; exit
}
```

Then just type

```
launch inkscape
```

in the terminal to run inkscape and clsoe the terminal at once.

**Comment by andresmrm** [comment]
Thanks for the quick reply @kovidgoyal !

I need this for a python script, that's why I can't use hotkeys to close the window.
The command you said seems to work well when using it manually on the terminal, maybe I can also use it with python, like this `subprocess.run('nohup %s & disown; exit' % cmd, shell=True)`. Would you have a better idea about how to do it on python? Thanks for the help!
(I tried using os.fork(), but the terminal stays open waiting the child.)

**Comment by kovidgoyal** [comment]
All you need to do is redirect stdin/stdout/stderr
```py
subprocess.Popen('inkscape', stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, stdin=subprocess.DEVNULL)
```

**Comment by andresmrm** [comment]
Oh, it works! Thanks!
And sorry for unintentionally misguiding you with the first message. I thought it would be easier to talk here about shell language.

**Comment by xuhdev** [comment]
> No there is no such option, and I dont really see the point. Closing the terminal automatically while there is still some process connected to it is just bad behavior. If you want to close the terminal at any time simple press ctrl+shift+w
> 
> So instead of typing: inkscape & exit
> 
> Type: inkscape & <ctrl+shift+w>
> 
This is useful! To clarify, the full command above is:

1. `inkscape & <Ret>` to start inkscape
2. Then, <Ctrl+Shift+w> to terminate kitty.

**Comment by xuhdev** [comment]
In case anyone steps upon here, this is what I have in my `.zshrc`:

```zsh
unsetopt HUP  # Keep jobs running after exiting shell.
unsetopt CHECK_JOBS  # Don't report on jobs when shell exit.
```

After setting these lines, simply close a kitty window as usual, and push `<Ctrl-shift-w>` if kitty "hangs".

**Comment by kovidgoyal** [comment]
Nowadays, there is an option to control this: close_on_child_death

**Comment by Flimm** [comment]
Thanks for the function `launch` for Bash and Zsh:

> ```
> function launch {
>     nohup $1 >/dev/null 2>/dev/null & disown; exit
> }
> ```

I would modify it so that it takes more than one argument, and so that it doesn't exit the shell:

```
function launch {
    nohup -- "$@" >/dev/null 2>/dev/null & disown
}
```

Now you can run `launch gedit textfile.txt` and it will open the named text file as expected. You can manually exit the shell and the terminal in your usual way, and the launched process will continue running, without running into problems when printing to stdout or stderr.

Here's the equivalent for the Fish shell:

```
function launch
    nohup -- $argv >/dev/null 2>/dev/null &
    disown
end
```

To detach a process after you have already run it, you can press <kbd>ctrl</kbd>-<kbd>z</kbd>, and then run `bg` and `disown`, but this won't detach stdout and stderr. You can do that [using `gdb` according to this Stack Overflow post](https://stackoverflow.com/a/26296282/247696).

One downside of this `launch` script is that it hides errors from nohup. For example, if the command passed to nohup does not exist, then no error is shown to the user. Another downside is that you lose the shell's autocomplete feature for the command itself.
