### ISSUE TITLE
Allow multiple types for hints kitten.

### ISSUE THREAD

**Issue by duckinator** [kovidgoyal/kitty#3087]
**Is your feature request related to a problem? Please describe.**
I tried to set up a keybinding that runs the hints kitten with multiple types, and there's no way to do so.

Specifically, I wanted hyperlink + url.

**Describe the solution you'd like**
Anything that lets me use multiple types with the hints kitten is fine.

The approach that I initially tried because it felt the most intuitive was this:

`kitty -o 'map f1 kitten hints --type hyperlink,url'`

**Describe alternatives you've considered**
I'm considering making a custom kitten, but I'm not sure whether that's the best solution.

**Comment by kovidgoyal** [comment]
Why? You dont know before hand whether you are inerested in a visible URL or a hyperlink? And what happens if a visible URL also is a hyperlink? hyperlinks and urls have very different parsing requirements. One is based on text and the other on markup. As such supporting them simultaneously would require more work than I am interested in. Patches are welcome.

**Comment by duckinator** [comment]
My reasoning was that it would be nice to have a single keybinding that just served the function of "opening links".

**Comment by kovidgoyal** [comment]
That's a nice goal, but the two types of links are both very different
in internal structure and also conflicting, so it's not really
attainable.

**Comment by duckinator** [comment]
Fair enough. :+1:
