### ISSUE TITLE
Can I paste into Fzf prompt (from clipboard) _without_ holding Shift?

### ISSUE THREAD

**Issue by artemave** [kovidgoyal/kitty#3121]
I am able to paste with middle mouse button into kitty or vim - no problem. But when I paste into fzf prompt things are different. When fzf is opened in the terminal, I need to press Shift for the mouse paste to work.

This only happens in kitty, not in other terminal emulators (e.g. alacritty). Is there a way to stick to the original mouse button behavior (no shift) everywhere?

Thank you!

**Comment by kovidgoyal** [comment]
You need to press shift to perform mouse actions when the program
running in the terminal asks for mouse events. Then kitty will report
button presses to the application rather than acting on them itself. If
alacritty doesnt do so, it is a bug in that prgram. And if fzf is asking
for mouse events, then it needs to handle those events itself.

**Comment by trygveaa** [comment]
It works exactly the same way in alacritty as in kitty for me. You can disable mouse mode in fzf by running `fzf --no-mouse`.
