### ISSUE TITLE
Really slow input lag with many windows open

### ISSUE THREAD

**Issue by chris-kahn** [kovidgoyal/kitty#313]
Running on macOS Sierra, a single Kitty window is absolutely faster than iTerm2 3. Scrolling the page in emacs/vim is noticeably more smooth.

As soon as I get to the 5th window open, there is very noticeable (and annoying!) input lag. With the 6th window open, Kitty is basically unusable... there is >1s delay before each character appears on screen from when I type. Whereas in iTerm, I can have 20 windows open and input is instantaneous.

Any idea what causes this?

**Comment by kovidgoyal** [comment]
No idea, I typically keep 8 - 10 kitty windows open on my linux box, with no noticeable performance degradation. Generally speaking, the more windows you have in a single kitty process, the more things a single iteration of the render loop (kitty does not use a separate thread per window) has to do. However, since cell data is sent to the GPU only if a window is dirtied, it shouldn't make too much difference. You can follow the instructions in the performance section of the readme to get some profiling data. Or if you prefer stick printf() into the relevant functions, which are in child-monitor.c (render() and io_loop())

**Comment by chris-kahn** [comment]
That would explain it. If I force macOS to open new processes with `open -na /Applications/kitty.app` then everything's buttery smooth with a dozen windows open. Something definitely cripples the single process. Can try to track this down more later...

**Comment by kovidgoyal** [comment]
The one thing I can think of is that with multiple windows, even though no new data is sent to the GPU every window is still redrawn with the current data on every tick. Maybe drawing on macOS is much slower. It should be possible to avoid the draws as well, just as currently data is only sent when needed.

**Comment by kovidgoyal** [comment]
See if https://github.com/kovidgoyal/kitty/commit/0c7d51dd9dd1e46d072b2d12af23dd1a680e21ea helps

**Comment by koekeishiya** [comment]
@kovidgoyal 

Confirmed working; tested with 16 windows now and they are all just as smooth as if I had only one. Previously, it was almost unsuable with 5 windows open.

Thanks for the quick fix as usual!

**Comment by chris-kahn** [comment]
Confirming that it's working perfectly now on my machine with 20 windows open

**Comment by chris-kahn** [comment]
Thanks for your fast response! 👍
