### ISSUE TITLE
How can I get super/meta

### ISSUE THREAD

**Issue by 71e6fd52** [kovidgoyal/kitty#315]
How can I get super/meta on linux

In konsole, when I press `<Super-A>` in `cat`, it receive`^X@sa`

**Comment by kovidgoyal** [comment]
The only modifiers you can use in traditional terminal programs are ctrl and alt (and partially, shift). I have no idea what konsole is doing. If you are writing a terminal program of your own, your best bet is to use the extended keyboard protocol documented here: https://github.com/kovidgoyal/kitty/blob/master/protocol-extensions.asciidoc

that allows you to use all modifier keys and even handle key press, repeat and release events.

**Comment by 71e6fd52** [comment]
Can I customize it

**Comment by kovidgoyal** [comment]
You can use send_text in kitty.conf to send arbitrary bytes on arbitrary key presses. Read the default kitty.conf for details.

**Comment by rien333** [comment]
So to reiterate: if I wanted to use the `super` modifier under linux with X11 I would have to either rewrite a terminal program to adhere to kitty's protocol extension, or have the keybinding send something like an escape code that I than catch within the configuration of a program (as in https://github.com/kovidgoyal/kitty/issues/498), e.g. my shell?

My final goal is to have global modifiers `super+v` and `super+c` for copying/pasting (and possibly other `super` bindings), which are quite hard to do with the above two methods. Can I maybe make it so that `super` sends `ctrl+shift` in kitty? (I guess I'll do this in X11 now, but this is not the most ideal workaround)

**Comment by 71e6fd52** [comment]
@rien333 map is supported `super` like:
```
map super+c copy_to_clipboard
```

**Comment by rien333** [comment]
Yeah I know, but that doesn't work for me. Could be my x11 conf, but `xev` reported normal values for my Super key iirc.

**Comment by kovidgoyal** [comment]
Use --debug-keyboard to see what key events kitty receives.
