### ISSUE TITLE
To tear or not to tear

### ISSUE THREAD

**Issue by jordwalke** [kovidgoyal/kitty#318]
I have a very fast key repeat rate. When I scroll in vim line by line, I notice some "wavy" rendering, almost like 1-2 pixel misalignment temporarily, only on portions of the screen at a time - as if the screen is broken up into layers, and not all layer move at the same time.

Related question: The docs mention that setting the update time to `10ms` should result in something like 100fps rendering. That isn't exactly the case because screens only refresh at `60fps`, and rendering every `10ms` would likely cause weird frame alignment problems. On Mac OS, does Kitty align with CVDisplayLink to ensure that misalignment doesn't cause dropped frames?

https://twitter.com/jordwalke/status/939064408986103808

**Comment by kovidgoyal** [comment]
That's tearing. And no kitty does not do any syncing with monitor refresh rates to avoid it. I have found that doing so makes latency too high for tasks like selecting text with the mouse. You can try it for yourself, by changing the call to glfwSwapInterval() line 349 of glfw.c see http://www.glfw.org/docs/latest/window_guide.html#buffer_swap

To me the tradeoff of increased latency for decreased tearing is not worth it. Try it for yourself and see if you like it. If so, I am willing to add an option to make the behavior configurable.

**Comment by andreypopp** [comment]
Interestingly I don't notice such effect when using Alacritty terminal emulator. Does it sync with display refresh rate? If it does — why I don't feel the latency? (Maybe this is because I got used to big latencies with tmux + vim but for me using alacritty or kitty is still worth it over Terminal.app/iTerm2 as perf benefits are hugely noticeable).

**Comment by kovidgoyal** [comment]
I suspect that the amount of latency introduced by syncing will depend on the details of your monitor/GPU/graphics drivers/etc. And whether you notice the latency will depend on the details of your brain and software usage history :)

If you read the wikipedia article I linked on tearing you will see that input latency is a common side effect of syncing and that is why it is often turned off in games, where latency is critical. As I said, I am happy to add an option to turn it on for people that want it, but I dont want to bother if no one will use it. So try it out (it's a one line change) and if you like it, let me know. 

Also I should say that I am not a macOS dev (unlike the developer of alacritty, I think). So there may well be macOS specific things kitty could do to improve there. If so, patches are most welcome.

**Comment by andreypopp** [comment]
>  And whether you notice the latency will depend on the details of your brain and software usage history :)

Definitely.

I just tried to compare two kitties side by side and I definitely prefer a version compiled with sync — "wavy" rendering is gone and it's much easier on eyes, also I don't notice the increase in input latency(though I only use keyboard and no mouse in terminal). I will try to use such patched version of kitty for a while and will report if I notice something weird.

**Comment by kovidgoyal** [comment]
Try selecting text with the mouse, at least on my system, with syncing turned on, I see a noticeable gap between the position of the mouse cursor and the position of the selection. It feels slightly laggy. 

I have not noticed any extra latency with the keyboard, but I suspect that is because key events are simply not fast enough. Possibly increasing the repeat rate will show up the issue.

**Comment by andreypopp** [comment]
No, I don't see any worrisome lag when using mouse to select the text. But as I said using mouse isn't what I do usually in terminal so I'm not concerned too much if it's worse with sync. Btw I have the fastest repeat rate configured in macOS preferences but it might not be as fast as you can configure it in Linux.

**Comment by kovidgoyal** [comment]
OK I'll leave this issue open. Let's what other people's experiences are.

**Comment by koekeishiya** [comment]
I'm running on macOS with a keyboard repeat rate of 15ms (fastest you can set in the macOS UI is 30ms) and I do experience "wavy" rendering when holding down *j* in neovim. Setting *glfwSwapInterval(1)* fixes this, but I do notice a slight key-input delay.

kitty config:
repaint_delay 10
input_delay 3

**Comment by jordwalke** [comment]
Low mouse drag latency is nice but I would imagine the number of “j”
Keystrokes in Vim (or equivalents) outnumber the number of terminal mouse drags for most people. Mouse drag interactions would tend to hide some latency as well since their motion is human driven and erratic. It’s thing like timer(or key repeat) driven animation where variance is most noticeable.

**Comment by kovidgoyal** [comment]
As I said before, what tradeoff you find acceptable is entirely subjective. For instance, I absolutely detest any latency in mouse dragging, because it makes it much harder to select text precisely. But whether that affects you or not will depend on how much you use the mouse, what speed and acceleration parameters you have set for the mouse, your general sensitivity to latency, etc. 

On the other hand a little bit of tearing while scrolling does not bother me at all. It does not affect my ability to scroll. It just looks a little bad. But for you, maybe it gives you a headache, I dont know. That's why I asked for people's experiences, to better inform the decision.

**Comment by kovidgoyal** [comment]
Incidentally, @koekeishiya you didn't say whether you actually prefer glfwSwapSelection(1) overall or not.

**Comment by jordwalke** [comment]
@koekeishiya  How are you measuring the input/paint delays? Since your screen only refreshes at fixed points in time, I'm wondering if these are typically actually observable in practice.

@kovidgoyal Should `glfwSwapInterval(1)` cause `glfw` to use `CVDisplayLinkRef` to drive the screen updates as referenced [here](https://github.com/glfw/glfw/blob/master/src/cocoa_init.m)? I'm sorry, but I'm quite inexperienced with `glfw` but I know that actually syncing the updates to `CVDisplayLink` is the only way to get consistent screen updates at 60fps on Mac (not just an *average* of ~60fps, but avoiding dropped frames entirely).

I think your position is a fair one - I found it interesting that the one other person I found that tried Kitty (Andrey, on this thread) also had the exact same "dealbreaking" observation that I had about tearing when using Vim. It's a small sample size but I have a feeling it's important to many other people as well and so having an option would be much appreciated (assuming it solves the problem).

**Comment by kovidgoyal** [comment]
@jordwalke See cocoa_monitor.m for how glfw uses CVDisplayLink. And see nsgl_context.m for how swapinterval is used. Since I am neither a glfw developer nor a macOS developer, I have no idea whether that does what you want it to or not. As best as I can tell, it simply sets a parameter on the OpenGL context, the OS graphics drivers are then responsible for syncing. See https://developer.apple.com/documentation/appkit/nsopenglcpswapinterval 

Why dont you just make the change in kitty and try it?

**Comment by koekeishiya** [comment]
@kovidgoyal As I notice a slight delay in key-input when *glfwSwapInterval(1)* is set, I find the tearing to be more acceptable. Though, as you said, this depends on the person in question, and so I think that it might still be worth offering this as a config setting.

**Comment by jordwalke** [comment]
@koekeishiya How are you measuring the increased delay that the user experiences?

Also, I wonder if it would be possible to somehow detect which mode to use depending on how much of the screen content changes. For changing at most one/two rows of text (things like moving a cursor left/right/up/down in vim, or entering one character of input) - I wonder if it would be possible to detect this and favor the buffer swap mode that favors lower latency, but when changing large amounts of screen content (where tearing can be perceived) use the other swap mode.

**Comment by kovidgoyal** [comment]
I actually like the idea of making the swap interval dynamic, i.e. setting it to 1 on scroll and zero if no scroll occurs since the last swap. But, I dont know how feasible that would be to implement. Something to investigate.

**Comment by kovidgoyal** [comment]
I have pushed an implementation that turn on swap interval dynamically to the tear branch. Try it out and let me know what you think. As far as I can tell, it reduces tearing significantly while not affecting latency while typing/selecting with the mouse. But since I am not very sensitive to tearing in the first place, hard to be sure.

**Comment by koekeishiya** [comment]
@kovidgoyal the *tear* branch works great on my end.

@jordwalke I'm not measuring the delay using any tools or such, I'm just using terminal as always (editing a lare file in neovim), and that's how I notice that my keypresses have more delay in a kitty instance running with synching enabled.

**Comment by kovidgoyal** [comment]
Sadly I had to revert the dynamic interval. It was causing very bad performance in X11 when only a single window is visible (for example for full screen windows). See https://github.com/kovidgoyal/kitty/commit/5a15f7e8add28365d122fffd5ce763d21c3579c9
