### ISSUE TITLE
Support for invis

### ISSUE THREAD

**Issue by jonjonw** [kovidgoyal/kitty#3186]
I would like to use the instant prompt function in [zsh-snap](https://github.com/marlonrichert/zsh-snap). It uses the `invis` capability which it appears kitty does not implement so I get the error 

`.znap.prompt.precmd:echoti:5: no such terminfo capability: invis`. 

Would it be difficult to add? I noticed that it's commented out in the python code that generates the terminfo.

**Comment by kovidgoyal** [comment]
This is deliberately not implemented as it is a security risk, invisible
text can be used to disguise commands and also because it would mean
adding yet another formatting attribute for a very marginal use case.

You can get a similar effect by simply setting the foreground and
background colors to the same value, though unlike invis, this will not
hide the text under selections.
