### ISSUE TITLE
It should be possible to enable IBus via config file, not just environment variable

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3206]
In 2018 Kovid [wrote](https://github.com/kovidgoyal/kitty/issues/469):

> Just a heads up: for the next kitty release 0.12.1 I am going to turn off IME by default. You need to set the environment variable:
> ```
> GLFW_IM_MODULE=ibus
> ```

This is inconvenient for me. Why not put it in `kitty.conf`?

**Comment by kovidgoyal** [comment]
Because thats how these IME systems like to be configured, via toolkit specific env vars. https://wiki.archlinux.org/index.php/IBus

**Comment by ctrlcctrlv** [comment]
Um, but GLFW isn't a toolkit, and anyway in Wayland those are deprecated.

**Comment by kovidgoyal** [comment]
Yes, it is https://github.com/glfw/glfw

And deprecated in favor of what?

**Comment by ctrlcctrlv** [comment]
In favor of simply running IBus Daemon or what have you

**Comment by kovidgoyal** [comment]
Except that IBUS daemon or what have you:

1) Introduce extra keyboard latency, more than doubling it, for very
marginal features unless you are an east asian inputter.

2) Cause hangs, and keyboard input bugs.

As such I am never defaulting to turning them on just because the daemon
is running. Lots of ill-informed distros do that without proper consideration.
So if you have some other non application specific config mechanism to suggest 
I am all ears, otherwise the env vars stay, regardless of the
Wayland developers in their infinite wisdom deciding env vars are
deprecated.

**Comment by ctrlcctrlv** [comment]
Is that environment variable actually supported by GLFW in general though? My impression was that it isn't and you added that to your patched GLFW which is only used in Kitty. So how is it actually different than an application specific mechanism? Would any other GLFW application on a given system recognize it?

**Comment by kovidgoyal** [comment]
If GLFW ever adds support for IBUS, I imagine it will also use an env
var. If it decides to implement some other method, then I will be happy
to add support for it at that time.
