### ISSUE TITLE
set environment variable TERM_PROGRAM to "Kitty"

### ISSUE THREAD

**Issue by reportaman** [kovidgoyal/kitty#3317]
Many terminal emulators set the environment variable TERM_PROGRAM to a sensible value that can be used to uniquely identify them. It works on my system with WezTerm, iTerm2, Terminal.app. It doesn't work on all terminals, but if devs of all terminals start accepting this, it can become a standard. Currently Kitty terminal emulator, and Alacritty do not set these.

### System

macOS Big Sur 11.2

**Comment by kovidgoyal** [comment]
What would be the point? It wont get forwarded over SSH by default, so
terminal programs cant rely on it. And this environment variable
approach was already tried with the TERM env var, it didnt work. People
started overriding it in their shell rc files, and we ended up with the
mess we are in today, where it cant be relied on either.

**Comment by lilyball** [comment]
Please revisit this.

The point is if I launch Kitty from another terminal, Kitty leaves `TERM_PROGRAM` alone, and programs running in Kitty will now incorrectly detect the wrong terminal.

This even affects bash on macOS. macOS's `/etc/bashrc` will source `/etc/bashrc_$TERM_PROGRAM` (if present). So if I launch Kitty from Terminal.app, bash will source `/etc/bashrc_Apple_Terminal` and try to set up a bunch of Terminal.app-specific behavior.

By also setting `$TERM_PROGRAM_VERSION` (the standard companion to `$TERM_PROGRAM`) this also allows programs to detect what version of the terminal emulator is running, which is very helpful when trying to enable behavior that is known to only work in newer versions (or work around bugs present in older versions).

> It wont get forwarded over SSH by default, so terminal programs cant rely on it

Wiping out `TERM_PROGRAM` is different than leaving it alone. If Kitty unset the var (and `TERM_PROGRAM_VERSION`) that would be better than nothing. Though I don't particularly find "it's not preserved by SSH" to be a compelling reason not to follow a de facto standard, or to do something that is purely additive (setting `TERM_PROGRAM` doesn't harm Kitty in any way).

This is also a bit of an odd argument to make when Kitty does set `TERM` to a special value, which is preserved by SSH except now I have to explicitly reset `TERM` when I SSH as the remote box does not have a terminfo entry for `xterm-kitty`. Heck, even `ssh localhost` fails as the terminfo entry is provided by the `TERMINFO` var (which is not preserved by SSH).

At least with `TERM_PROGRAM` I can configure SSH to preserve with the `SendEnv` config command, so I can in fact choose to preserve `TERM_PROGRAM`.

**Comment by kovidgoyal** [comment]
@lilyball TERM_PROGRAM is not a standard, its just something Apple uses. Terminal developers long ago decided that environment variables with terminal name/version are not a good way to detect/query terminal features. Google the terminal-wg discussion on feature detection for an example of the latest. 

Env vars get inherited across child processes, which means: a) they are inaccurate as you yourself point out in your launch kitty from terminal.app contrived example b) waste system resources being copied to every single process c) are easily overridden by users making them useless. 

And in this case TERM_PROGRAM provides no extra information over TERM. If TERM does not work for you, then neither will TERM_PROGRAM. 

As such I am not going to create digital noise chasing Apple's bad idea. They were too lazy to patch the shells on their systems to do proper terminal detection. So they came up with this kludge. 

That said if you find yourself launching kitty from terminal.app all the time, simply add

env TERM_PROGRAM whatever

to kitty.conf.

And with regards to ssh localhost, use the ssh kitten aliased to ssh, it magically makes TERM and terminfo work when using ssh, everywhere.

Oh and for posterity, the proper way to do terminal name and version detection is to use the XTVERSION escape code.

**Comment by lilyball** [comment]
> TERM_PROGRAM is not a standard, its just something Apple uses.

It's also used by Visual Studio Code (along with `TERM_PROGRAM_VERSION`). Searching online right now, I'm seeing that it's used as well by [Hyper](https://github.com/vercel/hyper/blob/c6dfab9e6770e41f1cab10ada42aae5a62399928/app/session.ts#L117) and [FluentTerminal](https://github.com/felixse/FluentTerminal/blob/e7df4a0743398791239cf5399c98e5628fc823c8/FluentTerminal.SystemTray/Services/TerminalsManager.cs#L210). I don't know offhand what other terminals to check.

> Terminal developers long ago decided that environment variables with terminal name/version are not a good way to detect/query terminal features. Google the terminal-wg discussion on feature detection for an example of the latest.

I found [this discussion](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/8) which mentions `TERM_PROGRAM` in passing but I don't see anyone actually discussing the pros/cons of `TERM_PROGRAM`.

I certainly agree that we need a better solution for feature detection! But I don't expect that to happen any time soon. And in the meantime, there doesn't appear to be much downside to setting this.

> And in this case TERM_PROGRAM provides no extra information over TERM. If TERM does not work for you, then neither will TERM_PROGRAM.

`TERM` doesn't have an equivalent for `TERM_PROGRAM_VERSION` though. In theory the terminfo file tells me what I need to know, except there are things not covered by it such as hyperlink support, information on handling of unicode text layout, etc. These are things that may require inspecting the version to handle. There's also a history of emulators reusing existing `TERM` names to say "I support everything that terminal does" (mostly because the existing one is in common terminfo databases) which means it's not fully reliable as a way to tell which terminal you're actually in. Heck, the inclusion of `TERM_PROGRAM` / `TERM_PROGRAM_VERSION` is worth it just to allow CLI programs to report the current terminal and version when generating bug reports.

> As such I am not going to create digital noise chasing Apple's bad idea. They were too lazy to patch the shells on their systems to do proper terminal detection. So they came up with this kludge.

Using a custom `TERM` _breaks a lot of things_. It doesn't work over SSH (which is why Kitty needs to have its hacky `kitty +kitten ssh` wrapper that I need to manually alias in my shell). There are lots of programs out there that do string matching on `TERM` instead of reading the capabilities directly (I wonder how many CLI programs think Kitty doesn't even support 256 colors?).

I do not think Apple developers were "lazy". I think they did not want to break SSH and wanted tools that do string matching (e.g. on `xterm-*`, which is _really common_), and so they picked an existing `TERM` to target for compatibility.

> Oh and for posterity, the proper way to do terminal name and version detection is to use the XTVERSION escape code.

Implementing bidirectional communication with the terminal is a pretty big ask for programs that just want to e.g. colorize their output. Heck, it's already hard enough convincing programs to use the terminfo capability strings for this instead of just hardcoding the xterm escapes.

---

At the very least, Kitty should _remove_ any inherited `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` env var, to avoid incorrect detection, and to make `/etc/bashrc` stop running the Apple Terminal initialization code when running `kitty` from a Terminal.app shell. I have worked around this locally by using `env` in my kitty.conf, but this doesn't help anyone else.

P.S. There appears to be no way to use kitty.conf to _delete_ a variable. Writing `env VAR` will set `VAR` to the empty string. This means that my solution of

```
env TERM_PROGRAM
env TERM_PROGRAM_VERSION
env TERM_SESSION_ID
```

will actually add those three env vars even if they weren't set before, which is annoying noise. (The inclusion of `TERM_SESSION_ID` here is because, again, this is a variable Terminal.app sets that's unique for each terminal session and _persists across relaunches_. It's used by the `/etc/bashrc_Apple_Terminal` code for preserving session state across relaunches, which is rather neat and demonstrates again why this needs to know it's specifically Apple Terminal, so it knows that `TERM_SESSION_ID` represents a uuid unique to the session and preserved across relaunches).

It would be much better if `env VAR` would delete it and `env VAR=` would set it to the empty string.

**Comment by kovidgoyal** [comment]
> > TERM_PROGRAM is not a standard, its just something Apple uses.
> 
> It's also used by Visual Studio Code (along with `TERM_PROGRAM_VERSION`). Searching online right now, I'm seeing that it's used as well by [Hyper](https://github.com/vercel/hyper/blob/c6dfab9e6770e41f1cab10ada42aae5a62399928/app/session.ts#L117) and [FluentTerminal](https://github.com/felixse/FluentTerminal/blob/e7df4a0743398791239cf5399c98e5628fc823c8/FluentTerminal.SystemTray/Services/TerminalsManager.cs#L210). I don't know offhand what other terminals to check. Edit: [WezTerm](https://wezfurlong.org/wezterm/index.html) is another.

Yeah, still doesnt make it a standard, in any shape or form. Do i really need to list the fifty odd terminal emulators that dont support it?

> 
> > Terminal developers long ago decided that environment variables with terminal name/version are not a good way to detect/query terminal features. Google the terminal-wg discussion on feature detection for an example of the latest.
> 
> I found [this discussion](https://gitlab.freedesktop.org/terminal-wg/specifications/-/issues/8) which mentions `TERM_PROGRAM` in passing but I don't see anyone actually discussing the pros/cons of `TERM_PROGRAM`.

That's because it is so obvious that env vars are not the right way to do this, that no one even considers it beyond a passing mention.

> 
> I certainly agree that we need a better solution for feature detection! But I don't expect that to happen any time soon. And in the meantime, there doesn't appear to be much downside to setting this.

Sure there is, you waste RAM across every process on your system and you perpetuate a bad idea.

> 
> > And in this case TERM_PROGRAM provides no extra information over TERM. If TERM does not work for you, then neither will TERM_PROGRAM.
> 
> `TERM` doesn't have an equivalent for `TERM_PROGRAM_VERSION` though. In theory the terminfo file tells me what I need to know, except there are things not covered by it such as hyperlink support, information on handling of unicode text layout, etc. These are things that may require inspecting the version to handle. There's also a history of emulators reusing existing `TERM` names to say "I support everything that terminal does" (mostly because the existing one is in common terminfo databases) which means it's not fully reliable as a way to tell which terminal you're actually in. Heck, the inclusion of `TERM_PROGRAM` / `TERM_PROGRAM_VERSION` is worth it just to allow CLI programs to report the current terminal and version when generating bug reports.
> 

Yes and once TERM_PROGRAM enters widespread use it too will be spoofed and bcome utterly unreliable. There is a long history of this. Those that do not learn from history are doomed to repeat it.

> > As such I am not going to create digital noise chasing Apple's bad idea. They were too lazy to patch the shells on their systems to do proper terminal detection. So they came up with this kludge.
> 
> Using a custom `TERM` _breaks a lot of things_. It doesn't work over SSH (which is why Kitty needs to have its hacky `kitty +kitten ssh` wrapper that I need to manually alias in my shell). There are lots of programs out there that do string matching on `TERM` instead of reading the capabilities directly (I wonder how many CLI programs think Kitty doesn't even support 256 colors?).

Since, unlike you, I actually deal with bug reports about TERM, I happen to be in an excellent position to know how many things using TERM=xterm-kitty breaks, and the answer is, very few.

> 
> I do not think Apple developers were "lazy". I think they did not want to break SSH and wanted tools that do string matching (e.g. on `xterm-*`, which is _really common_), and so they picked an existing `TERM` to target for compatibility.
> 

The usage of an env var to implement shell integration and then propagating that env var into every child processes environment is what is lazy.

> > Oh and for posterity, the proper way to do terminal name and version detection is to use the XTVERSION escape code.
> 
> Implementing bidirectional communication with the terminal is a pretty big ask for programs that just want to e.g. colorize their output. Heck, it's already hard enough convincing programs to use the terminfo capability strings for this instead of just hardcoding the xterm escapes.
> 

Programs that only need to colorize their output dont need to do terminal detection, and in the real world, do not do so. Using TERM or anything else.

> At the very least, Kitty should _remove_ any inherited `TERM_PROGRAM` and `TERM_PROGRAM_VERSION` env var, to avoid incorrect detection, and to make `/etc/bashrc` stop running the Apple Terminal initialization code when running `kitty` from a Terminal.app shell. I have worked around this locally by using `env` in my kitty.conf, but this doesn't help anyone else.
> 

No one else runs kitty from terminal.app on a regular enough basis for this to be an issue. And if there is indeed another such benighted sould they are free to set TERMINAL_PROGRAM to whatever floats their boat in kitty.conf.

> P.S. There appears to be no way to use kitty.conf to _delete_ a variable. Writing `env VAR` will set `VAR` to the empty string. This means that my solution of
> 
> ```
> env TERM_PROGRAM
> env TERM_PROGRAM_VERSION
> env TERM_SESSION_ID
> ```
> 
> will actually add those three env vars even if they weren't set before, which is annoying noise. (The inclusion of `TERM_SESSION_ID` here is because, again, this is a variable Terminal.app sets that's unique for each terminal session and _persists across relaunches_. It's used by the `/etc/bashrc_Apple_Terminal` code for preserving session state across relaunches, which is rather neat and demonstrates again why this needs to know it's specifically Apple Terminal, so it knows that `TERM_SESSION_ID` represents a uuid unique to the session and preserved across relaunches).
> 
> It would be much better if `env VAR` would delete it and `env VAR=` would set it to the empty string.

A good idea, now implemented in master.
