### ISSUE TITLE
Add keynames to documentation website

### ISSUE THREAD

**Issue by Sleepful** [kovidgoyal/kitty#3340]
Add these aliases

https://github.com/kovidgoyal/kitty/blob/master/kitty/key_names.py 

to

https://sw.kovidgoyal.net/kitty/

probably to this section

https://sw.kovidgoyal.net/kitty/conf.html#keyboard-shortcuts

**Comment by Sleepful** [comment]
Also 
`map cmd+apostrophe something` doesn't work
`map cmd+' something' does work but messes with syntax highlighting in the file in my editor

**Comment by kovidgoyal** [comment]
Why? Those are common names for the keys. The idea of the aliases is to
make it intuitive to use key names. As such they shouldnt need to be
documented.

**Comment by Sleepful** [comment]
@kovidgoyal intuitive to whom? I'm telling you it is guesswork.

**Comment by Sleepful** [comment]
I had to search the codebase for some keywords because I was afraid some symbols were working properly. I did not know what you named these  I could find some of the keywords in the website by using `cltr+f` in the `Configuration` section because it has a good amount of helpful examples, so those include some of these keywords, but that wasn't the greatest and not all keywords are included in those examples. If you actually need examples of the multiple names that each symbol could have then I can give you such examples.

**Comment by kovidgoyal** [comment]
They are not keywords, they are *aliases*. If those aliases are not
intuitive to you adding them to the docs isnt going to make any
difference, since you again wont know what to search for. If the aliases
for a key are "foo" and "bar" but you think of it as "jumbo", adding foo
and bar to the docs isnt going to make them searchable. 

So again, if there are common aliases for those keys that are missing, I
am happy to add them, but I dont see the point of listing them
somewhere in the docs.

**Comment by Sleepful** [comment]
> adding them to the docs isnt going to make any
difference
If they were in the docs I would have found them sooner, because that's the first place I look.
Any future user could benefit from finding them in the docs, otherwise they won't know about them.
If it isn't intuitive to me, it won't be for other people either.
