### ISSUE TITLE
Prefix key: How to `map ctrl+space c    new_window`

### ISSUE THREAD

**Issue by nochiel** [kovidgoyal/kitty#338]
- Is it possible to map functions to keys in the way one would in tmux/screen, i.e. with a prefix key?
I'd like to do things like the following in `kitty.conf`:
```conf
map ctrl+space c new_window
map ctrl+space space next_layout
```
- I find the prefix key model easy on the wrists instead of having to press `ctrl+shift+key` for the common case.

p.s. Thanks for introducing the `combine` keyword for mapped functions.

**Comment by kovidgoyal** [comment]
No, it's not possible, but it should not be hard to add, it would basically work like combine, except that it would put the keyboard handler into an "operator pending" mode where it soaks up the next keypress and dispatches the action based on it. Something like:

```
map ctrl+space prefixed_cmd <key> <function>
```

Just FYI, there were two reasons I chose ctrl+shift as kitty's base modifier:

1) It cannot be used for most terminal programs
2) At least on my keyboard, you can press both ctrl and shift together using only a single thumb. This is why I did not add a prefix mode in the first place. To me, pressing ctrl+shift+<key> is easier than pressing ctrl+<key> followed by <other key>

**Comment by nochiel** [comment]
> 2. At least on my keyboard, you can press both ctrl and shift together using only a single thumb. This is why I did not add a prefix mode in the first place. To me, pressing ctrl+shift+ is easier than pressing ctrl+ followed by [...]

I see. I've just tried getting used to my left thumb on <kbd>ctrl+shift</kbd>.  I can definitely see how it could be easier and more efficient in many cases.  But I find myself having to take my hands off the home row: usually my left pinky hits <kbd>capslock</kbd> (`swapcaps`) and my right hand finger hits whichever prefix key is configured. 

Also, perhaps the 'operator pending' mode you described could make it possibly for an entirely mouseless use of kitty when selecting regions to copy?

Thanks again.

**Comment by kovidgoyal** [comment]
You can already do completely mouse free selecting of regions to copy, just press ctrl+shift+h and configure the pager used for it in kitty.conf (defaults to less) to be something that supports keyboard selection, such as vimpager. You can even (if you are running kitty from master) click urls using only the keyboard (ctrl+shift+e).

**Comment by kovidgoyal** [comment]
I looked into this, and while it is trivial to implement in kitty itself, it cannot be made robust because of limitations in glfw. Basically, the glfw keyboard API is too limited to make this work. See https://github.com/glfw/glfw/issues/1140  until I get around to implementing the new keybaord API for glfw, this is not possibel to implement.

**Comment by nochiel** [comment]
Okay.  Thanks again @kovidgoyal. (Incidentally, I'm also getting faster and more comfortable using left-small-finger-on-shift + left-index-on-capslock.)

**Comment by kovidgoyal** [comment]
This is implemented in the xkb branch.

**Comment by nochiel** [comment]
Thank you, sir!

**Comment by benbrastmckie** [comment]
> This is implemented in the xkb branch.

I have been trying to figure out how to map `ctrl+space` followed by `c` to the creation of a new window, and tried the following using the documentation:
```
clear_all_shortcuts yes
kitty_mod ctrl+space
map kitty_mod+c new-tab
```
I also tried the following, avoiding using `kitty_mod` entirely:
```
map ctrl+space>c new-tab
```
So far, neither of these work for me. I have been combing though the excellent documentation, but haven't found just what I'm looking for. As an aside, my reasoning is that I also use Tmux, and want to preserve my existing muscle memory since I'll be going back and forth. And I like the key combination. Thanks so much!

**Comment by kovidgoyal** [comment]
map ctrl+space>c new_tab

**Comment by benbrastmckie** [comment]
Thanks so much!
