### ISSUE TITLE
Feature request: option to remember_window_location

### ISSUE THREAD

**Issue by fluffynuts** [kovidgoyal/kitty#3438]
kitty has a config option `remember_window_size`. In addition, I'd really appreciate a `remember_window_position` which I'd expect to place kitty at the same spot as the last time it was open, assuming that that location is available, meaning that if a kitty term were open on a monitor which is now no longer available, then it should open on the default monitor, preferably in the same relative location, but mostly just to avoid remaining hidden / off-screen.

I could accomplish this through window manager settings. This would just be a nice-to-have.

**Comment by kovidgoyal** [comment]
I'm afraid window position is not something that can be robustly
remembered, since tiling window managers and everything on wayland dont
allow applications to position their windows. As such I am not going to
implement a feature that does not work robustly.

**Comment by fluffynuts** [comment]
the user-focused solution would be to behave as best as possible

it's as if you openly desire people _not_ to use your solution ):

**Comment by fluffynuts** [comment]
I know I don't matter, but your persistent attitude towards me has driven me to choose another solution.

Every time I come humbly for assistance, you're abrasive. Every time I reach out, you strike.

**Comment by fluffynuts** [comment]
neither is window size, especially considering tiling window managers, yet that's implemented

I get it: you don't want to implement something your users want unless it aligns with your vision. That's fine: kitty is _your_ project. Not my adoptive, any more. glhf.

**Comment by resolritter** [comment]
Commenting for the sake of other people who might find this issue in the future.

If I were to want this in i3/Xorg, although the concepts might broadly to other Xorg-based environments, my idea would be as follows:

1. Listen for events for windows. On i3 this can be done with `i3-msg -t subscribe -m '[ "window" ]'`. Sample output (notice the `{"change": "new"}`):

```
> i3-msg -t subscribe -m '[ "window" ]'
```

`{"change":"new","container":{"id":94281752024768,"type":"con","orientation":"none","scratchpad_state":"none","percent":1.0,"urgent":false,"marks":[],"focused":false,"output":"HDMI-A-0","layout":"splith","workspace_layout":"default","last_split_layout":"splith","border":"none","current_border_width":0,"rect":{"x":810,"y":382,"width":300,"height":350},"deco_rect":{"x":0,"y":0,"width":0,"height":0},"window_rect":{"x":0,"y":0,"width":300,"height":350},"geometry":{"x":810,"y":365,"width":300,"height":350},"name":"Foo","window":94371841,"window_type":"normal","window_properties":{"class":"discord","instance":"discord","window_role":"browser-window","title":"Foo","transient_for":null},"nodes":[],"floating_nodes":[],"focus":[],"fullscreen_mode":0,"sticky":false,"floating":"auto_on","swallows":[]}}`

2. If the events for your platform doesn't yield the coordinates, fetch it using `xdotool getwindowgeometry`.

3. Using the events, record the window's position on either close or open or whatever, depending on what you want.

4. When a new window is created, move it to the recorded position with a command. On i3 it'd be `i3-msg 'move position [x] px [y] px'`, otherwise you could try `xdotool windowmove`.

This highlights how environment-dependent the solution is. On the upside, it's more scriptable than what some on/off setting could offer. For instance, you could move *conditionally* based on some window parameters such as title.

FWIW some terminal emulators have a `-geometry` option which will try to position the window at the chosen coordinates, so in that case you'd be able to skip the last step; I don't think kitty has it, though.
