### ISSUE TITLE
Cascadia Code ligature rendering issues

### ISSUE THREAD

**Issue by kgizdov** [kovidgoyal/kitty#3504]
**Describe the bug**
Release 0.20.1 renders some ligatures incorrectly. For example:
```
###########################################
```
looks like this:
![hashes](https://user-images.githubusercontent.com/3164953/115302341-02792b00-a16b-11eb-8278-37dd3c0b5b0b.png)
while:
```
>>--->--||--<<--|-->--||---<<---|
```
looks like:
![dashes](https://user-images.githubusercontent.com/3164953/115302467-22105380-a16b-11eb-80ca-b14694cb8e65.png)

There seems to be extra spaces here and there and some missing characters too.

**To Reproduce**
1. install kitty 0.20.1
2. install Cascadia Code 2102.25
3. set Cascadia Code as default font family

**Expected behavior**
There should be no spaces or missing characters from the render.

**Screenshots**
It should look like so:
![cascadia-code-reference](https://user-images.githubusercontent.com/189190/107696218-88a65c00-6c66-11eb-8514-fe86b437124e.png)

**Environment details**
OS: Arch Linux

```
$ kitty --debug-config
kitty 0.20.1 created by Kovid Goyal
Linux yavin4 5.11.15-arch1-2 #1 SMP PREEMPT Sat, 17 Apr 2021 00:22:30 +0000 x86_64
Arch Linux \r (\l)
LSB_VERSION=1.4
DISTRIB_ID=Arch
DISTRIB_RELEASE=rolling
DISTRIB_DESCRIPTION="Arch Linux"
Loaded config files: /home/gizdov/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
bold_font             CascadiaCode Bold
bold_italic_font      CascadiaCode BoldItalic
cursor                Color(red=237, green=212, blue=0)
font_family           CascadiaCode
font_size             12.5
foreground            Color(red=237, green=212, blue=0)
italic_font           CascadiaCode Italic
scrollback_lines      20000
strip_trailing_spaces smart
symbol_map            {(8277, 8277): 'NotoColorEmoji'}
tab_bar_edge          1
Added shortcuts:
	alt+ctrl+- KeyAction(func='change_font_size', args=(True, '-', 2.0))
	alt+ctrl+= KeyAction(func='change_font_size', args=(True, '+', 2.0))
	alt+ctrl+backspace KeyAction(func='change_font_size', args=(True, None, 0.0))
Removed shortcuts:
	shift+ctrl+- KeyAction(func='change_font_size', args=(True, '-', 2.0))
	shift+ctrl+= KeyAction(func='change_font_size', args=(True, '+', 2.0))
	shift+ctrl+backspace KeyAction(func='change_font_size', args=(True, None, 0.0))
```

**Additional context**
This was working fine in 0.20.0 with [this patch](https://github.com/kovidgoyal/kitty/commit/912c46fc57362d3bd2a2f82b4b0a2ef939d6e1ec) applied on top only.

**Comment by kovidgoyal** [comment]
kitty doesnt support infinite length ligatures for performance reasons. It has a max ligature size of 9 characters, IIRC. Anything longer and you will get some rendering artifacts. That has always been the case.

**Comment by kgizdov** [comment]
hey, I just got the `kitty 0.21.2` on arch and ligatures do look better, however, I'm getting some weird behaviour with `Cascadia Code 2105.24`. For example, when I have a few `#` it works fine:
![short_hash](https://user-images.githubusercontent.com/3164953/123983714-c1a05c80-d9cc-11eb-8e06-4cc088e4b62a.png)
but when it gets longer one of the hashes starts to disappear bit by bit at the end:
![medium_hash](https://user-images.githubusercontent.com/3164953/123983970-f0b6ce00-d9cc-11eb-8bac-91fb60c81b40.png)
and if it becomes very long, like in a progress bar, the hashes start to disappear one by one and only empty space it rendered:
![long_hash](https://user-images.githubusercontent.com/3164953/123984310-3378a600-d9cd-11eb-8e0d-ba24d781f618.png)
the longer the string the bigger the gap:
![longest_hash](https://user-images.githubusercontent.com/3164953/123984456-50ad7480-d9cd-11eb-821b-ae9eeed9f9f3.png)
but the cursor is in the correct place, while symbols disappear visually. However, if the string overflows on the next line, then it starts anew - first few characters are rendered correctly and longer strings start missing hashes.
Is that expected behaviour?

**Comment by kovidgoyal** [comment]
yes it is, basically the ligature takes up less length than individual characters, since with individual characters there is spacing between each character. So you will get the full ligature being shorter than the individual characters one after another.

**Comment by kgizdov** [comment]
my only concern was the artefacting at the end, where a ligature does get truncated, even though is should extend further. I think Cascadia Code did purport _infinite_ ligatures support for the first time and something to do with mono spacing. Like, if you look on the second picture, there is one ligature occluding the other.

**Comment by kovidgoyal** [comment]
Yeah is see the artifact, but that looks like a font bug as far as I can tell, however, I will take a look at it in detail when I have some time.

**Comment by kgizdov** [comment]
Just to provide some test data - went and tested the same font with same ligatures in Sublime Text 4 and there it works as expected with all of the above examples. No occlusion and, thus, no truncation or space at the end. So possibly something weird happening. Hopefully, this helps with debugging. Cheers.

**Comment by kovidgoyal** [comment]
You are presumably running out of date kitty. Update and you will be
fine. I think your issue is the same as #3729

**Comment by kgizdov** [comment]
I mentioned above that I'm running 0.21.2, which is the latest release. I could try to run the baster branch if you think it's solved there.

**Comment by kovidgoyal** [comment]
OK, I tried it on my Arch system and I cannot reproduce. The # ligature takes up all the cells available, with no blanks at the end, tested with:

```
kitty --config NONE -o 'font_family Cascadia Code' python -c "print(('#' * 60), end=']'); input()"
```

I do see the rendering artifacts at the end of it, but that is a font bug as I thought. The infinite ligature is actually longer than the string of individual characters, as a result the last glyph is being moved back to fit causing the rendering artifact. This commit prevents that from happening, with it, I now get a truncated last character instead, as expected: https://github.com/kovidgoyal/kitty/commit/e07ba2c53d62cbb6b738778c8bc1616e50e71297

You wont see this bug in other programs because kitty always renders within cell boundaries, other programs are happy to overflow.

**Comment by kgizdov** [comment]
I see. Thanks for having a look at it. I will report upstream to Cascadia Code.

**Comment by kgizdov** [comment]
apparently, something is not quite as it should be - https://github.com/microsoft/cascadia-code/issues/527

**Comment by aaronbell** [comment]
For convenience, here is the comment that I left on this bug:

> The fun thing with these infinite ligatures is that in the font's construction , the final `#` of `###` is the same glyph as the final `#` in
> 
> <img width="808" alt="Screen Shot 2021-07-05 at 5 50 40 AM" src="https://user-images.githubusercontent.com/8460297/124474083-f3ab1900-dd54-11eb-9558-10bf88ac312b.png">
> 
> On the font side, here's the substitution for, say `#####`:
> `#` - numbersign_start.seq
> `#` - numbersign_middle.seq
> `#` - numbersign_middle.seq
> `#` - numbersign_middle.seq
> `#` - numbersign_end.seq
> 
> And as the string gets longer, the number of `# - numbersign_middle.seq` only gets longer. There's no other difference.
> 
> If `###` renders fine and a really long string of `####################` does not, then the bug is on kitty's end. In both situations the ligated form has the same advanced width as the constituent `#`.

**Comment by kgizdov** [comment]
Went and did some experiments to possibly help with issue identification. Firstly, if I test with a character that has not ligatures, I get this:
![cascadia-code-zeros](https://user-images.githubusercontent.com/3164953/124488294-5a155300-ddb8-11eb-94ba-5e7ae134b995.png)
Then I went and tested Cascadia Code, Cascadia Code Mono and Cascadia Code PL. The triple compare is this:
![cascadia-code-tripple-compare](https://user-images.githubusercontent.com/3164953/124488391-76b18b00-ddb8-11eb-991e-be6e6eb06944.png)
For some reason font size is not consistent, even though `kitty` is running with no config - so maybe the font does have different size between variants (@aaronbell )
Then I noticed that when I run `print(('=' * 3), end=']')`, I get a weird artefact:
![cascadia-code-equals3](https://user-images.githubusercontent.com/3164953/124488764-e3c52080-ddb8-11eb-96c9-c98f92eac5e3.png)
This should instead be this 
![threeequals](https://user-images.githubusercontent.com/3164953/124488927-1838dc80-ddb9-11eb-8e52-96d5ed7cd342.png)
but when there is a `]` behind it turns into a different ligature as above. Weird. It also only happens for `===]` and not for any other number of `=`.
It is also interesting to see what happens when the font overflows the line:
![cascadia-code-overflow](https://user-images.githubusercontent.com/3164953/124489442-ad3bd580-ddb9-11eb-8a0c-b89326b7c377.png)
seems like the issue is reset and and extra `#` character is consistently being drawn at the same place atop an already existing one. This starts to happen at around `'#' * 90`.
At this point, I thought that this should not be isolated to `#`, but to possibly every ligature, but since `#` has vertical features it won't be apparent on the horizontal ones. And I was correct.
This `-------------------` is just a line. However, it does produce and extra space at the end and the length of the space is proportional to the number of `-`. Now let's put a vertical feature in there, like `|`, this has an interesting and possibly revealing effect:
`-|`
![Screenshot from 2021-07-05 18-04-21](https://user-images.githubusercontent.com/3164953/124491022-7797ec00-ddbb-11eb-8025-8b7691eef6bd.png)
`-|]` 
![Screenshot from 2021-07-05 18-03-38](https://user-images.githubusercontent.com/3164953/124490935-5b944a80-ddbb-11eb-8d02-bf1498b33c39.png)
`118 * '-' + '|'` has this at the end:
![Screenshot from 2021-07-05 18-07-25](https://user-images.githubusercontent.com/3164953/124491378-e07f6400-ddbb-11eb-83e9-6fcf45a15fc2.png)
at `119 * '-'` the vertical `|` cannot be seen anymore. If we add `]`, the ligature is no longer working:
![Screenshot from 2021-07-05 18-08-41](https://user-images.githubusercontent.com/3164953/124491509-0dcc1200-ddbc-11eb-9d5f-d5270e9623f5.png)
Finally, I manually marked the bounds of each cell
![cascadia-code-artefact-test1-lines](https://user-images.githubusercontent.com/3164953/124492317-f5102c00-ddbc-11eb-989d-94a4d323874c.png)
I think there are two explanations for this and possibly two separate issues as well. The wrong ligature is selected at the end of a string when `]` is present, which breaks the sequence and has effects along a few characters behind. Also, there is some evidence that some ligature sequence (middle or end) is ever so slightly longer/shorter, causing clipping to occur at the end of these strings.

I'd really appreciate if we could have a productive discussion on this and get to the bottom of this. I don't mind investigating further and/or committing dev time if pointed in the correct direction. Thanks.

**Comment by kovidgoyal** [comment]
On Mon, Jul 05, 2021 at 06:08:55AM -0700, Aaron wrote:
> > If `###` renders fine and a really long string of `####################` does not, then the bug is on kitty's end. In both situations the ligated form has the same advanced width as the constituent `#`. 

I'm afraid that does not follow, if each ligated glyph's advance is 1
pixel more than the advance of the unligated glyph, the string of
ligated glyphs is going to end up longer than the unligated string by an
amount proportional to the number of glyphs. Depending on how many extra
pixels are present in the canvas, this overhang will cause rendering
artifacts only beyond a certain string size, as then the overflow will 
cross the canvas boundary.

And indeed, with the following patch to kitty you can see exactly that
happening:

```diff
diff --git a/kitty/freetype.c b/kitty/freetype.c
index 1e4962b4..888c1526 100644
--- a/kitty/freetype.c
+++ b/kitty/freetype.c
@@ -629,6 +629,7 @@ render_glyphs_in_cells(PyObject *f, bool bold, bool italic, hb_glyph_info_t *inf
         }
         x_offset = x + (float)positions[i].x_offset / 64.0f;
         y = (float)positions[i].y_offset / 64.0f;
+        printf("%d: x=%f adv=%f canvas_width: %u\n", i, x_offset, (float)positions[i].x_advance / 64.0f, canvas_width);
         if ((*was_colored || self->face->glyph->metrics.width > 0) && bm.width > 0) {
             place_bitmap_in_canvas(canvas, &bm, canvas_width, cell_height, x_offset, y, baseline, i);
         }
```

Then run kitty with:

```
kitty --debug-font-fallback --config NONE -o 'font_family Cascadia Code' python -c "print(('#' * 60), end=''); input()"
```

The last line of output will be something like (exact numbers will
depend on monitor DPI:

```
59: x=1014.062500 adv=17.187500 canvas_width: 1020
```

showing that there is not enough space for the last glyph. Now change
the 60 above to 5 and the last line is:

```
4: x=68.750000 adv=17.187500 canvas_width: 85
```

Showing there is just enough space for the last glyph. 

And by examining the numbers, we see that the advance for a ligated
glyph is 17.1875 which is the same as the advance for the unligated
glyph. *However* the advance for this glyph and indeed all other glyphs
in this monospaced font based on the glyph metrics should be 17. And
yet, harfbuzz is setting the advance for these glyphs to 17.185,
probably because of some boundary corssing or GPOS rule. I dont know
exactly how harfbuzz calculates these advances, so I cant be more
specific.

And that is the root cause of this issue. The overhang on 0.185 does not
matter when rendering individual glyphs since each glyph is rendered in a
fixed size cell of 17 units (the advance from the glyph metrics), so, in
effect it is clamped to 17. However when rendering the ligature, those
extra 0.185 add up for every successive glyph, causing the overhang and
the truncated rendering.

So to fix it, the font needs to be changed in whatever manner is
needed to ensure that the advance for the # character calculated by
harfbuzz is the same as the nominal advance from the glyph metrics.

**Comment by aaronbell** [comment]
Thanks for the analysis @kgizdov. The various versions of Cascadia Code are identical. The only difference between `Code` and `Mono` is that Mono is not using the ligature for infinite `###` marks. 

@kovidgoyal There are two "advanced widths". Internal to the font, each of the number sign alternate forms are exactly 1200 units, identical to Mono. Here's a screen from FontGoggles, which is built on top of Harfbuzz where you can see the 1200 units mentioned on the left:
<img width="770" alt="Screen Shot 2021-07-05 at 12 57 31 PM" src="https://user-images.githubusercontent.com/8460297/124513891-a056bc00-dd90-11eb-9b55-5081804007b9.png">

The other "advanced width" that you mention in your comment is likely the 'full width' of the glyph that includes any horizontal overlaps. The infinite ligature numbersigns have a slight overlap (aka, negative sideabearings) to ensure that they connect smoothly with the preceding and proceeding glyphs as pixel rounding can cause slight gaps between glyphs. I suspect that the Harfbuzz metric that you're looking at is including that overlap in its determination:

<img width="236" alt="Screen Shot 2021-07-05 at 1 00 56 PM" src="https://user-images.githubusercontent.com/8460297/124514065-0cd1bb00-dd91-11eb-8fdd-307b83ac2da4.png">

This sort of overlapping is not uncommon in the world of fonts (Fira Code does the same for these sorts of glyphs), and it is also quite common in fonts for scripts that feature connecting elements. I would fully expect that text in scripts like Arabic, or Devanagari would demonstrate a similar issue. As I haven't seen this sort of problem in other applications that rely on Harfbuzz (such as FontGoggles), I have to conclude that kitty is perhaps using the wrong harfbuzz function to calculate glyph widths, leading to this misalignment.

**Comment by aaronbell** [comment]
BTW @kgizdov, a couple of notes about questions you raised:

`===]` This was an interesting situation where the ligature for `equal_equal` activated on the first `=`, but the substitution that was supposed to happen on the second `=` did not occur due to it matching an `ignore` command in the OT feature. I've re-arranged the code so that this will not happen in the future. Thanks for finding this!

`-|]` Here the `|]` ligature takes precedence over the infinite arrow`-|` form. Perhaps unexpectedly, but that's the reason why it jumps from a merged `-|` form to a split `-|]` form.

**Comment by kovidgoyal** [comment]
On Mon, Jul 05, 2021 at 01:13:30PM -0700, Aaron wrote:
> This sort of overlapping is not uncommon in the world of fonts (Fira Code does the same for these sorts of glyphs), and it is also quite common in fonts for scripts that feature connecting elements. I would fully expect that text in scripts like Arabic, or Devanagari would demonstrate a similar issue. As I haven't seen this sort of problem in other applications that rely on Harfbuzz (such as FontGoggles), I have to conclude that kitty is perhaps using the wrong harfbuzz function to calculate glyph widths, leading to this misalignment. 

kitty is designed for actual *monospaced* fonts. That design allows it
to render every cell on the screen in parallel on the GPU for extreme
performance. If your font is using metrics that are different for some
glyphs compared to other glyphs, then it is not actually monospaced
anymore. Other applications render text as continuous lines, not as
individual cells.

And no, there is only one function in harfbuzz for getting glyph
positions, so there is no chance that kitty is using the wrong one.

And yes, Arabic and Devanagari scripts will not work with kitty's
rendering model, that is by design. Those scripts are inherently *not*
monospaced.

@the OP: You can probably work around this issue by using
adjust_cell_width to make the cell width 1px wider than the metrics
specified in the code. That will take care of the overhang.

**Comment by kovidgoyal** [comment]
Although, thinking about it, I think I can workaround this issue, basically have to change the glyph placement code when drawing ligatures to respect negative LSB which it currently doesnt as for single cell glyphs negative LSB would leak outside the cell.

**Comment by aaronbell** [comment]
That’s a good idea. Though I’d suggest doing it with all glyphs rather than just ligatures. It would help with Arabic (which the next version of Cascadia includes) and box drawing characters (which also feature the overlap).

**Comment by kovidgoyal** [comment]
On Mon, Jul 05, 2021 at 07:50:29PM -0700, Aaron wrote:
> That’s a good idea. Though I’d suggest doing it with all glyphs rather than just ligatures. It would help with Arabic (which the next version of Cascadia includes) and box drawing characters (which also feature the overlap).

It cant be done with all glyphs, only ligatures, as glyphs are rendered independently
in fixed sized cells. And box drawing characters are rendered without
using fonts at all.

**Comment by kovidgoyal** [comment]
I was wrong, the negative LSB is already handled in ligatures https://github.com/kovidgoyal/kitty/blob/master/kitty/freetype.c#L577  there bitmap_left is the LSB which is -1 for the ligature glyphs, however LSB does not affect advance, only glyph relative placement, so the original issue remains and I dont see a good way to fix it. As far as I can see this needs to be fixed in the font, using an overlap is going to cause overlarge advances, which means long strings of these characters occupy a different width than the individual glyphs would, making the font not really monospace anymore.

**Comment by aaronbell** [comment]
Unfortunately I have no plans to change the way the font works because doing so will cause rendering regressions in every other coding environment. It seems that the approach kitty uses for rendering glyphs (at least as far as I understand it) is incompatible with this feature of Cascadia Code.

@kgizdov I’m sorry that we weren’t able to resolve this for you. I’d suggest using Cascadia Mono, but then you’d lose all coding ligatures.

**Comment by kgizdov** [comment]
@kovidgoyal I'm confused by [this line](https://github.com/kovidgoyal/kitty/blob/cea8d4a87de2ac747594c72b4898747272b8eb2b/kitty/freetype.c#L580). Why should kitty be ignoring width correction for long ligatures? Because of char by char width estimation or?

Also, I think I found a similar issue with another font - [Iosevka](https://github.com/be5invis/Iosevka).
When the ligature for `=>` kicks in, everything is fine:
![iosevka_arrow](https://user-images.githubusercontent.com/3164953/124585596-1e34c900-de5e-11eb-95b9-8d90b21f6569.png)
But when it get longer:
![iosevka_long_arrow](https://user-images.githubusercontent.com/3164953/124585632-2856c780-de5e-11eb-98e5-1d09da586496.png)
it overflows as discussed with Cascadia Code. However, if it was purely the same issue with overflowing, making it even longer will have wider side effects. Except it doesn't:
![iosevka_very_long_arrow](https://user-images.githubusercontent.com/3164953/124585731-44f2ff80-de5e-11eb-941e-e41c9e7366a8.png)
I also think in the case of Iosevka the overhang is not there, since there are tiny gaps visible between each character. Can't confirm, because can't get FontGoggles to compile for me yet.

**Comment by kovidgoyal** [comment]
On Tue, Jul 06, 2021 at 03:43:26AM -0700, Konstantin Gizdov wrote:
> @kovidgoyal I'm confused by [this line](https://github.com/kovidgoyal/kitty/blob/cea8d4a87de2ac747594c72b4898747272b8eb2b/kitty/freetype.c#L580). Why should kitty be ignoring width correction for long ligatures? Because of char by char width estimation or?

Because without that the glyph would be moved back and rendered on top
of the previous one, which will cause the rendering artifact you
reported, rather than a truncated glyph, which looks less bad. 

> 
> Also, I think I found a similar issue with another font - [Iosevka](https://github.com/be5invis/Iosevka).
> When the ligature for `=>` kicks in, everything is fine:
> ![iosevka_arrow](https://user-images.githubusercontent.com/3164953/124585596-1e34c900-de5e-11eb-95b9-8d90b21f6569.png)
> But when it get longer:
> ![iosevka_long_arrow](https://user-images.githubusercontent.com/3164953/124585632-2856c780-de5e-11eb-98e5-1d09da586496.png)
> it overflows as discussed with Cascadia Code. However, if it was purely the same issue with overflowing, making it even longer will have wider side effects. Except it doesn't:
> ![iosevka_very_long_arrow](https://user-images.githubusercontent.com/3164953/124585731-44f2ff80-de5e-11eb-941e-e41c9e7366a8.png)
> I also think in the case of Iosevka the overhang is not there, since there are tiny gaps visible between each character. Can't confirm, because can't get FontGoggles to compile for me yet.

I dont get a rendering artifact in Iosevka running kitty master. There
is some underflow because the ligature is smaller than N * cell size

**Comment by kgizdov** [comment]
Alright, I will try master and see how it goes.

**Comment by kgizdov** [comment]
I just upgraded to `kitty 0.23.0` on Arch Linux, and I am pleased to say I no longer experience any of the above issues. Everything works as expected. :)

**Comment by kovidgoyal** [comment]
Yes, I did the simple expedient of rounding the advances, which takes care of this for most fonts. See 55319cd

**Comment by rixx** [comment]
I'm running `kitty 0.23.1` on Arch, and I'm running into a similar issue with the above mentioned Iosevka font with `=` ligatures. Here's how different amounts of equal signs look in a row:
![2021-11-27T09:47+01:00](https://user-images.githubusercontent.com/2657547/143674829-acd26881-1b0a-4a7a-8fbf-dd726bbc07d7.png)

I'm not sure if this is a font bug or a Kitty bug.

**Comment by kovidgoyal** [comment]
you need to install the version of iosevka with glyph names embedded.

**Comment by vdrandom** [comment]
Seems like MacOS version 0.27.1 is still affected:
<img width="450" alt="Screenshot 2023-02-18 at 13 43 51" src="https://user-images.githubusercontent.com/3367071/219863815-e76fca33-3753-45c4-b595-4c2dc03b7d3e.png">

**Comment by onion108** [comment]
kitty 0.38.1 install from homebrew with font CaskaydiaCove Nerd Font Mono, also has weird size specifically in `<<=`:
<img width="121" alt="スクリーンショット 2025-01-10 17 50 02" src="https://github.com/user-attachments/assets/64284bde-4c7d-42f4-8f56-ce42ab90793d" />
As an example that correctly rendered (from `neovide`):
<img width="34" alt="スクリーンショット 2025-01-10 17 51 02" src="https://github.com/user-attachments/assets/1ffb777c-a3af-4fbf-bdfd-afcd956b7acb" />
