### ISSUE TITLE
Significant regression for tab operations on MacOS when mapped to ctrl in 0.20.1

### ISSUE THREAD

**Issue by bufdev** [kovidgoyal/kitty#3512]
**Describe the bug**

I have the following lines in `kitty.conf`:

```
map ctrl+left previous_tab
map ctrl+right next_tab
map ctrl+shift+left move_tab_backward
map ctrl+shift+right move_tab_forward
map ctrl+t new_tab
map ctrl+q close_tab
```

Since upgrading to 0.20.1, there is a significant regression in all tab operations. Using these shortcuts to open a tab, close a tab, or move to the previous/next tab can take up to a second.

If I comment out these shortcuts and use the defaults (such as Cmd+t for open tab instead of Ctrl+t as I have mapped), no such delay exists.

**To Reproduce**

- Add the above to `kitty.conf` on MacOS.
- Try opening, closing, or going to the previous/next tab using the mapped ctrl+ shortcuts.
- See the delay.

**Expected behavior**

I expect there to be no performance penalty for different shortcut mappings.

**Screenshots**

N/A

**Environment details**

MacOS 11.2.3
Kitty 0.20.1

```
kitty 0.20.1 created by Kovid Goyal
Darwin mbp.lan 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.2.3 BuildVersion:	20D91
Loaded config files: /Users/bufdev/.config/kitty/kitty.conf

Config options different from defaults:
Added shortcuts:
	ctrl+q KeyAction(func='close_tab', args=())
	ctrl+t KeyAction(func='new_tab', args=())
	ctrl+left KeyAction(func='previous_tab', args=())
	ctrl+right KeyAction(func='next_tab', args=())
Changed shortcuts:
	shift+ctrl+left KeyAction(func='move_tab_backward', args=())
	shift+ctrl+right KeyAction(func='move_tab_forward', args=())
```

**Additional context**

See above for minimal kitty.conf.

**Comment by kovidgoyal** [comment]
I cannot replicate. First of all ctrl+left/right are the macos shortcuts
for changing workspace/virtual desktop/lord knows what apple calls it.
So those key events are not delivered to kitty at all.
And using ctrl+t for new tab and ctrl+q for close_tab is instantaneous for me, with

kitty --config NONE -o 'map ctrl+t new_tab' -o 'map ctrl+q close_tab'

**Comment by bufdev** [comment]
To be clear here: I downgraded to 0.19 and the problem was fixed. ctrl+left/right have been sent to kitty for me for years in MacOS, and given the above configuration, work just fine in 0.19 to go to the next and previous tab.

This seems like a pretty big regression - is your stance that if you can’t instantly replicate, the result is a closed issue, not further drilling into a potential bug, and asking the filer for further help? This doesn’t seem like the correct solution.

**Comment by bufdev** [comment]
Of note, I remapped the default behavior for macOS, so ctrl+left/right do nothing in macOS. So we could drill down further here instead of closing this issue.

**Comment by kovidgoyal** [comment]
Dont get hung up on the closed status. I close all bug reports that dont
seem likely to be kitty bugs to me. I cannot replicate. I can think of
nothing that could possibly cause one set of keyboard modifiers to
change their performance vs another. If that's happening, its happening
in a layer lower than kitty. Since you can replicate you are welcome to
bisect and see if you can find the commit that is causing the
regression. And run with --debug-keyboard which will show you what key
event are delivered to kitty exactly. You will see that kitty is not
getting the events immediately on your machine.

If I had to guess it will have something to do with something you have
changed on your system and #3463. So bisect and check.

**Comment by bufdev** [comment]
Again to be clear, downgrading to 0.19.3 completely fixed the issue, and upgrading to 0.20.1 recreates it, with no other changes to the system. The only change was the kitty version. I’ll also have others try to reproduce on their macOS machines.

I’ll do more investigation and try bisecting to find the exact commit that introduced this, to help out the project, as I have been a happy kitty user for years and have recommended it to many (and we appreciate your efforts), I am just not sure this should be written off as a non-kitty issue so quickly.

**Comment by kovidgoyal** [comment]
Did you even try running with the command line I posted earlier?

kitty --config NONE -o 'map ctrl+t new_tab' -o 'map ctrl+q close_tab'

and see if you can replicate with that. Thinking about it, this is most likely because of the new global menubar entries for new/close tab, which get handled by the OS, not kitty. For whatever reason on your system they arent performing well.

**Comment by bufdev** [comment]
I will try this tomorrow morning and report back.

**Comment by bufdev** [comment]
This also happens with `kitty --config NONE -o 'map ctrl+t new_tab' -o 'map ctrl+q close_tab'`. I'll do a bisect later.

**Comment by kovidgoyal** [comment]
No need to do a bisect, its pretty clear whats happening. Global menu
shortcuts are slow on your system. Simply add extra shortcuts at the
bottom of kitty.conf to workaround.

For example::

  map ctrl+t new_tab
  map cmd+t new_tab

Now the global menu entry will use cmd+t and ctrl+t should work as
before.
