### ISSUE TITLE
hovering mouse over URL with multiple lines inside a tmux pane

### ISSUE THREAD

**Issue by marconetto** [kovidgoyal/kitty#3559]
It seems when I hover the mouse over a URL with multiple lines inside a tmux pane only the first line of the URL becomes underlined. 

I'm actually not sure if it is a problem with kitty or tmux, given the screenshots below.

**Screenshots**
Kitty0.20.2+tmux3.1c (with two panes, where the problem happens)
![image](https://user-images.githubusercontent.com/7735345/116637632-cf892100-a93a-11eb-8c10-b5cdcf185d28.png)
Kitty0.20.2+tmux3.1c (with a single pane, where no problem happens)
![image](https://user-images.githubusercontent.com/7735345/116637937-956c4f00-a93b-11eb-888b-0345e114e44b.png)
iterm3.3.12+tmux3.1c (with two panes, where no problem happens)
![image](https://user-images.githubusercontent.com/7735345/116637744-1e36bb00-a93b-11eb-89c0-c0411ce89d45.png)

OS: MacOs Big Sur

**Comment by kovidgoyal** [comment]
Presumably iterm2 special cases url detection for tmux, it has a bunch of special integration with tmux. In this case its probably aware of the tmux window geometry and uses that when detecting urls. I'm afraid since I dont think terminal multiplexers are a good idea,  its not something I am particularly interested in implementing, but patches welcome, provided they dont have too much code bloat/performance overhead.
