### ISSUE TITLE
Asian characters rendering problem.

### ISSUE THREAD

**Issue by Menchen** [kovidgoyal/kitty#356]
Asian characters(tested with Chinese and Japanese) are broken.

![screenshot_20180303_004334](https://user-images.githubusercontent.com/6707265/36927151-ed2d7316-1e7b-11e8-9ed3-b2a8570cd6c6.png)

Tried changing the font and still not working.

**Comment by kovidgoyal** [comment]
Asian characters render fine. If they are not rendering on your system, it is because the fallback font your system is using for them is bad. You haven't said what system you are on, so I cant help you more than that. But on linux, for example, with Arial Unicode MS as the fallback font, see attached screenshot. 
![screenshot_20180303_085956](https://user-images.githubusercontent.com/1308621/36930153-52eb9490-1ec1-11e8-89bd-eab87bdf2fac.png)
