### ISSUE TITLE
Extending selection

### ISSUE THREAD

**Issue by vsajko** [kovidgoyal/kitty#358]
Xterm an Urxvt supports extending selection with right mouse click. VTE terminals has similar behavior but with shift+click.
Is it possible to achieve similar behavior in Kitty?

**Comment by kovidgoyal** [comment]
I tried it in gnome-terminal and as far as I can see, all it does is let you extend the current selection, not create disjoint selections. Doesn't seem very useful to me, why not just drag with the mouse to extend the selection? Maybe it's useful with touchpads where dragging is hard? 

Should be a simple patch to implement support for it via shift+click, so I'll leave this issue open in case anyone wants to contribute a patch.

**Comment by vsajko** [comment]
It is simple patch to implement with right-click and I have this almost ready it but I don't like solution with shift+click or ctrl+shift+click.
This requires 2 hands and as such and don't see it it as usable.

Xterm/urxvt  will also distinguish what will be selected with right click based on initial click. If it was double-click, right click will select everything between first 'word' and right-click but right-click will behave like double-click. And this is really useful. 

I know that people from xterm and urxvt use that feature with right click and I don't know any VTE user to use shift+click. I might be wrong, I don't know everybody.

Should this be configurable (shift-click vs right-click), what do you think ?

**Comment by kovidgoyal** [comment]
I'm OK with using right click instead of shift+click. But note that there is an additional complication. When a terminal program is running that has grabbed the mouse, then using shift+click will allow you to make selections using kitty rather than passing the click to the terminal program. So if you want to support right click to extend the seelction, you would also need to support shift+right click in this mode.

**Comment by kovidgoyal** [comment]
Oh and there is also rectangle_select_modifiers to worry about.
