### ISSUE TITLE
Add unscroll to the rc protocol

### ISSUE THREAD

**Issue by resolritter** [kovidgoyal/kitty#3604]
**Is your feature request related to a problem? Please describe.**

Title is self-explanatory. Since there's [scroll-window](https://sw.kovidgoyal.net/kitty/rc_protocol.html#scroll-window) already, I think unscroll will fit as well.

I've tried to use the escape code with `kitty @ send-text` (`kitty @ send-text --match id:$id '\033[3+T'`) but it didn't work; I can open another issue for that if it's interesting. I'd still prefer to use it through the protocol rather than sending the escape code, though.

**Comment by kovidgoyal** [comment]
scroll-window scrolls the kitty viewport, not the actual screen contents, unlike unscroll. What is the actual usecase you are trying to implement? send-text will not work since the unscroll command has to come from the client to the terminal, send text goes from the terminal to the client. You can just do printf with the escape code, assumingyour script is running inside the window you want to unscroll and not elsewhere.

**Comment by kovidgoyal** [comment]
On Sun, May 09, 2021 at 08:57:30PM -0700, João Paulo Silva de Souza wrote:
> > What is the actual usecase you are trying to implement?
> 
> I am trying to unscroll a remote terminal running a Bash shell

That much is fairly obvious :) I meant in what context as part fo what
larger workflow.
