### ISSUE TITLE
listen_on in kitty.conf not taken into account

### ISSUE THREAD

**Issue by Kabouik** [kovidgoyal/kitty#3615]
**Describe the bug**
Unless I misunderstood how this should work, my `listen_on unix:/tmp/kitty` in `kitty.conf` is ignored and generates Python errors when I try using associated features in a new kitty window. Yet starting a new window with `kitty --listen-on unix:/tmp/kitty` works. Should the equivalent option in `kitty.conf` not make it default in every kitty window I open?

**To Reproduce**
1. Add `listen_on unix:/tmp/kitty` in `kitty.conf`.
2. Start a new kitty window.
3. Use features that depend on `listen_on`, like [nnn's preview-tui](https://github.com/jarun/nnn) and see Python errors.
4. Try 3 in a kitty window started with `kitty --listen-on unix:/tmp/kitty` and see no error.

**Expected behavior**
I am sorry if I misunderstood how it works, but I was expecting that my `kitty.conf` `listen_on` option would be default in every kitty window started with no flags.

**Screenshots**
`kitty --debug-config`:
![Screenshot_20210513_001](https://user-images.githubusercontent.com/7107523/118128369-1545ef00-b3fb-11eb-9c01-56817c4cbf21.png)

`nnn preview-tui` in a window started with no flag but `listen-on` set in `kitty.conf`:
![Screenshot_20210513_003](https://user-images.githubusercontent.com/7107523/118128671-81c0ee00-b3fb-11eb-881e-76e253b09216.png)

`nnn preview-tui` in a window started with the `--listen-on` flag:
![Screenshot_20210513_002](https://user-images.githubusercontent.com/7107523/118128711-92716400-b3fb-11eb-9f8d-809c0a7e52cb.png)

**Environment details**
OS: Debian Sid run as a LXC container within SailfishOS; but I observed the same in Solus 4.

```
Output of kitty --debug-config:

kitty 0.19.3 created by Kovid Goyal
Linux debian-sid 4.4.153-perf #7 SMP PREEMPT Mon May 18 10:31:30 UTC 2020 aarch64
Debian GNU/Linux bullseye/sid \n \l
Loaded config files: /etc/xdg/kitty/kitty.conf, /home/user/.config/kitty/kitty.conf
Running under: X11

Config options different from defaults:
active_border_color        Color(red=59, green=60, blue=102)
active_tab_background      Color(red=53, green=53, blue=53)
active_tab_foreground      Color(red=117, green=113, blue=94)
adjust_line_height         1.0
allow_remote_control       y
background                 Color(red=28, green=40, blue=54)
background_image           /home/user/Pictures/Wallpapers/mminimal.png
background_image_layout    scaled
bold_font                  FiraCode Bold
bold_italic_font           FiraCode Bold Italic
click_interval             0.5
color1                     Color(red=249, green=85, blue=95)
color10                    Color(red=52, green=187, blue=153)
color11                    Color(red=255, green=255, blue=85)
color12                    Color(red=88, green=156, blue=245)
color13                    Color(red=231, green=85, blue=152)
color14                    Color(red=57, green=120, blue=187)
color2                     Color(red=32, green=175, blue=137)
color3                     Color(red=253, green=240, blue=41)
color4                     Color(red=88, green=156, blue=245)
color5                     Color(red=147, green=77, blue=149)
color6                     Color(red=30, green=158, blue=230)
color7                     Color(red=187, green=187, blue=187)
color8                     Color(red=84, green=84, blue=84)
color9                     Color(red=250, green=139, blue=142)
cursor                     Color(red=187, green=187, blue=187)
cursor_blink_interval      0.0
font_family                FiraCode-Regular
font_size                  9.0
foreground                 Color(red=255, green=255, blue=255)
hide_window_decorations    1
inactive_border_color      Color(red=43, green=49, blue=54)
inactive_tab_background    Color(red=39, green=40, blue=34)
inactive_tab_foreground    Color(red=117, green=113, blue=94)
italic_font                FiraCode Italic
listen_on                  unix:/tmp/kitty
macos_option_as_alt        3
open_url_modifiers         3
open_url_with              ['firefox']
rectangle_select_modifiers 2
scrollback_lines           4000
scrollback_pager           ['less', '+G', '-R']
select_by_word_characters  -./_~%+#
selection_background       Color(red=180, green=213, blue=255)
selection_foreground       Color(red=28, green=40, blue=54)
shell                      /bin/bash
tab_title_template         {index}:{title}
term                       xterm-256color
update_check_interval      0.0
url_prefixes               ('http', 'https', 'file', 'ftp', 'gemini', 'irc', 'gopher', 'mailto', 'news', 'git', 'www')
Added shortcuts:
	 shift+down KeyAction(func='scroll_line_down', args=())
	 shift+up KeyAction(func='scroll_line_up', args=())
	 control+minus KeyAction(func='decrease_font_size', args=())
	 control+0 KeyAction(func='restore_font_size', args=())
	 control+1 KeyAction(func='goto_tab', args=(1,))
	 control+2 KeyAction(func='goto_tab', args=(2,))
	 control+3 KeyAction(func='goto_tab', args=(3,))
	 control+4 KeyAction(func='goto_tab', args=(4,))
	 control+5 KeyAction(func='goto_tab', args=(5,))
	 control+6 KeyAction(func='goto_tab', args=(6,))
	 control+7 KeyAction(func='goto_tab', args=(7,))
	 control+8 KeyAction(func='goto_tab', args=(8,))
	 control+9 KeyAction(func='goto_tab', args=(999,))
	 control+equal KeyAction(func='increase_font_size', args=())
	 control+d KeyAction(func='scroll_page_down', args=())
	 control+o KeyAction(func='goto_tab', args=(0,))
	 control+t KeyAction(func='new_tab', args=())
	 control+u KeyAction(func='scroll_page_up', args=())
	 control+w KeyAction(func='close_tab', args=())
	 control+left_bracket KeyAction(func='previous_tab', args=())
	 control+right_bracket KeyAction(func='next_tab', args=())
	 control+enter KeyAction(func='new_window', args=())
	 shift+control+d KeyAction(func='scroll_end', args=())
	 alt+t KeyAction(func='set_tab_title', args=())
	 shift+alt+c KeyAction(func='kitten', args=['hints', '--type path --program @'])
	 shift+alt+e KeyAction(func='kitten', args=['hints', '--program @'])
	 shift+alt+i KeyAction(func='kitten', args=['hints', '--type line --program -'])
	 shift+alt+p KeyAction(func='kitten', args=['hints', '--type path --program -'])
	 shift+alt+y KeyAction(func='kitten', args=['hints', '--type line --program @'])
	 control+alt+e KeyAction(func='next_layout', args=())
	 control+alt+t KeyAction(func='new_tab_with_cwd', args=())
	 control+alt+y KeyAction(func='kitten', args=['hints', '--multiple --type line --program @'])
	 control+alt+left_bracket KeyAction(func='move_tab_backward', args=())
	 control+alt+right_bracket KeyAction(func='move_tab_forward', args=())
	 shift+control+alt+i KeyAction(func='kitten', args=['hints', '--multiple --type line --program -'])
	 shift+control+alt+p KeyAction(func='kitten', args=['hints', '--multiple --type path --program -'])
Changed shortcuts:
	 shift+control+b KeyAction(func='show_scrollback', args=())
	 shift+control+u KeyAction(func='scroll_home', args=())
	 shift+control+enter KeyAction(func='launch', args=['--type=window', '--cwd=current'])
	 shift+control+backspace KeyAction(func='send_text', args=['all', b'\x15'])
```

**Comment by kovidgoyal** [comment]
Works fine for me with the following steps:

kitty.conf
```
listen_on unix:@moo
allow_remote_control yes
```

start two kitty instances, run 

kitty @ ls

which uses remote control

command succeeds as expected in both. Doing

env | grep KITTY

shows KITTY_LISTEN_ON is set, as expected, with the socket name modified
by the process PID, so that multiple kitties work. I dont use nnn so cant
comment on that.

**Comment by Kabouik** [comment]
Thanks for the fast answer!

`nnn` was just an example because I know it uses `listen_on` in the described workflow, but I experience the same issue if I do:

```
git clone https://github.com/dexpota/kitty-themes ~/.config/kitty/themes
cd ~/.config/kitty/themes && fzf --preview 'head -n 40 {} && kitty @ --to unix:/tmp/kitty set-colors -a -c {}'; cd -
```
It changes the kitty theme dynamically if I do the second command in a kitty window started with the `--listen-on` flag, but not in a window started with no flag but with `listen_on` set in `kitty.conf`.

I tried doing what you described in your post:

1. Start two kitty windows (`listen_on` and `allow_remote_control` being set in `kitty.conf`).
2. Run `kitty @ ls`.
3. Get the Python errors.
4. `env | grep KITTY` confir,s that `KITTY_LISTEN_ON` is set, but step 3 fails anyway.

**Comment by kovidgoyal** [comment]
When you set listen on in kitty.conf the actual socket name will be
modified with the process PID, otherwise you would have multiple kitties
listening to the same socket which is nto possible. So in your command
dont use --to, its not need, but if you do want touse it useit like
this:

kitty @ whatever --to $KITTY_LISTEN_ON

**Comment by Kabouik** [comment]
There must be something I am misunderstanding (I'm sorry), because I still have the same issue with 

```
 cd ~/.config/kitty/themes && fzf --preview 'head -n 40 {} && kitty @ set-colors -a -c {}'; cd -
```

or 

```
 cd ~/.config/kitty/themes && fzf --preview 'head -n 40 {} && kitty @ --to $KITTY_LISTEN_ON set-colors -a -c {}'; cd -
```

And your simpler example with `kitty @ ls` still fails here.

**Comment by kovidgoyal** [comment]
No clue sorry, I suggest uninstalling the distro kityt which is a still old and using the official binary, https://sw.kovidgoyal.net/kitty/binary.htmlother than that am out of ideas.

**Comment by Kabouik** [comment]
Thanks for your help anyway @koekeishiya.

Unfortunately I cannot use a newer version on this machine because of the dropped support for the now deprecated `wl-shell` (#2897), and my compositor is missing `xdg-shell` (with no possibility to upgrade given my particular combination of OS/LXC/mobile machine). I had tried prior to posting here to compile kitty from master but faced that issue. However 0.19.3 has full support for `listen_on` and `allow_remote_control` and I faced the same issue on another machine running Solus, so I'm wondering if this couldn't be a real bug or conflict with something else.

**Comment by kovidgoyal** [comment]
then I need a way to reproduce, following the steps I posted above works
fine, with current kitty.

**Comment by Kabouik** [comment]
Forget the bit about the same issue in Solus, that machine was still running with an older `kitty.conf` that had unrelated issue. It works on the Solus machine with either 0.20.3 and 0.19.3, and the same config as the machine described above. Apologies for the confusion there.

So there must be something missing or conflicting on that Debian machine. The main differences I can think of is Debian is a LXC container on the machine with the issue, and there is no `xdg-shell` support due to the host system being SailfishOS, but I am not sure that could be related to the issue I described (_i.e._, no problem when using `--listen-on` flag, errors when using only `kitty.conf`'s `listen_on`).

**Comment by Kabouik** [comment]
I had a hardcoded `KITTY_LISTEN_ON=unix:/tmp/kitty` in the `.bashrc` of that machine, for no good reason at all except a plugin I used that once printed an error along the line "Please use KITTY_LISTEN_ON before running this plugin!" when I still had other issues in my `kitty.conf`. So I probably tried to resolve that issue by setting the environment variable directly in my `.bashrc` before I understood how it worked, still had issues because my `kitty.conf` was still not perfect, fixed those latter issues, and then forgot about what I set in my `.bashrc`…

Sorry for the noise @kovidgoyal, it's working perfectly now, even in the Debian LXC container running on SailfishOS. Hopefully my mistake here will be helpful to other kitty beginners struggling with setting up their `kitty.conf` and `listen_on`.

**Comment by fev4** [comment]
This works for me when using
```
listen_on unix:@kitty
```
But then the preview is not rendered correctly, here's an example:

![Selection_363](https://user-images.githubusercontent.com/16828078/150697688-1cf61453-ffc4-46e3-8cc5-d1636fe2e45a.png)

Is there a way to make it render correctly?

**Comment by plum** [comment]
> Not sure if this is still an active issue, but I solved the issue with integration with **nnn's preview-tui** by simply making sure `listen_on` precedes `allow_remote_control` in kitty.conf
> 
> E.g., this works:
> 
> ```
> listen_on unix:/tmp/kitty
> allow_remote_control yes
> ```
> 
> but this does not:
> 
> ```
> allow_remote_control yes
> listen_on unix:/tmp/kitty
> ```

I can confirm this is true for me , running nnn with kitty and preview-tui

**Comment by page-down** [comment]
> ... making sure listen_on precedes allow_remote_control ...
> ...
> but this does not:
> ```
> allow_remote_control yes
> listen_on unix:/tmp/kitty
> ```

It makes no difference which of these two options precedes the other.
Check the environment variable `KITTY_LISTEN_ON` before running nnn.

I can't reproduce this.
Steps I tried:
- Make sure that `allow_remote_control` comes before `listen_on` in the configuration file, and only those two.
- Run kitty
- The environment variable `KITTY_LISTEN_ON` points to the correct UNIX socket.
- Run nnn's preview-tui plugin and the image is displayed normally.

**Comment by plum** [comment]
I appreciate your checks Page-Down.

However, for now I cannot agee. 
I have spent more than a few hours making every conceivable test, and then only discovering the tip here. 
Success straight away, with that simple change.

- I have checked carefully  the environmental variable KITTY_LISTEN_ON target.

BTW. 'listen_on'  entered in kitty.conf is the environmental variable in kitty language I assume; 
- when I  enter KITTY_LISTEN_ON in either bashrc or .profile, the target is not created, and is reported as 'doesn't exist'

## Summary:

configuring kitty preview with nnn:
- 'listen_on' must be configured in kitty.conf
- listen_on' must precede 'allow_remote_control'

The advice at nnn is precisely to enter the listen_on and 'allow__remote_control'  variable in kitty.conf. They do not mention order.
There is some confusion arising , because KITTY_LISTEN_ON variable is variously described as 'listen_on' in kitty language, or as a more global wording 'KITTY_LISTEN_ON'.

- - That is, as it appears to me. 

Many people are led to try this nnn file browser , and I think  it would be kind to get the offered  right , between the two departments, nnn and kitty.
I would vouch for both applications as being  superior , and the combination quite special for productive and enjoyable work in console.

**Comment by plum** [comment]
> This works for me when using
> 
> ```
> listen_on unix:@kitty
> ```
> 
> But then the preview is not rendered correctly, here's an example:
> 
> ![Selection_363](https://user-images.githubusercontent.com/16828078/150697688-1cf61453-ffc4-46e3-8cc5-d1636fe2e45a.png)
> 
> Is there a way to make it render correctly?

I have the same issue. I suspect it is not a kitty issue, however. But cannot be sure.

xdg reports markdown  as being text/plain file association on my system, as it should be.

I wonder if you solved the problem?

**Comment by page-down** [comment]
> Success straight away, with that simple change.

The options will be overridden by later defined entries of the same name or by options from the command line.
Press the default shortcut Ctrl+Shift+F6 to see the options that are actually in effect.

Update to the latest version, start with an empty config file, make sure `kitty @ --to "$KITTY_LISTEN_ON" ls` is working, then check icat kitten. finally troubleshoot nnn's preview-tui plugin.

What you have found is not the root of the problem. I'm curious that this **magical tip** works for you.

> There is some confusion arising ... KITTY_LISTEN_ON ... listen_on ...

These are described in the documentation.

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.listen_on
https://sw.kovidgoyal.net/kitty/invocation/#cmdoption-kitty-listen-on
https://sw.kovidgoyal.net/kitty/glossary/#envvar-KITTY_LISTEN_ON
https://sw.kovidgoyal.net/kitty/remote-control/#cmdoption-kitty-to

@plum
>> ... the preview is not rendered correctly ...
>
> I have the same issue. ...
> I wonder if you solved the problem?

That looks like it's using a pager that doesn't support escape sequences very well, such as an older version of `less`.
Update the `less` in the `PATH` seen by `nnn` to the latest version or replace it with another pager.

@kovidgoyal
When `kitty @ --to` is explicitly specified and the value is empty, should it report an error and exit? Instead of silently falling back to using the escape sequence.

For example, if the default is `--to auto`, when `--to "$EMPTY_LISTEN_ON_HERE"` is specified, it is no longer "auto", there is no more automatic "detect" or "fallback".

**Comment by kovidgoyal** [comment]
On Sun, Feb 19, 2023 at 03:37:52AM -0800, page-down wrote:
> @kovidgoyal
> When `kitty @ --to` is explicitly specified and the value is empty, should it report an error and exit? Instead of silently falling back to using the escape sequence.
> 
> For example, if the default is `--to auto`, when `--to "$EMPTY_LISTEN_ON_HERE"` is specified, it is no longer "auto", there is no more automatic "detect" or "fallback".

IIRC the default is empty. So --to "$EMPTY" should work same as no --to.

**Comment by plum** [comment]
Thank for you r kind cosideration. 
OK I'll investigate that probably next weekend; I need to be sure what you're saying but I'm a little tired now; its hard to understand your statements, although clearly written,   because I lack the necessary familiarity with kitty.  For now, I'm happy.
I'll definitely pursue the matter thoroughly as you suggest,  though, because , as a  long time at console writer, I am sure  this combination is right for me.  

Certainly previewing files helps with copious notes. I also use fzf scripts  for preview and note taking , but nnn is overall especially useful and I shall continue to use both for previews and writing.
I consider this combination an improvement to my work flow, not another try at another way. I have long used vifm and also before that ranger, but shan't be going back.

**Comment by plum** [comment]
>

**Comment by plum** [comment]
@ page-down
Ref: escape sequences and pager:
you're entirely correct. I had switched to more and it was OK. 
My system (on arch) his up to date, including less, no doubt.
Strangely, when such a file is viewed with less directly from the command line, and not through the  nnn, it renders perfectly well.
