### ISSUE TITLE
DejaVu Sans Mono glyph offset rendering issue

### ISSUE THREAD

**Issue by jarcode-foss** [kovidgoyal/kitty#3627]
In kitty (`0.20.3`) font rendering for DejaVu Sans Mono has placement issues for size `10.5`. Issue may persist for other fonts as well.

This appears to be a problem with the font renderer not correctly applying x/y bearing. For reference, FreeType 2 stores these in `bitmap_left` and `bitmap_top` fields from the `FT_GlyphSlot` structure. [See here for documentation](https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_glyphslotrec).

I have personally ran into this issue writing some unrelated UI code for OpenGL that relies on FreeType 2.

You can observe this issue by using the mentioned font/size and typing `HR`; the left bearing is too large on the `H` and causes its rightmost pixels to be aligned directly next to the following `R` (which has no left bearing). I presume this is some sort of off-by-one bug since these values are already provided by FreeType in pixels. [Image here](https://i.imgur.com/Yzy7JeS.png) (ignore web browser; upper left window is Emacs with correct rendering, bottom left and right is Kitty demonstrating the issue in htop and bash prompt).

**Comment by kovidgoyal** [comment]
In kitty the screen is divided into equi-sized cells. Every character is
rendered exactly once and stored on GPU. That is how kitty gets its
performance. The cell width is calculated as the maximum *advance* of
all printable ascii characters in the font, see calc_cell_width() in
freetype.c. The problem here is incorrect metrics in DejaVu Sans Mono.
You can workaround it by using adjust_cell_width in kitty.conf.

**Comment by jarcode-foss** [comment]
I have _personally_ written code that avoids this problem with fixed-width cells for an unrelated application, testing with these exact font settings and the exact same font rendering library. The font is not bugged, the problem is incorrectly applying the `bitmap_left` value (in kitty's case, the total offset is _too_ high just for characters with this value as non-zero, implying an off-by-one bug).

Breaking the font appearance entirely with a global cell width offset is not an acceptable solution for a rendering bug that can be fixed while maintaining fixed cell width (this is one of the most popular monospaced fonts on linux, implying it is bugged with a common ASCII character is a significant charge to make...)

**Comment by jarcode-foss** [comment]
Now that I've looked more closely at the rendering it is almost certainly a _negative_ `bitmap_left` value that kitty seems to completely ignore.

**Comment by jarcode-foss** [comment]
Yup, you are just explicitly ignoring negative values for no apparent reason. See `freetype.c:563`.

This is a bug in kitty, and I presume you have closed many other issues with the false assumption that the font in question is bugged...

**Comment by kovidgoyal** [comment]
Wait, so first, its that kitty is not applying bitmap_left, then its that it is incorrectly applying it, and now its that it is incorrectly applying a negative bitmap_left? Why dont you read the code instead, its all in a couple of functions in freetype.c, start in place_bitmap_in_canvas, where you will see that bitmap_left is indeed being applied, negative or not. Kindly dont assume you are the only person that understands FreeType because you wrote some code for it.

**Comment by kovidgoyal** [comment]
I would love to know how a negative offset is to be applied in a fixed cell, that would imply that the character has to start in the previous cell. Again, this is NOT POSSIBLE in fixed cell rendering. So again, THIS FONT IS A BUGGY POS if it requires characters to be offet into previous cells to be rendered correctly, it cannot be used in fixed cell rendering.

**Comment by jarcode-foss** [comment]
FreeType2 can return negative values for the `bitmap_left` member of ` FT_GlyphSlot`. You are effectively ignoring them. Snippet for reference:

```c
    // Calculate column bounds
    int32_t xoff = (ssize_t)(x_offset + bm->bitmap_left);
    uint32_t extra;
    if (xoff < 0) src.left += -xoff;
    else dest.left = xoff;
    // Move the dest start column back if the width overflows because of it
    if (dest.left > 0 && dest.left + bm->width > cell_width) {
        extra = dest.left + bm->width - cell_width;
        dest.left = extra > dest.left ? 0 : dest.left - extra;
    }
```

`x_offset` can be 0, which makes sense since you're rendering it to a texture. If it is a glyph map, this could mean the character is actually at the edge of the texture, meaning you need to pad your glyph textures to account for negative values here.

**Comment by jarcode-foss** [comment]
Additionally, you should not be baking in glyph offsets into the texture, this is something you'd ideally want to apply when translating the glyph in a shader since you might run into artifacts with glyph overlapping (although perhaps there's a performance reason for this; there's more than one way to go about it).

**Comment by kovidgoyal** [comment]
Yes, there is a performance reason for it, and no, it's not going to
change. Simply use a better monospaced font, that is capable of
rendering characters inside their non-negative bounding boxes.

**Comment by jarcode-foss** [comment]
[This image](https://www.freetype.org/freetype2/docs/tutorial/metrics.png) in the documentation for FreeType 2 demonstrates the actual bounds of the glyph itself and how it is translated for rendering. Many fonts use positive and negative values for both axis; this is completely valid in the strange world of font rendering. Many other terminal emulators (including those with _fixed cell sizes_) avoid this issue by simply applying the translations _correctly_ and allowing the user to configure a pixel or two of padding to the window.

On the performance front, it's worth noting that the majority of programmable-pipeline graphics hardware is capable of translating 2D textures without completely melting down. You even save some texture space by properly packing the glyphs. Upon closer look it seems like most graphics accelerated font rendering uses this straightforward approach, including most web browsers.

Thanks for bothering to reply at least, but I think I'll use a terminal emulator impacted by less programmer stubbornness.

**Comment by kovidgoyal** [comment]
On Sat, May 15, 2021 at 06:40:03PM -0700, Levi Webb wrote:
> [This image](https://www.freetype.org/freetype2/docs/tutorial/metrics.png) in the documentation for FreeType 2 demonstrates the actual bounds of the glyph itself and how it is translated for rendering. Many fonts use positive and negative values for both axis; this is completely valid in the strange world of font rendering. Many other terminal emulators (including those with _fixed cell sizes_) avoid this issue by simply applying the translations _correctly_ and allowing the user to configure a pixel or two of padding to the window.

It's not fixed cell sizes, every cell is rendered INDEPENDENTLY, JUST
ONCE. Therefore the contents of cells cannot overlap each other, which
is what this broken ass font of yours requires to render correctly.

And thanks for the link to the FreeType tutorial, like I'd never
seen it before. Why dont you take the time to understand what you are
speaking off before being so patronizing. 

And yes, lots of fonts use negative values, no font other than this one
needs those negative values to be large enough for one ASCII character
to be rendered inside the previous character's advance box.

> 
> On the performance front, it's worth noting that the majority of programmable-pipeline graphics hardware is capable of translating 2D textures without completely melting down. You even save some texture space by properly packing the glyphs. Upon closer look it seems like most graphics accelerated font rendering uses this straightforward approach, including most web browsers.

Ah ofc, as long as something doesnt cause things to melt, one should
maintain a whole separate array of offsets that will be zero for every
font except this one and then apply it to every cell render on everybody's
GPU, rather than just not using a broken font. But hey, the GPU will not
melt, and who cares about wasted cycles.

> 
> Thanks for bothering to reply at least, but I think I'll use a terminal emulator impacted by less programmer stubbornness.

Feel free. You appear to be extremely wedded to DejaVu Sans.

**Comment by jarcode-foss** [comment]
> It's not fixed cell sizes, every cell is rendered INDEPENDENTLY, JUST
ONCE. Therefore the contents of cells cannot overlap each other, which
is what this broken ass font of yours requires to render correctly.

_Most_ fonts do this. It's how `g` or `j` is rendered below the baseline in most fonts. You just happen to handle this by baking the offset into the glyph texture (which makes the texture larger than it needs to be, _outsizing_ the actual cell), rather than simply copying the texture and rendering translations. Your approach occasionally breaks because you only resize the glyph texture columns in one direction for the X axis.

> Ah ofc, as long as something doesnt cause things to melt, one should
maintain a whole separate array of offsets that will be zero for every
font except this one and then apply it to every cell render on everybody's
GPU, rather than just not using a broken font. But hey, the GPU will not
melt, and who cares about wasted cycles.

I don't know how else to put this (since my sarcasm was missed) but _two additions_ in a fragment shader is probably going to _save_ you performance compared to padding the hell out of individual glyphs in your texture. Modern OpenGL also allows you to be pretty efficient when it comes to uploading arbitrary data for shaders to make use of.

By the way, storing glyph translation data is how most OpenGL font renderers work (alongside glyph coordinates in a texture packed with glyphs). It also would not be _"zero for most fonts"_, because you would be able to also store positive `bitmap_left` and `bitmap_top` values, which would allow you to remove your strange code for dynamically sizing the space reserved for the glyph _and_ the padding to account for offsets.

Insisting fonts are broken when your rendering breaks conventions for how monospaced fonts function in FreeType seems to be a matter of ego. Your insistence that fonts should conform to your naive implementation tells me I should spend my time elsewhere, since a PR will clearly be ignored.

**Comment by kovidgoyal** [comment]
On Sat, May 15, 2021 at 08:21:54PM -0700, Levi Webb wrote:
> > It's not fixed cell sizes, every cell is rendered INDEPENDENTLY, JUST
> ONCE. Therefore the contents of cells cannot overlap each other, which
> is what this broken ass font of yours requires to render correctly.
> 
> _Most_ fonts do this. It's how `g` or `j` is rendered below the baseline in most fonts. You just happen to handle this by baking the offset into the glyph texture (which makes the texture larger than it needs to be, _outsizing_ the actual cell), rather than simply copying the texture and rendering translations. Your approach occasionally breaks because you only resize the glyph texture columns in one direction for the X axis.

Your broken ass font requires rendering into a *neighboring cell*. This
has absolutely nothing to do with handling of baselines. We are talking
displacement OUTSIDE THE BOUNDING BOX OF THE CELL. Not displacement
WITHIN THE CELL. And for the record, the actual cell includes the space
below the baseline, that's where underlines are drawn.

Using variable sized textures to save a few pixels per sprite requires a
ton of code, since one then has to pack those textures somehow into an
atlas, which is a pretty hard problem to do optimally. For a few hundred
sprites, in the common case it is completely not worth it. And it
requires extra GPU computation on top of it for placing the sprite *on
every single render* whereas pre-positioning the sprite inside the cell
requires that computation *once*.  And yes, I know this extra
computation wont cause the GPU to melt thank you very much. But the fact
remains that the tradeoff is not worth it in my opinion. If you want to
change my mind, post some numbers, not hand waving.

And for that optimization, one broken ass font renders one glyph
sub-optimally. Boo hoo. Use a better font.


> 
> > Ah ofc, as long as something doesnt cause things to melt, one should
> maintain a whole separate array of offsets that will be zero for every
> font except this one and then apply it to every cell render on everybody's
> GPU, rather than just not using a broken font. But hey, the GPU will not
> melt, and who cares about wasted cycles.
> 
> I don't know how else to put this (since my sarcasm was missed) but _two additions_ in a fragment shader is probably going to _save_ you performance compared to padding the hell out of individual glyphs in your texture. Modern OpenGL also allows you to be pretty efficient when it comes to uploading arbitrary data for shaders to make use of.

I like the probably and pretty weasel words there :)) Do a benchmark and
post some numbers. 

> 
> By the way, storing glyph translation data is how most OpenGL font renderers work (alongside glyph coordinates in a texture packed with glyphs). It also would not be _"zero for most fonts"_, because you would be able to also store positive `bitmap_left` and `bitmap_top` values, which would allow you to remove your strange code for dynamically sizing the space reserved for the glyph _and_ the padding to account for offsets.

Again, if you think it can be done in a performant and robust fashion, I
eagerly await the PR with performance numbers.

> 
> Insisting fonts are broken when your rendering breaks conventions for how monospaced fonts function in FreeType seems to be a matter of ego. Your insistence that fonts should conform to your naive implementation tells me I should spend my time elsewhere, since a PR will clearly be ignored.

Right you have one broken font that you have now nicely elevated to a
"convention". And for the record, feel free to send a PR. If it
demonstrates your "probable" performance improvement and works with
CoreText as well as FreeType and doesn't break rendering for fonts other
than your pet font, I will most definitely consider it.

**Comment by kovidgoyal** [comment]
Oh and if you do decide to work on a PR remember to ensure that the contents of a cell *never* bleed into neighboring cells, as this is a hard requirement for me.
