### ISSUE TITLE
Fcitx5 works under X11 but not Wayland

### ISSUE THREAD

**Issue by zeertzjq** [kovidgoyal/kitty#3642]
**Describe the bug**
Fcitx5 works under X11 but not Wayland.

**To Reproduce**
1. Have Fcitx5 running.
2. Run kitty with environment variable `GLFW_IM_MODULE=ibus` under Wayland.
3. Fcitx5 doesn't work.

**Environment details**
OS: Arch Linux
DE: Plasma 5.21.5
kitty: 0.20.3

**Additional context**
Problem exists with `kitty --config NONE`.
Fcitx5 works with `linux_display_server x11` or under X11.

**Comment by kovidgoyal** [comment]
On wayland kitty uses the wayland text input protocol, not dbus. I'm
guessing fcitx5 either doesn't support that yet or need to have it
configured. See #3410

**Comment by wengxt** [comment]
No, the issue is compositor need to support text input. IME doesn't use text-input, but zwp_input_method. Compositor acts as a bridge between text input and zwp_input_method

But the protocol is not in a good shape anyway, so no wonder it's in a poor state.

@kovidgoyal Would you mind adding support the dbus based protocol under wayland? Even for ibus case,  SetCursorLocationRelative could be used to report cursor location and that could at least allow people to type.

**Comment by wengxt** [comment]
Also, fcitx5's dbus allow client to render the input window on the client side, if you'd like to add fcitx support to kitty, this is also useful for wayland case: https://github.com/fcitx/fcitx5-qt/blob/0d0eb237a6e5a5d7424945b5a5623360c1d5e544/qt5/dbusaddons/interfaces/org.fcitx.Fcitx.InputContext1.xml#L68

I think ibus might also have similar thing but I'm not sure.

**Comment by kovidgoyal** [comment]
Not something I am interested in. Given that Wayland has an official way
to do text input, it's crazy for ever application to carry around dbus
based support for it. 

That said, if you wish to work on it, feel free. As long as it does not
conflict with text-input and is optional, I am willing to accept a PR.
