### ISSUE TITLE
Line height affected by how À looks like

### ISSUE THREAD

**Issue by Tosche** [kovidgoyal/kitty#3658]
I'm a font designer and got a complaint that a combination of certain fonts and Kitty results in a strange spacing of line highlight. Upon investigation, I noticed that Kitty seems to look at one particular glyph in a font (À, Agrave, U+00C0) and compares its shape with how hheaAscender is set. If the former is higher than the latter, Kitty seems to add some amount of space at the bottom of the line.

This is a pretty non-standard way of determining a line height and no other editor does this in my knowledge. Could this calculation be changed to simply look at hheaAscender?
![FontLineHeightBug](https://user-images.githubusercontent.com/5482424/119853564-397bf280-bf08-11eb-8f76-98e1e6aa35c1.jpg)

**Comment by kovidgoyal** [comment]
No, kitty doesn't do that. I am guessing you are on macOS, on macOS kitty creates a string containing only ASCII characters  "AQWMH_gyl " repeats it several times and renders it using CoreText. The cell height is then calculated as the difference in the origins for two consecutive lines. I dont know why CoreText is rendering your font with an incorrect line height, you would need to ask Apple that.

The relevant code in kitty is cell_metrics() in core_text.m, see for yourself.

**Comment by Tosche** [comment]
If Apple was in the wrong, Kitty shouldn't be the only app with the misbehaviour, yet it is. Using random characters in a font to determine the line height is inadvisable nonetheless.

I'm not familiar with any C-related languages, but using these values should be the right approach, shouldn't it?
https://developer.apple.com/documentation/coretext/ctfont-q6r

CTFontGetAscent(theFont);
CTFontGetCapHeight(theFont);
CTFontGetDescent(theFont);
CTFontGetLeading(theFont);

**Comment by kovidgoyal** [comment]
No, it's not. The goal of the current code is to get the same line
height as native cocoa rendering would give you. The line height will be
the same in *any* application that uses cocoa to render text. If I had
to guess the cause for your font's issues, it is because you are
defining some glyphs that are taller than most other glyphs and cocoa is
detecting that and adjusting line height to make sure they fit.

And the issue is showing up in kitty, because as is usual for Apple's
half-assed APIs, while one can interrogate the line height using the
method kitty uses, there is no way to interrogate for the adjusted
*baseline*, so kitty uses just CTFontGetAscent() for that, and that
knows nothing about CoreText's line height fiddling based on its scan of
all glyph bounding boxes in the font. One could in theory check the
difference between the line height used by CoreText and the line height
based on the font's declared metrics and use that difference to adjust 
the baseline, but that have never been needed for any font I have ever
come across.

Simply correct the bounding box heights of the glyphs in your fonts and
the issue will be fixed.

**Comment by Tosche** [comment]
> The line height will be the same in any application that uses cocoa to render text.
I disagree. Same font shown in Terminal and TextEdit that use Cocoa of course, and line spacings look fine. Changing to a test font with different À does not affect their line height (whereas it does on Kitty).
<img width="691" alt="スクリーンショット 2021-05-27 18 10 05" src="https://user-images.githubusercontent.com/5482424/119868335-d180d880-bf16-11eb-9190-b86feb812d73.png">

And I tested with a bunch of other fonts and apps. Most apps use fonts' internal values (apart from Kitty) and the height of certain character will not affect line height. It seems pretty clear to me that Kitty is doing extra that is not quite necessary.

**Comment by kovidgoyal** [comment]
On Thu, May 27, 2021 at 01:08:48PM -0700, Toshi Omagari wrote:
> > The line height will be the same in any application that uses cocoa to render text.
> I disagree. Same font shown in Terminal and TextEdit that use Cocoa of course, and line spacings look fine. Changing to a test font with different À does not affect their line height (whereas it does on Kitty).
> <img width="691" alt="スクリーンショット 2021-05-27 18 10 05" src="https://user-images.githubusercontent.com/5482424/119868335-d180d880-bf16-11eb-9190-b86feb812d73.png">

Look at the code, or write your own code to do it and you will see
CoreText is adjusting the line height when using your font so that it 
does not match the font's declared metrics.

Let me simplify it for you. Your font has declared metrics of ascent N
units. The problematic glyph has a ascent of N + delta units. As a result
CoreText is calculating the line height for your font as N + delta +
descent instead of N + descent. 

Fix the problematic glyph to fit within the declared max ascent of your
font, or change the declared max ascent to accomadate that glyph, then
CoreText will not feel the need to monkey with your fonts metrics and it
will work fine in kitty.
