### ISSUE TITLE
Remote control -a or --all doesn't work

### ISSUE THREAD

**Issue by Davincible** [kovidgoyal/kitty#3678]
Applying remote control options with the all flag only applies it to the current kitty window, instead of all kitty windows as is supposed to. I have tested with the set colors option, and the set opacity option, but both only change it in the current window.

`kitty @ set-background-opacity --all 0.2`
`kitty @ set-colors -a -c /home/tyler/.config/kitty/colors-kitty.conf`

Tested both with my own config, and `kitty --config NONE  -o allow_remote_control=yes -o dynamic_background_opacity=yes`

running `5.12.2-1-MANJARO, kitty 0.20.3`

**Comment by kovidgoyal** [comment]
Works fine for me. Note that remote control will work for all windows in
*one kitty process*. Not all kitty processes. If you are creating
multiple kitty windows by running kitty each time, use
--single-instance.

**Comment by Davincible** [comment]
Ahh I see, with that option it does work. Does using that option have any performance implications?

**Comment by Luflosi** [comment]
Yes, it should make all but the first launch faster and use less memory.

**Comment by Davincible** [comment]
What's stopping you from setting it as the default option then? So far I have only heard positive things about using this :)

**Comment by kovidgoyal** [comment]
On Tue, Jun 01, 2021 at 08:26:46AM -0700, David Brouwer wrote:
> What's stopping you from setting it as the default option then? So far I have only heard positive things about using this :)

It's unexpected behavior. You typically expect invoking a program
multiple times to open multiple instances. But if you prefer this
behavior, alias kitty to it in your system.

And it's not all roses, having all terminal windows in a single process
means that a crash will take them all down, and if one terminal has a
program that is spewing a lot of output it can potentially slow down all
the rest of the terminal windows, since kitty doesn't use a unique thread
per window, just a single thread for I/O and one for rendering.

**Comment by Davincible** [comment]
Hmm that makes sense. I'd prefer not using single instance in that case, and noticed you can use sockets to still send control messages to kitty instances. However, every kitty instance needs their own unique socket, and you subsequently need to send your messages to all sockets, and any regex pattern like `--to /tmp/kitty*.sock` doesn't work. 

What would you suggest in this situation? I only need to control colors/opacity, and sockets work, but they only seem to be single instance

**Comment by Davincible** [comment]
But how do you open sockets dynamically? You can't just hardcode one socket as only one instance can connect to that

**Comment by kovidgoyal** [comment]
Read the documentation of listen_on, it will tell you what pattern the
socket filenames take. Enumerate them using ls pattern* in you script.
