### ISSUE TITLE
Different colors and transparency for different programs

### ISSUE THREAD

**Issue by sujay1844** [kovidgoyal/kitty#3691]
I like transparency in the terminal. But I don't want transparency when I'm using vim or neovim. 
Is there any way to do this in kitty?? I've never heard of any terminal emulator that does this.

**Comment by Luflosi** [comment]
I think all you need to do is change the background color setting of vim and neovim ever so slightly, so that it is not the same as the background color setting in kitty. This should cause kitty to not render transparency in these programs.

**Comment by sujay1844** [comment]
I've been doing that only for the past few days. But that doesn't render the exact color.
Example, my vim colorscheme's background is #282C34 but kitty renders it as #262626

**Comment by Luflosi** [comment]
> but kitty renders it as #262626

How did you determine this color?

**Comment by sujay1844** [comment]
I updated that comment with a picture

**Comment by sujay1844** [comment]
> How did you determine this color?

With a colorpicker ofc

**Comment by Luflosi** [comment]
It works for me. My vim colorscheme sets the background color to `#272822`. If I start kitty with `kitty --config=NONE -o background='#272822' -o background_opacity=0.0`, I get a transparent window, even when vim is running. If I change one of the colors a tiny bit, e.g. `kitty --config=NONE -o background='#272722' -o background_opacity=0.0`, the background becomes opaque when launching neovim.
Using color pickers will not necessarily give you the color you specified because of things like color correction. This is also the case for web browsers AFAIK. I don't know where the huge difference between the left and right window is coming from.

**Comment by sujay1844** [comment]
Transparency is not fully gone. If you can see the edge of the kitty window, you can see my wallpaper. Not sure if it's visible in the screenshot though

**Comment by rinkjames** [comment]
I _just_ posted an issue that seems too tie into this #3692

**Comment by Luflosi** [comment]
> If you can see the edge of the kitty window, you can see my wallpaper.

This is the padding or margin around the window. You can try setting `window_margin_width` and `window_padding_width` to zero (this is the default) but that will probably still leave a gap of smaller than one cell because the available space cannot be divided perfectly into a whole number of cells. The "trick" I told you works by making vim set the background of every cell so that it is a little different than the background color of kitty. The padding or margin does not belong to any cells and so is not affected by this.

**Comment by kovidgoyal** [comment]
Indeed, @Luflosi  is correct. kitty will render background colors that are the same as its background as transparent. This is done for compatibility with old terminal programs that explicitly use a background color instead of using the "default" color. A common example of such a program is alsamixer.

Thanks to this behavior that is, as far as I know, unique to kitty, you can indeed have some programs transparent and others not transparent, by adjusting the background colors those programs use, accordingly. 

As for window margin and padding their colors are not affected by the color of the terminal program, and so they will remain transparent.

However, all this is somewhat hacky. If you dont want nvim to be transparent, enable remote control in kitty and write a wrapper script that uses remote control to change the transparency in the kityt window before launching nvim and that restores it after nvim quits. Use that wraper script to run nvim. Or maybe nvim has some way to specify escape codes to send the terminal at startup/shutdow, I know vim does, not familiar with nvim.
