### ISSUE TITLE
Don't require glew 2.0

### ISSUE THREAD

**Issue by remyabel** [kovidgoyal/kitty#37]
This is an extension of https://github.com/kovidgoyal/kitty/issues/36

The [general changes ](http://glew.sourceforge.net/log.html) added by glew 2.0 (aside from extensions that are not used in kitty) are:

> Enhancements:
> 
> - Forward context support added
> - OSMesa support added
> - EGL support added
> - MX support discontinued
> - Improved cmake build support 

The top three are OSX specific. If I change setup.py to only require 1.13.0 and implement the patch in my previous issue where the window hints are only applied for `isosx` it works perfectly fine on my system.

**Comment by kovidgoyal** [comment]
I'm not sure what the minimum required version of glew is, I do know that everything works with glew 2.0. And as mentioned on #36 those tests are not OS X specific. I prefer kitty fail with a clear and comprehensible error at build time rather than either not function correctly or fail with a cryptic error message at run time. Initially, I had no hard requirement on glew >= 2.0, but there was somebody for whom kitty failed at runtime with an older version of glew installed. And annoyingly it failed with the error

```
RuntimeError: OpenGL is missing the required ARB_copy_image extension
```

so it was not at all clear that an outdated version of glew was to blame.
