### ISSUE TITLE
Variable font axis setting support

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3711]
Some modern programming fonts, such as JetBrains Mono, come in variable font format. See <https://github.com/JetBrains/JetBrainsMono/tree/master/fonts/variable>.

This is cool because it allows fine grained control of how bold you want your bold to be, beyond distributed masters.

[Incosolata now also has a variable font.](https://v-fonts.com/fonts/inconsolata) One of my favorite things about it is that it also has a width axis, so you can make bold wider as well if you wish, or make both wider.

Would you accept a patch in the genre of #2248 to allow setting variable font axes when specifying `font_family` etc? This would make Kitty very modern indeed.

**Comment by kovidgoyal** [comment]
In principle, yes.

**Comment by kovidgoyal** [comment]
Note that the var branch has support for both variation axes and font features and a UI for configuring them. However the UI still needs some polishing/finishing. I will open an RFC issue asking for feedback when it is ready. Closing this issue in favor of that one (I will make a post here as well when that issue is actually opened).

**Comment by kovidgoyal** [comment]
There are some screenshots of the font configuration UI here: https://github.com/tonsky/FiraCode/issues/1591

**Comment by kovidgoyal** [comment]
Merged into master, follow-up on #7570
