### ISSUE TITLE
DECDMAC / DECINVM ?

### ISSUE THREAD

**Issue by ctrlcctrlv** [kovidgoyal/kitty#3737]
The [libsixel](https://github.com/libsixel/libsixel) documentation, (specifically the man page for `img2sixel`,) refers to [DECDMAC](https://vt100.net/docs/vt510-rm/DECDMAC.html) and [DECINVM](https://vt100.net/docs/vt510-rm/DECINVM.html) as possible ways to store a libsixel image in resident memory and restore the image later, similar to Kitty's system of image ID's.

However, DECDMAC and DECINVM seem to be able to store _any_ string for later execution for an indefinite period.

Two questions:

1. should this be implemented in general?
2. should this be implemented in the upcoming patch for #2511 ?
    1. if yes, should they be limited to SIXEL graphics or implemented for _all_ strings?
    2. if they should be implemented for all strings, is that a security problem?

**Comment by kovidgoyal** [comment]
On Wed, Jun 16, 2021 at 01:41:03PM -0700, Fredrick Brennan wrote:
> 1. should this be implemented in general?

Possibly, though I dont know of anything that uses it, so why?

> 2. should this be implemented in the upcoming patch for #2511 ?

I dont think this is a suitable mechanism for storing images, at least
without modification. The VT510 had a 6 KiB limit on macro size. That
would need to go. The macros would have to be cached to disk just like
existing graphics are. Since this is a general mechanism, not an image
specific one, it would need to use a dedicated disk cache. 

Do any terminal emulators currently implement this? If so it might be worth
considering, otherwise its just a bunch of extra code for something that
would not be used anyway. The whole point of implementing sixel support
is for ecosystem compat, if nothing in the ecosystem uses this, why
bother?

Using these as s storage mechanism for images is definitely sub-optimal,
for example, if you clear the screen the stored images are not removed,
unlike with the graphics protocol.

**Comment by kovidgoyal** [comment]
Closing but if you have reasons for implementing, feel free to discuss.

**Comment by ctrlcctrlv** [comment]
Thanks for taking the time to write a detailed reply. I appreciate it.

Mostly I was curious. I noted that `img2sixel` provides support for this mode. I note also, that mlterm supports this. If you try:

```bash
printf '\033P1;0;0!zecho ls;ls\x0a\033\' && printf '\033[1*z'
```

You receive in the window `echo ls;ls`. Note, though, that this is just printed to you as output, if you press return, neither command runs.

I also note that if I run `img2sixel ~/Workspace/libsixel/images/logo.png -u -n 2` and then DECINVM 2, I receive image as I expect:

![image](https://user-images.githubusercontent.com/838783/122316118-4b3e2d80-cee9-11eb-84d6-becbc73f3ab4.png)

You know I like Kitty to have the most features. If there's a sequence we don't support, I like us to support it. So, mlterm is ahead of us in this regard. I wonder if other terminals will implement these. It seems that people may consider it a requirement for a full libsixel integration, even though I confirmed it does not work on xterm.

**Comment by kovidgoyal** [comment]
Well, if support for this gets widespread I will be willing to re-consider, as it is, its just another hack on top of sixel, that I am not particularly keen to implement, since it is fairly complex, requiring disk caching etc. to be done right. And kitty already has a superior solution for it.

**Comment by ctrlcctrlv** [comment]
No problem, thanks for your advice. This jumped out at me as potentially dangerous as well. mlterm is not implementing it "correctly" if the goal is to properly implement a DEC terminal. A DEC terminal would have executed "ls; echo ls".

**Comment by schrmh** [comment]
Regarding support in xterm, I wrote to Thomas Dickey and mentioned the comment with the printf and he answered that ,,xterm doesn't support macros -", gave a link to https://vt100.net/emu/dcsseq_dec.html and also wrote that he also wrote that xterm doesn't support it ,,because until this bug report, I've seen no programs that attempt to use it.".

Btw. when you click on my mention of this issue just above this comment you will get to a comment that includes another thing where img2sixel can make use of that stuff — when you want to play gifs from the internet in your terminal (saitoha published a video regarding this a few years ago).
