### ISSUE TITLE
Rendering bug for groups of letters

### ISSUE THREAD

**Issue by dolmen** [kovidgoyal/kitty#3857]
**Describe the bug**

After a few weeks of use (kitty process started almost one month ago, used daily) I suddenly have input and output issues with *some* groups of letters which are rendered as spaces.
Here is the non-exhaustive list of letters affected (grouped with comma as consecutive characters in ASCII order):
* `!`
* `&`
* `*+`
* `@A`
* `E`
* `G`
* `IJ`
* `LMN`
* `PQRS`
* `U`
* `WY`
* `Z[\]`
* backquote
* `{`
* `}`
(see screenshot below).

If I start a new kitty process, it doesn't have this issue, so it looks like a state bug.

This is not an input problem. Verified by typing `echo "A" | od -x`, or by typing `echo "A"` (which render as empty line) and copy-pasting which correctly gives an `A` in the clipboard.

All tabs are affected.

**To Reproduce**
I have no idea how to reproduce this.

But **I keep my terminal open if you want me to do some diagnostics on the live process** (2021-07-23).

**Screenshots**
Here is the output of `man ascii`
![kitty-bug-uppercase-compressed](https://user-images.githubusercontent.com/129536/126760288-add3906f-422b-4302-a525-dc6e01da6607.png)

**Environment details**

kitty 0.19.3 on MacOS (via homebrew)

```
allow_remote_control socket-only
listen_on unix:/private/tmp/kitty-{kitty_pid}

font_family Fira Code Retina
font_size 12.0


font_features FiraCode-Retina +zero +onum

symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

# == Window layout ==========================================
remember_window_size  yes

editor vim

# == MacOS ==================================================
macos_quit_when_last_window_closed yes
macos_show_window_title_in all
confirm_os_window_close 1

tab_bar_edge top
tab_bar_style powerline

macos_thicken_font 0.75
```

**Additional context**

**Comment by kovidgoyal** [comment]
First update kitty, you are using a very old version. 

Second how do you know this is caused by kitty being long running, as
opposed to something triggerring a bug? Does it regularly happen after
leaving kitty open for a month or more. I do that as a matter of course
(although on Linux not macOS) and have never seen this.

**Comment by dolmen** [comment]
I don't know if this caused by long running. I can remove that from the title.

But I just try to give all the circonstances of this bug which I have no idea on how to reproduce.

**Comment by kovidgoyal** [comment]
I suggest you update kitty first. Then try to reproduce this bug. If it
happens again, note the circumstances. Once you are sure it's not a one
off, run kitty with --dump-bytes and post the dump file after
reproducing again. I can try to reproduce with that data. Note that with 
--dump-bytes you need to reproduce in a single kitty window, as
otherwise the dump bytes output will be meaningless. 

At the moment, its far more likely to me to be a one off or something
already fixed. So if you can repro with up to date kitty, ping me and I
will re-open.
