### ISSUE TITLE
Set WM_COMMAND for fancy session managers

### ISSUE THREAD

**Issue by irb** [kovidgoyal/kitty#3885]
I'm not an expert in the X11 protocol or KDE Plasma session management, but I am trying to replace urxvt with kitty and have found that, while rxvt, urxvt, and xterm all get restored when logging in to a saved session, kitty (or alacritty for that matter) do not. It appears that this might be because kitty doesn't set the WM_COMMAND property like older terminals do, meaning that I have to manually start, place and resize about 20 terminal instances across 12 desktops every time I log in. If I'm not mistaken, KDE saves the contents of WM_COMMAND to its session file (and I would presume GNOME would do something similar).

I've had minimal luck in just scripting the layouts I want, because there doesn't appear to be a way to tell KDE which desktop to start each terminal on from a script. 

If there's a better way to accomplish this of course I'm all ears.

**Comment by kovidgoyal** [comment]
dup of #1197

kitty already has the ability to define sessions, see https://sw.kovidgoyal.net/kitty/overview/#startup-sessions

However, this does not have the ability to specify desktops for OS
windows, since I dont know of a robust cross window manager way to do
that. For that I suggest using a more scriptable window manager.

**Comment by kovidgoyal** [comment]
Oh and as for scripting kwin, am fairly sure wmctrl works with it.
