### ISSUE TITLE
kitty.actions#get_all_actions is returning a KeyError

### ISSUE THREAD

**Issue by fladson** [kovidgoyal/kitty#3900]
**Describe the bug**
```
from kitty.actions import get_all_actions

get_all_actions()

*** KeyError: 'win'
```

**Environment details**
```
kitty 0.22.2 
```

**Comment by kovidgoyal** [comment]
It doesn't return an error for me running from master

```
kitty +runpy 'from kitty.actions import get_all_actions; get_all_actions()'
````

**Comment by page-down** [comment]
I can confirm that this works in the v0.22.2 version built from source, but not with the release version.

from src tag v0.22.2
```shell
$ git checkout v0.22.2
$ make
$ ./kitty/launcher/kitty --version
kitty 0.22.2 created by Kovid Goyal
$ ./kitty/launcher/kitty +runpy 'from kitty.actions import get_all_actions; get_all_actions()'
```

from v0.22.2 release (macOS)
```
$ kitty --version
kitty 0.22.2 created by Kovid Goyal
$ kitty +runpy 'from kitty.actions import get_all_actions; get_all_actions()'
Traceback (most recent call last):
  ...
  File "lib/python3.9/kitty/actions.py", line 64, in get_all_actions
KeyError: 'win'
```

After troubleshooting, it seems that `is_action` returns `False` in the release version because the function `__doc__` is missing.

https://github.com/kovidgoyal/kitty/blob/v0.22.2/kitty/actions.py#L39
```python
    def is_action(x: object) -> bool:
        doc = getattr(x, '__doc__', '')
        return bool(doc and doc.strip().startswith('@ac:'))
```

from src tag v0.22.2
```shell
./kitty/launcher/kitty +runpy 'import inspect; from kitty.window import Window; is_action = lambda x: (bool(getattr(x, "__doc__", "") and getattr(x, "__doc__").strip().startswith("@ac:"))); print([x[0] for x in inspect.getmembers(Window, is_action)]);'
```
result: `['copy_and_clear_or_interrupt', 'copy_or_interrupt', ...]`

from v0.22.2 release (macOS)

result: `[]`

```
$ kitty +runpy 'import inspect; from kitty.window import Window; print([x[0] for x in inspect.getmembers(Window, lambda x: (bool(getattr(x, "__doc__", ""))))]);'
['__class__', '__delattr__', '__dir__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']
```

**Comment by kovidgoyal** [comment]
yes, the binary builds dont contain docstrings for efficiency. So this
function will not work there.

**Comment by fladson** [comment]
Thanks for the help guys, I will use that to run it.

**Comment by fladson** [comment]
hey @kovidgoyal I did what you suggested but I am getting a different error now, any idea why?
![Screenshot 2021-08-04 at 20 26 29](https://user-images.githubusercontent.com/554507/128234705-3e266c56-64cb-4abd-9df9-136ce90b7d49.png)

Should I source a different directory? Root level didn't work as well.
![Screenshot 2021-08-04 at 20 27 19](https://user-images.githubusercontent.com/554507/128234838-d2dfa4f8-b65f-45ca-bb73-b21dd5af13a6.png)

**Comment by kovidgoyal** [comment]
The root directory is the correct one. But I was wrong this wont work, since the binary build will run with optimize hardcoded, the python runtime discards the doc strings anyway. For the time being you will need to actually build from source and run, I will think about the best way to make this work in binary builds.

**Comment by kovidgoyal** [comment]
And this fixes it: https://github.com/kovidgoyal/kitty/commit/276a82d1f7edaadba5998575d87b78375ec9bb00

**Comment by fladson** [comment]
Now it is running, thanks for the help!
