### ISSUE TITLE
Window buttons missing on kitty terminal

### ISSUE THREAD

**Issue by skulldealer** [kovidgoyal/kitty#3942]
**Describe the bug**
Window buttons missing on gnome 40

**To Reproduce**
1. On gnome 40, fedora(Wayland I guess)
2. Install kitty

**Screenshots**
![1629188572386388841873321647759](https://user-images.githubusercontent.com/77295140/129690959-462285bf-ea60-4c40-894e-8b1dd81feb54.jpg)

**Environment details**
![16291887137227302079252003680199](https://user-images.githubusercontent.com/77295140/129691330-7c5e2ae0-5e0c-4e51-97c2-528a8cf496f1.jpg)

**Additional context**
`kitty --config NONE` shows the same problem.

**Comment by kovidgoyal** [comment]
dup of #3824

**Comment by skulldealer** [comment]
Hello Sir, I am not able to solve this issue. I am new to linux and terminal.

Should I add this in kitty.conf?

kitten_alias hints hints --alphabet qfjdkslaureitywovmcxzpq1234567890

**Comment by kovidgoyal** [comment]
Sorry that should be #3284

**Comment by metanoia1980** [comment]
IM having the same problem with GNOME on Debian 12, no buttons, and titlebar is also white despite the whole theme being dark

**Comment by berlisuharmanto** [comment]
> Hello Sir, I am not able to solve this issue. I am new to linux and terminal.
> 
> Should I add this in kitty.conf?
> 
> kitten_alias hints hints --alphabet qfjdkslaureitywovmcxzpq1234567890
> 
> Or should I use
> 
> KITTY_ENABLE_WAYLAND=1

Ey mate, if you still wonder how to fix it, I think I just found it. I thought something weird that I have my top bar on my kitty installation on my pc but not on my laptop eventho I use same distribution (I m on ubuntu 24 with Gnome 46  btw). 

Just search on google like you want to install kitty on the first place. Then open "Install Kitty", on the top of the page you will find Binary Install. Just slap copy paste the curl to your terminal and it will open your kitty with top navigation bar, simple right? No, its STILL NOT DONE YET, because when you close it you can't reopen it with terminal or even app center. You need to follow "Desktop Integration on Linux", just follow and copy all the commands then you will find kitty already installed on your distro cool right?

Hope this will help you :)

**Comment by adityadewhy** [comment]
# OS specific tweaks
linux_display_server x11

# Window decorations - show title bar with buttons
hide_window_decorations no
window_decorations full

keep these settings and it will work, seems to me that when the display server is system(it detects wayland if true) or wayland, it just simply doesnt work, i have tried fixing it via gnome tweaks but no luck. but the above 3 lines brought the 3 buttons to my title-bar
