### ISSUE TITLE
[MacOS/arm64] Setting a new theme quits kitty.app

### ISSUE THREAD

**Issue by Dekker1** [kovidgoyal/kitty#3952]
**Describe the bug**
When I use the new `themes` kitten, the kitty program crashes. It does not seem to matter whether I set the theme interactively or directly in the command. When starting kitty again, the theme is correctly set.

(This bug might be related to MacOS, or the fact that this is a M1 machine, but I have no way to verify this).

**To Reproduce**
1. Open kitty.app on MacOS
2. run `kitty +kitten themes Nord`
3. Kitty program quits.

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Darwin Phosphorus.local 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:27 PDT 2021; root:xnu-7195.141.2~5/RELEASE_ARM64_T8101 arm64
ProductName:	macOS ProductVersion:	11.5.2 BuildVersion:	20G95

Config options different from defaults:
```

**Comment by kovidgoyal** [comment]
It will be because signal handling of SIGUSR1 is not working on macOS
probably because it needs some special non-POSIX code for it. I will
look into that when I am next on a mac machine. 

In the meantime, use --reload-in=none and manually reload the config by
pressing the shortcut for it.

**Comment by Dekker1** [comment]
Thank you. What is the shortcut to reload the configuration?

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/

**Comment by kovidgoyal** [comment]
And ^+⌘+f5 on macOS

**Comment by fladson** [comment]
Hey @kovidgoyal that workaround is working fine, I just wanted to know if there is a way to reload the config in a "non-interactively" way.
Is it possible to send the key combination as input and make kitty execute the correspondent action (`kitty @ cmd+control+,`? Or can I include the `load_config_file` in the list of actions, so I can put `kitty @ load_config_file` in a bash script for example?

**Comment by kovidgoyal** [comment]
You just have to wait for the next release with the fix. IIRC reloading config file is not a remote control action.

**Comment by TheFoolishPupil** [comment]
I have the same issue mentioned here, however I had been reliably using `kitty-theme -t -L` in conjunction with launching kitty via `/usr/local/bin/kitty -o allow_remote_control=socket-only --single-instance --listen-on unix:/tmp/kitty` to enable switching between two themes on the fly. I'm now getting that the `kitty-theme` command is not found and I'm not entirely sure if it is because I had mucked something up or if it is explainable some other way. I was looking around the docs to try to find where I had the command from at all and can't seem to come across it in the docs and changelog to try to find an explanation. Any wisdom on the matter would be much appreciated.

I know this been discussed before but just to add context what I am ultimately looking for is for the theme to be set and change dynamically according to the MacOS system theme, but the workaround I had was treating me well... Thanks for your time :)
