### ISSUE TITLE
configure option to disable any network activity

### ISSUE THREAD

**Issue by pavel-the-best** [kovidgoyal/kitty#3970]
**Is your feature request related to a problem? Please describe.**
It's not quite good that sometimes when you 
start your favourite terminal it spawns a request to idk which server.
This can be used by
1) the owners of the server to collect some quite unexpected statistics data about kitty users' workflows

**Describe the solution you'd like**
Configure option like "offline_mode" that disables all the network activity by kitty.

**Describe alternatives you've considered**
Completely disabling by default any unexpected internet queries.

**Comment by Luflosi** [comment]
Such an option already exists, see https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.update_check_interval.

**Comment by pavel-the-best** [comment]
I'm sorry, I didn't find it at first glance.
But are there any other internet queries and will there be?
Because I don't want kitty to send some other unexpected things to unexpected servers after an update.
Offline mode option, as it seems to me, solves that problem.

**Comment by Luflosi** [comment]
> But are there any other internet queries and will there be?
Because I don't want kitty to send some other unexpected things to unexpected servers after an update.

There are no other internet queries. kitty is open source, so you can check for yourself if you like.

kitty doesn't really send any information. It's literally just a GET request to https://sw.kovidgoyal.net/kitty/current-version.txt:
https://github.com/kovidgoyal/kitty/blob/495981badeef7115e759e8c8078000793f2a8342/kitty/update_check.py#L50

I'm very certain that kitty will never make any other connections to the internet in a future version but since I'm just a guy on the internet and not the main developer, you should to ask @kovidgoyal for his answer.

**Comment by kovidgoyal** [comment]
There is already an option to turn it off. And if you dont trust me to
not do malicious things how is it going to help you to have an option
that I will implement and maintain.
