### ISSUE TITLE
ssh `RemoteCommand` does not work with `kitty +kitten ssh`

### ISSUE THREAD

**Issue by yodahuang** [kovidgoyal/kitty#3988]
**Describe the bug**
I have this in my `~/.ssh/config`:
```
Host server
    User yodahuang
    HostName foo.bar.my.server
    RemoteCommand cd /my/secret/folder && exec $SHELL --login
    RequestTTY yes
```
What I expect is that when I do `ssh server`, it's automatically `cd`ed to `/my/secret/folder`. This works well with plain ssh. However, if I do `kitty +kitten ssh`, it does not work. Instead it's telling me `Cannot execute command-line and remote command.`

**To Reproduce**
1. Put `RemoteCommand` and `RequestTTY` in your ssh config
2. Verify it works with vanilla open ssh client (the functionality is added in https://github.com/openssh/openssh-portable/commit/1112b534a6a7a07190e497e6bf86b0d5c5fb02dc)
3. Verify it does not work with `kitty +kitten ssh`

**Environment details**
```
kitty 0.23.0 (827b6598b2) created by Kovid Goyal
Linux yhuang-dell 5.4.0-81-generic #91~18.04.1-Ubuntu SMP Fri Jul 23 13:36:29 UTC 2021 x86_64
Ubuntu 18.04.5 LTS \n \l
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
Running under:X11
Loaded config files:
  /home/yhuang/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity      0.8
font_family             MesloLGS NF
font_size               14.0
Colors:
	active_border_color     #ebcb8b   
	active_tab_background   #e5e9f0   
	active_tab_foreground   #2e3440   
	background              #2e3440   
	color0                  #3b4252   
	color1                  #bf616a   
	color10                 #a3be8c   
	color11                 #ebcb8b   
	color12                 #81a1c1   
	color13                 #b48ead   
	color14                 #8fbcbb   
	color15                 #b48ead   
	color2                  #a3be8c   
	color3                  #ebcb8b   
	color4                  #81a1c1   
	color5                  #b48ead   
	color6                  #88c0d0   
	color7                  #e5e9f0   
	color8                  #4c566a   
	color9                  #bf616a   
	cursor                  #81a1c1   
	foreground              #d8dee9   
	inactive_tab_background #3b4252   
	inactive_tab_foreground #d8dee9   
```

**Additional context**
`kitty --config NONE` produce the same result.

**Comment by kovidgoyal** [comment]
Yes, this is because the ssh kitten works by executing a script on the
remote machine, there is no way that I know of to do that and also honor
RemoteCommand, short of parsing the ssh config file, as well as the -o
command line flags, which is rather more effort than is worth it for me,
but patches are welcome.

**Comment by mschilli87** [comment]
@kovidgoyal:

Why was this closed as 'completed' when it is in fact a (known) bug that apparently could be fixed but 'just' requries developer time to do so? I almost opened ([yet another](https://github.com/kovidgoyal/kitty/issues/8560)) duplicate of this.

As far as I am concerned, [your comment above](https://github.com/kovidgoyal/kitty/issues/3988#issuecomment-911162436):

> ...there is no way that I know of to [...] also honor RemoteCommand...

directly contradicts [your own documentation](https://sw.kovidgoyal.net/kitty/kittens/ssh/) (highlight mine):

> The ***ssh kitten*** is a thin wrapper around the traditional [ssh](https://man.openbsd.org/ssh) command line program and ***supports all the same** options and arguments and **configuration***.

I completely understand that this is an edge for you that might not be worth fixing. But if your documentation would have clearly stated that while `kitten ssh` does support speficying a command to run on the remote destination via the command line (

```sh
kitten ssh [options] <destination> [command]
```

), it does *explicitly **not*** support the `RemoteCommand` configuration option, I would have i) saved a lot of time troubleshooting my SSH config, ii) reconsidered 'blindly' setting

```sh
alias s="kitten ssh"
```

in my shell's configuration file.

Personally, I will remove that alias because I i) *need* `RemoteCommands` to work and ii) *never* `alias`-replace established tools with alternatives that are not 100% backwards/upstream compatible.
I *might* add a `Host <destination>_no-remote-command` that mirrors the `Host <destination>` configuration except for *not* specifying `RemoteCommand <remote-command>`and create an alias `ssh_<destination>` as `kitten ssh <destination>_no-remote-command -- <command>` for specific hosts where I need kitty-integration enough to justify that extra effort.

Finally, note that combining `kitten ssh` with an SSH config that contains *both* `RemoteCommand` *and* `LocalForward` *for the same host* causes blocking of the respective ports for subsequent attempts to connect via `ssh` (proper):

```sh
sed -n '/^Host <destination>$/,/^$/p' ~/.ssh/config
```

```
Host <destination>
  IdentityFile ~/.ssh/<identity>
  LocalForward <port> <remote>:<port>
  ExitOnForwardFailure yes
  RemoteCommand echo success
```

```sh
ssh <destination>
```

```
success
Connection to <destination> closed.
```

```sh
kitten ssh <destination>
```

```
Cannot execute command-line and remote command.
```

```sh
ssh <destination>
```

```
bind [<remote>]:<port>: Address already in use
channel_setup_fwd_listener_tcpip: cannot listen to port: <port>
Could not request local forwarding.
```

```sh
ps -p $(lsof -ti:<port>)
```

```
  PID TTY           TIME CMD
 <PID> ??         0:00.01 ssh: /tmp/kssh-rdir-<id>/kssh-<id>-<id> [mux]  
```


```sh
kill -9 $(lsof -ti:<port>)
ssh <destination>
```

```
success
Connection to <destination> closed.
```

**Comment by mschilli87** [comment]
@kovidgoyal: Does that merge mean that the next release of kitty will support arbitrary remote commands just like ssh proper?

**Comment by kovidgoyal** [comment]
No, it means RemoteCommand in your ssh config now works with the ssh kitten.

**Comment by mschilli87** [comment]
That's what I meant. Sorry for my unclear language and thank you for the confirmation and implementing this. I'll give it a try then as soon as this lands in a release that makes it to my system.
