### ISSUE TITLE
Tab stops are reset in the current shell upon opening a new kitty tab/window

### ISSUE THREAD

**Issue by wardw** [kovidgoyal/kitty#4012]
**Describe the bug**

Tab stops are reset in the current shell upon opening a new kitty tab or kitty window.  For example, by default I observe tab stops with 8 spaces.  If I use `tabs -4` to change this to 4 spaces this will persist - but only until I open or close a new kitty tab/window after which tabs are reset back to 8 spaces in the original shell.

**To Reproduce**

    tabs -4
    echo -e "\tx"    # Tab character prints as 4 spaces

Press `ctrl+shift+t` to open a new tab.  Then use the mouse to go back to first tab.

    echo -e "\tx"    # Tab character now prints with 8 spaces

Example output of the above steps:

    > echo -e "\tx"
            x
    > echo -e "\tx"
        x

**Environment details**

Tested independently on two systems:

+ Arch Linux (latest rolling) with kitty version 0.23.1
+ Fedora F34 with kitty version 0.21.2
+ Reproducible with an empty config using `kitty --config NONE`.
+ Reproducible under `zsh` (v5.8) and also `bash` (v5.1.0, with default config).

**Additional context**

Running `tabs -4` in a shell startup script persists for the new shell in the new kitty tab.  It's the tab stops in the current shell that is somehow reset (which is otherwise untouched?).

Lastly, please let me know if I missed something, or e.g. if `tabs -4` isn't the recommended way to change tab stops in kitty.  In this case I'd be grateful if you may have a helpful suggestion on what I might do differently.

**Comment by kovidgoyal** [comment]
Its not opening a new window, its resizing of the current window (which can happen when you open a  new window, depending on layout). And that is because there is no well defined way to reflow tab stops on resize. kitty currently resets them to default on resize.  Note that using non default values for tabstops is not recommended as it can mess up other programs (as the man page for the tabs program will tell you). 

I dont particularly mind using some other strategy for tabstops on resize, but I would like some motivation, pointers to the algorithm used by other terminals, or similar to do so. 

Note that tabs in terminals dont have an actual width, they are instead a bunch of clumn numbers that can be at arbitrary spacing (the tabs program just simulates them having a width by setting the column numbers to be equidistant).

**Comment by kovidgoyal** [comment]
no followup
