### ISSUE TITLE
FreeBSD: kitty becomes unresponsive in Wayland

### ISSUE THREAD

**Issue by svzer** [kovidgoyal/kitty#4058]
**Describe the bug**
Every time I close a tab or a window in kitty, it freezes and becomes unresponsive. 
The issue only occurs with Wayland : in an X11 session, it worked fine. Setting ```linux_display_server``` to ```x11``` also fixes the issue in Wayland, but only if the compositor offers XWayland support.
I could also probably add that when I build kitty from source, in Wayland it freezes a few seconds after I launched it, but works flawlessly with X11.

**To Reproduce**
1. Open a new window / tab
2. Close the window / tab or even rename the tab
3. See error

**Environment details**
OS : FreeBSD

**Comment by kovidgoyal** [comment]
I'm afraid I dont have access to a BSD system to test with. I get no
freezes with kitty on Linux under four different Wayland compositors:
weston, sway, mutter and kwin using both Intel and AMD GPUs.

If someone with a BSD system wants to help track it down, I am happy to 
help as I can. You can run with WAYLAND_DEBUG=1 that might shed some
light on where the freeze occurs. I suggest posting that log here and
possibly in the issue tracker of the compositor, since this is likely
an interaction between the compositor and the client and wayland
compositor developers are much more likely to be able to glean useful
information from the log.

Closing as I cant really support BSDs myself, but feel free to continue
posting.
