### ISSUE TITLE
macOS Chinese IME certain control keys are directly displayed by kitty

### ISSUE THREAD

**Issue by Camouflager** [kovidgoyal/kitty#4062]
I'm using the default Chinese input method on macOS. I use kitty+vim to write latex or txt documents from time to time. However I notice that some IME-related key controls are also directly sent to kitty.

For example, when typing Chinese, keys like "=" and "-" are used to select characters in the IME. But they are also displayed in the terminal:

<img width="454" alt="Screen Shot 2021-09-25 at 13 18 22" src="https://user-images.githubusercontent.com/26111796/134759412-123b62f5-dc25-4a51-a932-ed1332580581.png">

I wonder if there's anyway to fix this. I've looked into sources under **glfw/** but got lost pretty quickly. Any help will be appreciated.

**Comment by kovidgoyal** [comment]
Relevant code is in glfw/cocoa_window.m in the keyDown function. And run kitty with --debug-input to get a detailed log of the events kitty is seeing and processing.

**Comment by Camouflager** [comment]
Looks like the first press of "=" will empty the markedText. And the release of it will change `state` from `GLFW_IME_PREEDIT_CHANGED` to `GLFW_IME_NONE`. Any ideas?

<img width="1424" alt="Screen Shot 2021-09-25 at 14 22 20" src="https://user-images.githubusercontent.com/26111796/134761094-63210596-1387-42d1-a282-87f7e559d774.png">

**Comment by kovidgoyal** [comment]
Look at the call to UCKeyTranslate, it is probably setting deadKeyState
to 0. Because = is not part of the dead key.

**Comment by Camouflager** [comment]
That's correct.

I don't think it's wise to just override deadkeystate? Any direction you could point me to look further? Like looking into sources in iTerm2?

**Comment by kovidgoyal** [comment]
Yes, you cannot override deadkeystate as there is no guarantee that = is part of the input method for other languages/engines. Basically this a bug in UCKeyTranslate, I dont think you can fix it in kitty. And iTerm2 will not be using UCKeyTranslate it will likely be using apple's cocoa api directly since it only runs on cocoa. The cocoa API is not suitable for a cross platform application, so I'm afraid you are essentially out of luck. You can try asking Apple to fix UCKeyTranslate or provide better APIs, but the chances they will listen to you are, well, not high :)

**Comment by kovidgoyal** [comment]
Actually thinking about it, there is possible hack you could try. Check if the key is = and the length of _glfw.ns.text is unchanged after the call to interpret keyevents and in_compose_sequence is true. If so restore deadkeystate to what it was before the call to uckeytranslate.

**Comment by kovidgoyal** [comment]
It would need significant testing to check if it breaks anything else.

**Comment by Camouflager** [comment]
Thanks, will look into it

**Comment by Camouflager** [comment]
After some searches I believe this is an issue specific to the Chinese IME. The way it works is that the handling of keys like "=" depends on the state of the IME, that is, whether the IME window is activated or not. So = is not a dead key in any traditional sense, because it depends on the state of the IME window. So UCKeyTranslate certainly doesn't work here, since its behavior is irrelevant to the state of the IME.

I may be wrong here so feel free to criticize. So far the hack works good enough for me. Although markedText is somehow always lost after I press =...

**Comment by kovidgoyal** [comment]
On Sat, Sep 25, 2021 at 08:42:54AM -0700, Camouflager wrote:
> After some searches I believe this is an issue specific to the Chinese IME. The way it works is that the handling of keys like "=" depends on the state of the IME, that is, whether the IME window is activated or not. So = is not a dead key in any traditional sense, because it depends on the state of the IME window. So UCKeyTranslate certainly doesn't work here, since its behavior is irrelevant to the state of the IME.

I'm somewhat confused. If = is processed by the IME window itself, then
it should "eat" that event and not pass it to the main window. But you
are saying that it both consumes that event *and* passes it to the
application? That seems like a clear bug in the IME. Which exact IME
engine is this?

**Comment by page-down** [comment]
> That seems like a clear bug in the IME. Which exact IME engine is this?

According to the issue description, I can reproduce it in the following input methods.

macOS 11.6
- Pinyin (Chinese, Traditional)
- Pinyin (Chinese, Simplified)
- and all other Chinese, Simplified IME engines

https://support.apple.com/guide/chinese-input-method/use-the-candidate-window-cim12992/104/mac/11.0

> Navigate in the Candidate window
> - Move to the next or previous candidate in the window: Use the arrow keys on your keyboard.
> - Move to the next or previous row in the window: Use any of the following keys on your keyboard: Equal Sign (=), Minus (–), Left Bracket ([), or Right Bracket (]).

None of the keys mentioned in the above document work properly. Pressing the arrow keys will cause the shell to respond and display the command history. Pressing Backspace will cause unconfirmed letters to be displayed after the symbols (Equal Sign, Minus, ...).

However, it works fine in other common GUI applications, covers various languages and GUI frameworks.

Tested some input methods for other languages and did not reproduce the same kind of issue. This may be a compatibility issue that can be improved, but it requires an investment of time and effort.

Also, on some open-source input methods, this issue does not exist because the key events are handled correctly.

**Comment by page-down** [comment]
It seems that this issue has been solved in the master branch by the way.

See https://github.com/kovidgoyal/kitty/issues/4219

**Comment by kovidgoyal** [comment]
That's a nice bonus!
