### ISSUE TITLE
Kitty image preview noop flag settable via shortcut e.g `map ctrl+i toggle_image_preview_noop`

### ISSUE THREAD

**Issue by wis** [kovidgoyal/kitty#4099]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when [...] I'm using Ranger with kitty image preview and select a big image it takes a long time to render preview and makes ranger unresponsive.

**Describe the solution you'd like**
a way to toggle image preview on and off with a shortcut

**Describe alternatives you've considered**
patching every program like Ranger that uses Kitty image preview protocol to add enable/disable image preview feature.

**Additional context**
none needed.

**Comment by kovidgoyal** [comment]
I am afraid not. Turning off image display means now every program running in kitty cannot be certain if the images it wants to display will display or not. I suggest you use a higher performance file browser, one that renders images not in the UI thread.

**Comment by kovidgoyal** [comment]
On Tue, Oct 05, 2021 at 11:46:37PM -0700, Wis wrote:
> > I suggest you use a higher performance file browser, one that renders images not in the UI thread.
> 
> Sorry, I did not think this through before posting, proof of [Brandolini's law](https://en.wikipedia.org/wiki/Brandolini%27s_law) (_"The amount of energy needed to [explain why an idea wouldn't work] is an order of magnitude larger than to produce it."_)
> So the blocking is caused by Ranger's main/UI thread reading-file-off-disk, image decoding, resizing and base64 encoding? not Kitty's base64 decoding raw pixel data and rendering?
> 
> https://github.com/ranger/ranger/blob/50f8971a6eccb43442bb53186fa83212d0763c01/ranger/ext/img_display.py#L632-L671

base64 encoding/decoding can happen at GB/s on modern CPUs. And in any case a high
performance client would use the fact that kitty's image display doesnt
need base64 encoding for local clients and just send it the image pixels
directly via either the filesystem or shared memory. And there is no
decoding of raw pixel data, the image protocol asks for data in either
RGB or RGBA formats that are directly displayed on the GPU.

> 
> > Turning off image display means now every program running in kitty cannot be certain if the images it wants to display will display or not. 
> 
> I don't see why that is an issue, by the way, but that's irrelevant considering the above.

Because you are considering the ecosystem as a whole. You are
proposing doing something that makes rendering of images
completely non-deterministic from the perspective of a client that may
rely on displaying images for its functionality.
