### ISSUE TITLE
kitty @ launch and --wait for child process?

### ISSUE THREAD

**Issue by kbd** [kovidgoyal/kitty#4123]
For things like writing a git commit message, doing a git interactive rebase, etc. I prefer to open a new editor window so as not to lose sight of my context in the terminal. What I'd really like to do is have vim temporarily open in a new window (split) below what I'm working on, have the calling terminal wait on it (because I need to finish editing my commit message or doing my rebase) then exit when the vim instance closes.

If have a script:

```
$ cat ~/bin/kw  
kitty @ launch --cwd current --copy-env --no-response -- "$@"
```

and call `kw sleep 10`, it correctly opens a window below and runs `sleep`, but the caller returns immediately without waiting on the child process to finish.

How can I wait for the child process to finish in `kitty @ launch` so that I can wait on git operations like writing a commit message? Thanks.

**Comment by kovidgoyal** [comment]
You cant, the remote control system runs synchronously, which means it cant
wait for arbitrary amounts of time, as that would freeze kitty. No to
mention that doing this would mean messages and their responses would
now need identifiers since they can come out of order.

I suggest you instead write a script that simply runs git commit ina
new window, git will open your editor for you and wait till the commit
is completed. Or if you really want to track things poll kitty with 
kitty @ ls to see when the window with the editor closes.

**Comment by kbd** [comment]
Here's the [current version](https://github.com/kbd/setup/blob/main/HOME/bin/kitty-launch-and-wait) of "launch kitty and wait for it to exit":

```shell
$ cat ~/bin/kitty-launch-and-wait
#!/usr/bin/env bash
set -Eeuo pipefail
wid="$(kitty @ launch --type=window --cwd=current --copy-env -- "$@")"
pid="$(kitty @ ls --match=id:"$wid" | jq '.[].tabs[0].windows[0].pid')"
gtail --pid="$pid" -f /dev/null
```

I set my `GIT_EDITOR` to this:

```shell
export GIT_EDITOR='kitty-launch-and-wait "$EDITOR"'
```

and then whenever git needs to open an editor it opens it in a new split instead of replacing my current terminal.
