### ISSUE TITLE
Ctrl+Shift+F5 doesn't work in fresh i3+arch

### ISSUE THREAD

**Issue by Danielgb23** [kovidgoyal/kitty#4163]
**Describe the bug**
I press Ctrl+Shift+F5 and nothing happens...

**Environment details**
```
kitty 0.23.1 created by Kovid Goyal
Linux perkunos 5.14.14-arch1-1 #1 SMP PREEMPT Wed, 20 Oct 2021 21:35:18 +0000 x86_64
Arch Linux \r (\l)
Running under:X11
Loaded config files:
  /home/perkunos/.config/kitty/kitty.conf

Config options different from defaults:
enable_audio_bell False

```

**Comment by drone1** [comment]
![image](https://user-images.githubusercontent.com/6324796/164980943-1a80113b-3912-4f77-b0b3-626de845b87e.png)
I'm using kitty 0.19.3 created by Kovid Goyal, on Ubuntu 21.10

ctrl+shift+f5 does this:
![image](https://user-images.githubusercontent.com/6324796/164981106-2f0dd471-8597-4c72-831a-fd5701330b90.png)
...which is weird because ctrl+shift+f2 works just fine (opens config in new window).

**Comment by kovidgoyal** [comment]
0.19.3 is too old that feature is not present there.

**Comment by drone1** [comment]
Oh that’s strange. I installed today.

**Comment by page-down** [comment]
> ... Why is the version here so out of date? ...

You need to ask the packager and maintainer of the corresponding Linux distribution.

Check out the following link to learn how to install the latest version maintained here.

https://sw.kovidgoyal.net/kitty/binary/

**Comment by drone1** [comment]
Already installed via those instructions. Mind blown though. Thanks !
