### ISSUE TITLE
BS at last column inconsistent with DEC terminals

### ISSUE THREAD

**Issue by ninjalj** [kovidgoyal/kitty#4170]
**Describe the bug**
As you probably know, DEC VT100+ terminals position the cursor at character cells, cannot position the cursor past the last column, and set a Last Column Flag when printing a character at the last column when AutoWrap mode is on. This flag is then checked before printing a character in AutoWrap mode to decide whether to advance to the next line before printing that character.

This flag is not checked on cursor movement commands, therefore BS (and CUB) at the last column should always (qualification: xterm's reverse wraparound mode changes this behavior) move to the previous to last column, even if a character has already been printed at the last column.

ncurses relies on this behavior, as can be seen by running the test program at VTE bug https://bugzilla.gnome.org/show_bug.cgi?id=731155 , which first writes "0%" at the right of the screen, and then writes "50%". Kitty ends up showing "50".

There is another test program at https://invent.kde.org/utilities/konsole/-/merge_requests/510#note_326117 which shows the behavior of other terminal emulators for <nothing> BS, CUD, CUU, CUB, CUF after the last column.

**Comment by kovidgoyal** [comment]
As I recall from when I was writing this code, I found the DEC behavior
extremely counter intuitive and unnecessary. Just try editing text near
the line boundary with cat. And no actual programs I know off actually
rely on it, other than vtetest. 

The LCF is clearly a very bad design (essentially a hack to workaround
the DEC's hardware limitations), since it is additional global
state that one then needs to specify the interaction of, with every other
terminal operation. IMO, it should be gotten rid of and all terminal
should do the "natural" thing which is allow the cursor to be offscreen
at the end of the line. Or pick some other natural behavior, as long as
it does not require the maintenance of a special global flag whose
behavior then needs to be specified with every other terminal operation.

Do you have some actual program that misbehaves in kitty? As I recall,
GNU grep has issues with the DEC behavior. For details, see
https://github.com/mattiase/wraptest

Then there is the fact that there is no consistency in these standards.
The LCF has to be reset by various operations, the DEC manual only
specified it for operations that existed at that time, not for
operations added later. And various hardware terminals did different
things and various software terminal emulators do different things.  See
the wraptest repo for details.

So if you want this fixed, across terminals, I suggest coming up with a
standard that documents the exact behavior. And note that even the
wraptest repo does not actually address what happens in various modern
scenarios, such as: printing a wide character when the cursor is in the
last column. Or printing a unicode variation width selector (VS 2015 VS
2016). Or unicode zwj followed by a ligating character.

Given all this confusion, I am not inclined to change kitty's behavior
from one arbitrary ruleset to another. What could change my mind is some
statistics showing such a change would benefit more programs than it
harms. Or failing that some documentation for a common standard all
terminals can follow and some indication that other terminals are
planning to follow it, so we can all converge to the same, well defined, behavior.
Right now all I see is VTE having one behavior, konsole another, xterm
another, rxvt another and so on. And all these behaviors changing across versions.

Am closing this issue for now, but feel free to continue the discussion.

**Comment by ninjalj** [comment]
ncurses depends on this behavior of BS, so there are probably programs that misbehave. At one point, aptitude did: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=455220 

grep problems are due to EL, not BS. 

TAB could also be problematic (could cause a character at the end of a line to be overwritten) if the prescribed DEC STD-070 behavior of canceling the LCF flag was followed, but if you look at the wraptest results, apparently only the VT220 terminal did that. BTW, the following causes kitty to overwrite a character (maybe I should open another bug for it ;P ):

    tput smam;tput hpa $((COLUMNS - 1)); printf "A\tB\n\n"

foot and putty also delete the last column on this BS case, so kitty isn't the only one with this behavior. putty shows the same trouble with the ncurses percentage test case, while foot gets away with it because it resets the LCF on DECSET/DECRESET DECAWM (ncurses actually does an rmam before printing to the last column, to avoid a line wrap, and then does an smam). The whole thing the test does is:

    write(1, "0\33[?7l%\33[?7h", 12)        = 12     ; 0<tput rmam>%<tput smam>
    write(1, "\10\10", 2)                   = 2      ; <BS><BS>
    write(1, "50", 2)                       = 2      ; 50

About the counter-intuitiveness of it all, yes, we are used to multi-line text edit controls, and screen where all character cells are addressable, but terminal emulators still have some behaviors inherited from typewriters, where you write on the current line, and can see the previous lines already printed on paper. Just be glad you don't hear a bell when you approach the last column, to warn you that you should end the current word, or hyphenate it, and then push the carriage lever and move the carriage ;P

**Comment by kovidgoyal** [comment]
Well, I think I'll wait till someone reports an actual issue with a
widely used program before making any changes here.

But thanks for the detailed issue report.
