### ISSUE TITLE
XTMODKEYS handling

### ISSUE THREAD

**Issue by scandum** [kovidgoyal/kitty#4290]
Just did some troubleshooting with a user of my terminal app (tintin) and it looks like Kitty has some issues with XTMODKEYS handling.

When enabled using `\e[>4;1m` Kitty is turning ctrl-a, ctrl-b, etc into special key sequences, while the xterm documentation states that:
```
               tells xterm to construct an escape
               sequence for ordinary (i.e., "other") keys (such as "2") when
               modified by Shift-, Control-, Alt- or Meta-modifiers.  This
               feature does not apply to special keys, i.e., cursor-, keypad-,
               function- or control-keys which are labeled on your keyboard.
               Those have key symbols which XKB identifies uniquely.
```
Most terminals, xterm included, interpret that as meaning ctrl-a and other "special" keys should not be modified.

Another issue is that Kitty doesn't recognize `\e>4n` to disable the mode as documented and supported by xterm, it only recognizes `\e[>4;0m`.

**Comment by page-down** [comment]
Support for XTMODKEYS escape code will be completely removed in upcoming releases (current master branch).

https://github.com/kovidgoyal/kitty/issues/4075

**Comment by scandum** [comment]
The issue discussed there seems similar, with Kitty remapping the ESC key when it shouldn't.

Looking through tintin's discord history there's also a report of Kitty sending a different code on Enter than xterm, and remapping the arrow keys.

It's better to disable XTMODKEYS 4 rather than leave it as is, but might be worth the trouble to fix it.

**Comment by page-down** [comment]
The final conclusion of the related issue is that there is no way to use a better keyboard protocol while being compatible with XTMODKEYS. Otherwise the terminal needs to be adapted specifically for certain programs, which seems difficult.

Please consider supporting kitty's keyboard protocol in your application to bring a better experience for the users.

https://sw.kovidgoyal.net/kitty/keyboard-protocol/

**Comment by kovidgoyal** [comment]
dup of #4075

**Comment by tmccombs** [comment]
Is there any possibility of getting some level of XTMODKEYS supported in kitty? Neovim 0.7 will try to use `CIS > 4; 2m` (see https://github.com/neovim/neovim/pull/17844) to distinguish between ambigous keys. It would be cool if kitty could support that. 

There is an [github issue on Neovim](https://github.com/neovim/neovim/issues/14400) to support the kitty protocol, but I don't know when or if it will ever be added to neovim, especially given that afiak, the only other terminal that currently supports the kitty keyboard protocol (foot), also supports XTMODKEYS, and the issue is marked as "non-trivial". 

It also sounds like the previous attempt at this supported `CIS > 4; 1m`, which has several exceptions, but `CIS > 4; 2m` escapes the exceptions as well (see https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyOtherKeys), so I would expect it to be closer to kitty's disambiguated escape codes. But, I am far from an expert on terminal escape codes, so there is likely complexity around it that I am missing.

Thanks for making a great terminal.

**Comment by kovidgoyal** [comment]
XTMODKEYS is a complete dead end. It's poorly designed, incompletely
specced and doesn't solve the full problem. I have no interest in
supporting it in kitty. If neovim wants to use inferior tech that's
their choice. There are other editors that did the sensible thing and
chose to support the kitty protocol, for example, kakoune and dte.

And it is not all tricky to implement support for the kitty protocol.
Unless neovim's code base is a complete mess, it will be a ~200 line
patch. The outline of which is:

1) Emit the query escape code to detect support at startup
2) When you get a positive response, send the escape code to push the
terminal state to full keyboard mode
3) The code to decode terminal events is literally 30 lines, see the
function decode_key_event in kitty's own source code which is used by
kitty's kittens. 30 lines of code and a simple lookup table for
functional key names.
4) At application shutdown/suspend/drop to terminal send escape code to
pop the keyboard mode back to whatever it was before nvim started.
