### ISSUE TITLE
Use the PC speaker for bell sound

### ISSUE THREAD

**Issue by allo-** [kovidgoyal/kitty#4321]
I do not know if it is already possible, but kitty seems to use an audio file for the bell and I do not see how to configure it to use the pc speaker like other terminals.

Is there any way to use the pc speaker? If not, it should probably be added.

**Comment by kovidgoyal** [comment]
No, it's not possible and no I'm afraid I have no interest in adding
support for the PC speaker. Since the PC speaker is pretty flaky and not
even present on most systems. If you prefer it there is already the
ability to run n arbitrary cmmand on bell, have it do whatever yo like,
including beep the pc speaker.
