### ISSUE TITLE
Kitty terminal community

### ISSUE THREAD

**Issue by mnhrdt** [kovidgoyal/kitty#436]
Where is the kitty users community? Is there a mailing list or an IRC channel to ask silly questions about the kitty terminal?

Anyway, here are my silly questionns / feature requests

1) Is is possible to disable completely the clickable urls ?  Even with the option "url_style none", the mouse cursor changes when an url is detected and it interferes badly with copy-paste.

2) Is it possible to specify the terminal size in characters, not in pixels ?  I want to launch several 80x25 terminals with different fonts, but it is excruciatingly complicated.

3) I understand it goes against the author's philosophy, but can you point me to the place in the source code where I should enable bold as bright?  I cannot stand bold fonts, and I would like to use instead brighter colors to distinguish them.

**Comment by kovidgoyal** [comment]
This is the community. No mailing lists/IRC. Feel free to ask your silly questions here, that way others can benefit from the answers as well. 

1. No you cannot disable the mouse cursor from changing over URLs. How does it interfere with copy/paste, changing the mouse cursor does not affect copy/paste.

2. No, but since kitty remembers the last used size via a config option, you can turn it off, figure out what size you need and set initial_window_width/height accordingly in kitty.conf.

3. There is no single place, it would be a fairly large/distributed patch. And having bold fonts does not preclude you from having bright colors. It's only broken terminal software that uses the bold escape code for bright colors instead of the the actual bright color escape codes.

**Comment by mnhrdt** [comment]
Regarding 2), this is not really practical if you are traversing a huge list of fonts from inside a script and you want to open a 80x25 terminal with each font.  I guess a patch for cell-based units for width/height would be much more localized.  Maybe inside the function "initial_window_size", if "w" and "h" have some unit suffixes, we can multiply them by the cell size.  Would you accept such a patch ?

**Comment by kovidgoyal** [comment]
I have no objections to a patch that adds another config option called, say, initial_window_size_units (px or cells).

**Comment by kovidgoyal** [comment]
But be aware, that currently at least the initial windows size is applied long before the cell size is calculated. I dont recall if that is actually necessary or not.

**Comment by kovidgoyal** [comment]
Reviewing the code, it is necessary, because to calculate cell size from font size you need the monitor DPI and to know the monitor DPI you have to create a window (as there could be more than one monitor and you dont know which monitor the window is going to end up on).

**Comment by kovidgoyal** [comment]
FYI, this is implemented in master

**Comment by Ramkumar47** [comment]
Hi Developer, i am one of ur kitty users... it is a great terminal!... i have a doubt, i saw that it is possible to set titles for tabs and windows in the terminal using commands like 
` kitty @ set-window-title something `
I am using multiple tabs and windows inside a single Desktop window (i hope u get what i mean by desktop window, i.e. the one has maximize, minimize buttons)  is it possible to set a title for that Desktop Window?.. because for my work, i would open multiple desktop windows of kitty and it would be helpful if i can find them based on a single title assigned to them

**Comment by Ramkumar47** [comment]
![image](https://user-images.githubusercontent.com/38280131/167804170-9716e27a-0906-4b28-8f70-b5a454aa2180.png)
for example, currently the window takes "zsh" as its default title and it doesn;t change unless i set one..  (i am using zshell).. i would like it to be some name for all the tabs and windows that i create within this desktop window
