### ISSUE TITLE
`coretext_all_fonts` affects kitty startup time

### ISSUE THREAD

**Issue by comex** [kovidgoyal/kitty#4410]
**Describe the bug**
`coretext_all_fonts` takes about 0.55 seconds when kitty starts up; this is likely unnecessarily slow because it copies data about all fonts rather than only the ones kitty needs to use.  I don't even have that many fonts installed (67 user-installed fonts); it would probably take longer if I had more.  While startup time of a terminal may not be the most important thing in the world, it would be nice if it were faster.

**To Reproduce**
1. Hack up kitty code to print how long it takes to run `coretext_all_fonts`.
2. Measure kitty's startup time by running `time kitty --config NONE /usr/bin/killall -9 kitty`.  (I imagine there's a better way to do this but I don't know how.)
3. Total startup time is usually 0.95 seconds (sometimes much longer, not sure why).
4. Of that, `coretext_all_fonts` is about 0.55 seconds.

**Environment details**
```
kitty 0.23.1 (59ea7485e4) created by Kovid Goyal
Darwin nickmbp.fios-router.home 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.6 BuildVersion:	20G165
Frozen: False
Paths:
  kitty: /Users/comex/src/kitty/kitty.app/Contents/MacOS/kitty
  base dir: /Users/comex/src/kitty/kitty.app/Contents/Resources/kitty
  extensions dir: /Users/comex/src/kitty/kitty.app/Contents/Resources/kitty/kitty
  system shell: /usr/local/bin/zsh
Loaded config files:
  /Users/comex/.config/kitty/kitty.conf

Config options different from defaults:
confirm_os_window_close 1
font_family             Menlo
font_size               12.0
Added shortcuts:
	cmd+a send_text all \x00a
	cmd+x send_text all \x00x
Changed shortcuts:
	cmd+c send_text all \x00c
	cmd+v send_text all \x00v
	cmd+w send_text all \x00w
```

**Comment by kovidgoyal** [comment]
In order to go from a font name, to an actual font, it is necessary to
list all fonts on the system. If for some reason your system is super
slow at doing that, there is nothing kitty can do about it. You should
figure out why your system is listing fonts so slowly. For context, on
my M1

kitty + list-fonts | wc -l
115

time kitty -o macos_quit_when_last_window_closed=y --config=NONE true

gives total time for startup + create window + wait for true to run and
exit + close window + shutdown
as 0.318 seconds

I am fairly sure Apple is smart enough to cache the list of 
fonts, so perhaps investigate why that caching is not working on your
system.

And if you would like kitty to do that caching for you instead of Apple,
then use the --single-instance startup option, then all startups will be
instant after the first. https://sw.kovidgoyal.net/kitty/faq/#how-do-i-specify-command-line-options-for-kitty-on-macos

**Comment by comex** [comment]
Upon further investigation it appears this is an OS version difference.  I made new installations of the same version of macOS (11.6) as well as the latest version (12.1) on an M1 system.  On 11.6, `time kitty +list-fonts >/dev/null` runs in around 0.45-0.55s, but on 12.1, it takes about 0.14 seconds.  Of that 0.14s, only about 0.08s is spent in `coretext_all_fonts`, putting its performance more in the range I’d expect.

I don’t know what changed between OS versions, but I’ve been meaning to upgrade my OS anyway, so from my perspective this can be considered resolved.

**Comment by kovidgoyal** [comment]
I doubt its anything to do with OS version, more likely the font cache
as corrupted on your 11 machine, but in either case, its not a kitty
issue.

**Comment by comex** [comment]
As I said, I got the numbers in my last comment from new installations of macOS 11.6 and 12.1 (i.e. installed onto blank volumes for the sole purpose of testing this), on the same machine as each other.  (The numbers in my original post are from a different machine.)
