### ISSUE TITLE
ssh alias "kitty +kitten ssh" does not play well with some devices

### ISSUE THREAD

**Issue by geolaw** [kovidgoyal/kitty#4418]
**Is your feature request related to a problem? Please describe.**
I have a few NAS devices at home, connecting to them via SSH with kitty results with errors : 
```
to a buffalo linkstation:

[glaw@optimus ~]$ ssh buffalo-nas pwd
X11 forwarding request failed on channel 0
BusyBox v1.7.0 (2009-04-29 19:12:57 JST) multi-call binary

Usage: mktemp [-dq] TEMPLATE

Create a temporary file with its name based on TEMPLATE.
TEMPLATE is any name with six 'Xs' (i.e., /tmp/temp.XXXXXX).

Options:
	-d	Make a directory instead of a file
	-q	Fail silently if an error occurs

sh: line 4: $tmp: ambiguous redirect
BusyBox v1.7.0 (2009-04-29 19:12:57 JST) multi-call binary

Usage: rm [OPTION]... FILE...

Remove (unlink) the FILE(s). You may use '--' to
indicate that all following arguments are non-options.

Options:
	-i	Always prompt before removing each destination
	-f	Remove existing destinations, never prompt
	-r,-R	Remove the contents of directories recursively

tic: File name needed.  Usage:
	tic [-e names] [-o dir] [-R name] [-v[n]] [-V] [-w[n]] [-1aCcfGgILNrsTtUx] source-file

To a qnap TS-251 :

[glaw@optimus ~]$ ssh qnap pwd
X11 forwarding request failed on channel 0
sh: line 78: tic: command not found

```
If I unalias ssh, back to the /usr/bin/ssh executable, my connections all work file. 

**Describe the solution you'd like**
something within the copy process of the terminfo directory to be more flexible when certain commands may not exist (e.g. tic) 

**Describe alternatives you've considered**
Now that I finally realized it had to do with the kitty ssh alias, I can unalias ssh when I need to connect - however however kitty works under the hood to copy the terminfo directory over should be more flexible.

**Additional context**
The buffalo-nas unit is very old, the qnap is not as old, but if you need any help testing, I would be happy to help test.

**Comment by page-down** [comment]
Since `kitty +kitten ssh` cannot be used as a drop-in replacement for the ssh command, it is not recommended to use it as an alias when you already know you will be connecting some special devices.

On some devices, the commands available are limited and there is not even a HOME directory that can be written to, so you will need to work out the installation of the TERMINFO file yourself.

You can write a script that copies the `xterm-kitty` TERMINFO file to `~/.terminfo/x/xterm-kitty` on the device. You only need to execute it once for each device you want to connect to after kitty has been upgraded to a new version, and you can connect directly using ssh on a daily basis.

For cases where TERMINFO cannot be installed at all, you can only use the not-recommended `TERM=xterm-256color`, do not use the kitty functions related to special escape codes, and hope that it works okay under your usage.
