### ISSUE TITLE
show_last_command_output should use the buffer from scrollback_pager_history_size

### ISSUE THREAD

**Issue by wz1000** [kovidgoyal/kitty#4435]
**Describe the bug**
I'm loving the new shelll integration features! I noticed a minor inconsistency with the `show_last_command_output` actions. It seems like they use the buffer from the `scrollback_lines` configuration rather than `scrollback_pager_history_size`, which would be quite a bit more useful if possible to implement.

**To Reproduce**
1. set `scrollback_lines` to `1000` and `scrollback_pager_history_size` to `10000`
2. run `seq 5000` in the shell 
3. trigger `show_last_command_output`
4. Scrollback buffer should show all 5000 lines of output from the `seq` command but only shows the last ~1000

**Comment by kovidgoyal** [comment]
Sadly this is not possible because prompt markings are not stored in
the big history buffer which is just plain text with SGR formatting
codes. One could in theory add OSC codes to it to mark the prompts, but
this is a lot of work and may cause issues with pagers that choke on
parsing OSC escape codes.
