### ISSUE TITLE
Is there a way to define custom `tab_bar.py` path?

### ISSUE THREAD

**Issue by cs1193** [kovidgoyal/kitty#4474]
**Describe the bug**
I have placed my `kitty` elsewhere other than `~/.config/kitty/kitty.conf`. I wanted to know if there is a feature where I can point out my `/path/to/tab_bar.py`

**To Reproduce**
1. Have `kitty.conf` and `tab_bar.py` on some other path `(eg).  $HOME/dev/kitty/`
2. In `kitty.conf` set `tab_bar_style custom`
3. `tab_bar.py` is not getting picked up
4. It shows the default `fade` tab from `.config/kitty`

**Comment by kovidgoyal** [comment]
tab_bar.py is always loaded from the kitty config directory. You can
control the location of that directory using environment variables. Read
the help for the --config option in kitty --help

**Comment by cs1193** [comment]
I agree with you that if you're attempting start `kitty` from a terminal (like iTerm), this should work fine. Like

`kitty --config ~/Development/dotfiles/kitty/kitty.conf`

But with config option, kitty is attempting to search `tab_bar.py` at default location

<img width="1253" alt="Screenshot 2022-01-08 at 5 15 26 PM" src="https://user-images.githubusercontent.com/948448/148642988-1e980e3e-4cac-4e59-b0dd-68c9e540d5c5.png">

**Another question -**

How do I define `--config` flag from `Applications`? 
I am trying to startup kitty from my `Dock`.

**Comment by page-down** [comment]
The file `tab_bar.py` will always be read from the configuration folder.

macOS is hard to specify environment variables, `KITTY_CONFIG_DIRECTORY` I don't know how to use for now.

The following won't work because `--config` only accepts files.

```shell
kitty --config /tmp/kitty-conf-dir/
IsADirectoryError: [Errno 21] Is a directory: '/tmp/kitty-conf-dir'
```

If you need to specify kitty startup parameters under macOS, see the following FAQ.

https://sw.kovidgoyal.net/kitty/faq/#how-do-i-specify-command-line-options-for-kitty-on-macos

However this doesn't seem to solve your problem.

May I ask if allowing users to customize the tab_bar.py path would be acceptable?

**Comment by kovidgoyal** [comment]
ln -s /path/to/real/config/directory ~/.config/kitty
