### ISSUE TITLE
Is it possible to traverse window panes and wrap around when reaching either end of screen ?

### ISSUE THREAD

**Issue by akharrou** [kovidgoyal/kitty#4494]
Is it currently possible to traverse window panes and wrap around when reaching either ends vertically or horizontally ? Else can this be added ? How hard could this be ?

![Jan-10-2022 21-21-11](https://user-images.githubusercontent.com/36056254/148818365-3ec21361-36f9-458b-afc2-83f043a8e4a9.gif)

**Comment by page-down** [comment]
Since not all layouts have the concepts of horizontal and vertical, I think the functionality you describe is not quite appropriate to add to kitty as a generic feature.

Although I think your suggestion is good and useful.

You can try to figure out the layout implementation in kitty and then write your own kitten to meet your specific needs.
