### ISSUE TITLE
[low priority] Appending theme name after `# BEGIN_KITTY_THEME` is really annoying.

### ISSUE THREAD

**Issue by shenlebantongying** [kovidgoyal/kitty#4497]
**`kitty.conf` should be just static once patched by `kitty +kitten themes`.**

Here is why:

People put their dotfiles in a git repo to sync across multiple machines, and terminal themes are not necessarily identical (Light theme for laptops to carry around and dark theme for home computers). Also, sometimes people just want to change the theme because they feel it.

Whenever I want to submit other changes and I changed the theme, this will pop up. I don't want to pollute the commit when I change other staffs. Manually removing it is annoying and unnecessary. It is a useless name too. If someone wants to see their theme, just fire up the kitty. 

![image](https://user-images.githubusercontent.com/20123683/149083368-1e211d11-624f-4115-9e08-b2947e9b71bd.png)

https://github.com/kovidgoyal/kitty/blob/0f7f69c21865df87dcc6d6291ca6606f5de470b6/kittens/themes/collection.py#L30-L32

**Comment by kovidgoyal** [comment]
I disagree. If I change my theme, it changes my config. I want that
config difference reflected in my dotfiles. If you are in the habit of
making random changes to your dotfiles that you dont check into version
control, why use version control at all.

**Comment by kovidgoyal** [comment]
Oh and if you really want to do this just exclude kitty.conf from your dotfiles and use the include directive in your kitty.conf to load the static part fothe configuration.

**Comment by gregorias** [comment]
> I disagree. If I change my theme, it changes my config. I want that config difference reflected in my dotfiles. If you are in the habit of making random changes to your dotfiles that you dont check into version control, why use version control at all.

I don't think this is a good argument. If I understand it correctly, it goes like this:
1. The current theme is part of a configuration.
2. All configuration (dotfiles) should either version controlled in its entirety or not at all ("why use version control at all").

The second point is not true. I don't think that entire configuration should be version controlled. To illustrate my point, consider a different variable, window size. It's like the current theme, a variable that configures Kitty's appearance, and it could be tracked in configuration.

If I change the window size, because I want to run windows side-by-side in my current session, should this be recorded in the repo and possibly replicated across my workstations? I find it quite silly.

Similarly, it would be silly for me to track the current theme. The crucial distinction is that what my current theme is, depends on my session and its environment. I like to change themes depending on lightning conditions. It's useless for me to keep track of that in VCS, just like I don't track a myriad other ephemeral variables that define what's currently happening on my screen.

I do want to keep in VCS what themes I have available. I also do want to keep what theme is the default one. Perhaps, because you don't change your themes regularly, for you every theme change is equivalent to changing what your default theme is?

**Comment by kovidgoyal** [comment]
So dont track it, I already posted how you can avoid doing so.

**Comment by gregorias** [comment]
> So dont track it, I already posted how you can avoid doing so.

That doesn't work, because the include static config part needs to be in the VCS. My dotfiles manager, Chezmoi, doesn't support partial file tracking.

No worries, I've solved this problem differently:

1. I've set the kitty.conf template to read from an environment variable:

```gotmpl
# BEGIN_KITTY_THEME
# {{ env "KITTY_CURRENT_THEME" }}
include current-theme.conf
# END_KITTY_THEME
```

2. I then set up in my shell, Fish, the variable:

```fish
# https://github.com/kovidgoyal/kitty/issues/4497
function extract_current_kitty_theme
  cat $XDG_CONFIG_HOME/kitty/kitty.conf \
    | grep -C1 BEGIN_KITTY_THEME | tail -n1 | tail -c+3
end
set -x KITTY_CURRENT_THEME (extract_current_kitty_theme)
```

3. I also made sure that my theme switching function keeps that variable up to date.

```fish
    if command -v kitty > /dev/null
      kitty +kitten themes --cache-age=90 --reload-in=all "$THEME"
      set -x KITTY_CURRENT_THEME (extract_current_kitty_theme)
    end
```

I was jus making an argument.
