### ISSUE TITLE
locale.Error: unsupported locale setting

### ISSUE THREAD

**Issue by juancarlospaco** [kovidgoyal/kitty#450]
```python-traceback
juan@x ~  $ kitty
[099 19:38:10.894564] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 186, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 117, in _main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.6/locale.py", line 598, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting


juan@x ~  [1]$ python --version
Python 3.6.4

juan@x ~  [1]$ gcc --version
gcc (GCC) 7.3.1 20180312
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

juan@x ~  $ uname -a
Linux x 4.15.14-1-ARCH #1 SMP PREEMPT Wed Mar 28 17:34:29 UTC 2018 x86_64 GNU/Linux

juan@x ~  $ lsb_release -a
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

juan@x ~  $
```
:bug:

**Comment by kovidgoyal** [comment]
python -c 'import locale; locale.setlocale(locale.LC_ALL, '')'

Will break. Which means either the python installation or the glibc installation on your system is borked,

**Comment by MaxNoe** [comment]
I just ran into this after a system update. Before it worked fine, now this error was thrown.
Just starting the terminal however did nothing.

I'd argue that this error should be `except`ed in kitty and converted into a warning so that people still have a (semi)functioning terminal so they can actually do something about it.

**Comment by kovidgoyal** [comment]
Umm it is logged and ignored. Has been for a looong time. What version of kitty are you on?

**Comment by kovidgoyal** [comment]
Actually no its ignored on macOS not linux, since it is common there and not on linux. In fact never heard of not being able to set local on linux.

**Comment by ctrlcctrlv** [comment]
I often encounter this problem when using the `vim` subprocess command. Not sure why.

E.g.:

```:!kitty```

returns

```
[053 21:30:05.314854] Traceback (most recent call last):
  File "/usr/bin/../lib/kitty/kitty/main.py", line 351, in main
    _main()
  File "/usr/bin/../lib/kitty/kitty/main.py", line 291, in _main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

As does even `:!bash -lc kitty`.

After some experimentation, it seems that the problem is that Arch Linux (as of time of writing) does not by default set an `LC_ALL`:

From file `/etc/profile.d/locale.sh`:

```bash
# export all locale (7) variables when they exist
export LANG LANGUAGE LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY \
       LC_MESSAGES LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT \
       LC_IDENTIFICATION
```

We can hack around this by adding to our own `~/.bash_profile`:

```bash
export LC_ALL=en_US.UTF-8
```

The error then stops with `:!bash -lc kitty`. I don't know why Arch developers decided not to export `LC_ALL`. Perhaps they have a good reason, I can't imagine what it is though. Adding the line to our `~/.bashrc` of course will make even regular `:!kitty` work, but for me it seems too hacky. Better would be for Kitty to not treat this as an error, and by default assume UTF-8.

**Comment by kovidgoyal** [comment]
On arch you are supposed to set the locale during installation. See the
Arch installation wiki. And the default locale is not UTF-8 its C or
POSIX. This is the minimal locale libc needs to function and all
processes start with it.

setlocale() is not about kitty, its about setting the locale for
libc. kitty already always assumes UTF-8, as character encoding (which
is not really what locale is about).

**Comment by ctrlcctrlv** [comment]
I did set my locale during installation. I don't know why `LC_ALL` is not exported. `LANG`, etc., are.

**Comment by ctrlcctrlv** [comment]
According to the Arch wiki, `LC_ALL` is only for debugging. https://wiki.archlinux.org/index.php/locale#LC_ALL:_troubleshooting

**Comment by kovidgoyal** [comment]
You dont need to export LC_ALL, lang is enough.

env | grep LC; python -c "import locale; locale.setlocale(locale.LC_ALL, ''); print('ok')"

**Comment by MaxNoe** [comment]
This was apparently due to a rename of the locale files (UTF-8 to utf8) and the plasma user config not being updated. After I removed the plasma config, everything worked again. 

However, I would rather have gotten a warning that the locsle config is bad instead of my terminal not starting at all.
