### ISSUE TITLE
Inconsistent cursor style when using Vi-mode keybindings in fish with kitty shell_integration

### ISSUE THREAD

**Issue by bool3max** [kovidgoyal/kitty#4508]
`fish --version`: `3.3.1`
`kitty --version`: `0.24.1`

I am running `fish` with Vi-mode keybindings

```
set -g fish_key_bindings fish_vi_key_bindings
```
When first entering `fish`, I am placed in insert mode as expected, and the cursor is a regular thin caret: 

![image](https://user-images.githubusercontent.com/12991998/149414467-850db1cf-848e-4eeb-a2fb-8b62ec85ffa6.png)

Going into normal mode results in the cursor switch to a block, as expected: 

![image](https://user-images.githubusercontent.com/12991998/149414571-d6ecc4c2-f5c3-4d1d-9b0b-15fee6151601.png)

However, from then on, switching back to insert mode **does not** result in the cursor style going back to a thin caret: 

![image](https://user-images.githubusercontent.com/12991998/149414671-97bfa463-4f35-4373-888b-1821e3f22b6f.png)

I am unsure if this is a fish-specific problem or a kitty issue. If it is unrelated to kitty, please feel free to close the issue.

Note that disabling shell-integration in kitty (via `shell_integration none` in the config) results in only one cursor style (that set by the terminal), as expected.

**Comment by kovidgoyal** [comment]
as far as I know, fish has no event for entering/exiting insert mode. If
such an event is added, kitty can use it, but without that, there isnt
any way to implement this as far as I know.

**Comment by bool3max** [comment]
Setting `fish_cursor_insert` to `line` fixes this, and it works even with `shell_integration none` in kitty. [More details here](https://github.com/fish-shell/fish-shell/issues/8635#issuecomment-1012856076).

**Comment by page-down** [comment]
I don't use fish vi mode, no wonder I didn't notice this issue. I haven't looked into it yet.

In vi mode, the current shell integration does have some duplicate actions. Since fish will also set the cursor shape.
I just did a simple test and set `fish_cursor_insert` to `line` and that solved the issue. Perhaps it can be further refined.

https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_cursor.fish
https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_cursor_xterm.fish

**Comment by page-down** [comment]
I addressed this issue in a recent PR. I forgot to mention this issue.

https://github.com/kovidgoyal/kitty/pull/4514

Hope everything works fine.

@bool3max 
Also, as far as I know `shell_integration none` is not a valid configuration value. Isn't this the same as enabling shell integration?
If you want to disable shell integration, it should be `shell_integration disabled`.

**Comment by Diaoul** [comment]
I've tested this, works perfectly! Previously had the issue #2743 and was looking for a way to have the cursor to a line in insert mode and block otherwise with no glitch.
I ended up with `shell_integration disabled` in kitty and `function fish_vi_cursor; end` as mentioned in https://github.com/fish-shell/fish-shell/issues/8233 but still had some issue on copy paste from primary clipboard...
Now I don't need any of this!

I guess this could be extended to other vi modes (visual and replace) but this is enough for me. Thanks @page-down!

**Comment by page-down** [comment]
@Diaoul 
If you are looking at the PR mentioned above, then it is out of date. What you mentioned is already implemented, maybe you want to look at the latest fish integration script in the git repo shell integration folder.

**Comment by Diaoul** [comment]
Indeed, I grabbed the version from the PR not the latest from the repo, thanks for pointing that out!
Wish the latest I am having a glitch when using the primary clipboard and also when CTRL-C in normal mode it keeps the block. I am trying to get clear reproduce steps...

**Comment by Diaoul** [comment]
Reproduce steps:
- Open terminal (insert mode)
- Paste from primary (middle mouse)

A new empty line is inserted above

**Comment by Diaoul** [comment]
Actually now I can also reproduce this with the code in the PR. I am not sure what is causing this issue but I have the same with Alacritty so probably not Kitty related but more like vi-mode with multiline shell prompt (starship).

**Comment by page-down** [comment]
> Actually now I can also reproduce this with the code in the PR.

I tried starship and fish vi mode, and without shell integration enabled, basic keystrokes A, I, ESC, etc. all cause similar problems as you describe.

As you described, this needs to be reported to starship to be fixed.
