### ISSUE TITLE
rectangle selection not working in neovim

### ISSUE THREAD

**Issue by cyrinux** [kovidgoyal/kitty#455]
Hi,

I can't do a rectangle mouse selection in neovim with mouse support enable.
If I bypass mouse grabbing with Shift, I can make normal selection.
But rectangle selection, with so Shift+Control+Alt doesn't work. 
Do you have an idea?
[
![peek 2018-04-11 23-29](https://user-images.githubusercontent.com/519083/38644529-179fc3c2-3de1-11e8-88e6-1b4edf73db50.gif)
](url)

Thanks!

**Comment by kovidgoyal** [comment]
Yes, rectangle select does not work when the mouse is grabbed. Why are you using it anyway? vim has its own rectangle select mode, IIRC Ctrl-V

Using the terminals mouse select in a fullscreen application is not a good idea, since for example, it does not restrict itself to windows in vim or scroll the text, etc.
