### ISSUE TITLE
Graphics protocol documentation inconsistency with actual behaviour

### ISSUE THREAD

**Issue by MatanZ** [kovidgoyal/kitty#4554]
The documentation is sometimes unclear and sometime contradicts kitty's actual behaviour:

1. It seems that kitty suppresses success reply when `i=0` (in `finish_command_response()`). icat uses this behaviour by sending the image with `i=0` and not reading the reply. If it is the intended behaviour, it should be documented. Otherwise, it is a bug.
2. The behaviour of placements without `p` parameter is not clear. It is documented as optional, but later the document says that _every_ placement is identified uniquely by image id and placement id. From the code it appears that placements with placement id=0 need not be unique, and on the other hand, they match any placement id and are deleted, when deleting by placement id (`d=i` or `d=n` with `p` parmeter).

**Comment by kovidgoyal** [comment]
On Sun, Jan 23, 2022 at 04:38:50AM -0800, Matan Ziv-Av wrote:
> The documentation is sometimes unclear and sometime contradicts kitty's actual behaviour:
> 
> 1. It seems that kitty suppresses success reply when `i=0` (in `finish_command_response()`). icat uses this behaviour by sending the image with `i=0` and not reading the reply. If it is the intended behaviour, it should be documented. Otherwise, it is a bug.

It is so documented. Quoting the docs:

Since a client has no a-priori knowledge of whether it shares a filesystem/shared memory with the terminal emulator, it can send an id with the control data, using the i key (which can be an arbitrary positive integer up to 4294967295, it must not be zero). If it does so, the terminal emulator will reply after trying to load the image, saying whether loading was successful or not.

The terminal responds only if you specify an id. Indeed in an
asynchronous protocol it is impossible to have responses without some
kind of id identifying what the response is for.

If that's not obvious to you from the documentation, feel free to send a
PR making it more obvious.

> 2. The behaviour of placements without `p` parameter is not clear. It is documented as optional, but later the document says that _every_ placement is identified uniquely by image id and placement id. From the code it appears that placements with placement id=0 need not be unique, and on the other hand, they match any placement id and are deleted, when deleting by placement id (`d=i` or `d=n` with `p` parmeter).

The statement "every placement is identified uniquely by i, p" means the
pair (i, p) is guaranteed to correspond to a single placement, not that
every placement has an placement number.
