### ISSUE TITLE
Display the last parts of the path on the OS window title

### ISSUE THREAD

**Issue by hbarcelos** [kovidgoyal/kitty#4567]
**Is your feature request related to a problem? Please describe.**
The problem I'm facing is better described with an image:

![image](https://user-images.githubusercontent.com/16565602/151215889-5892fc9f-b325-4197-8a4f-76d23e116c7d.png)

Here I have 3 terminals open for 3 different projects I'm currently working on, but I cannot visually distinguish between them.

**Describe the solution you'd like**
In case `kitty` needs to display the CWD path in the title, it would be great if it could show the last parts of the path as a priority.

Suppose we have are in the following directory:
```
~/path/to/very/deeply/nested/directory
```

Kitty could:
1. Display only the basename of the current directory: `directory`
2. Display only the basename of the current directory prefixed with `~` or `/` when it makes sense: `~/Downloads` / `/var/log`
3. Based on the above, if the path lenght is over X (ideally X is configurable), Kitty could:
  a. Use an ellipsis relative to `~` or `/`: `~/.../directory`
  b. Use a single letter for all the intermediary directories: `~/p/t/v/d/n/directory`
  c. Maybe mix `a` and `b`: `~/p/.../n/directory`

**Describe alternatives you've considered**
It's possible to use `kitty @ set-window-title` to change the title of the current window, but I'm not sure how to make the title immutable after that, specially when `shell_integration` is enabled and there are multiple windows in the same tab.

**Additional context**
N/A

**Comment by page-down** [comment]
You should use the escape sequence to output the title.

First disable the shell integration title feature.
(You can also see the shell integration script, change it and then install it manually.)
```text
shell_integration no-title
```

fish - built-in "single letter" style pwd
https://fishshell.com/docs/current/cmds/fish_title.html
https://fishshell.com/docs/current/cmds/prompt_pwd.html

zsh
https://wiki.archlinux.org/title/zsh#xterm_title

bash
`PROMPT_COMMAND` (array) or `PS1`
https://tldp.org/HOWTO/Xterm-Title-4.html

busybox sh (ash)
~/.profile
```shell
my_title() {
    basename "$PWD"
}
PS1="$PS1\e]2;\$(my_title)\a"
```

**Comment by t-fritsch** [comment]
thanks a lot for the tricks @page-down 

Maybe I'm wrong (please forgive me if that's the case, I'm new to kitty, maybe I missed something) and sorry for digging up this old issue, but I think that those tips don't solve the base issue which is "kitty is truncating tab bar titles at the end instead of the start".

Even with a "shorter" title, there will always be some situations when the title is too large to fit in the available space and then truncated by kitty.

For instance, in the following image, I use `ZSH_THEME_TERM_TITLE_IDLE="%2d"` configuration (oh-my-zsh) to display only the 2 last folders in the title (_shown in the OS window title_). When I'm in a `~/workspace/vscode-extensions` folder, and the space is too small to display the full title for each tab, kitty prints `workspace/vscode-...` when I'd find it more meaningful to have `...vscode-extensions`.

<img width="1022" alt="image" src="https://user-images.githubusercontent.com/10920280/203663750-5f7184c8-1470-4867-81ea-7f3d11c00d03.png">

Is there a setting or any other way to control how kitty truncates the tab titles ?

PS: use of `ZSH_THEME_TERM_TITLE_IDLE="%2d"` is a temporary setting since I'd love to have in tab titles the same result as with power10k setting `typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique` (shown in the prompt below tabs in my screenshot) 🥹

**Comment by kovidgoyal** [comment]
THere is no setting, but you can customize how tab title are rendered
completely by writing your own python function to render them. See the
docs for tab_title_template.

**Comment by page-down** [comment]
@t-fritsch
> ... those tips don't solve the base issue which is ...

What I offer is a way to address the root causes of the problem, not the symptoms.
Letting programs with context directly output the most important information as titles can reduce the situation where tabs are indistinguishable.

As with the prompt theme in your example, the shell, as the program being run, knows best how to reduce the path string length. You can just output the prompt's reduced path as the title.

**Comment by t-fritsch** [comment]
thanks a lot @kovidgoyal and @page-down, I've payed a closer look to the documentation at https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.tab_title_template and found a way to achieve what I wanted, maybe it'll be useful to someone (don't judge me, I don't know python at all 😅 ) :

```
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title if len(title) <= max_title_length else '…' + title[-max_title_length+1:]}"
```

![image](https://user-images.githubusercontent.com/10920280/203953944-e8b525ef-e5b5-46cb-b5b1-e18b0576596a.png)

This is nice thank you ! However I noticed a small weird behavior, maybe I did something wrong but when I switch from one tab to another, the titles change too :

 ![image](https://user-images.githubusercontent.com/10920280/203955471-90f9b235-a9ae-4348-a9ff-2030998fb5a6.png)

- previous active tab title changed from `...code-extensions` to `...de-extensions`
- new active tab title changed from `.../pomotroid-pr` to `...ce/pomotroid-pr`

I've not modified the default value of `active_tab_title_template`. Do you have any idea of what I did wrong ?

**Comment by page-down** [comment]
@t-fritsch

> ... found a way to achieve what I wanted ...

This will be inaccurate and problematic if your title contains double-width characters, or if it contains escape sequences. The escape sequence will be cut off in the middle.

> ... when I switch from one tab to another, the titles change too ...

This behavior comes from the following.

https://github.com/kovidgoyal/kitty/issues/5548

I'm not a fan of dynamically changing tab widths, preferring a fixed length no matter how you switch tabs, and I'm aware of some tab width issues that arise from this change.
This one is also on my long list.

**Comment by t-fritsch** [comment]
thank you @page-down 

You're right my solution is far from perfect, I've just posted it in case anyone would like to avoir "...xxxx..." tab titles, but there may still be some work to be done to get something robust. Anyway since I've configured zsh to use only current path as window title, I hope I'll avoid the kind of problems you mentioned, at least it works fine so far in my situation.

Regarding variable tab width, I've looked at the issue and commit you gave. If I understand, it changed the way tab width were calculated to allow the tab whose title is small to "give" the unused space back to other tabs, resulting in variable tab width.

What I don't understand is why this would have an impact here since the only thing I do is switch tab, the "needed" width of every tab isn't supposed to change, does it ?

**Comment by MihiroH** [comment]
I resolved this using `tab_title_template`.
If the title contains a slash, it displays only the last part of the path (basename); otherwise, it shows the command name.
```
tab_title_template "{title if '/' not in title else title.split('/')[-1]}"
```
