### ISSUE TITLE
Use the new shell integration in the hints kitten

### ISSUE THREAD

**Issue by permelin** [kovidgoyal/kitty#4598]
It happens quite often that I want to copy or otherwise use the output of a command, so I was happy about the new functionality we got in 0.24.

But it's currently more limited than it needs to be. It seems only logical to me that this new feature should be integrated with hints so that we can do `kitten hints --type=output` to really use it to its full potential.

Or am I missing something? The changelog mentions "opening the output of the last command in a new window" but I can't find how to do something like that.

> This allows lots of niceties such as jumping to previous prompts, opening the output of the last command in a new window, etc.

See https://github.com/kovidgoyal/kitty/discussions/4477 for the most obvious usecase.

**Comment by kovidgoyal** [comment]
I dont follow your use case. If you want to browse the output of the last command press ctrl+shift+g which will open it in an overlay window. If you want it in a new window rather than an overlay, create amapping for it, see https://sw.kovidgoyal.net/kitty/launch/

As for the hints kitten it works on what is on the screen currently, which it has to since its visual in nature. You can scroll up and launch the hints kitten to have it hint any particular segment of output.

**Comment by permelin** [comment]
Sorry, my bad.

1. I hadn't noticed that you added `--stdin-source=@last_cmd_output` to `launch`.
2. I didn't know that you could launch with `--type=clipboard`.

That solves everything. Thanks!
