### ISSUE TITLE
`kitty +kitten ssh` disables color with bash

### ISSUE THREAD

**Issue by qiujiangkun** [kovidgoyal/kitty#4602]
![image](https://user-images.githubusercontent.com/33482468/151749860-5662a9fb-c397-4516-a5b4-cff9f5d2fb48.png)
`kssh` is an alias to `kitty +kitten ssh` in my case.

It's obvious that something with term info is not set correctly

**Comment by kovidgoyal** [comment]
the ssh kitten simply copies terminfo files. If you think it is not
doing that correctly copy them yourself as described here: https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer

I highly doubt your issue is caused by terminfo, far more likely you
have some heuristic somewhre in your shell's rc files that's breaking.

**Comment by qiujiangkun** [comment]
I think my terminfo is copied correctly, `.terminfo/x/xterm-kitty` exists.
Rather color in `.terminfo/x/xterm-kitty` is not enabled for me.
