### ISSUE TITLE
SSL errors with themes still

### ISSUE THREAD

**Issue by curtosis** [kovidgoyal/kitty#4628]
#3936 doesn't seem to be fixed on 0.24.2 on macOS 12.1, even with manually downloading cacert.pem and setting the env var (as in https://github.com/kovidgoyal/kitty/issues/3936#issuecomment-899970778).

**Comment by kovidgoyal** [comment]
I dont see how that's possible, and I cannot reproduce. Make sure you are using the official kitty binaries from https://sw.kovidgoyal.net/kitty/binary/

**Comment by curtosis** [comment]
Ahh... looks like it's a problem with the macports build then. Thanks!

**Comment by judaew** [comment]
Hi @kovidgoyal, I'm the kitty maintainer at MacPorts. It looks like the problem occurs for those who do not have curl-ca-bundle as a dependency. I think it would be great to mention this optional dependency on the following page:

https://sw.kovidgoyal.net/kitty/build/#dependencies

**Comment by kovidgoyal** [comment]
It's not a dependency. The dependency is python, with a working ssl
module. kitty simply uses python's urllib to fetch URLs. If ssl is not
working in python, that would affect more programs than just kitty.
If for whatever reason macports python is unable to verify SSL
certificates, then it should be fixed, rather than making kitty depend
on cacerts.
