### ISSUE TITLE
escape codes sent to terminal

### ISSUE THREAD

**Issue by timblechmann** [kovidgoyal/kitty#4659]
not sure if this is a bug or a misconfiguration on my side, but escape codes are forwarded to the shell. e.g. `cmd-left`/`cmd-right` cause `D`/`C` to appear on the shell, while `cmd-a` gives `7;9u`.
in a way i would expect that unhandled escape codes are not forwarded to the shell, but (silently) ignored.

**Comment by kovidgoyal** [comment]
This is a feature. Read
https://sw.kovidgoyal.net/kitty/keyboard-protocol/ 
You should bind those bytes to some meaningful action in your shell
config.

And if you want to disable it, use 
map cmd+left discard_event

in kitty.conf

**Comment by timblechmann** [comment]
fair enough: though i wonder if it makes sense to use `discard_event` as default, considering that there are dozens of possible shortcuts and it's the default behaviour for other terminal emulators as well (principle of least surprise)

**Comment by kovidgoyal** [comment]
Principle of least surprise is trumped by principle of move the
ecosystem forward.

**Comment by timblechmann** [comment]
>  move the ecosystem forward.

i'm not sure if manually editing config files with dozens of duplicate lines is moving forward or backwards. seriously: i haven't seen terminals that echo escape codes for 15+ years :P

**Comment by kovidgoyal** [comment]
Sigh, the terminal isn't echoing the escape code the shell is. And that
is because the shell is part of a stagnant ecosystem that hasn't been
able to add support for even basic key events for *forty* years. Somebody,
somewhere has to give this ecosystem a kick in its pants. Sadly, that
someone is me. So now I have to deal with endless ill-informed, passive
aggressive snark from the legions of internet warriors. Such is the
price of progress.
