### ISSUE TITLE
Glyph display issue

### ISSUE THREAD

**Issue by CarlosEvo** [kovidgoyal/kitty#467]
I know there are issues regarding unicode glyphs, but I am on 9.0.0 and new display issues show up for double width powerline glyphs.

![image](https://user-images.githubusercontent.com/11689106/38965397-6027cc0c-4331-11e8-888d-87d59dbbf9fe.png)

when on colored backgrounds, the second half of the glyph is in the default foreground color (white), while it is set to the color on the left half (black in this case).

I really appreciate your contribution to this cool terminal ❤️

**Comment by kovidgoyal** [comment]
I'm going to need more information that that. What font is this? What unicode codepoint are you using to get those glyphs? Note that if you are using private area unicode codepoints (PUA), this is not going to work, since PUA are single width. kitty has a hack where, if a PUA codepoint is followed by a space, it uses the space as well. So to fix your issue (assuming it is indeed because of PUA) you need to make sure the space following the PUA codepoint also has the correct foreground set.
