### ISSUE TITLE
Font rendering in kitty is different from system's rendering

### ISSUE THREAD

**Issue by tiberiuichim** [kovidgoyal/kitty#47]
I'm using ArchLinux with Plasma 5.9 and I've attached a screenshot from Yakuake, a terminal that uses the Konsole engine. My problem is that the characters are too spaced out and fuzzy.

Left side is Kitty (installed from yaourt -S kitty-git), right side is Yakuake

![kitty-to-yakuake](https://cloud.githubusercontent.com/assets/141568/22773586/9f921d56-eeab-11e6-9481-121dfae37aff.png)

**Comment by kovidgoyal** [comment]
What font is this?

```
fc-match monospace
```

**Comment by tiberiuichim** [comment]
LiberationMono-Regular.ttf: "Liberation Mono" "Regular"

But I've configured it to use "Cousine for Powerline", both terminals use the same font

**Comment by tiberiuichim** [comment]
This is a screenshot with just monospace

![kitty-monospace](https://cloud.githubusercontent.com/assets/141568/22773840/f1dd5098-eeac-11e6-8621-4e9ba3769263.png)

**Comment by kovidgoyal** [comment]
kitty calculates cell width by querying the sizes of all the ascii characters and taking the maximum width from that. See calc_cell_width() in freetype.py. I'm guessing it is because these fonts are not properly monospaced. Probably the underscore character is wider than all the other. You can stick a print statement in that function to confirm.
