### ISSUE TITLE
Unable to get shell integration working correctly (MacOS, Zsh)

### ISSUE THREAD

**Issue by suessflorian** [kovidgoyal/kitty#4788]
**Describe the bug**
Prepending prompts with some sort of escape code `133;A` and command output with `133;C`.

**To Reproduce**
1. Ctrl+Shift+h or Ctrl+Shift+g
2. See escape codes prepended.

**Recording**
https://user-images.githubusercontent.com/23600725/156856048-68ed461a-988c-4ec8-801e-3d4a4252e25d.mov

**Environment details**
```
kitty 0.24.3 created by Kovid Goyal
Darwin florians-mbp-2.lan 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.1 BuildVersion:	21C52
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/floriansuess/.config/kitty/kitty.conf

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_NZ.UTF-8
	SHELL                               /bin/zsh
	USER                                floriansuess
```

**Additional Context**
Escape codes are not prepended upon `shell_integration disabled`.

**Comment by suessflorian** [comment]
Hugely appreciate the work you've done on this terminal @kovidgoyal by the way 🙇‍♂️

**Comment by page-down** [comment]
I can reproduce the issue.

I remember that there was a recent update to `kitty ansi sanitizer`, maybe it has something to do with that?

**Comment by kovidgoyal** [comment]
This is just because less on macOS does not handle OSC escape codes.
Not sure what the best solution for it is. I suppose one could detect
macOS and strip them ourselves. It would be sad to do that since it
means prompts and hyperlinks wont be marked in case the user is using a
more capable pager program than the builtin less. As a workaround if you
install less form brew and use that as your pager, you should be fine.

It's a real shame macOS has such poor basic utilities.

**Comment by suessflorian** [comment]
Oh @kovidgoyal I totally see, well 😅 I was hoping, especially for the fantastic ctrl+shift+g I could start using `nvim` directly as my pager, so I'm not phased here. I'd be happy to close this and leave this issue by blaming macOS?

**Comment by kovidgoyal** [comment]
leave it open for now, let me think about it.

**Comment by suessflorian** [comment]
Hey @kovidgoyal, I've just tried using `less` installed via brew.

```
Documents/my-dotfiles % which less
/opt/homebrew/bin/less
 Documents/my-dotfiles % less --version
less 590 (PCRE2 regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

Still seeing those escape codes 🤔

**Comment by suessflorian** [comment]
Also seeing the escape codes when trying out `nvim` as a pager. Maybe there's something wrong with my machine 🤔... Wondering if other people are running into this.

**Comment by page-down** [comment]
That's because there is no homebrew bin directory in kitty's own environment variable PATH.
So kitty found `/usr/bin/less`, which is still the one that comes with macOS.
Use the following configuration option to add your homebrew bin path.
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.exe_search_path

As for using Neovim as a pager, here is my configuration and it works fine.
https://github.com/kovidgoyal/kitty/issues/719#issuecomment-952039731

**Comment by karlb** [comment]
I also see this problem on Linux with the following versions:
kitty 0.25.0 created by Kovid Goyal
fish, version 3.4.1
less 551 (GNU regular expressions)

**Comment by karlb** [comment]
Yes, it works with less 590. Thanks for the quick reply, I'm really not used to the less version making a difference!
