### ISSUE TITLE
Kitty 0.24.4 breaks Pureline (works fine on 0.24.1)

### ISSUE THREAD

**Issue by mxtm** [kovidgoyal/kitty#4833]
Hello,

I'm using Arch Linux and after updating from Kitty 0.24.1 to 0.24.4 my [Pureline](https://github.com/chris-marsh/pureline) setup totally breaks, despite no other configuration changes. Downgrading back to Kitty 0.24.1 fixes this.

Expected behavior, as on Kitty 0.24.1:

![2022-03-14-120127_691x273_scrot](https://user-images.githubusercontent.com/1544145/158212095-df2bdb08-ecff-47ed-9219-0e5a23a6cbf5.png)

Behavior after updating to Kitty 0.24.4:

![2022-03-14-120229_549x183_scrot](https://user-images.githubusercontent.com/1544145/158212184-6ccf15fa-2b33-43c5-b407-ce619a9ee830.png)

My Kitty configuration is as follows:
```
font_family monospace
font_size 8

enable_audio_bell no

background #262729

color0 #2a2a2a
color1 #f92671
color2 #a6e22e
color3 #fd971f
color4 #1692d0
color5 #9e6ffe
color6 #5e7175
color7 #ffffff
color8 #2f2f2f
color9 #ff669d
color10 #beed5f
color11 #e6db74
color12 #66d9ef
color13 #df92f6
color14 #a3babf
color15 #ffffff
```

AFAIK my configuration for Pureline is just the example configuration. If any changes were made, they were quite minimal.

**Comment by kovidgoyal** [comment]
That will most likely be because it doesnt make use of PROMPT_COMMAND correctly.
Report it there. It needs to check if PROMPT_COMMAND is an array first.
If it's a string it needs to either remove trailing semi-colons from PROMPT_COMMAND
before appending to it or use a newline as separator.

Or turn off shell_integration in kitty.conf.
