### ISSUE TITLE
Drag to resize windows

### ISSUE THREAD

**Issue by pxeger** [kovidgoyal/kitty#4856]
Here by windows I mean kitty windows (panes within a tab), not OS windows.

**Describe the solution you'd like**
When I drag up and down (for horizontal splits) or left and right (for vertical splits) with the mouse on the border between windows, I'd like them to resize.

I think this should snap to exact terminal cell sizes (like `resize_window {direction} 1` already does); allowing adjustable padding between windows would just seem pointless and annoying.

**Describe alternatives you've considered**
I know I could just use keyboard shortcuts to resize the windows, but I prefer the intuition and visual association with dragging with the mouse. This also mirrors almost all other mouse-based window managers.

**Additional context**
I used to use tmux. Kitty's window management features have *almost* completely replaced the feature set of tmux for me (while being less janky), but this is the one feature I'm missing.

**Comment by page-down** [comment]
This also has been on my list for a while.

Previously, this was difficult to achieve because the border was likely to be only one pixel, and it was unacceptable for pixels around the border to not respond to mouse clicks due to this feature.

However, recent versions have added visual window selection, and I think it is possible to implement dragging the border to change the window size on this interface.

**Comment by kovidgoyal** [comment]
This is not something I consider useful myself, but patches are welcome.
As page-down mentions, it would need to have a dedicated mode for
resizing since otherwise it will prevent mouse clicks/drags when window
borders are very narrow.
