### ISSUE TITLE
Use cmd instead of ctrl+shift on macos

### ISSUE THREAD

**Issue by tbodt** [kovidgoyal/kitty#487]
I could just copy all the keybinds from the default config file and replace ctrl+shift with cmd, but that would require manual updating if new keybinds are added in the future. Maybe this could be something similar to i3's config, where it has `set $mod Mod1` at the top and all the keybindings refer to `$mod`, so you can change `$mod` in one place.

**Comment by kovidgoyal** [comment]
You are not going to use a new keybinding unless you somehow become aware of it, at which time you can simply add it to your conf file with whatever binding you prefer.

And note that the reason kitty uses ctrl+shift by default is because that combination cannot be used in terminal programs, so you can simply leave the default definitions around and add cmd shortcuts for those function you actually use. 

And note that adding set $mod Mod1 at the top of your config file is not going to affect the default shortcuts, since those are read before your config file. So I dont see what doing that would achieve?

**Comment by tbodt** [comment]
I do see why kitty uses ctrl+shift. My complaint is that I have to spend 5 minutes remapping keys, on top of the 10 minutes I've spent configuring fonts and colors, before I can actually use the thing. (I'd also appreciate a directory of colorschemes which I could choose from with an `include`, but that's another issue.)

Since, unlike i3, kitty reads both the default and the user config files, there could instead be a `map_mod` config option, defaulting to `cmd` on mac and `ctrl+shift` elsewhere, and mappings could be written as `mod+enter`.

**Comment by kovidgoyal** [comment]
Really, it takes you ten minutes to copy/paste and do a global search and replace? I'm afraid I am not going to change the default modifier based on platform, that means that everywhere in the documentation one has to add per platform caveats.

**Comment by tbodt** [comment]
Thanks 😸

**Comment by gdzien** [comment]
> Really, it takes you ten minutes to copy/paste and do a global search and replace? I'm afraid I am not going to change the default modifier based on platform, that means that everywhere in the documentation one has to add per platform caveats.

Oh, great tried that terminal for a while... guess I will be better off with iTerm in the end, at least developers there are not jerks.
