### ISSUE TITLE
hello how do you set kitty as your main shell?

### ISSUE THREAD

**Issue by fislysandi** [kovidgoyal/kitty#4916]
i scoured trough the wiki and it said that you had to put shell_integration in the conf file but i put that in its still zsh when i open it up is there an actual way to change that? i saw titus do this https://www.youtube.com/watch?v=NdHjsT3FK8w but certainty i will not get an explanation and just be told git gud wich is kinda sad...

i. just. wanna. switch. to. linux.

i wouldnt writing this if you allowed me to chsh -s kitty and thats it.

but i appriciate all your work have done for this project such as ability to prievew images inside of ranger with no to little tweaking.

**Comment by ComedyTomedy** [comment]
It's not clear what you're asking, and you're almost certainly asking it in the wrong place.

You need to know the difference between a Terminal Emulator and a Shell, because you seem to be confused by this. It's sorta analogous to how a webpage runs in a browser. A shell runs in a terminal emulator.

Zsh is your "Shell", the thing that prints "$" and runs the commands you type. Other shells include Bash or Fish.

Kitty is a "Terminal Emulator" meaning the app that provides a window for the shell to run inside. Other examples would be XTerm or URxvt.

`chsh -s` is for changing your default shell, so (for example) if you run `chsh -s bash`, in future it'll be bash instead of zsh that runs inside `kitty`.

Linux can be confusing at first and there's a lot to learn, but it's very rewarding in the long run ☺ good luck with it.
