### ISSUE TITLE
Font symbol rendering issues

### ISSUE THREAD

**Issue by alexruf** [kovidgoyal/kitty#4939]
I recently started to migrate from iTerm2 to kitty.

What I immediately recognized is that kitty seems to have some issues in rendering font symbols (or at least is doing it differently than my old terminal).

iTerm2:
<img width="376" alt="iterm2" src="https://user-images.githubusercontent.com/806969/162414727-d80c4dd1-a1d1-4fd2-ae6f-7157ff6ac97b.png">

kitty:
<img width="376" alt="kitty" src="https://user-images.githubusercontent.com/806969/162414755-974c8655-dde3-4e9e-aab9-2d62dd36bfc0.png">

As a shell prompt, I am using [Starship](https://starship.rs/). The font is [Hack Nerd Font](https://github.com/ryanoasis/nerd-fonts).
I already checked is there is something wrong with my `kitty.config`, but that does not seem to be the case. Using the default configuration gives me the same result.

**Comment by kovidgoyal** [comment]
That's not a rendering issue.  That's a bug in nerd fonts. Where it is incorrectly using an RTL code point for the bomb symbol instead of a PUA code point. Which is why it is being rendered, correctly in kitty in RTL mode. This is supposedly going to be fixed in nerd fonts 3. In the mentime you can either use a different symbol or report the bug to starship/nerd fonts or turn off rtl rendering in kitty.conf with force_ltr

**Comment by alexruf** [comment]
Thank you very much for clarifying and the background information! I will try out the suggested workaround.
