### ISSUE TITLE
XKB compose table error causing high CPU usage

### ISSUE THREAD

**Issue by Lokaltog** [kovidgoyal/kitty#495]
When running kitty 0.9.0 it spams these errors after startup, causing high CPU usage and lag:

```
...
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
[116 22:38:05.713276] [glfw error 65544]: Failed to create XKB compose table
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
[116 22:38:05.714297] [glfw error 65544]: Failed to create XKB compose table
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
[116 22:38:05.715315] [glfw error 65544]: Failed to create XKB compose table
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
[116 22:38:05.716334] [glfw error 65544]: Failed to create XKB compose table
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
[116 22:38:05.717358] [glfw error 65544]: Failed to create XKB compose table
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
[116 22:38:05.718383] [glfw error 65544]: Failed to create XKB compose table
xkbcommon: ERROR: Couldn't read Compose file /usr/share/X11/locale/: No such device
[116 22:38:05.719419] [glfw error 65544]: Failed to create XKB compose table
...
```

This issue happens on version 0.9.0, I'm running the build from the arch community repo. I've tested an older cached build, and this issue does _not_ happen on version 0.8.4. Also, I'm running kitty on a desktop PC and on a laptop, and this issue does not happen on version 0.9.0 on the laptop - an identical error is only printed once and otherwise it works fine. Version 0.8.4 does not print the error message at all on any system.

Both systems are running arch linux and both were updated (and rebooted) today. The main difference between the systems is that I'm running dual monitors on the desktop. I can't recall editing any files in `/usr/share/X11/locale` on any system. I've checked `locale.gen` and run `locale-gen` just in case but it makes no difference.

Pacman logs for libxkbcommon in case it's related, but I've been running kitty for months without any issues related to libxkbcommon:

```
[2017-12-21 23:14] [ALPM] upgraded libxkbcommon (0.7.2-1 -> 0.8.0-1)
[2017-12-21 23:14] [ALPM] upgraded libxkbcommon-x11 (0.7.2-1 -> 0.8.0-1)
```

**Comment by kovidgoyal** [comment]
kitty has switched to using libxkbcommon since 0.9 see the changelog. The only way you can get that output printed multiple times, is if there are multiple XkbMapNotify events being delivered. These events are typically delivers when keyboard keys are re-mapped or layout changed and similar. Presumably you have something on your desktop system that is causing those events. Earlier versions of kitty would simply ignore them, not kitty responds to them.

Track down what is sending those events and stop it and you will be fine. 

And you can fix the libxkb error by fixing your env vars, see for example: https://bbs.archlinux.org/viewtopic.php?id=228658

Note though that fixing the libxkb error will not fix high CPU usage since something on your system is still causing those events to be sent.
