### ISSUE TITLE
Support for background_image_layout centered

### ISSUE THREAD

**Issue by jeffr1975** [kovidgoyal/kitty#4951]
I would like the option for "background_image_layout centered".  Right now it is limited to scaled and tiled.  I would like the background image to be centered, using the native resolution of the image.  There would be just transparent space on all 4 sides of the transparent image.

**Comment by kovidgoyal** [comment]
Not something I am interested in, patches welcome.

**Comment by page-down** [comment]
Previous PR
https://github.com/kovidgoyal/kitty/pull/4167

https://github.com/kovidgoyal/kitty/pull/4167#issuecomment-986010843

> ... I think it makes sense to be able to center the tiled image.
>
> background_image_layout tiled
> background_image_anchor center

Maybe someone would like to re-implement the `background_image_anchor` option.

@jeffr1975
You can now achieve this with the following configuration. (but if a program changes the window logo of the current window, for example by placing it in the four corners, then the center one will disappear/replaced, because it is not the background image)

https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.window_logo_position

> ... using the native resolution of the image ...

You should note that there is still a issue where window logo images cannot be displayed in native resolution on HiDPI monitors.

https://github.com/kovidgoyal/kitty/pull/4167#issuecomment-986010843

> ... it does not support HiDPI. The background image `image@2x.png` uses 4 pixels to display one image pixel on a 4K monitor.

**Comment by jeffr1975** [comment]
Thank you very much @page-down for pointing me in the right direction.  window_logo_path and window_logo_position were all that I needed.  I realized my ubuntu distro package was version 0.21.x which did not have this functionality but I upgraded to 0.24.4 and now I am all set!  Thanks again!  Kitty is the best!
![Screenshot from 2022-04-11 07-30-17](https://user-images.githubusercontent.com/79524510/162740932-13d141eb-ef22-4bd9-a599-8bdc876a6923.png)
