### ISSUE TITLE
Allow setting tab title from command line

### ISSUE THREAD

**Issue by salmankhilji** [kovidgoyal/kitty#4960]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to set the _tab_ title from the main kitty command line.

**Describe the solution you'd like**
Add `--tab-title=TAB_TITLE` command line option to `kitty`.

**Describe alternatives you've considered**
Here is a workaround:
```sh
kitty --session <( cat <<EOF
new_tab MyTabTitle
launch bash --rcfile /my/setup.script
EOF
)
```
**Additional context**
I have setup project various project shortcuts that launch kitty in different configurations.  Each shortcut opens a setup tab, which then runs a script to open additional tabs.  (Since my setup requires some logic, I can not use regular session files.)  Though the script running within the setup tab can contain the `kitty @ set-tab-title MyTabTitle` command, doing so first creates a tab with the wrong (default) title, which is then corrected by the script as soon as it starts running.

Similar in vain to the options passed to the `launch` command, I'd like to be able to set the _tab_ tile from the git-go instead of relying the on program running within the tab to correct it later on.

**Comment by kovidgoyal** [comment]
I dont think this makes sense. It's common to have a single os window
for which setting a title at the invocation time is OK. If one uses tabs
then its always more than one so invocation time is not the correct time
to set the title. And you can have your script set the title of the tab
before creating any new tabs so you will never see the wrong title,
since tab titles are visible only when there is more than one tab
(unless otherwise configured).
