### ISSUE TITLE
Kitty colorspace on macOS is sRGB

### ISSUE THREAD

**Issue by lukepighetti** [kovidgoyal/kitty#5014]
On macOS the colorspace Kitty is using appears to be sRGB, ideally it should be P3 wide, or at the very least, configurable.

**Comment by kovidgoyal** [comment]
Please dont waste my time opening duplicate issues.

**Comment by lukepighetti** [comment]
This issue is not resolved

**Comment by lukepighetti** [comment]
Updated issue, please reopen

**Comment by page-down** [comment]
> ... making colorspace configurable ...

This configuration option has been implemented. Please see the latest associated commit in the first issue you linked to.

Also, I believe a duplicate (because someone has already requested it) issue will not be reopened. This is for better project management and communication (which is preferred by the maintainer).

**Comment by page-down** [comment]
See the recent commits, this has not yet been released.
You can try to configure it in `kitty.conf` after the next nightly release update.

```conf
macos_colorspace displayp3
```
