### ISSUE TITLE
Support "-e" parameter

### ISSUE THREAD

**Issue by fdw** [kovidgoyal/kitty#502]
Most terminals accept a parameter `-e command` or `--exec command` so that the terminal is started with that command instead of the usual shell. Kitty allows the user to do the same with a different syntax: `kitty command`. For better interoperability, I would suggest to add the `-e` parameter.

Examples:
https://linux.die.net/man/1/urxvt
https://github.com/jwilm/alacritty/blob/master/alacritty.man
https://github.com/thestinger/termite/blob/master/man/termite.1

**Comment by kovidgoyal** [comment]
Using -e is strictly inferior. It means you have to quote the entire argument when using anything more than a single command. Why do you need to interoperate terminals anyway? It's not like they are fungible widgets in any case. 

I don't think adding unnecessary complexity to kitty's command line semantics is worth the goal of interoperability in this case. Adding -e would mean making kitty's --help output longer and having two ways to do the same thing. Not to mention the ambiguous semantics of using -e and specifying arguments at the same time.

**Comment by fdw** [comment]
I have several shortcuts set up that start a terminal with a specific command (f.e. [ranger](https://ranger.github.io/) or ssh), and these shortcuts all followed the pattern `$term -e {command}`. So as long as all terminals agree on `-e`, I only have to change `$term`. However, since I switched to Kitty, they didn't work and I had to find and change all shortcuts.

As a user, I like it when all similar applications agree on a quasi-standard and I don't have to go hunting for the difference.

**Comment by kovidgoyal** [comment]
So make ${term} = termite -e or urxvt -e in when using those terminals and just kitty when using kitty.

**Comment by sheegl** [comment]
I think a problem that emerges because of this I think is that kitty cannot be used as the default terminal. For example trying to open a file inside the file manager with terminal vim doesn't work. My guess is that `.desktop` files expect the `-e` argument.

**Comment by AGitBoy** [comment]
That's the problem. To get kitty to work as a default terminal emulator you would have to either patch upstream code for the launching mechanisms to add a specific exception for Kitty, or just add the -e option for the sake of compatibility. Right now I have to manually edit the .desktop files of Ranger and the like to make it openable in kitty:
`Exec=ranger` becomes `Exec=kitty ranger`, and I have to comment out the 'Terminal' line. Kitty is unusable as a default terminal emulator because of this.

**Comment by kovidgoyal** [comment]
Let's see. Both xterm and gnome-terminal can launch programs without using -e. 

And I tried running gnome-terminal -e and this is what it output:

```
gnome-terminal -e cat                                                                   
# Option “-e” is deprecated and might be removed in a later version of gnome-terminal.# 
# Use “-- ” to terminate the options and put the command line to execute after it.#
```

so it seems that gnome-terminal might soon not work with desktop files either. kitty works both with the -- and without it. Let me re-iterate, `-e` is a stupid idea. I am definitely not going to have kitty use it for the command to execute. But, it occurs to me, that there is a way to support this broken use case and not complicate kitty's CLI, I can make -e a dummy argument that kitty simply ignores. That way running kitty -e  xxx will be the same as running kitty xxx. Of course, this means that -e always has to be the last option, but since what we care about here is compatibility with GUI launchers, that should not be an issue.

**Comment by AGitBoy** [comment]
Thanks! KDE uses `-e` for its launchers, which seems to be the issue.
