### ISSUE TITLE
Detecting kitty

### ISSUE THREAD

**Issue by mrzv** [kovidgoyal/kitty#5039]
I would like to be able to detect whether I'm running inside kitty. I was checking that `TERM` is set to `xterm-kitty`, but just got a bug report (mrzv/saturn#1) that boiled down to the user's `TERM` being set to `xterm-24bit`. I see #957, which explains how to query the terminal capability `TN`, which I assume will be set to `xterm-kitty` regardless of what `TERM` is set to (please correct me if I'm wrong), but deciphering the response looks challenging.

Is it reasonable to just hard-code the check for the specific string? Namely, I get `^[P1+r544e=787465726d2d6b69747479^[\`. The numbers inside decode to `xterm-kitty`:
```
>>> from binascii import hexlify, unhexlify
>>> unhexlify(b'787465726d2d6b69747479')
b'xterm-kitty'
```

If I just check equality with the full string, is it something that's going to be stable? Is there a cleaner way to do this without parsing all possible codes?

This is all predicated on me being able to implement `printf '\eP+q544e\e\\'; read` in Python, which has so far eluded me.

**Comment by kovidgoyal** [comment]
There is no way to do this robustly if you are not willing to parse
terminal escape codes. Not to mention that while you are waiting for the
response from the terminal you can easily miss for instance key presses
from the user that will be sent on the same terminal pipe, unless you
parse them or buffer and re-interpret them. Also not all terminals will
respond to this escape code, so you should follow it up with a more
widely supported one, so that once you get the response to that you can
stop waiting for the response to TN. See for example, 
https://sw.kovidgoyal.net/kitty/graphics-protocol/#querying-support-and-available-transmission-mediums

As for how to do it in python, something along the lines of

```python
with open(os.ctermid(), 'wb') as f:
    f.write(the query escape codes)
with open(os.ctermid(), 'rb') as f:
    # read data from f querying for availablity with select and parse it till you
    # get what you need and discard the rest
```
