### ISSUE TITLE
open at current shell directory (not current working directory)

### ISSUE THREAD

**Issue by benjaminBrownlee** [kovidgoyal/kitty#5057]
The current commands `new_window_with_cwd` and `new_tab_with_cwd` can often behave in manners that are generally unhelpful to the user. Instead of opening a new pane at the directory that your shell is at, the terminal will open at whatever the working directory the current running process is at.

As an example, suppose I navigate to a directory and begin editing a python file. When I open the file, nvim attaches a language server which runs at a different working directory. When I finish editing the file, I open the split so I can run it side by side with the code. However, because the pane running nvim is also running a language server that has a different working directory, the split opens at `/usr/lib/node_modules/pyright/dist`, which is not helpful at all. This can happen with many other programs which may run a process in a different working directory.

I noticed that tmux's implementation of this using its `pane_current_path` option does not have this issue, which could offer as a reference point to how we would implement this new feature.

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/launch/#cmdoption-launch-cwd

**Comment by benjaminBrownlee** [comment]
Thanks, I don't know why I did not find this before...

**Comment by glacials** [comment]
@kovidgoyal Thanks for the docs, this helped me with the same issue! Is this something you'd be open to accepting a PR for to change the behavior of `new_*_with_cwd`? The actions feel a bit like traps, because they sound like what I want and at first they perform how I want, until later when I happen to use it during a running process with its own working directory. I'm curious if there's a compelling use case for the current behavior?

**Comment by kovidgoyal** [comment]
The current behavior is the *correct* behavior. Read the discussion linked to above.
