### ISSUE TITLE
Kitty draws red line at the bottom of the window

### ISSUE THREAD

**Issue by wjakob** [kovidgoyal/kitty#506]
Hi,

I've noticed that Kitty sometimes draws a pulsating red line at the bottom of the window (last row of pixels).  It appears and disappears as the cursor blinks and is thus likely related to the cursor drawing code. I wasn't sure if this is a bug or a feature (and how to turn it off in the latter case).

The following video shows what it looks like (you may need to download the video to see it, Dropbox compresses too much in the web preview): https://www.dropbox.com/s/l79uoqkp8wdu7t7/kitty.mp4?dl=0

My Kitty configuration is here in case this helps: https://github.com/wjakob/term-tools/blob/master/config/kitty.conf

The bug appears with a current version compiled yesterday (i.e. Saturday Apr 29, 2018).

Thanks,
Wenzel

**Comment by maximbaz** [comment]
For me it reproduces only with background opacity and a certain font size:

`~/.config/kitty/kitty.conf`:

```
font_size                        10.0
background_opacity               0.95
```

It doesn't happen all the time, but I can reproduce this at least once in 5 times using these steps:

Open chrome (or anything with a white background) and `kitty cat` in tabbed layout, switch back and forth so that kitty is transparent and you see chrome under it. Then type anything in kitty, and as soon as you start typing, the bottom line of white color appears.

It feels that if I open vim instead of cat and move cursor through some colorful text, it will reproduce more often. But I'm not sure this is actually true, maybe it's just a coincidence.

Also, when the bug reproduces, if I increase and then immediately decrease the font size, the line will disappear and the bug will no longer reproduce with this terminal instance.

**Comment by kovidgoyal** [comment]
I'm surprised that background_opacity would have anything to do with it. Are you sure about that? Also seems odd that it is not consistently reproducible. I would certainly expect that it can be worked around by adjusting the font_size (and therefor the cell height) slightly. Also does the tab bar have to be visible for it to reproduce?

**Comment by kovidgoyal** [comment]
See if this makes a difference:
```py
diff --git a/kitty/layout.py b/kitty/layout.py
index 8d31e01b..bda1148e 100644
--- a/kitty/layout.py
+++ b/kitty/layout.py
@@ -254,7 +254,7 @@ def top_blank_rect(w, rects):
 
 def bottom_blank_rect(w, rects):
     b = w.geometry.bottom
-    if b < central.bottom:
+    if b <= central.bottom:
         rects.append(Rect(central.left, b, central.right + 1, central.bottom + 1))
 ```

**Comment by maximbaz** [comment]
I definitely cannot reproduce it without `background_opacity: 0.95`, tab bar does not have to be visible, and the patch above seems to fix the issue 👍

**Comment by wjakob** [comment]
Thanks -- I've merged your patch and will keep an eye out (it happened only occasionally, so it may take me a few days to confirm).
