### ISSUE TITLE
copy_to_clipboard fails to copy

### ISSUE THREAD

**Issue by Sohex** [kovidgoyal/kitty#5061]
**Describe the bug**
I'm unable to copy from kitty using copy_to_clipboard (or copy_or_interrupt).

**To Reproduce**
1. Highlight text
2. Press ctrl+shift+c
3. Press ctrl+shift+v and see nothing get pasted.

**Environment details**
I can't paste the debug output here because it fails to copy to my clipboard. I'm using kitty 0.25.0 on Sway on Arch Linux.
My config is:
```
include /home/sohex/.config/kitty/gruvbox-dark.conf
sync_to_monitor yes
touch_scroll_multiplier 5.0

map f1 copy_to_buffer a
map f2 paste_from_buffer a

copy_on_select clipboard
map ctrl+c copy_or_interrupt
```

**Additional context**
copy_on_select successfully copies text to the clipboard. Running kitty with debug-input shows that the copy_to_clipboard event is firing.
```
KeyPress matched action: copy_to_clipboard
handled as shortcut
```

**Comment by kovidgoyal** [comment]
I cannot replicate on sway. copying and pasting works fine with kitty
0.25.0 with the following steps:

1) Start kitty --config NONE
2) run a command
3) select some text
4) press ctrl+shift+c
5) press ctrl+shift+v 
6) text is pasted as expected

5) also works with gnome-terminal instead of kitty.

Run kitty form a terminal and see if any errors are printed to stderr.
Other than that I dont have any suggestions for you.

**Comment by Sohex** [comment]
Nothing printed to stderr running from another terminal and I was able to copy from other terminals fine, the issue was only occurring with kitty. After a reboot it's working again though, so I'll just chalk it up to gremlins. Thanks for looking though!
