### ISSUE TITLE
Tab Bar should make full use of window width

### ISSUE THREAD

**Issue by philiprhoades** [kovidgoyal/kitty#5092]
The Tab Bar should make full use of the window width - eg some wider than normal tab titles should expand to full text width if the space is available on the Tab Bar.

eg Here is the Tab Bar of one of my regular windows - except that the pipe characters are equidistant and with a small point size font, there is appropriate space padding:

2_curr | newsboat | ytd | bookmarks | vimwiki | txts | tabfern | bisq | bin | log | src | github | gitlab | ruby | jekyll | rails | wasm | curr | curr

This Tab Bar only uses about 75% of the width of the window (I use Sway and all my windows are full screen) - that is fine.  However, if I enlarge the font of the window with a few CTRL-SHIFT-+ , the Tab Bar then looks like this:

2_curr | new... | ytd | boo... | vim... | txts | tab... | bisq | bin | log | src | git... | git... | ruby | jek... | rai... | wasm | curr | curr

BUT, the Tab Bar still only takes up about 90% of the window width - it should use 100% of it to fit as much as possible of tab names into the bar.

Does this make sense? - I can do some screen captures if it doesn't . . 

Thanks for Kitty - I love it!

**Comment by kovidgoyal** [comment]
as far as I know the tab bar does use all available space. If you can
come up with some reproducible scenario where it doesnt, feel free to
update this ticket and I will take a look. In order to do that,
create a kitty session file to create the tabs with custom titles and
run it as

kitty --config NONE --session tabs.session -o remember_window_width=no

Post the session file and the width of the terminal in cells which you
can get by running 

tput cols
