### ISSUE TITLE
Font rendering issue

### ISSUE THREAD

**Issue by rncar** [kovidgoyal/kitty#516]
Maybe is something stupid, but I cant find a solution for this,
some kind of strechy fonts.

I was trying `adjust_line_height` and `adjust_column_width`.
Other fonts. ( [Luculent](http://eastfarthing.com/luculent) in the screenshot )
No luck.

I am using a monitor in vertical mode (rotated), I dont know if this will help.
Arch linux.

![screen](https://user-images.githubusercontent.com/12891839/39555846-76094536-4e7c-11e8-8dfc-a085fccd85d8.png)

My kitty.conf
```
font_family      Luculent
italic_font      auto
bold_font        auto
bold_italic_font auto
font_size        20.0
```

Great project, by the way.

**Comment by kovidgoyal** [comment]
Does your monitor have highly different xdpi/ydpi? Does it work if the monitor is not rotated?

**Comment by rncar** [comment]
Kitty works fine when not rotated.

**`xrand`**
```
DP-3 connected 1600x2560+0+0 left (normal left inverted right x axis y axis) 641mm x 400mm
```

**`xdpyinfo | grep -B 2 resolution`**
```
screen #0:
  dimensions:    1600x2560 pixels (655x412 millimeters)
  resolution:    62x158 dots per inch
```


**`grep DPI /var/log/Xorg.0.log`**
```
[     9.074] (--) NVIDIA(0): DPI set to (62, 158); computed from "UseEdidDpi" X config
[     9.397] (==) modeset(G0): DPI set to (96, 96)
```

**Comment by kovidgoyal** [comment]
The problem is almost certainly the weird DPI

```
DPI set to (62, 158)
```

IIRC glfw, the toolkit kitty uses supports overriding DPI via Xft.dpi You can use that in your rotate script to correct the DPI kitty gets. Use xrdb to set it and glfw should pick it up automatically after that. This of course means that you will have to restart kitty after a rotation, but I dont really see a way around that given that the DPI reported by X is wrong.

**Comment by rncar** [comment]
Working like a charm just adding `Xft.dpi: 96` to `.Xresources`.
Thanks for the help.
A new happy Kitty user.
