### ISSUE TITLE
Background opacity on Mac OS?

### ISSUE THREAD

**Issue by kammerdienerb** [kovidgoyal/kitty#517]
Using the most recent build for Mac OS, I built kitty and successfully configured it to my liking. It is great, but the background_opacity option just makes my background lighter. The comments in the configuration file say that it only works for systems that support window transparency. Scanning through the code, the cocoa backend seems to implement opacity.. what gives?

**Comment by kovidgoyal** [comment]
transparency works fine on my macOS machine. Presumably something is messed up in the graphics drivers on your machine. I'm not a macOS guru so I can't help with that. Look in console.app for an error messages from kitty or run kitty from a terminal as

/Applications/kitty/app/Contents/MacOS/kitty --debug-gl

and see if you get any errors. Although, for this kind of thing, I suspect the problem is in a lower level than kitty.
