### ISSUE TITLE
Support for font style variants like italic

### ISSUE THREAD

**Issue by imyxh** [kovidgoyal/kitty#523]
Alright, sorry if I misunderstand this, but as I see it you can't specify italic fonts as a variation of the regular font file, at least for OpenType/TrueType collections.
For example, I have the Iosevka typeface installed (which is also affected by #297), and when I press `ctrl+i` in LibreOffice it'll change it to the italic variant. But kitty seems to require me to specify a font name in kitty.conf, and since I don't have a font file explicitly named "Iosevka Italic" (LibreOffice confirms this) I can't make italic fonts work.

Here are some of my configurations, with the light variant used as an example for brevity in `grep`. The same issue carries to Fira Code and other Iosevka fonts.

    $ fc-list | grep "Iosevka Term Light" | grep Italic
    /usr/share/fonts/TTF/iosevka-light.ttc: Iosevka Term,Iosevka Term Light:style=Light Italic,Italic

    $ kitty --debug-config | grep Iosevka
    bold_font            Iosevka Term Bold
    bold_italic_font     Iosevka Term Bold Italic
    font_family          Iosevka Term Light
    italic_font          Iosevka Term Light Italic

    $ kitty list-fonts | grep "Iosevka Term Light" | grep Italic
        Iosevka Term Light Italic

I also tried another method but I think you should just see for yourself:
![image](https://user-images.githubusercontent.com/12703838/39668259-a3265d80-507d-11e8-9764-66e494c364ae.png)
Same thing happens with Fira Code, of course.

**Comment by kovidgoyal** [comment]
Iosevka is a pretty bad font it's not actually designed for monospace, dont use it. If you want to use an italic font use one that is actually designed to be used as a monospaced font. That means its regular and italic variants have to have the same character widths. As far as I know, Fira Code has no italic variant at all. It has only normal and bold variants. So if you want to use it, you have to find an italic font that has the same metrics as it does. 

For example, here is a screen shot with DejaVu Sans the following config:

```
kitty -c NONE -o font_family=DejaVu\ Sans
```

![screenshot_20180506_082043](https://user-images.githubusercontent.com/1308621/39669334-94bdba84-5106-11e8-948c-6c02094c2e49.png)

No need to manually specify the italic variant and no rendering issues. And here is one with Operator Mono

![screenshot_20180506_082333](https://user-images.githubusercontent.com/1308621/39669346-cf8b57d4-5106-11e8-8c08-f013021e1e7c.png)

Italic fonts in a truly monospaced context like kitty are tricky. The font designer has to make sure that the italics characters actually fit in the exact same width as regular characters, otherwise you get rendering artifacts. Most GUI programs such as LibreOffice are not actually monospaced they happily use whatever widths the font needs for individual characters. 

Finally, if for some reason you really, relly want to use Iosevka, you can work around it by using the adjust_column_width setting. This means there will be extra spaces around regular characters, but the italic characters will fit.

**Comment by imyxh** [comment]
Oh, alright. I was wondering why it would work with Qterminal but not kitty; is it that kitty is more strict about monospace than other terminals?

**Comment by kovidgoyal** [comment]
Yes, kitty actually renders things in a character grid and manages to achieve its great performance by doing that (it stores alpha masks of each character in a GPU cache so it only ever needs to a render a character once). Qt based terminals (like konsole and qterminal) are "unique" in that they render text like a GUI app instead of in a character grid (they basically draw things a line at a time instead of a character at a time, using Qt's text APIs). This gives them terrible performance and lots of cursor movement bugs.

**Comment by SammysHP** [comment]
> For example, here is a screen shot with DejaVu Sans the following config:
> 
> ```
> kitty -c NONE -o font_family=DejaVu\ Sans
> ```
> 
> ![screenshot_20180506_082043](https://user-images.githubusercontent.com/1308621/39669334-94bdba84-5106-11e8-948c-6c02094c2e49.png)

Several years later, but if someone finds this issue looking for a solution to bad DejaVu font rendering: **The example from @kovidgoyal doesn't show DejaVu Sans Mono!**

Here is a comparison. DejaVus Sans Mono at the top, the example from @kovidgoyal below. The reason for this is that the font is not named `DejaVu Sans` but `DejaVu Sans Mono`. See `G` or `Q` for the differences.

![20231117_193918](https://github.com/kovidgoyal/kitty/assets/922874/ac69749d-ee25-46ed-a622-3ae40beac7af)

Unfortunately DejaVu uses font properties that do not work well with grid based rendering (which is a design decision of kitty that we have to accept because everything is based on it).

(Now my question is: What font was actually used in the example in 2018?)
