### ISSUE TITLE
Pureline and trueline not rendering

### ISSUE THREAD

**Issue by HunterretnuH** [kovidgoyal/kitty#5254]
Hi,
I've been using kitty for a few years now together with pureline and it was working flawlessly.
Around a year ago it just stopped appearing and my prompt started looking like this:
![image](https://user-images.githubusercontent.com/48928894/177858513-7dfe8337-761f-440c-af2d-1892e65f4573.png)

I'm sourcing required script at the end of my .bashrc:
`~/Self_compiled/pureline/pureline ~/.pureline.conf`
I'm sure that script is sourced as expected (I just added echo command to it for verification).
I also have gnome-terminal currently installed and it works well when I use it.

If the script is sourced manually (by just pasting the same line that is added to .bashrc into terminal) after starting terminal then everything works, but not when it's sourced in .bashrc.

Today I decided to "fix it" by using different powerline as I planned to change pureline to something else for a long time.
I decided to use trueline, but it has exactly the same problem. The only difference is that there is completely no prompt (just a cursor).

It also works fine when sourced manually.

I tested it with empty kitty.conf and empty .bashrc but there was no difference and I don't have any good idea what else I could check.

Can you please verify if this problem is specific to my machine or maybe there exist some compatibility issue with kitty and these bash powerline scripts.

I'm using Archlinux 5.18.5 and kitty 0.25.2. Of course I can provide any required additional information.

**Comment by kovidgoyal** [comment]
It will almost certainly be caused by those scripts not using PROMPT_COMMAND correctly. In bash the way to use PROMPT_COMMAND is to check first if it is empty, if so set it as an array, otherwise check if it is already anarray and if so append to it and finally if it is not an array to remove any trialing spaces and semi-colons from it and then append a semi-colon and your command to it. See kitty.bash in the kitty source code for an example.

**Comment by HunterretnuH** [comment]
Thanks for an advice. I checked the way PROMPT_COMMAND is set and it may not be fully correct, but it's not the reason why these scripts are not working. The reason it's not working is that there are variables declared using `declare` keyword in these scripts and they are missing when it's sourced in `.bashrc`.

I've found that if I use `declare` to declare a variable and assign value to it in `.bashrc` then it won't work.

EXAMPLE 1:
1.Add this line to `.bashrc`: `declare TEST_VARIABLE=1`
2.Open new kitty terminal.
3.`set | grep TEST_VARIABLE`
4.TEST_VARIABLE won't be found.

EXAMPLE 2:
1.Add this line to `.bashrc`: `TEST_VARIABLE=1`
2.Open new kitty terminal.
3.`set | grep TEST_VARIABLE`
4.TEST_VARIABLE will be found.

EXAMPLE 3:
1.Add this line to `usr/lib/kitty/shell-integration/bash/kitty.bash`: `declare TEST_VARIABLE=1`
2.Open new kitty terminal.
3.`set | grep TEST_VARIABLE`
4.TEST_VARIABLE will be found.

It doesn't look like expected behavior, but I'm not an expert here. 

One of the differences between creating variable normally compared to using `declare` keyword is that variables created using `declare` will be local to the function they are created in (there is even note regarding that in line 72 of `kitty.bash`). There seems to be some difference between the way `kitty.bash` and `.bashrc` are sourced. I don't know how exactly is sourcing of `.bashrc` handled during kitty initialization but maybe it is wrapped in some function and it causes these variables to be lost.

Could you share your thoughts about this?

**Comment by kovidgoyal** [comment]
Ah yes, this is a limitation of bash. See https://stackoverflow.com/questions/2891473/bash-function-source-declare-boom
and https://stackoverflow.com/questions/49772668/why-are-bash-variables-not-global-if-sourced-script-runs-in-a-function

Your prompt scripts should be modified to use declare -g instead of
plain declare when wanting to create global variables. They cannot
assume they are not being sourced inside a function.

BASH provides no way that I know of to be able to source a file from
inside a function and still have it be in global scope, so there is
nothing kitty can do here.

**Comment by kovidgoyal** [comment]
On second thoughts, it may be possible to do the sourcing outside any functions, though that will make the code a lot uglier.
