### ISSUE TITLE
Automated Text Input Gets Transformed into All Lowercase

### ISSUE THREAD

**Issue by Lonniebiz** [kovidgoyal/kitty#5353]
kitty 0.19.3
debian 11
autokey 0.95.10

When I input commands into kitty via [Autokey](https://github.com/autokey/autokey), all uppercase letters get transformed into lowercase, causing any case-sensitive command (with capital letters) to fail. Here's a [video](https://youtu.be/hW_GEHk5HGc) of the behavior.

**Comment by kovidgoyal** [comment]
I'm afraid I have no interest in debugging autokey. If you want to send
text to kitty, kitty has extensive native capabilities for that already.
https://sw.kovidgoyal.net/kitty/remote-control/

**Comment by Lonniebiz** [comment]
I'm not asking you to debug autokey, my friend. I'm requesting that you debug kitty. Other terminal emulators do not exhibit this unwanted behavior. The bug is in kitty (not Autokey).

Plus those native capabilities you mention cannot follow me into the remote computers that I administer. Nor do they follow me into every application I use that is not kitty. With autokey, I can RDP into a remote windows server and automate text input into any application on that remote computer as well. So, if I have to pick between kitty and autokey, kitty loses.

With that say, I do like the way kitty renders and scales text. If it didn't have this bug, I'd probably use it.

**Comment by kovidgoyal** [comment]
No, the bug is in AutoKey. It will likely be using the broken ass hack
called XTEST to do what it does. As I said I have no interest in
debugging it. I strongly suggest you don't rely on workflows that depend
on XTEST. I provide robust, well designed interfaces to send text to
kitty. If you dont want to use them, that's your lookout. They work
remotely, locally and completely robustly, unlike autokey.

And, my friend, if you don't want to use kitty, feel free not to
use it. You are not doing me a favor by using it.

**Comment by Lonniebiz** [comment]
@kovidgoyal : No problem:
`sudo apt purge kitty`

Done.

**Comment by kovidgoyal** [comment]
@Lonnie Best

Lonnie Best > /dev/null

Goodbye.
