### ISSUE TITLE
Selected item in bash history is hard to read due to colors in light themes 

### ISSUE THREAD

**Issue by mrueegg** [kovidgoyal/kitty#5388]
**Describe the bug**
When I use a light theme with Kitty, the selected item in the bash history completion is very hard to read.
I tried different kinds of light themes ,the behavior is the same.
Is there a way to override the color used for the selected item in the history completion? 

**To Reproduce**
1. Ctrl+r
2. type some text
3. scroll up/down through history completion list
4. highlighted element is very hard to read due to coloring

**Screenshots**
![image](https://user-images.githubusercontent.com/206944/185091808-b2b41f61-d4aa-451d-92ce-faa2edebfeed.png)

**Environment details**
Kitty 0.25.2
[PaperColor Light theme](https://github.com/craffate/papercolor-kitty/blob/master/papercolor-light.conf)

**Additional context**
Kitty is awesome :-)

**Comment by kovidgoyal** [comment]
The colors come from bash, not kitty. You need to change them there. You
can also remap the colors in kitty.conf but that will change them for
everything, not just the history list.

**Comment by mrueegg** [comment]
@kovidgoyal Thanks for the swift response. 
Do you have any pointer for me which bash color affects the history list?
I couldn't find that so far.

**Comment by kovidgoyal** [comment]
No clue, sorry, I dont use bash

**Comment by page-down** [comment]
Related feature request discussion:
Accessibility: Enhanced contrast (TL;DR: No)
https://github.com/kovidgoyal/kitty/issues/5278

@mrueegg
This appears to be fzf, not a built-in feature of bash. You need the following link.
https://github.com/junegunn/fzf/wiki/Color-schemes

@kovidgoyal
Do you think the user could use the custom `marker` feature to improve such problems?
Find all cells with insufficient contrast and mark them with a color that is dynamically calculated (based on the value of the current fg color and bg color of each cell).

That said, I think the root cause should be addressed rather than using such hacks.

**Comment by mrueegg** [comment]
@page-down Thanks, changing the fzf colors by applying the PaperColor theme did the trick.
For future reference: here's a list of fzf color themes: https://github.com/junegunn/fzf/wiki/Color-schemes
