### ISSUE TITLE
URLs invisible on "text hints" screen with Solarized Light colors

### ISSUE THREAD

**Issue by mbunkus** [kovidgoyal/kitty#541]
I'm using the Solarized Light colors (see below for corresponding config entries). With these settings, URLs become invisible on the "text hints" screen when trying to open an URL with the keyboard. Here's an example how it looks in regular operation and in "text hints" mode:

Regular:
![deepinscreenshot_select-area_20180516081157](https://user-images.githubusercontent.com/414282/40099708-6c3ae70c-58e1-11e8-937d-428309edb55c.png)

"Text hints":
![deepinscreenshot_select-area_20180516081212](https://user-images.githubusercontent.com/414282/40099712-7127b9ac-58e1-11e8-9107-96db7ffb1b82.png)

While this isn't a problem if there's only a single URL visible, I often have a dozen or more URLs visible, making it hard to distinguish between them.

Ideally the color used by the hints should be configurable. The default `kitty.conf` doesn't seem to contain a setting for that, unfortunately.

My environment:

Arch Linux, 64-bit
kitty from Arch packages, v0.9.1-1

My color configuration:

```
###### Solarized Light
foreground #657b83
selection_foreground #586e75
background #fdf6e3
selection_background #eee8d5

color0 #073642
color8 #002b36
color1 #dc322f
color9 #cb4b16
color2 #859900
color10 #586e75
color3 #b58900
color11 #657b83
color4 #268bd2
color12 #839496
color5 #d33682
color13 #6c71c4
color6 #2aa198
color14 #93a1a1
color7 #eee8d5
color15 #fdf6e3
```

**Comment by kovidgoyal** [comment]
URLS are highlighted using the "intense white color" which is color15. Fix your theme to not use the background color for intense white and you will be fine.

**Comment by mbunkus** [comment]
Always using "intense white" makes the assumption that the background color is dark. It would make much more sense to either base the decision which color to use on the setting of the background color (if the background color is dark, use intense white; if background is light, use e.g. intense black) or let the user configure the color used.

What you're basically saying amounts to "kitty doesn't support themes with light background colors".

**Comment by kovidgoyal** [comment]
No I'm saying that if you are using a light color theme, use a non-broken one. i.e one that sets intense white to intense color7 when using a light background color. Your color them has to maintain the contrast invariants of the first 16 colors, otherwise it is terminally (pun-intended) broken. That means color0 should be the background and color7 should be the foreground and color 15 should be the intense foreground.

**Comment by SevereOverfl0w** [comment]
Hi, I followed up with this with my theme author, who pointed me at: http://pod.tst.eu/http://cvs.schmorp.de/rxvt-unicode/doc/rxvt.7.pod#XTerm_Operating_System_Commands

Which is very clear that color0 should be black, and color7 should be white.  They have no relation to the background/foreground.  Is there another resource you're using which contradicts this one?

**Comment by kovidgoyal** [comment]
According to that link you posted, which I quote here:

```
Numbers 0-7 corresponds to low-intensity (normal) colours and 8-15 corresponds to high-intensity colours. 0=black, 1=red, 2=green, 3=yellow, 4=blue, 5=magenta, 6=cyan, 7=white
```

color15 is the "intense" variant of color7, color7 is supposed to have maximal contrast with color0 (of the first 8 colors). Therefore, logically, color15 must have greater contrast with color0 to be more "intense". Otherwise it is not more intense but instead less intense. In other words if color0 if black color8 should be "blacker" and if color0 is white color8 should be "whiter", similarly for the color7/color15 pair

**Comment by SevereOverfl0w** [comment]
But that has no effect on the foreground/background contrast.  In this case the URL is colored assuming that there's going to be contrast between color7 & background, but for light color schemes that isn't the case.

**Comment by kovidgoyal** [comment]
On Sun, Jun 07, 2020 at 05:25:26AM -0700, Dominic Monroe wrote:
> But that has no effect on the foreground/background contrast.  In this case the URL is colored assuming that there's going to be contrast between color7 & background, but for light color schemes that isn't the case.

And that's exactly the point, your light color scheme is not maintaining
the contrast relationships of the basic colors.

**Comment by SevereOverfl0w** [comment]
Every light color scheme has to reduce the contrast between color0 and the background.  It wouldn't be possible to have a light background with white on it otherwise.

**Comment by kovidgoyal** [comment]
Shrug, you want to insist that light color schemes should sacrifice readability in the name of maintaining hue values, that's your perogative. I disagree.

**Comment by SevereOverfl0w** [comment]
I'm not saying they should sacrifice readability. I use them because they improve readability.

I'm saying that if they want to follow the spec, and have color7 be white _and_ have the background be white (which the spec doesn't mention, so there's no assumption of contrast between them unless you're assuming a dark colour scheme) , then the url hinting will never work.

One easy solution is to enforce your assumption that color7 is the background, and set that for urls in hint mode. It's not my preferred solution as I find it harder to read text in that style, but it's better than unreadable.

**Comment by kovidgoyal** [comment]
On Mon, Jun 08, 2020 at 12:39:50AM -0700, Dominic Monroe wrote:
> I'm not saying they should sacrifice readability. I use them because they improve readability.
> 
> I'm saying that if they want to follow the spec, and have color7 be white _and_ have the background be white (which the spec doesn't mention, so there's no assumption of contrast between them unless you're assuming a dark colour scheme) , then the url hinting will never work.

What spec? What you linked to is just a URXVT man page. There is no spec
I have ever heard of that assigns fixed colors to numbers. And if there
were your light color scheme would already violate it since I am pretty
certain it does not follow this putative specs values for colors.

> 
> One easy solution is to enforce your assumption that color7 is the background, and set that for urls in hint mode. It's not my preferred solution as I find it harder to read text in that style, but it's better than unreadable.

An easier solution is to use a better light color scheme.

**Comment by SevereOverfl0w** [comment]
I was curious to go read, wikipedia pointed me at this standard which names the colours https://www.ecma-international.org/publications/standards/Ecma-048.htm 

I'm not certain that this is actually correct though?

**Comment by kovidgoyal** [comment]
The ECMA 48 standard is indeed the relevant standard, but it has nothing
to say about how colors should be mapped in themes. All it tells you is
the default values for the first eight, not even the first 16 numeric
codes.

Let me try to get this across one final time. The way terminal color
themes work is by re-assigning the first 8 or 16 or for better themes,
all 256 colors. Terminal applications are not supposed to be theme
aware. The idea is that terminal applications use the color slots,
without knowing their actual RGB values and things just work assuming
those RGB values have been carefully chosen. Now sadly there is no slot
labelled "background" and "foreground" in any standard, but de facto,
the background and foreground colors are assumed to be slot 0 and 7
respectively. If a theme is changing the background and foreground colors
while breaking that assumption, it is going to break any terminal
application that tries to use the users colors instead of defining its
own.

The *only* way for a terminal application to ask for "more intense
foreground color" is to ask for color 15. Your theme is breaking that.

**Comment by SevereOverfl0w** [comment]
> All it tells you is the default values for the first eight,

This doesn't seem right.  It doesn't seem to mention "default" in the text around SGR at all.  30 is just "black display".

I had a search around and https://iterm2colorschemes.com/ has 30 as consistently black. https://github.com/alacritty/alacritty/wiki/Color-schemes uses "black" to configure color0 but it seems to vary from scheme to scheme whether set a light colour for black.  Gruvbox works as you say, color0 is white, but solarized has color0 as black.  It does seem odd to me to have both 30 as black and 39 as default, if they're intended to be the same.

I'm really struggling to figure out if the premise (that color0 and foreground are the same) is true.  I don't see any indication that it is the case in classical standards. I haven't been able to find supportive evidence online for color0 and foreground to be equivalent.  Maybe I'm not looking in the right places, it would be useful to have a link to share with theme authors to explain how it should be done.

> Let me try to get this across one final time.

I appreciate you taking the time to go back & forth with me on this.  I'm not trying to be difficult :smile:.  I've been struggling to understand the broader point here.  In my experience, most tools allow some form of configuration for colours and I'd assumed it's just part of how a terminal application has to function.  Your point below got it through to me.

> Terminal applications are not supposed to be theme aware.
> The only way for a terminal application to ask for "more intense foreground color" is to ask for color 15. Your theme is breaking that.

Makes sense, there's a request you're trying to make of the environment, and it isn't available.

**Comment by kovidgoyal** [comment]
On Mon, Jun 08, 2020 at 05:29:38AM -0700, Dominic Monroe wrote:
> > All it tells you is the default values for the first eight,
> 
> This doesn't seem right.  It doesn't seem to mention "default" in the text around SGR at all.  30 is just "black display".

Yes, terminals in those days were not themeable at all. Hence the
standard is entirely silent on themeing, and you cant really derive
meaning about how themes should behave from it. In a themeable context,
the colors can really only be interpreted as defaults. If you treat them
as absolutes, then themes can change only the background and foreground,
and I think you will find no real-world theme does just that.

> > Let me try to get this across one final time.
> 
> I appreciate you taking the time to go back & forth with me on this.  I'm not trying to be difficult :smile:.  I've been struggling to understand the broader point here.  In my experience, most tools allow some form of configuration for colours and I'd assumed it's just part of how a terminal application has to function.  Your point below got it through to me.

No worries, I enjoy the occasional debate, sharpens my understanding of
things to have to explain them.

> 
> > Terminal applications are not supposed to be theme aware.
> > The only way for a terminal application to ask for "more intense foreground color" is to ask for color 15. Your theme is breaking that.
> 
> Makes sense, there's a request you're trying to make of the environment, and it isn't available.

**Comment by rafalglowacz** [comment]
I run into this thread before finding out that the hints kitten has on option for it nowadays, so just for reference, it's `--hints-text-color` as documented on [the kitten's page](https://sw.kovidgoyal.net/kitty/kittens/hints/) and it can be used to fix the invisible hints without swapping black and white in the base color palette.

**Comment by mb720** [comment]
To expand on @rafalglowacz comment: Since `open_url_with_hints` seems to be a synonym for `kitten hints` (according to [this](https://github.com/kovidgoyal/kitty/blob/a04d19df4afd2ada6b783a50b5ebe024f6005592/kitty/boss.py#L2084)), I settled on the following mapping for using a different color when selecting URLs:

    map kitty_mod+e kitten hints --hints-text-color green
