### ISSUE TITLE
0.26.0 has cursor placement issues with oh my posh

### ISSUE THREAD

**Issue by recursiveribbons** [kovidgoyal/kitty#5437]
**Describe the bug**
No problems in 0.25.2

Starting 0.26.0, when used with Oh My Posh, Kitty places the cursor in strange places. Backspace also breaks the placement completely.

Something must have changed in-between the two versions.

**To Reproduce**
1. Install Kitty (no config required)
2. Install Oh My Posh (no config required)
3. Have a situation where the prompt is slightly longer (e.g. a longer git branch name)
4. The curser is in weird locations

**Screenshots**
Here, the curser is on the first spot on the second line, before the letter n

<img width="640" alt="Screenshot 2022-08-29 at 11 03 20" src="https://user-images.githubusercontent.com/18372809/187165816-cf58cc8e-ed84-4e64-9635-955c9c75e980.png">

**Environment details**
```
kitty 0.26.0 created by Kovid Goyal
Darwin Robins-Work-MacBook.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	12.5.1 BuildVersion:	21G83
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config files:
  /Users/robin/.config/kitty/kitty.conf

Config options different from defaults:
background_opacity   0.9
font_family          FiraCode Nerd Font Mono
font_size            13.0
remember_window_size False
Colors:
	background           #2e3440   
	color0               #3b4252   
	color1               #bf616a   
	color10              #a3be8c   
	color11              #ebcb8b   
	color12              #81a1c1   
	color13              #b48ead   
	color14              #8fbcbb   
	color15              #eceff4   
	color2               #a3be8c   
	color3               #ebcb8b   
	color4               #81a1c1   
	color5               #b48ead   
	color6               #88c0d0   
	color7               #e5e9f0   
	color8               #4c566a   
	color9               #bf616a   
	cursor               #81a1c1   
	foreground           #d8dee9   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                robin
```

**Additional context**
The problem is reproducable with `kitty --config NONE` and a fresh install (no configs) of Oh My Posh

**Comment by kovidgoyal** [comment]
Nothing has changed in wcwidth calculations in years in kitty. And this
will almost certainly be because you are using a bunch of symbols in
your prompt whose widths whatever shell you are using is getting wrong.
The mismatch in the expected width and the actual width will cause this.

I'm afraid I am not going to install ohmyposh just to test this. If you
can provide the value of PS1 I will see if I can reproduce.

**Comment by page-down** [comment]
I don't use oh my posh, but I installed kitty 0.26.0, oh-my-posh 8.36.5 specifically to test this, and it worked fine according to your reproduction steps.

You can try updating all software to the latest and removing the zsh rc file to confirm if the problem still exists.

Not related to this issue:
Instead of using patched fonts, it is recommended to use standalone Nerd Font symbol font, as described in the FAQ.
https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font
