### ISSUE TITLE
Font spacing different between hi-DPI/regular on macOS

### ISSUE THREAD

**Issue by mcmillion** [kovidgoyal/kitty#5454]
**Describe the bug**
Font spacing is different depending on DPI (or at least between a regular 1440p monitor and Retina laptop screen):

![Screen-Shot-2022-08-31-at-4 53 03-PM](https://user-images.githubusercontent.com/717799/187793293-e2b6309c-0c59-4423-aeff-af32584d5bb5.jpg)

**To Reproduce**
1. Move kitty between retina and non-retina screens

**Environment details**
```
kitty 0.26.1 created by Kovid Goyal
Darwin Chozo.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:23 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T6000 arm64
ProductName:	macOS ProductVersion:	12.5.1 BuildVersion:	21G83
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/zsh
Loaded config files:
  /Users/mlm/.config/kitty/kitty.conf

Config options different from defaults:
active_tab_font_style   (False, False)
bold_font               JetBrainsMono Nerd Font Bold
bold_italic_font        JetBrainsMono Nerd Font Bold Italic
confirm_os_window_close 0
font_family             JetBrainsMono Nerd Font Regular
font_size               14.0
italic_font             JetBrainsMono Nerd Font Italic
macos_option_as_alt     3
macos_titlebar_color    1
shell_integration       frozenset({'disabled'})
tab_bar_style           separator
tab_separator           |
tab_title_template       {title} 
window_margin_width     FloatEdges(left=6.0, top=6.0, right=6.0, bottom=6.0)
Removed shortcuts:
	cmd+enter →  new_window
Changed shortcuts:
	cmd+- →  change_font_size all -1.0
	cmd+= →  change_font_size all +1.0
Colors:
	active_tab_background   #2c323d   
	active_tab_foreground   #979eab   
	background              #282c34   
	color0                  #2c323d   
	color1                  #e06c75   
	color10                 #98c379   
	color11                 #e5c07b   
	color12                 #61afef   
	color13                 #c678dd   
	color14                 #56b6c2   
	color15                 #abb2bf   
	color2                  #98c379   
	color3                  #e5c07b   
	color4                  #61afef   
	color5                  #c678dd   
	color6                  #56b6c2   
	color7                  #979eab   
	color8                  #3e4452   
	color9                  #e06c75   
	cursor                  #e06c75   
	foreground              #abb2bf   
	inactive_tab_background #2c323d   
	inactive_tab_foreground #979eab   
	selection_background    #979eab   
	selection_foreground    #282c34   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /opt/homebrew/bin/zsh
	USER                                mlm
```

**Additional context**
This started sometime after 0.25 which was the last version I was on.

I can somewhat dial things in with `adjust_column_width` and `macos_thicken_font`, but it's still noticeably different between resolutions.

**Comment by kovidgoyal** [comment]
There are no changes to font rendering since 0.25 but feel free to
bisect to find the offending commit. And at least to my eyes apart from
the text looking sharper in one screenshot, I can see no significant
difference beyond about a pixel which is to be expected since cell width
is the product of DPI and font size both of which are floating point
numbers converted to integers.

**Comment by mcmillion** [comment]
FWIF, something definitely changed in 0.25.1:

![test](https://user-images.githubusercontent.com/717799/187821316-1cb21a39-5c42-403b-b9a0-5e7310f90acf.jpg)

These are both with same settings on same retina display.

**Comment by kovidgoyal** [comment]
That looks like its using a different font, use --debug-font-fallback and again I can think of nothing that has changed between 0.25.0 and 0.25.1, feel free to bisect to find the offending commit.

**Comment by kovidgoyal** [comment]
Also, dont use patched fonts. https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font

**Comment by page-down** [comment]
>  ... no significant difference beyond about a pixel which is to be expected ...

Since the number of pixels in a cell is an integer, when your DPI is not a multiplier difference, it is likely that each cell will differ by one pixel.

> ... something definitely changed in 0.25.1 ...
> ... same settings on same retina display ...

I can't reproduce this on my environment.
I can't find any code changes related to this in any of the commits for 0.25.1.

> That looks like its using a different font, ...

Looks like the same font to me.

By the way, even with a multiplied DPI, depending on the configured font size, the cells may not be guaranteed to be multiplied as well.
I use a font size of `12.99` to ensure that the cell width is multiplied between 1080p (1x) and 4K displays (3840*2160px, 2x). However, the font will be unnoticeably faded (thin) at this point.

@kovidgoyal
In order not to sacrifice font size in base DPI, do you think that getting multiples of cell widths (e.g. 2x, integer) at multiples of DPI requires introducing DPI-specific font size configuration?
So I no longer need to configure `12.99`, but can use `13` font size on LowDPI hardware.
Currently `modify_font` is applied to all DPI displays, making it impossible to apply `modify_font cell_width -1px`,  `modify_font cell_height +1px` to HiDPI.

Previous GitHub issue related to DPI and fonts:
https://github.com/kovidgoyal/kitty/issues/4114

**Comment by kovidgoyal** [comment]
@page-down: Per DPI font size adjustment is too much complication. One
pixel differences in sizes on different DPI monitors is not worth the
tradeoff of that much complication.
