### ISSUE TITLE
Kitty graphics protocol: Add an option to disable scrolling images when scrolling terminal (Fixed placement)

### ISSUE THREAD

**Issue by evanc577** [kovidgoyal/kitty#5517]
**Is your feature request related to a problem? Please describe.**
Disabling image scrolling would be useful for TUI applications that want to display images in a fixed location.
For example, in https://github.com/ncmpcpp/ncmpcpp/pull/437 which implements artwork display in a music player, currently if the UI is scrolled while an image is displayed, the image is scrolled off screen and lost.

**Describe the solution you'd like**
A control character which disables image scrolling.

**Describe alternatives you've considered**
Patch the application to not scroll. But for ncurses I have no idea how.

**Additional context**
Initial image placement:
![Screenshot_20220921_013512](https://user-images.githubusercontent.com/14303970/191422557-e091e8d9-c6c3-41f8-9c5c-f1a0026800f6.png)
Image should stay in the same location, but it is moved off screen when the UI is scrolled:
![Screenshot_20220921_013522](https://user-images.githubusercontent.com/14303970/191422562-84b16900-90ad-4dad-90be-c4d46eb2385d.png)

**Comment by kovidgoyal** [comment]
TUI applications use what is called the "alternate screen". That has no
scrollback, therefore such applications are expected to manage scrolling
themselves. So when they cause a scroll, they should reposition the
image using a placement command however is appropriate. 

I dont touch ncurses with a 10-foot barge pole, but you dont need it for
this. Simply add a hook to the application so that whenever it scrolls,
your function is called and you write the escape code to scroll the
image image placement to the tty directly. You are presumably already
writing to the tty directly since ncurses has no image support.

Longer term I would suggest dropping ncurses and moving to something
like notcurses instead.
