### ISSUE TITLE
Do not set default to tab.{title,name} when renaming tab

### ISSUE THREAD

**Issue by ad-chaos** [kovidgoyal/kitty#5532]
**Is your feature request related to a problem? Please describe.**
Imagine you cd'ed into a directory with a rather long name or ran an incantation that spans several line and would like to rename the tab something sensible, you run the mapping that renames tabs and before you can change the name you have to backspace over the existing name, which is rather frustrating.

**Describe the solution you'd like**
Do not set the `--default` option of the ask kitten to `tab.{name,title}`
https://github.com/kovidgoyal/kitty/blob/42178a4570849bf808e44b1902c6f86221acc57f/kitty/boss.py#L1653
Pressing enter over an empty prompt restores the original name anyway.

**Describe alternatives you've considered**
I know I know I can just `set editing-mode vi` in my `~/.inputrc` and then just `<esc>S` but, I mean that's two keystrokes too many and what I am asking here is for a *sane* default, not a solution :)

**Comment by kovidgoyal** [comment]
The default readline binding for erase to beginning of line is ctrl+u
no need for vi mode. kitty uses the existing tab title because often one
wants to edit the existing title slightly and having to retype it
is much more frustrating than erasing to beginning of line, when you
want a different title altogether.

**Comment by ad-chaos** [comment]
Fair enough 👍
