### ISSUE TITLE
How do I send the ignored key code ctrl+;?

### ISSUE THREAD

**Issue by atanasj** [kovidgoyal/kitty#5538]
I believe not being able to send `ctrl+;` is more an issue with terminals than kitty, but I really need this combination for my emacs config... Is there anyway I can get `ctrl+;` to be sent in kitty?

**Comment by page-down** [comment]
Configure a recognized shortcut in the program that does not support the kitty keyboard protocol, and then configure `ctrl+;` in kitty to send the escape sequence for that shortcut.

https://sw.kovidgoyal.net/kitty/faq/#how-do-i-map-key-presses-in-kitty-to-different-keys-in-the-terminal-program

**Comment by atanasj** [comment]
Thanks @page-down. I've really tried to figure this out, but have not had any luck with either the `ANSI` key codes or the `CSI`ones documented on the website here: https://sw.kovidgoyal.net/kitty/keyboard-protocol/?highlight=csi. 

I am able to map the key combo to send something, but it is not sending what I want. I have tried the below mappings, however in `emacs` it sends the `^` character. I have looked at various posts but cannot seem to figure it out. Any other advice would be greatly appreciated. 

```
map ctrl+; send_text application ^[[59;6u
map ctrl+; send_text application ^[[59;57442u
```

**Comment by page-down** [comment]
@atanasj

> ... not had any luck with either the ANSI key codes ...
> ... but it is not sending what I want ...

I guess you read any possible relevant information but missed the super-long FAQ link I specifically posted above.

```text
... To figure out what bytes to use for the send_text you can use the show_key kitten. Run:
kitty +kitten show_key
```

Also, what I mean is:
Configure `ctrl+a` (shortcut you don't normally use and recognized by emacs) to perform the action you need, then configure `ctrl+;` send `ctrl+a` in kitty (which will obviously take effect for all software running in kitty).

You can't let emacs get `ctrl+;` by configuring `ctrl+;` by sending some magic code, because it can't distinguish between ambiguous keystrokes.

Also, I don't use `emacs` and don't know if the following project will solve your problem, but I noticed that it seems to mention `kitty` and supports `ctrl+;`.

https://github.com/CyberShadow/term-keys
