### ISSUE TITLE
Allow using `edit-in-kitty` as the default editor on remote hosts

### ISSUE THREAD

**Issue by purpleKarrot** [kovidgoyal/kitty#5546]
I often ssh into remote hosts and work with git there. To select an editor, git respects the configuration `core.editor` and the environment variables `$GIT_EDITOR` and `$EDITOR`. But since `edit-in-kitty` is a shell function rather than a separate tool, it cannot be configured to be used as the default editor.

It would be nice if `edit-in-kitty` was implemented as a kitten instead of a shell function.

It would also be nice if the ssh kitten provided something like a `kitty_as_editor` option that sets the `$EDITOR` environment variable appropriately on remote hosts.

**Comment by kovidgoyal** [comment]
Simply copy the contents of the edit-in-kitty function into a shell
script and have the ssh kitten copy it to some place on your remote
PATH. And you can set EDITOR to whatever you like in ssh.conf and the
ssh kitten will forward it to the remote host for you. 

Making it a kitten is sub-optimal because it then requires kitty to
exist on the remote host and kitty is only pre-compiled for a subset of common server
platforms. It's on my TODO list to create a statically
compiled multiplatform kitty-tool executable. If and when that gets done
it can host edit-in-kitty.
