### ISSUE TITLE
Redrawing glitches when resizing kitty in a floating window

### ISSUE THREAD

**Issue by MachFour** [kovidgoyal/kitty#559]
Steps to reproduce:
 * Open kitty and set the window to be floating (I'm using i3)
 * Run neovim
 * `:colors morning` (makes it easier to see)
 * Resize the window a few times

The first line won't be drawn properly a good chance of times. Some screenshots are attached.
Of course, pressing `CTRL-L` in neovim to cause it to repaint the screen makes the dark area disappear.

![2018-05-21-18 17 32](https://user-images.githubusercontent.com/5557146/40297665-e30ecc90-5d23-11e8-821f-1a9e802e0bee.png)
![2018-05-21-18 22 01](https://user-images.githubusercontent.com/5557146/40297666-e4287860-5d23-11e8-9b66-c4675408cf01.png)

**Comment by kovidgoyal** [comment]
I dont really see what kitty can do about that. When a resize happens kitty sends the application the SIGWINCH signal, it is then up to the application to redraw itself. Presumably whatever neovim is doing to redraw itself is not the same as what it does with a :redraw command. I can tell you that this does not happen with vim, which I use in kitty all day long.

It's possible there is something kitty is doing that neovim does not like, however this kind of thing is pretty hard to debug, since it likely depends on the exact timing of the signal and subsequent redraw and resizes and the contents of the screen at the time of the resize.

neovim should really just redraw the entire screen on resize, which will prevent this sort of thing from happening. redrawing the entire screen is not particularly slow either, so I dont know why it's doing incremental updates anyway.

If you want to debug this, follow the same procedure as for #542 create a dump file, then trim it down to only the part after the resize, and see if you can isolate the problem.

**Comment by kovidgoyal** [comment]
Well yes, resizing is not a reversible operation in general, this is becaue on a resize lines are rewrapped, some might scroll of th escreen, etc. You cannot change size and then change back and get the exact same screen (it might work if you resize to a size larger than the original but not otherwise). 

The question is why is neovim not redrawing itself correctly after the resize? Either:

1) nvim is ignoring some SIGWINCH signals (maybe if they happen too close together)
2) kitty is not sending some SIGWINCH signals
3) kitty is making changes to the screen after sending the SIGWINCH signal.
4) nvim is not properly redrawing the screen after receiving a SIGWINCH

(1), (4) are nvim bugs. (2) and (3) are kitty bugs. You can eliminate (2) and (3) by some debugging in kitty. Look in pty_resize() function for where kitty sends the signal and screen_resize() for where kitty redraws the screen after a resize. Adding a couple of printf() in those functions should tell you if kitty is doing things in the correct order or not.

**Comment by MachFour** [comment]
Just had a look at screen_resize() in screen.c, around line 200 where there's a check whether the cursor is beyond the content, and is moved inside it if so (`if (cursor_is_beyond_content)`).

This logic seems quite similar to what you changed as a result of the previous issue with neovim. Do you think that they are related?

**Comment by kovidgoyal** [comment]
It doesn't matter, there can be no guarantees of cursor position after a resize, imagine if the cursor was ona line that no longer exists. Applications cannot rely on the cursor position being well defined after resize.

**Comment by MachFour** [comment]
I uncommented the `printf` statements in `screen_resize()`, and added a `printf(TIOCSWINSZ)` call after then corresponring ioctl call in `pty_resize()`.

What happens when I change the window size is that it doesn't seem to do the ioctl call at all, and every time I resize, it prints 

Resizing tall to wide:
```
 old_size: (88, 58) new_size: (177, 29)
old_cursor: (0, 0) new_cursor: (1, 0) beyond_content: 0
```
Resizing wide to  tall:
old_size: (177, 29) new_size: (88, 58)
old_cursor: (0, 0) new_cursor: (1, 0) beyond_content: 0
```
and after both resizes the top line was not drawn properly as in the screenshots above.

I should have said earlier, these bad redraws seem to happen randomly, maybe after 3 in 10 resizes.

**Comment by kovidgoyal** [comment]
I cannot replicate that, withthe following patch:
```
diff --git a/kitty/child-monitor.c b/kitty/child-monitor.c
index ea7e802c..768fb20a 100644
--- a/kitty/child-monitor.c
+++ b/kitty/child-monitor.c
@@ -409,6 +409,7 @@ mark_for_close(ChildMonitor *self, PyObject *args) {
 static inline bool
 pty_resize(int fd, struct winsize *dim) {
     while(true) {
+        printf("ioctl: %f\n", monotonic());
         if (ioctl(fd, TIOCSWINSZ, dim) == -1) {
             if (errno == EINTR) continue;
             if (errno != EBADF && errno != ENOTTY) {
diff --git a/kitty/screen.c b/kitty/screen.c
index f8fdaf58..7bb98436 100644
--- a/kitty/screen.c
+++ b/kitty/screen.c
@@ -148,6 +148,7 @@ realloc_lb(LineBuf *old, unsigned int lines, unsigned int columns, index_type *n
 static bool
 screen_resize(Screen *self, unsigned int lines, unsigned int columns) {
     lines = MAX(1, lines); columns = MAX(1, columns);
+    printf("redraw: %f\n", monotonic());
 
     bool is_main = self->linebuf == self->main_linebuf;
     index_type num_content_lines_before, num_content_lines_after, num_content_lines;
```

resizing floating kitty window always prints out a pair of redraw and ioctl. If you are not seeing an ioctl being called then something is very wrong. You shoud at least be seeing an error message saying failed to send resize signal.

**Comment by kovidgoyal** [comment]
pty_resize is called via set_geometry in window.py. Stick a print in there to see if that is being called.

**Comment by MachFour** [comment]
Ah, stupid mistake, sorry. I put the printf() call _inside_ the `if (ioctl(fd, TIOCSWINSZ, dim) == -1)` check. So it is calling ioctl() correctly. But the rendering bug is still there.

I still think it could be something to do with the resizing logic, because it doesn't happen in other terminals. But I don't have any other insights right now.

**Comment by kovidgoyal** [comment]
Sorry, I dont see how this is a kitty bug. Either neovim is redrawing the screen correctly after resize, in which case it does not matter what kitty does before sending SIGWINCH, or it is not, in which case it is a neovim bug. For reasons I have explained above, there is no cursor position/line contents that neovim can rely on from before the resize.

The fact that :redraw redraws the screen correctly makes it highly likely that this is a neovim bug. You can probably work around it by using the VimResized autocmd to manually issue a redraw.
