### ISSUE TITLE
Documentation missing as to why xterm-kitty terminfo is required instead of xterm terminfo

### ISSUE THREAD

**Issue by jahway603** [kovidgoyal/kitty#5597]
Documentation is missing as to why xterm-kitty terminfo is required instead of xterm terminfo
Also, this was added with one of the very first commits on GitHub, but no explaination as to why this is required: https://github.com/kovidgoyal/kitty/commit/3bb429df

**Comment by kovidgoyal** [comment]
Because kitty is not xterm.

**Comment by kovidgoyal** [comment]
Oh and it is documented: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.term

**Comment by page-down** [comment]
I have answered this question briefly according to my own understanding.
https://github.com/kovidgoyal/kitty/discussions/4223

If you want to learn more, other previous related discussions:

```text
Please submit xterm-kitty terminfo to ncurses database
https://github.com/kovidgoyal/kitty/issues/879

[question] kitty terminfo in ncurses database
https://github.com/kovidgoyal/kitty/issues/2773

Can we talk about "xterm-kitty"? ...
https://github.com/kovidgoyal/kitty/discussions/3873
```

@jahway603

> ... I do not have the answer to the question "Do you know what xterm-kitty is actually used for, what makes it better with KiTTY compared to xterm?" ...

- [KiTTY](https://github.com/cyd01/KiTTY) is a fork of PuTTY, `kitty` is not `KiTTY`.
- Other CLI software needs to know what kitty can do and send commands correctly through the escape sequence specified in the terminfo db. (And there's more.)
- kitty is not xterm, specifying `TERM=xterm` will guarantee that kitty will not work properly. You will notice troubles when you use certain programs that involve differences between the two. Use `infocmp` to learn the differences.
- This is **NOT** an optional dependency that only affects colors, text styles and other similar things, it is actually **required**.
- As for what is a terminfo database, please refer to the `terminfo(5)` man page.

In addition, there are third-party software that uses `$TERM == xterm-kitty` to detect and enable certain features specifically for kitty. (Although this is not recommended and should rather be queried using escape sequences.)

**Comment by MichaIng** [comment]
The question may make more sense the other way round: What terminal features does KiTTY add or handle differently compared to PuTTY, which are seen sufficiently important that it is worth creating an own terminfo, so that KiTTY does not work well with `xterm` while PuTTY does and passes `TERM=xterm` as default? + I'm not aware of any other SSH client which requires an own terminfo.

This I do not see answered as far as I read, only
> Since kitty aims to move the terminal ecosystem forward

which still does not say which exact enhanced or added terminal feature makes it worth to require every user pushing a new terminfo to every SSH server it connects to (which is not always possible or allowed, as mentioned in one of the threads already).

You'll have good reasons, I'm sure, so I'm just interested.

**Comment by trygveaa** [comment]
> Then the question is why KiTTY uses kitty by default

KiTTY doesn't use kitty, the two projects have nothing to do with each other.
