### ISSUE TITLE
How to set KITTY_PUBLIC_KEY in socket communication?

### ISSUE THREAD

**Issue by hacker-DOM** [kovidgoyal/kitty#5632]
I'm trying to create a Hammerspoon (macos automization) workflow to open a small Kitty window in the current space :D

For that reason I did something like:

```bash
cd  ~/.config/kitty
echo "foobar"  >  ./gitignore/rc-pass
ln -s  gitignore/rc-pass  rc-pass
```

and set my conf:

```
allow_remote_control password
listen_on unix:/tmp/mykitty
remote_control_password "foobar" ls
```

Now, I have:

- from my (sole) Kitty instance:
    - running `kitty @ ls` will auto-use the password file (so it will work)
    - running `kitty @ --password wrong ls` will override the password, and, it being incorrect, ask me if I want to accept the connection

SO far so good! 🙂 The problem is that when I do the following **in a different terminal**:

- `ls /tmp`
- find `kitty`'s pid
- `kitty @ --to unix:/tmp/mykitty-97321 --password 'foobar' ls`

I get

```
Password usage requested but KITTY_PUBLIC_KEY environment variable is not available
```

Which part of my flow is not correct? 😹🙀

**Comment by kovidgoyal** [comment]
If you want to use passwords with socket communication (though there
isn't much point since if you are using a socket, you are not exposing RC
over SSH), then you need to store the public key of the kitty instance
you want to communicate with somewhere. You can do so by, for instance, 
by having your shell rc file store the value of the KITTY_PUBLIC_KEY env
var somewhere. Or you can use a session file with kitty one of the
launched sessions to run a script to store it.
