### ISSUE TITLE
Tab will cause text fragment

### ISSUE THREAD

**Issue by bin4ryio** [kovidgoyal/kitty#573]
<img width="307" alt="screenshot_2018-05-24 23 20 51_ufosin" src="https://user-images.githubusercontent.com/21124691/40495389-aeedf728-5fa9-11e8-8635-ea8d03787e7b.png">

Whenever I tab-tab completion on Kitty, the first 2 word of the command will stuck on the screen. As attached screenshot is an after effect.

The flow is as followed:

1. I type `vi`
2. I hit [tab][tab]
3. Screen display `vivim` where the leftmost `vi` can't be backspaced

I'm using Mac OS X latest build of Kitty. Sorry if this issue has been posted, I can't seem to find one related.

**Comment by kovidgoyal** [comment]
With what shell? It is likely something in your shell config causing this. Most probably the custom prompt. Typically, use of unicode characters that have two char width in the unicode standard causes problems, because kitty will render them in two cells but most shells typically dont follow the standard and assume tey are one cell wide. 

The other possibility is th euse of a multi-line prompt, though that is unlikely as I have never seen a bug report about it before.

In any case start witha  simply shell promt, then add mosr customizations step by step till you find the problem.

**Comment by kovidgoyal** [comment]
no followup
