### ISSUE TITLE
OSX Error Bonk when pressing <control>-/ in Kitty…

### ISSUE THREAD

**Issue by evantravers** [kovidgoyal/kitty#576]
I use ctrl-/ (undo in readline and emacs) as a leader key for tmux, so I press it a lot.

When I press it in iterm2, no sound is played, but in kitty I get an error beep/bonk, and it's getting a little annoying.

I'm using the latest release of Kitty, OSX High Sierra, and a standard kitty.conf with the colors changed.

**Comment by kovidgoyal** [comment]
I cannot replicate this. Pressing Ctrl+/ produces no beep on my mac. And running cat and then pressing it shows that it generates the bytes 0x1f, as expected. If you are getting a beep it is being caused by whatever software you are running inside kitty, not kitty itself. You can always turn off the beep in kitty.conf if you can't figure out how to stop whatever it is that is creating it.
