### ISSUE TITLE
Support for TrueType collections?

### ISSUE THREAD

**Issue by imyxh** [kovidgoyal/kitty#577]
I hate to bother you with another issue mentioning Iosevka, but this looks distinct from the previous issues filed because I actually can't get kitty to use the Iosevka Term as the font at all, which hasn't been mentioned yet as far as I've checked. Iosevka Term has no ligatures or anything else that I know would break kitty; kitty just refuses to display it.
Here's a screenshot that should explain:
![image](https://user-images.githubusercontent.com/12703838/40580227-664e6498-60ef-11e8-8025-9db8f3a4d97c.png)
The lower part with QTerminal is the expected result, of course. Fully monospaced with no ligatures.

It's probably worth noting that when I set the font as "monospace" or just comment out the line, kitty will use some other weird font even if I have "Iosevka Term Regular" specified as my monospace font in GNOME tweaks.
All other applications handle this fine, so I suspect that something's up with `fontconfig.find_best_match` in the source code. Or perhaps there's just another incompatibility with the way Iosevka is made.

Thanks!

**Comment by kovidgoyal** [comment]
I cannot replicate this. Installing both Iosevka and Iosevka Term (I installed the ttf files and ran fc-cache) and using

```
kitty -c NONE -o 'font_family=Iosevka Term' -o font_size=15
```

![screenshot_20180527_081234](https://user-images.githubusercontent.com/1308621/40582009-d964f3de-6185-11e8-9378-0bd4358eb57e.png)

You can debug fontconfig matching in fontconfig.c in fc_match() print out what parameters are being passed to fontconfig to chekc they are as expected. If they are then the issue is whitht he fontconfig configuration on your syste,. Look for fontconfig .conf files either in /etc or the user fontconfig directory.

**Comment by kovidgoyal** [comment]
I've never actually tested it with ttc as they are pretty rare. If you zip them up and attach the file, I'll take a look. Or just remove them and install the ttf files. As far as I know upstream does not release ttc, so where are you getting them from? https://github.com/be5invis/Iosevka/releases/tag/v1.13.3

**Comment by imyxh** [comment]
Alright, I just replaced them with .ttf files and it works fine now.
The [Iosevka pack](https://github.com/be5invis/Iosevka/releases/download/v1.13.3/iosevka-pack-1.13.3.zip) is a collection of .ttc files.
I think I'll rename this bug to be a feature request for TrueType collections, then.
