### ISSUE TITLE
xterm-kitty not setting up correctly in NetBSD

### ISSUE THREAD

**Issue by jahway603** [kovidgoyal/kitty#5814]
**Describe the bug**
After trying [everything in the FAQ](https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-when-sshing-into-a-different-computer), NetBSD 9.3 server shows me "Error opening terminal: xterm-kitty." when trying to run certain commands (htop in this case) but the `.terminfo.cdb` file and `~/.terminfo` directory was all created when running `kitty +kitten ssh myserver`.

**To Reproduce**
1. Type `kitty +kitten ssh myserver`, which connects to the NetBSD server.
2. Type `htop`
3. Get the error `Error opening terminal: xterm-kitty`, even though all the files were created on the NetBSD server via the kitty client.

**Screenshots**

**Environment details**
Kitty terminal running on Arch/Artix linux work correctly with all other OSes I've tried when running the commands in the FAQ.

**Additional context**
Unsure if Issue https://github.com/kovidgoyal/kitty/issues/4622 was fixed.

**Comment by kovidgoyal** [comment]
As I said in #4622 I dont have a netbsd host to test with. If you say
both the terminfo files are being correctly created then kitty has done
its job. Beyond that you will need to debug whatever application is
failing to open terminfo. You can also run infocmp to make sure that
ncurses itself is able to read terminfo.

**Comment by page-down** [comment]
That's because your htop relies on a higher version of ncurses and you need to recompile terminfo with the tic from ncurses.

```shell
rm -rf ~/.terminfo/78 ~/.terminfo/x
/usr/pkg/bin/tic -x -o ~/.terminfo ~/.terminfo/kitty.terminfo
```

The `tic` used by ssh kitten is the first one in the PATH when connecting. And this PATH is not the PATH you configured in shell rc.
I don't know how to make the old version of terminfo co-exist with the new version and have the programs that come with netbsd and the self-installed programs work at the same time.

You need to configure `TERMINFO` yourself and make sure that the new version of terminfo you compile is not under `~/.terminfo/` because it will be overwritten by ssh kitten on the next connection.

**Comment by jahway603** [comment]
@page-down it's not clear what I can do to make this work correctly

**Comment by page-down** [comment]
@jahway603
> ... it's not clear what I can do ...

- Remove the `~/.terminfo/78` and `~/.terminfo/x` folders created by ssh kitten (version 0.26.5 and earlier) on NetBSD.
- Generate the `xterm-kitty` terminfo database using the command `tic` from the higher version of ncurses that `htop` depends on.
- Do not use ssh kitten (version 0.26.5 and earlier) to connect again, as that will overwrite the files you have generated.

Or try installing the nightly release and using the ssh kitten.
