### ISSUE TITLE
Shell integration changes reported working directory in subshells

### ISSUE THREAD

**Issue by brandonchinn178** [kovidgoyal/kitty#5911]
**Describe the bug**
I use `(cd ... && some cmd)` a lot when working in monorepos to execute commands in subdirectories while remaining in the root directory. But I noticed that opening a new window with `launch --cwd=last_reported` will open to the directory that was changed in the subshell, not the one I'm actually running in.

I'm running in zsh, and I noticed the zsh integration uses `chpwd_functions`, which always runs, even in subshells. I'm not sure what the best solution is; one option is to just always report the current directory in `precmd` (which is what I, as a user, would expect the behavior to be).

**To Reproduce**
1. `(cd /tmp && echo hi)`
2. Trigger `launch --cwd=last_reported`
3. `pwd` is now `/tmp`

**Screenshots**

**Environment details**

**Additional context**

**Comment by kovidgoyal** [comment]
I dont follow, if you are running a command in a different directory and
that command reports its directory, then last-reported will and should
use that reported directory. Once the command finishes executing the
prompt is redrawn and presumably the current directory is once again the
parent directory. Or are you saying that the parent directory is not
restored? If so that would be a bug in chpwd_functions, you should
report it to zsh. And as a workaround, instead of doing (cd x && whatever)
do
cd x; whatever ; cd -

If you are saying you want to run in a sub directory but not have that
sub directory reported, your best bet is to add no-cwd to shell
integration and just add cwd reporting to your own prompt drawing
function in zshrc. 

If I have misunderstood, feel free to post further.

**Comment by brandonchinn178** [comment]
Yes, the parent directory is not restored. It's not a zsh problem because chpwd_functions is doing what it says: it runs every time the directory is changed. When you do `(cd foo && blah)`, the shell isnt adding an extra `cd $ORIGINAL_DIR` to the end; it's simply that changing directories in a subshell doesnt change the directory in the parent shell (this isnt specific to zsh, this is just basic UNIX behavior).

Yes, I could fix it myself for my own configuration, but I would argue that the current implementation is not anyone's desired behavior.

**Comment by kovidgoyal** [comment]
On Fri, Jan 20, 2023 at 08:02:36PM -0800, Brandon Chinn wrote:
> Yes, the parent directory is not restored. It's not a zsh problem because chpwd_functions is doing what it says: it runs every time the directory is changed. When you do `(cd foo && blah)`, the shell isnt adding an extra `cd $ORIGINAL_DIR` to the end; it's simply that changing directories in a subshell doesnt change the directory in the parent shell (this isnt specific to zsh, this is just basic UNIX behavior).

I disagree, if chpwd_functions is run in subshells, then the shell
should take responsibility for running it in the parent shell as well
after the sub shell. Otherwise, chpwd_functions is meaningless. It
basically reports some changes and not others. Or the shell should not
pass it to a sub-shell. 

I can of course trivially workaround this by simply unconditionally
reporting the cwd in precmd but that's an unnecessary performance hit. I
would much rather have chpwd_functions fixed properly.

or maybe I can cache the last reported cwd and compare it in precmd to
the current cwd and only report if changed.

**Comment by brandonchinn178** [comment]
> then the shell should take responsibility for running it in the parent shell as well after the sub shell

That's how `chpwd_functions` works. `chpwd_functions` _only_ runs when a shell changes directories. In the case of `(cd foo && something)`, **the parent shell isn't changing directories**. The parent shell is staying in the same directory, spawning a child shell which changes directories, then kills the child shell. The parent shell isn't changing directories, so the parent shell isn't running `chpwd_functions`.

Ah but actually, you have already implemented this: https://github.com/kovidgoyal/kitty/commit/d92f89e47f8f91e995b5a129a9199bca426e262b. When will you be making the next release?

**Comment by kovidgoyal** [comment]
Use a nightly build.
