### ISSUE TITLE
Option to disable ligatures across style changes

### ISSUE THREAD

**Issue by zrajm** [kovidgoyal/kitty#5950]
Tmux uses '<' and '>' to indicate that not all window names fit into the status line. I noticed this combining with a hyphen (truncated) window title, showing '->' as an arrow ligature, even though the '-' had a different style (foreground and background color) than the '>'. It seems very counter intuitive to render ligatures across style borders.

I would suggest an option (`disable_ligatures style`, maybe?) to break ligatures when they occur across a style border. (Ligatures are already broken like this across different fonts [e.g. a change in bold or italic] but not when the style difference is foreground or background color.)

This is what I saw:

    echo $'\e[1m<\e[0m- \e[32m<\e[0m- \e[42m<\e[0m-'

![styles](https://user-images.githubusercontent.com/1286805/215491038-2f156279-b119-44d3-84c3-281ea7b07abc.png)

This is what I expected to see:

![styles2](https://user-images.githubusercontent.com/1286805/215493384-137c717b-36ff-4a15-8de6-6044605a763e.png)

In the end I solved my Tmux issue by changing the '<' and '>' overflow indicators to a different symbol, but I found Kitty's behavior puzzling, so I'm creating an issue here nontheless.

**Comment by kovidgoyal** [comment]
I'm not a fan of this. It makes debugging ligature issues much harder.
There could be some barely perceptible style change that breaks a
ligature. And then it may be not desired to break ligatures for some
style changes, for example you could want a line ligature made of
repeated hyphens with different parts of the line in different colors.
Or some syntax highlighting code could highlight some chars in a
ligature but not all of them since it will have no idea what th efont
considers a ligature.

Given that implementing it is both work and imposes runtime overhead
(checking the styles per cell) and is a change in existing behavior, I
am going to pass.
