### ISSUE TITLE
Whatever `safe_builtins` in `tab_bar.py` is for, it can be circumvented by using `re.__builtins__`

### ISSUE THREAD

**Issue by ces42** [kovidgoyal/kitty#6005]
**Describe the bug**
[tab_bar.py](https://github.com/kovidgoyal/kitty/blob/master/kitty/tab_bar.py) restricts the builtins accessible from the tab title format specification by doing this:

https://github.com/kovidgoyal/kitty/blob/2307892b5019f6a45078910d254a3f626527d818/kitty/tab_bar.py#L225-L227

However it can be circumvented by using the dictionary `re.__builtins__`.

On a related not, would it be possible to add `chr` to these? Otherwise I don't see a way to reference get unicode characters inside this expression without directly pasting them into the config (backslashes are not allowed in f-string expressions).

**Comment by kovidgoyal** [comment]
It's not a security mechanism, its just a way to limit what can be used in tab title templates to relatively fast/side-effect free things to prevent users from easily shooting themselves in the foot. It can be bypassed in myriad ways since this is python. The point is to make sure doing that is not easy/accidental.

And I dont follow your use case. Why do you need char? For example:

```
kitty -o 'tab_title_template \U0001f408'
```

displays a cat as expected.

**Comment by ces42** [comment]
Oh, got it.

I want `ord` because I want to specify a unicode character in the python-expression part of the f-string, so that I can have fancy nerd font icons in my tab titles but I don't want meaningless unicode characters in the window title that is exposed to the os. Specifically I want something like
```
tab_title_template "{title.replace('vim:', '\Ue62b')}"
```
but this doesn't work and neither does
```
tab_title_template "{title.replace('vim:', chr(0xe62b))}"
```

**Comment by kovidgoyal** [comment]
You need a lower case u
\u1234 not \U1234 upper case U in python is for non-BMP codepoints
(beyond 0xffff)

That said I have no problem with adding chr to safe_builtins
