### ISSUE TITLE
+kitten does not work when remote server has fish shell

### ISSUE THREAD

**Issue by shyim** [kovidgoyal/kitty#602]
Hey,
i would connect to my server using ktity +kitten root@host like described in the faq page. But when the default shell is fish remote, it occures a error

```
fish: Expected a string, but instead found a redirection
cat >$tmp << 'TERMEOF'
           ^
```

**Comment by kovidgoyal** [comment]
That's because fish shell does not support heredocs.

https://github.com/fish-shell/fish-shell/issues/540

**Comment by kovidgoyal** [comment]
Oh and generally speaking fish shell is not POSIX compliant, which means the kitten will not work with it, since it needs a POSIX compliant shell.

**Comment by Snuggle** [comment]
At the moment, the best way to deal with this is to do the following:
`chsh -s /usr/bin/bash` on remote, then disconnect.
`kitty +kitten ssh user@hostname` to connect and transfer terminfo files.
`chsh -s /usr/bin/fish` on remote, reconnect **without** using SSH kitten.

@kovidgoyal While the ssh kitten doesn't like fish, it's not really alias-ready sadly.
```
fish: Expected a string, but instead found a redirection
cat >$tmp << 'TERMEOF'
           ^

Connection to 192.168.0.111 closed.
```

You really shouldn't be using your interactive shell to run scripts like this, anyway. You should prefix #!/bin/bash on the top of your shell script so that it's run by a POSIX compatible shell.

If this isn't possible (I've seen you've done some weird thing with exec, you might be able to use `bash -c exec` instead.)

🐈 💖 🐟

**Comment by kovidgoyal** [comment]
It is not possible to execute bash it has to run with the login shell. And you dont need to do all those convoluted things if you insist on using non-POSIX compatible shells. The FAQ entry about it has alternate one-liner you can use. And it is perfectly alias ready for 99% of people that use POSIX compatible shells.

**Comment by Snuggle** [comment]
Ah, my apologies for bumping this issue, I didn't realize there was an alternative in the F.A.Q.

Is there a reason why the SSH kitten can't run the alternate command in the background if a non-POSIX shell is being used? If it could check `$SHELL` or something?

**Comment by kovidgoyal** [comment]
Remember that the value of shell that matters exists on the remote server, the kitten has no way of knowing what it is until it connects, at which point it is too late.

The reason that the login shell has to be used is because the only way for the kitten to find out what the login shell on the remote server is, that is cross platform and reliable is to use the getpwnam() C function on the server, which cannot be done from a shell script. So instead the kitten lets sshd run the login shell and simply uses argv[0] to detect the login shell. 

The downside to this approach is that the login shell has to be POSIX compatible, otherwise the shell script used to do this will not work.

For non-POSIX shells you can use the alternate one liner from the FAQ or you can write a replacement for this kitten that uses some other interpreted language that you know is available on all the machines you ssh into, such as python or perl. Both of those can call getpwnam() so they can run the login shell themselves without needing sshd to do it.

But note that you only need to copy over the terminfo file to the remote server once after that you can just use a normal ssh. So if I were you I'd just use that one liner once and then use normal ssh.
