### ISSUE TITLE
font weird in Ubuntu 22.04 virtual machine

### ISSUE THREAD

**Issue by maixianyu** [kovidgoyal/kitty#6069]
**Describe the bug**
font rendering is incomplete. part of area in font is missing.

**To Reproduce**
1. Ubuntu 22.04 virtual machine
2. install curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
3. open kitty. type something like pwd, then bug shows

**Screenshots**
![image](https://user-images.githubusercontent.com/16153380/221466919-776d9395-2822-4569-a697-60fbfcabe538.png)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```
![image](https://user-images.githubusercontent.com/16153380/221467107-f84c4f64-5296-4416-8f1e-7c5147543129.png)

**Additional context**
Try to reproduce the problem with `kitty --config NONE`
YES. `kitty --config NONE` can produce the problem also

**Comment by kovidgoyal** [comment]
This will be an issue with your graphics drivers in the VM. Try using
software rendering.

**Comment by maixianyu** [comment]
> This will be an issue with your graphics drivers in the VM. Try using software rendering.

it works. thanks!

**Comment by PiotrNap** [comment]
Hi @kovidgoyal

The same problem just happened to me. I tried setting software rendering (even with 3D acceleration), but it didn't helped. Do you have any idea what could be the issue here?

![image](https://user-images.githubusercontent.com/59693946/236940139-ec5f7a4a-1884-427a-9802-373b6cad9ab8.png)

VM Display settings: 
![image](https://user-images.githubusercontent.com/59693946/236944343-72a5ee9a-6308-4507-8b45-775dd12585c7.png)

Thx
