### ISSUE TITLE
inactive_text_alpha config option affect on a tabbar.

### ISSUE THREAD

**Issue by neyuki** [kovidgoyal/kitty#612]
Hello.

Is that a bug or a feature, what when i set inactive_text_alpha option, it's fade not only inactive windows, but tabbar also? Kitty from master on linux.

Thank you.

**Comment by kovidgoyal** [comment]
A feature, I think :) Why do you not want the tab bar faded?

**Comment by neyuki** [comment]
Description of the option said nothing about tabbar. And by this logic, after inactive_text_alpha 0, tabbar will be hided. Certainly a bug.

**Comment by kovidgoyal** [comment]
Why would the tab bar be hidden? This affects only the background, so unless your wallpaper happens to match the foreground color of the tab bar it wont be hidden any more than the rest of kitty would be hidden.

Thinking about it, I dont see why the option should not apply to the tab bar. If you want a semi transparent window, why would you not also want the tab bar to be semi transparent? Although I have to say that since that option applies only to the default background color and the tab bar uses multiple background colors, the option wont affect it anyway.

**Comment by neyuki** [comment]
foreground #ebdbb2
background #282828

active_tab_foreground   #d79921
active_tab_background   #282828
active_tab_font_style   bold
inactive_tab_foreground #928374
inactive_tab_background #282828
inactive_tab_font_style italic

With such setup & inactive_text_alpha 0.0 tabbar will be hidden.

I don't see any correlation with tabbar as entity and inactive window text. Tabbar is what, something what belongs to a window? Even then, why active tab text faded too?

**Comment by kovidgoyal** [comment]
Ah never mind. For some reason, I thought you were talking about background_opacity, not inactive_text_alpha, sorry.
