### ISSUE TITLE
distinguish left and right modifier keys in kitty's keyboard protocol

### ISSUE THREAD

**Issue by unxed** [kovidgoyal/kitty#6169]
**Is your feature request related to a problem? Please describe.**
Some console applications needs to know what modifier key was pressed exactly, left or right key, for keys like Control, Alt, etc. So does far2l — Far Manager port for Linux. Unfortunately, current version of kitty's extended keyboard protocol do not distinguish left and right modifier keys in modifiers field.

**Describe the solution you'd like**
Non-used bits of modifiers field should be used for right Control, Alt, etc keys. Current bits should be interpreted as left keys. Updated spec could look like this:
```
left shift     0b1              (1)
left alt       0b10             (2)
left ctrl      0b100            (4)
left super     0b1000           (8)
left hyper     0b10000          (16)
left meta      0b100000         (32)
caps_lock      0b1000000        (64)
num_lock       0b10000000       (128)
right shift    0b100000000      (256)
right alt      0b1000000000     (512)
right ctrl     0b10000000000    (1024)
right super    0b100000000000   (2048)
right hyper    0b1000000000000  (4096)
right meta     0b10000000000000 (8192)
```

**Describe alternatives you've considered**
Currently in far2l I am using key tracking method to workaround this limitation: I remember right Control key state by tracking its keypress and keyrelease events so I can know if it is held currently or not. But I am not sure if it is reliable method: what if focus on window is suddenly lost and right Control key release event not comes? I was unable to reproduce such situation, but not sure this could never happen.

**Comment by kovidgoyal** [comment]
I dont see much point, this is not a common use case and tracking the
press and release events works fine. Indeed, it would need to be
implemented that way inside kitty anyway, since some OS backends dont report
per variant modifier states. 

If focus is changed and a release event is missed, on the next event the
modifiers will no longer have ctrl/alt so this situation can be
detected. The only case where it wont be detected if if say the left
modifier is pressed, focus is changed, then the right modifier is
pressed and then focus is restored. This is pretty unlikely and not
worth worrying about, IMO. And even if kitty were to implement it, its
implementation would suffer from the same limitation.

**Comment by eugenesvk** [comment]
Yeah, this would be very nice to have especially for all the terminal text editors so you could use e.g. right alt as your symbol key and left alt as your command key combo and don't have those interfere with each other. Or even have the same thing in the terminal so you could easily type any symbols

(and it's not a common use case because there is no good support for it anywhere, even many GUI apps fail here requiring you to resort to niche advanced remapping tools)

**Comment by hacker-DOM** [comment]
I don't seee into the details that @kovidgoyal  is talking about, but one solution would be to do this on the OS/kernel level. Eg on Mac I use Karabiner (thru Goku) and have a lot of such modifier bindings

**Comment by trygveaa** [comment]
> Yeah, this would be very nice to have especially for all the terminal text editors so you could use e.g. right alt as your symbol key and left alt as your command key combo and don't have those interfere with each other. Or even have the same thing in the terminal so you could easily type any symbols

Why would you do this on the application level rather than with a keyboard layout for the whole OS? See e.g. the US international keyboard layout which does exactly this.

**Comment by eugenesvk** [comment]
I do this with Goku, but it's a poor substitute because the OS is blind - it has no application specific context, so you can't limit something to insert mode vs normal mode. Then you also can't bind various app-specific functions. And with some kludge you would have separate places for keybind config, which is bad ergonomics (eg, you can't have native app hints because now the app is blind to what is going on in goku), etc., etc

Also your layout example is just as bad since it also first differentiate between left and right modifiers (I also have a custom keyboard layout with various dead keys)

The only proper solution is for the app to do the basics right and recognize all the keys the keyboard has to offer

**Comment by eugenesvk** [comment]
(and then Goku is not x-platform, so you have to waste time recreating your setup on each OS)

**Comment by hacker-DOM** [comment]
I mean he does have a point 😃

@kovidgoyal Any chance of accepting that the V1 of the protocol might not be the final version?

**Comment by kovidgoyal** [comment]
I dont see anything new here after my last comment.
