### ISSUE TITLE
potential typo in keyboard protocol spec

### ISSUE THREAD

**Issue by unxed** [kovidgoyal/kitty#6172]
`57427 ~` probably should be `57427 u`?

Noticed here: https://github.com/wez/wezterm/issues/3478

**Comment by kovidgoyal** [comment]
It's not a typo. If you look at the table carefully, you will notice
that all keys that have a legacy letter encoding have an alternate
encoding with CSI ~

This was done because there already exist terminals that use these forms
for these keys, so using the same encoding for basic events in the kitty
protocol allows programs that support these encodings to work
automatically.
