### ISSUE TITLE
No `make docs` target

### ISSUE THREAD

**Issue by AndrewBelt** [kovidgoyal/kitty#622]
When compiling with `python3 setup.py linux-package`, the build fails at
```
The kitty man page is missing. If you are building from git then run: make docs
```
There is no `docs` target in the root Makefile. I think you mean `make man` and `make html`? Or you could just add a `docs` target

```Makefile
docs: man html
```

**Comment by aenda** [comment]
I think the following patch is sufficient to fix it.

```
diff --git a/setup.py b/setup.py
index 83867d0..2ea1c00 100755
--- a/setup.py
+++ b/setup.py
@@ -543,6 +543,7 @@ def copy_man_pages(ddir):
         shutil.rmtree(os.path.join(mandir, 'man1'))
     except FileNotFoundError:
         pass
+    run_tool(["make", "-C", "docs", "man"])
     src = 'docs/_build/man'
     if not os.path.exists(src):
         raise SystemExit('''\
@@ -559,6 +560,7 @@ def copy_html_docs(ddir):
         shutil.rmtree(htmldir)
     except FileNotFoundError:
         pass
+    run_tool(["make", "-C", "docs", "html"])
     src = 'docs/_build/html'
     if not os.path.exists(src):
         raise SystemExit('''\
```

**Comment by aenda** [comment]
This is still an issue because the command `python3 setup.py linux-package` gives error code 1. For example, this breaks the PKGBUILD for kitty on arch linux, since it will exit because of an error, and even if it were adjusted it would exit before it could run `make docs`. And as far as I can tell, make docs does not work until the compilation has been done, so it cannot be run beforehand. Would it make more sense to just print the warning about missing documentation but still exit cleanly as long as no other errors occurred?

**Comment by kovidgoyal** [comment]
You need to run

python3 setup.py build
then
make docs
then
make linux-package

**Comment by kovidgoyal** [comment]
Or just 
make
make docs
make linux-package

**Comment by aenda** [comment]
Thanks!

**Comment by shoober420** [comment]
Thanks for fixing this!

**Comment by kovidgoyal** [comment]
You're welcome, it really wasn't a big deal :)
