### ISSUE TITLE
Text rendering is very poor

### ISSUE THREAD

**Issue by MannyFay** [kovidgoyal/kitty#6294]
**Describe the bug**
The rendering of text is very poor in Kitty (against Terminal.app or iTerm2).
Is there a way to boost this up?

**Screenshots**
![Screenshot 2023-05-20 at 21 14 59](https://github.com/kovidgoyal/kitty/assets/45234439/10d17a6a-845f-433d-965f-677f175f04d1)

**Environment details**
* MacBook Air M1
* macOS Ventura

**Comment by kovidgoyal** [comment]
I dont see whats poor about it. Regardless, kitty has easily the most
customizable text rendering of any terminal emulator. earch kitty.conf
for text and font.

**Comment by MannyFay** [comment]
Thank's for the fast reply.
I'm new to Kitty and want to give it a try in my every day work.
Here is a screenshot from iTerm2 and Kitty. iTerm2 is on the left and Kitty is on the right.

Is there anything wrong in my kitty.conf, because the text is way more crisp in iTerm.
![Screenshot 2023-05-21 at 11 10 05](https://github.com/kovidgoyal/kitty/assets/45234439/f3a896bd-e125-4f00-817c-d6c8405fd0dd)

**Comment by kovidgoyal** [comment]
maybe my eyes are too old but I cannot see a significant difference in
your screenshots. As I said, looks for the various relevant settings in
kitty.conf to adjust rendering to how you like it. Start with
text_composition_strategy

**Comment by jneidel** [comment]
If the text is looking weird after updating kitty to >=0.28 setting `text_composition_strategy legacy` fixed this for me [see](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy).

**Comment by Shirk** [comment]
> If the text is looking weird after updating kitty to >=0.28 setting `text_composition_strategy legacy` fixed this for me [see](https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.text_composition_strategy).

You sir, are a godsend.. I was trying to find out what made my fonts all go from regular to semi-bold since updating kitty and the `text_composition_strategy` was really the culprit.

Is this documented in the unmodified kitty settings (because I can't find it anywhere in my configuration and had to add it)?
There is a very noticeable difference between how fonts used to be rendered pre 0.28 and how they are rendered now *if you are on a retina / 2.0x hidpi screen* so I had hoped any hints as to what changed ^^'
<img width="509" alt="Screenshot 2023-05-22 at 11 01 01@2x" src="https://github.com/kovidgoyal/kitty/assets/304352/14c4e60b-4387-4041-ab5d-9d77fc4c646a">
<img width="512" alt="Screenshot 2023-05-22 at 11 02 11@2x" src="https://github.com/kovidgoyal/kitty/assets/304352/6dc14c5a-40cf-462b-9af3-d2269438d6de">
