### ISSUE TITLE
Create a split with a specific size

### ISSUE THREAD

**Issue by dantearaujo1** [kovidgoyal/kitty#6310]
I'm trying to develop a add-on for a neovim pluggin that open kitty split at the bottom of my OS window, but i would like to create a split with a specifc height. I already used resize-window to decrease vertical size after launch with --location hsplit, but it seems that if i close the split and open again from neovim it will remember the last size of split and apply resize-window again making the split really short. 

when using kitty @ launch --location "hsplit". Add some args like --location-height 10 --location-width

**Comment by kovidgoyal** [comment]
There is no concept of defined sizes in kitty layouts, since they
are reflowable, i.e. they split up available space between their
windows. Instead of doing a resize, you can use kitty @
set-enabled-layouts to change to a layout with a specified bias instead.
This will mean the next created window will use that bias. And setting
the bias multiple times should not change the effective bias as it is
not an increment operation.
