### ISSUE TITLE
Glitchy resize on macOS

### ISSUE THREAD

**Issue by yairchu** [kovidgoyal/kitty#6341]
**Describe the bug**
When resizing the window on macOS the text "jumps" and "stretches" briefly

**To Reproduce**
Drag the window from the corner frantically :)

**Screenshots**
https://github.com/kovidgoyal/kitty/assets/97606/1a63f2e6-9425-4d87-a156-36a42da6ddac

**Environment details**
```
kitty 0.26.5 created by Kovid Goyal
Darwin MacBook-YAir.local 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:01:02 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T8112 arm64
ProductName:		macOS ProductVersion:		13.3.1 ProductVersionExtra:	(a) BuildVersion:		22E772610a
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                yairchu
```

**Additional context**
I've had the exact same issue in Lamdu (which also uses GLFW) and fixed it so [it resizes very nicely now](https://www.reddit.com/r/nosyntax/comments/13iax30/smooth_resize_and_automatic_layout_demo/).
I don't know how Kitty is built one of the causes for this in Lamdu was rendering in a dedicated thread. Rendering had to move to the main thread to avoid window-size rendering races. I can try to solve it and make a PR if given some pointers.
Cheers, Yair

**Comment by kovidgoyal** [comment]
https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.resize_draw_strategy

**Comment by yairchu** [comment]
> https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.resize_draw_strategy

Just tried all resize strategies. Both `static` and `scaled` look glitchy like my attached video. Only `blank` doesn't. That's a strange behavior imho

**Comment by kovidgoyal** [comment]
Set placement_strategy to top-left in kitty.conf.

**Comment by yairchu** [comment]
> Set placement_strategy to top-left in kitty.conf.

Reproduces also with this option.

**Comment by kovidgoyal** [comment]
Then I am out of ideas. As I said a PR is welcome. Relevant code is in glfw.c and shaders.c and child-monitor.c. Feel free to ask if you need more pointers. Grep for live_resize

**Comment by yairchu** [comment]
I believe that the problem lies in `refresh_callback` just calling `request_tick_callback()` and not actually repainting the window.

**Comment by yairchu** [comment]
But it won't do it immediately, and the OS may already redraw the frame with the wrong image for the window.

**Comment by yairchu** [comment]
> The OS cannot redraw anything except the existing front buffer until
swapBuffers() is called, which is only called on an actual redraw.

The OS has to draw a frame to show on the screen.
While it indeed cannot redraw any app's own frame without the app doing so, it may reuse the app's last frame at a wrong position or scale it (or anything really, "undefined behavior") if the app didn't produce a frame when it requested one.

**Comment by kovidgoyal** [comment]
On Mon, Jun 05, 2023 at 02:11:30PM -0700, Yair Chuchem wrote:
> > The OS cannot redraw anything except the existing front buffer until
> swapBuffers() is called, which is only called on an actual redraw.
> 
> The OS has to draw a frame to show on the screen.
> While it indeed cannot redraw any app's own frame without the app doing so, it may reuse the app's last frame at a wrong position or scale it (or anything really, "undefined behavior") if the app didn't produce a frame when it requested one.

The OS does not request frames. Rendering on macOS is entirely client
side driven. And in kitty rendering happens *much* faster than the
refresh rate of the monitor. Indeed, in kitty rendering is actually
paused waiting for timing events from CVDisplayLink you can turn that
off if you want with sync_to_monitor in kitty.conf

And if what you claim is actually happening, and previous frames are
being rendered distorted, the problem isnt caused by requesting a loop tick. All rendering
is ansynchronous anyway, the OS sends events on the event loop, the
application responds to them asynchronously.

You can have kitty redraw arbitrarily fast by setting repaint_delay and sync_to_monitor in kitty.conf.
If you find that fixes the issue the solution is to override these
setttinfs during a live resize.

**Comment by kovidgoyal** [comment]
On Tue, Jun 06, 2023 at 12:34:17AM -0700, Yair Chuchem wrote:
> > And if what you claim is actually happening
> 
> I attached a video that demonstrates the issue. It is a screen recording that demonstrates my claim.
> 
> Or do you think I would modify the video to create a fake impression that an issue exists?
> I understand that you don't know me, so no offense taken, but is this something that you've stumbled upon people doing?

I was referring to your explanation of the cause of the issue.

**Comment by yairchu** [comment]
> The OS does not request frames. Rendering on macOS is entirely client
side driven

`- (void)drawRect:(NSRect]dirtyRect;` gets called when a resize is happening. IIUC if it is supposed to draw when called. If instead it initiates an asynchronous request to draw then the image drawn may not fit the expected frame size. This would not be a problem if the previous image would had been padded with black borders for example but it appears to be stretched.

**Comment by kovidgoyal** [comment]
On Tue, Jun 06, 2023 at 01:17:43AM -0700, Yair Chuchem wrote:
> > I dont see how it could possibly "draw immediately".
> 
> What I meant is that when the call returns the image is supposed to be drawn.

Drawn on what? We are doing buffered rendering here. Drawing happens on a
backbuffer and when that is done, the front and back buffers are
swapped. Are you saying that you want the complete draw+swap operation
to happen in the drawRect callback? If so, that is definitely not how
GLFW operates.

**Comment by yairchu** [comment]
> Are you saying that you want the complete draw+swap operation
to happen in the drawRect callback? If so, that is definitely not how
GLFW operates.

I'm not sure that's accurate. If I look at the GLFW "splitview" example:

* It does `glfwSetWindowRefreshCallback(window, windowRefreshFun);`
* `windowRefreshFun` does call `glfwSwapBuffers(window)`
* With a breakpoint we can see that `windowRefreshFun` gets called from `_glfwInputWindowDamage` which in turn gets called from `-[GLFWContentView drawRect:]` (through a lot of Cocoa calls eventually it comes from `glfwWaitEvents`)

**Comment by kovidgoyal** [comment]
On Tue, Jun 06, 2023 at 01:36:08AM -0700, Yair Chuchem wrote:
> * With a breakpoint we can see that `windowRefreshFun` gets called from `_glfwInputWindowDamage` which in turn gets called from `-[GLFWContentView drawRect:]` (through a lot of Cocoa calls eventually it comes from `glfwWaitEvents`)

Which means it happens at next event loop tick. glfwWaitEvents spins the
event loop. In kitty's glfw fork there is no waitevents since it
directly runs inside the event loop.

**Comment by yairchu** [comment]
I don't know about the differences with kitty's fork but for the upstream GLFW, if we log after `splitview.c`'s call to `glfwWaitEvents();`:

```C++
glfwWaitEvents();

static int iter = 0;
printf("WaitEvents %d finished\n", iter);
iter++;
```

We can see that `glfwWaitEvents();` doesn't return until the resize is finished. Same is true for `glfwPollEvents();` btw. This is because unfortunately Cocoa enters a modal loop for the resize.

**Comment by kovidgoyal** [comment]
yes I know, that modal loop was precisely why I changed kitty's glfw fork to use the cocoa event loop directly. There are a whole bunch of unfixable issues otherwise. See for example 0dc6ac26c352def3227f77050e1d779c286b1cb7 and fcb26e5dc760b138d2eb604acef9c5af6f686b90. The latter points us to a most likely solution. Turn off rendering only on render frames (aka CVDisplayLink timer events) during a live resize. Which you can test with sync_to_monitor as I have mentioned several times before. Then swap buffers will be called *very soon* after the refresh callback instead of at the next display link timer event.

**Comment by kovidgoyal** [comment]
OK should be easy enough to special case rendering during a live resize
on macOS by factoring the resize rendering code into a separate
function. I'll do it when I have a minute. Or feel free to send a PR if
you are impatient.

**Comment by yairchu** [comment]
Just checked 89875af5e6988474111a35e76058f2e79105af77 and it seems that the problem is still there. Perhaps it's a bit different (actually it's kind of cool):

https://github.com/kovidgoyal/kitty/assets/97606/6a263a46-096f-4a22-9cda-d3ce66f7f68b

Perhaps it doesn't repro on all systems? I'm on an M2 MBA macOS 13.3.1 connected to an external screen.

**Comment by kovidgoyal** [comment]
That's good enough for me :) It doesnt repro on my machine and looks
pretty good on yours. You can probably get rid of the last bits by
setting sync_to_monitor no and repaint_delay 0 in kitty.conf. If that
does work then one can look into forcing those during a live resize.

I am actually thinking of ditching resize_draw_strategy and just always
using scale and showing the cell count. This is because with
semi-transparent windows static looks rather bad.
