### ISSUE TITLE
Reload kitty.conf

### ISSUE THREAD

**Issue by mihaicristiantanase** [kovidgoyal/kitty#635]
Is there a way of reloading the kitty.conf file without restarting kitty?
The use case for this feature would be, for example, to quickly change the colorscheme (from bright to dark).

**Comment by SolitudeSF** [comment]
to change colorscheme you can use [`kitty @ set-colors`](https://sw.kovidgoyal.net/kitty/remote-control.html#kitty-set-colors)

**Comment by mihaicristiantanase** [comment]
Ok, I've enabled remote control and used this command, but the colors still don't change unless I restart kitty.
I've tested 0.11.0.
I've ran the command in kitty.

**Comment by SolitudeSF** [comment]
you should use `-all --configured` flags to apply colors to all existing and new windows and supply the `conf` file with colors.

**Comment by mihaicristiantanase** [comment]
That worked, thanks!

Not sure why providing the config file (which kitty already knows about) is necessary, but probably will be fixed in the future.

**Comment by SolitudeSF** [comment]
because you can use put your coloschemes into separate `conf` files and source them on demand. or you can just provide a list of colors as commandline arguments. basically, sourcing the default config file is not the only option.

**Comment by mihaicristiantanase** [comment]
I see.
Maybe not providing any file should fallback to the loaded conf file?

**Comment by kovidgoyal** [comment]
Just for reference, you dont need to enable remote control just to change colors, you can also use terminal escape codes, that work in most terminals, not just kitty https://sw.kovidgoyal.net/kitty/faq.html

And why would you want to change colors back to kitty.conf, since the colors are presumably already set to those in that conf file.

**Comment by mihaicristiantanase** [comment]
Not sure I understand your question, but basically, I have 2 colorschemes set in kitty.conf and I'd like to switch between them without restarting kitty. Previously, I uncommmented the one I want and comment the other and then restart kitty. With "@ set-colors" it's just the commenting part :)

**Comment by kovidgoyal** [comment]
Create a second conf file and pass that to @ set-colors, then you dont need to do the commenting part at all.

**Comment by mihaicristiantanase** [comment]
This is great, thanks!

**Comment by tammersaleh** [comment]
It'd still be useful to be able to reload the `kitty.conf` file while iterating on configurations.  Any chance this is on the upcoming feature list?

**Comment by kovidgoyal** [comment]
Nope, it is way more effort than it is worth. kitty is far more configurable than pretty much any other terminal emulator, to the extent that even how the OpenGL shaders that kitty uses are compiled depends on kitty.conf

**Comment by jesse-c** [comment]
Should I expect `kitty @ set-colors` to work within tmux? I receive this error:

```
kitty @ set-colors ~/.config/kitty/themes/ayu_light.conf
Traceback (most recent call last):
  File "Python/runpy.py", line 280, in run_path
  File "Python/runpy.py", line 85, in _run_code
  File "kitty/__main__.py", line 119, in <module>
  File "kitty/__main__.py", line 115, in main
  File "kitty/__main__.py", line 22, in remote_control
  File "kitty/remote_control.py", line 175, in main
  File "kitty/remote_control.py", line 123, in do_io
  File "kitty/remote_control.py", line 103, in recv
TimeoutError: Timed out while waiting to read command response. Make sure you are running this command from within the kitty terminal. If you want to run commands from outside, then you have to setup a socket with the --listen-on command line flag.
```

macOS 10.15.4
kitty 0.16.0
tmux 3.0a

**Comment by kovidgoyal** [comment]
No idea, tmux loves to mess with escape codes it does not understand, so
quite possibly not.

**Comment by wookayin** [comment]
@jesse-c I made `kitty @remote_control commands` work inside tmux! 🎉🎉

I need to implement some hacks because the kitty remote-control program has a direct interaction rather than printing control sequences to stdout; well, but there should be a way to bypass tmux via passthrough sequences. I wish kitty could officially support this by being aware of tmux (@kovidgoyal, what do you think?), but as of now this would be the only way.

Here is the script for you: https://github.com/wookayin/kitty-tmux

**Comment by kovidgoyal** [comment]
On Thu, Mar 26, 2020 at 12:25:06AM -0700, Jongwook Choi wrote:
> @jesse-c I made `kitty @remote_control commands` work inside tmux! 🎉🎉
> 
> I need to implement some hacks because the kitty remote-control program has a direct interaction rather than printing control sequences to stdout; well, but there should be a way to bypass tmux via passthrough sequences. I wish kitty could officially support this by being aware of tmux (@kovidgoyal, what do you think?), but as of now this would be the only way.

If there is a reliable way to detect tmux other than hacks based on env
vars, sure, otherwise you can always add a command line option to kitty @
to wrap generated escape sequences.

**Comment by kovidgoyal** [comment]
And note that the remote control protocol is actually two way, so you would need to presumably wrap the sequences both ways. Unless tmux only filters them one way for some unfathomable reason. And then there will be the whole tmux inside tux thing, where tmux is not smart enough to not unwrap escape sequences if it is running inside itself. https://github.com/tmux/tmux/issues/846

So that means you will have to wrap things multiple times depending on how many nested tmuxes there are, which you have no way of knowing.

**Comment by pblgomez** [comment]
I have enabled remote control, but when I type this command:
```
kitty @ set-colors --all --configured ~/.config/kitty/kitty.conf
```
It only changes colors the one terminal I am typing on.

**Comment by Luflosi** [comment]
If you're using kitty on Linux, you're probably starting multiple instances. In this case, see https://sw.kovidgoyal.net/kitty/invocation.html#cmdoption-kitty-single-instance.

**Comment by nicu-chiciuc** [comment]
Here's another usecase for reloading the config. I'm currently using ~6 tabs witch each tab having 2-6 open panes. I usually leave kitty running for extended periods of time so that I maintain this layout. Restarting kitty means that I'll have to recreate my desired layout.

I know that it's possible to have scripts where I can configure so that I start out with my necessary layout, but it would be nice to also have this alternative.

**Comment by kovidgoyal** [comment]
It's been possible to reload kitty.conf for years. Press ctrl+shift+f5

**Comment by nicu-chiciuc** [comment]
thanks @kovidgoyal, I guess searching the docs first is a good idea. For OSX the default shortcut is `⌃+⌘+,`

**Comment by RAprogramm** [comment]
how to reload conf from terminal? i mean ctrl+shift+f5 is working, but i want to do it from neovim for example. what is keymaps bind command?

**Comment by kovidgoyal** [comment]
Read the first couple of paragraphs of
https://sw.kovidgoyal.net/kitty/conf/

**Comment by RAprogramm** [comment]
> Read the first couple of paragraphs of
> https://sw.kovidgoyal.net/kitty/conf/ 
> 

Thanks, already done!
