### ISSUE TITLE
SSH into ubuntu linux causes really weird duplicate visual issues

### ISSUE THREAD

**Issue by imajes** [kovidgoyal/kitty#6379]
**Describe the bug**

ssh'ing into a remote linux server (ubuntu, zsh) from macos (zsh) causes duplicate characters displayed on screen, as well as cursor position jumping around
 
**To Reproduce**
1. ssh in to server
2. do some typing
3. See error

**Screenshots**

https://github.com/kovidgoyal/kitty/assets/2073/f66546c2-5b8e-4e1c-8a4f-d4dce9662acc

**Environment details**
```
kitty 0.28.1 (07bcc5ba61) created by Kovid Goyal
Darwin reamde.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:52:24 PDT 2023; root:xnu-8796.121.2~5/RELEASE_ARM64_T6000 arm64
ProductName:		macOS ProductVersion:		13.4 BuildVersion:		22F66
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /opt/homebrew/bin/zsh
Loaded config files:
  /Users/james/.config/kitty/kitty.conf

Config options different from defaults:
bold_font            SauceCodePro Nerd Font Mono Medium
bold_italic_font     SauceCodePro Nerd Font Mono Medium Italic
font_family          SauceCodePro Nerd Font Mono Light
font_size            18.0
italic_font          SauceCodePro Nerd Font Mono ExtraLight
window_padding_width FloatEdges(left=10.0, top=5.0, right=10.0, bottom=5.0)
Added shortcuts:
	cmd+left →  prev_tab
	cmd+right →  next_tab
Colors:
	background           #2b2b2b   
	color1               #da4839   
	color10              #83d082   
	color11              #ffff7b   
	color12              #9fcef0   
	color13              #ffffff   
	color14              #a0cef0   
	color2               #509f50   
	color3               #ffd249   
	color4               #6d9cbd   
	color5               #cfcfff   
	color6               #6d9cbd   
	color7               #ffffff   
	color8               #323232   
	color9               #ff7b6a   
	cursor               #ffffff   
	foreground           #e5e1db   
	selection_background #5a637e   
	selection_foreground #2b2b2b   

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/bin:/bin:/usr/sbin:/sbin
	LANG                                en_US.UTF-8
	SHELL                               /opt/homebrew/bin/zsh
	USER                                james

```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

Yep, this happens with `--config NONE`.

**Comment by imajes** [comment]
this'll be because `$TERM` is set to something... unique.

**Comment by zasdaym** [comment]
How do you solve this issue?

**Comment by sirenkovladd** [comment]
+1

**Comment by mtalexan** [comment]
I'm experiencing the same thing.  `$TERM` is set to the default `xterm-kitty` still, and it happens even with `kitty --config NONE`.  

It only happens when my remote server uses zsh, and it seems to be related/exacerbated by the `zsh-autosuggestions` plugin.  But even with `zsh-autosuggestions` disabled, it still happens.  There's no problem when zsh with `autosuggestions` is used from kitty on the local system, it's only when it's on the remote system.

As a point of refernece, this happens if the local system is Fedora or Ubuntu and the target is Ubuntu.  It does NOT happen when the remote system is OpenSUSE, even though the local systems and the remote systems all have identical shell configurations (they all use nix home-manager to share configs).

**Comment by mtalexan** [comment]
I found what @imajes was talking about thru an explanation [on Reddit](https://old.reddit.com/r/linux4noobs/comments/tkvs8o/kitty_terminal_with_ssh_issues/).  

---

It's not really mentioned in the kitty documentation, or the `kitty.conf`, but the issue _is_ with kitty setting `TERM=xterm-kitty` by default.  This is normally done so that `kitty-terminfo` is used, which is more feature-ful and therefore highly desirable when you know it's avaiable (like when running locally), but it causes problems if `kitty-terminfo` doesn't exist on the target/remote system. 

When you use `kitten ssh my_server`, the plugin automatically copies the kitty-terminfo to the remote system temporarily, so everything works fine.  But if you just use regular `ssh my_server` it doesn't.  It seems it plays worse havoc with `zsh` than with `bash`, which is purely coincidence. In reality, both will have problems.  

There are 3 possible solutions:
1. Always use `kitten ssh` instead of `ssh` when running in a kitty terminal from the local machine.
2. Install `kitty-terminfo` on all remote systems.
3. Manually override the `TERM` variable to something reasonable before SSH-ing.

The first option isn't terrible, but it won't always work as expected.  It's copying a bunch of stuff to the remote system, and if others log in with the same shared credentials into the same remote system at the same time, it can cause problems.  It's also slower to initially connect, but it supports re-using the connection for multiple windows.  You have to read the [Kitty SSH Plugin documentation](https://sw.kovidgoyal.net/kitty/kittens/ssh/) for a full list of pros and cons.  

Installing `kitty-terminfo` on all the remote servers usually won't be an option, so that's probably out unless everyone else also using the server is likely to use kitty from their machines and you're willing to add the support to the remote server for it.  

Manually overriding the `TERM` variable is probably your best bet.  Basically, whenever you do `ssh my_server`, you need to instead do `TERM=xterm-256color ssh my_server`.  This sets the `TERM` to something standard, but you'll lose a number of the Features touted by kitty for remote sessions.  I'm not sure the copy-paste will work properly for example, and it almost certainly won't be able to display images in the terminal.

**Comment by kovidgoyal** [comment]
*Do not* change TERM, you will break other things. Read the docs: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.term

And the issues with terminfo files missing are documented in the FAQ: https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work

**Comment by mtalexan** [comment]
Is there a compatibility mode for kitty so it can connect to servers/containers/shells that are unable to have kitty terminfo installed even temporarily?  Like many people, I often need to be able to enter a subshell in containers where kitty terminfo can't be installed, even temporarily. Other times I'm able to have it installed temporarily, but not permanently (`kitty +kitten ssh --kitten shell_integration=no-rc` and `kitty +kitten run-shell`?). Is there some way for kitty to still be usable for these primary use cases, or do I just need to use a different terminal emulator?

**Comment by rafalglowacz** [comment]
Upon running into this issue I checked my dotfiles and realized I've been on `TERM=xterm-256color` for over 2 years (not just for SSH, everywhere). I'll probably try xterm-kitty for a few days to see what I've been missing out on, but to be honest, I didn't see any issues whatsoever in that time. And switching to xterm-kitty and ssh'ing into my cloud instance immediately resulted in problems described by OP.

**Comment by s7117** [comment]
I just encountered this issue as well when using ssh along with zsh-autosuggesions. While setting TERM to xterm-256color on the host does work, this is not ideal according to:

> _Do not_ change TERM, you will break other things. Read the docs: https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.term
> 
> And the issues with terminfo files missing are documented in the FAQ: https://sw.kovidgoyal.net/kitty/faq/#i-get-errors-about-the-terminal-being-unknown-or-opening-the-terminal-failing-or-functional-keys-like-arrow-keys-don-t-work

Running the following command from the FAQ mentions above fixes it on the remote host and doesn't require sudo:
```
infocmp -a xterm-kitty | ssh myserver tic -x -o \~/.terminfo /dev/stdin
```

**Comment by mtalexan** [comment]
Yes, the issue seems to be that kitty uses a unique term type that is a little different from a standard xterm-256color. If you don't have that term type on the remote system, it seems to fall back to some weird non-compatible format that acts especially badly with the control characters the zsh-autosuggestion uses.
