### ISSUE TITLE
Lock number of columns and rows, scale font as needed to fill window.

### ISSUE THREAD

**Issue by loops** [kovidgoyal/kitty#6433]
I'm connecting to an old application that only works with a fixed 80 cols and 25 rows.  It would be nice to force this geometry, and automatically scale the font as needed, to fill the entire window.  This allows the user to easily alter and pick a comfortable window and font size, without having to manage them independently.

There aren't a lot of terminals that offer this feature, but one of them is ironically also named Kitty:

       https://github.com/cyd01/KiTTY

But it is only offered in its Windows version, not when compiled for Linux.

**Comment by kovidgoyal** [comment]
kitty -o initial_window_width=80c -o initial_window_height=25c -o remember_window_size=n -o font_size=whatever_floats_your_boat

**Comment by loops** [comment]
HI there, thanks for the quick answer!

I didn't make the request clear enough sorry.   The desire is for the font to automatically scale when the user changes the dimensions of the window, without having to fuss to manually find a font size that fills the entire canvas.

**Comment by kovidgoyal** [comment]
I dont see the point of having windows with differently sized text on
your screen, that's just chaos. Just dont resize the window. If you are
using a tiling WM make it a "float" window so that it is not resized. Or
use --class/--name to make th ewindow non-resizble with your window
manager.

Or write a script that adjusts the font size however you like using the
kitty remote control API. You can get the current window size in pixels
with kitten icat --print-window-size and see
https://sw.kovidgoyal.net/kitty/remote-control/

**Comment by loops** [comment]
Thanks. 

The user in question, sometimes wants to go full screen (and still maintain fixed geometry), and also sometimes just adjusts the window in order to get a bigger font size.    They can't just increase the font size, because then the geometry of the window is wrong.   So, when they want a bigger font, they just use their window manager to make their window larger, and automatically get a larger more readable font, that doesn't break the application by changing the geometry.

I agree it is a niche request, so I wont bother you about it again, but once you've used it, it's really quite refreshing and stops a lot of fighting to manually keep the window size/geometry and font in sync.
