### ISSUE TITLE
Glyph icon size

### ISSUE THREAD

**Issue by vulgrim** [kovidgoyal/kitty#648]
Since the last kitty-git AUR update my glyph icons are smaller. My font is Fira Code and I use Font Awesome icons. 
`symbol_map U+F07B,U+F07C,U+F102,U+F103,U+F126,U+F135,U+F14A Font Awesome 5 Free`
kitty version : 0.11.1
Can I make my glyph icons bigger again ?

**Comment by kovidgoyal** [comment]
There have been no changes to the font rendering code in a while, so I dont think it is anything kitty related, unless you are upgrading from a very old version. You cannot control the size of individual symbols, since they are sized to fit inside the same cells as all other characters. You can adjust the cell size, via the adjust_* settings in kitty.conf, that will give more space for the icons, at the cost of extra blank space around other characters.

**Comment by kovidgoyal** [comment]
It looks like in the latter case it is being rendered single width rather than dual width. I assume it is not a proper unicode symbol but a special glyph? In that case make sure there is a space after it, as private use unicode symbols are only rendered in two cells if theya re followed by a space.

**Comment by vulgrim** [comment]
Older kitty version
![2018-06-17-144601_700x88_scrot](https://user-images.githubusercontent.com/9071958/41507985-5d9f04ba-723d-11e8-8431-15818143dc35.png)
New kitty version
![2018-06-17-144647_694x99_scrot](https://user-images.githubusercontent.com/9071958/41507986-5dc747c2-723d-11e8-8c2b-c31d8e6138fe.png)

**Comment by maximbaz** [comment]
@vulgrim it has to be something on your side, I'm also on Arch using Fira Code + Font Awesome and icons didn't change size after the upgrade. I don't have `symbol_map` though, fontconfig seems to choose correct font for icons anyway. Try bisecting your kitty / zsh configuration.
