### ISSUE TITLE
Layouts are not working

### ISSUE THREAD

**Issue by fourcolors** [kovidgoyal/kitty#651]
So I've edited my kitty.conf to have map 
```
enabled_layouts *
map ctrl+alt+1          goto_layout tall                                                                                                                                                        
map ctrl+alt+2          goto_layout stack
```

I restart kitty and those commands don't work. Am I missing something here? or is this a bug? I'm on OSX

**Comment by kovidgoyal** [comment]
Works for me on macOS.

**Comment by fourcolors** [comment]
@kovidgoyal nope, not working.

**Comment by fourcolors** [comment]
@kovidgoyal Just because you close all of your tickets doesn't mean there aren't bugs dude.

**Comment by fourcolors** [comment]
@kovidgoyal Also, I think you awesome stuff and you're project is amazing but dismissing me like is pretty arrogant.

**Comment by kovidgoyal** [comment]
Umm since you opened another bug report saying none of your key board shortcuts are working, why would anyone consider this bug report relevant to anything? It's obviously not working for you because none of your keyboard shortcuts are working.

Oh and over the fifteen odd years I have been maintaining open source projects used by millions of people, I have developed extremely good instincts about when a bug report is an actual bug and when it is not. I can, of course, sometimes be wrong, if so, you are welcome to provide some more evidence for why I might be wrong, calling me arrogant is not going to help you.

**Comment by rockpunk** [comment]
Necro posting because I came across this issue when working through my own misunderstanding:

> Layouts only work with Kitty windows (started with cmd+enter), not 'OS Windows' (started with cmd+w)

Might be worth calling this out somewhere in the docs

**Comment by kovidgoyal** [comment]
It's mentioned in multiple places in the docs, starting with the very
first section in the overview after design philosophy, named Tabs and
Windows: https://sw.kovidgoyal.net/kitty/overview/#tabs-and-windows
