### ISSUE TITLE
Please use a different test image than Lenna

### ISSUE THREAD

**Issue by jamessan** [kovidgoyal/kitty#661]
Recent uploads of kitty to Debian have been rejected due to the distribution of the Lenna test image (background [here](https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html)).  Would you replace it with an image that doesn't have questionable rights to distribute and is more inclusive, e.g. the [Utah teapot](https://en.wikipedia.org/wiki/Utah_teapot)?

**Comment by kovidgoyal** [comment]
Sure, if you can propose a suitable alternate image, feel free to send a PR. I'd prefer a photo, rather than a generated image such as the teapot, since viewing photos is the main use case of kitty's image support. Preferably a photo that is widely used as a demo for image processing libraries. Remember to change the reference to the image in gr.py

As for Debian policies, since it is a demo image, you can simply delete it and gr,py from your package, since it affect neither the tests nor kitty itself.
