### ISSUE TITLE
Disable C1 controls in UTF-8 encoded text (to improve security)

### ISSUE THREAD

**Issue by gsauthof** [kovidgoyal/kitty#6739]
**Is your feature request related to a problem? Please describe.**
Apparently, Kitty supports C1 controls in UTF-8 encoded text which may have security implications and thus is problematic.

**Describe the solution you'd like**
Disable that support by default and provide an option to enable it again.

**Describe alternatives you've considered**
Use another terminal.

**Additional context**

This issue is discussed in a comprehensive write up on [terminal emulator attack vectors](https://dgl.cx/2023/09/ansi-terminal-security) (David Landbeater, 2023-09) and discovered vulnerabilities. 

Unfortunately, Kitty is kind of prominently mentioned in its 'Terminals to avoid' section:

> Additionally some terminals support C1 controls in UTF-8 encoded text, which per [this 2015 posting to oss-security](https://www.openwall.com/lists/oss-security/2015/09/20/1) is problematic. Some terminals have the ability to turn this off, if they do not such as Kitty I cannot recommend their use.

**Comment by kovidgoyal** [comment]
As I explained in exhaustive detail to David in private correspondence,
this is not an actual security issue, and hand waving about it doesn't
make it one. 

He claims its a security issue based on two things:

1) It's under specified
Doesn't matter kitty and VTE both decode C1 correctly by decoding bytes
as UTF-8 and only then looking for control chars. I don't know about
wezterm, but I would be extremely surprised if it doesn't do this as
well.

2) There is some elaborate made up scenario in a mailing post of two
independent processes/threads writing to the tty at the same time which
could possibly end up creating a C1 escape code.

The problems with this completely nonsensical scenario are:

a) If two independent processes are writing to the terminal at the same
time you have *much bigger* problems than C1 controls. All sorts of
things will break, and this will be immediately noticeable to a user.

b) If the attacker can control the output of either of those processes,
which he would have to do in order to actually do something malicious
with a non-negligible probability, he can just get the process to
write whatever C0 escape codes he wants in the first place. 

About, the *only* reasonable bad thing one can say about C1 controls is
that sanitizing a stream of utf-8 text has to work by decoding the UTF-8
and sanitizing that, then re-encoding. Nowadays, UTF-8 decoders/encoders are
trivially available everywhere so I dont think this is an undue burden
on terminal programs.

I am very unhappy with the way that article was written. David
didnt even bother to mention my dissenting opinion before hand waving
about C1 controls and labelling them "unsecure". Pure unadulterated FUD.

I am not in the business of breaking other people's code and long
existing standards on the basis of FUD.

That said, there is one very tempting (to me) reason to drop C1
controls. It would allow me to rewrite the parser in kitty to work on
bytes rather than code points which will speed up various things.

So, in conclusion, there is no security issue here. I may in the future
drop C1 controls in kitty, for performance reasons, but that wont be
anytime soon and it certainly wont be because of this FUD.

**Comment by gsauthof** [comment]
Ok, I think it's good that you have posted your response here such that kitty users who read that article and research the background find it.

The reference OSS message states:

> Since I see no reasonable application-side mitigation for this, I
think the right recommendation should be disabling C1 control codes in
terminal emulators, at least in UTF-8 mode, but preferably just across
the board. **AFAIK nothing is using them.** They don't even work reliably
across all terminal emulators; many users have C1 disabled from the
old days where that was the right way to use certain legacy 8-bit
encodings, and some UTF-8 terminal emulators probably don't even
support them at all.

(emphasis mine)

Do you agree with that  highlighted assertion?

Or are there some applications out there that would likely break with C1 control code support removed/disabled?

**Comment by kovidgoyal** [comment]
On Sat, Oct 21, 2023 at 06:10:03AM -0700, Georg Sauthoff wrote:
> Ok, I think it's good that you have posted your response here such that kitty users who read that article and research the background find it.
> 
> The reference OSS message states:
> 
> > Since I see no reasonable application-side mitigation for this, I

The reasonable mitigation on application side is to sanitize the text
of both C0 and C1 escape codes. Either before the text is encoded to UTF-8
or directly in UTF-8 as I described above, via a simple decode, check,
encode step. This is literally a 100 line C header file. And that is C, in
Python it would be 3 lines, and I am sure it would be similar in any
modern language.

> think the right recommendation should be disabling C1 control codes in
> terminal emulators, at least in UTF-8 mode, but preferably just across
> the board. **AFAIK nothing is using them.** They don't even work reliably
> across all terminal emulators; many users have C1 disabled from the
> old days where that was the right way to use certain legacy 8-bit
> encodings, and some UTF-8 terminal emulators probably don't even
> support them at all.
> 
> (emphasis mine)
> 
> Do you agree with that  highlighted assertion?
> 
> Or are there some applications out there that would likely break with C1 control code support removed/disabled?
>

It has existed as a standard for multiple decades now, so I would be
extremely surprised if nothing used it. Some person on the internet
stating that he doesn't know of anything using it does not constitute
proof or even strong evidence.

Here is a bug caused by a terminal not supporting it:
https://github.com/alacritty/alacritty/issues/3105
here is another
https://bugs.launchpad.net/ubuntu/+source/vte3/+bug/1297051
