### ISSUE TITLE
Always underline URLs

### ISSUE THREAD

**Issue by pallaswept** [kovidgoyal/kitty#6766]
**Is your feature request related to a problem? Please describe.**
Sometimes there is a URL on screen, but in order to see it underlined, I must hover it with the mouse. It would be nice to know if there is a URL, just by looking.

**Describe the solution you'd like**
Behaviour just like when you hover a URL with the mouse, only, URLs would be underlined all the time, even without mouse hover.

**Describe alternatives you've considered**
Can't think of any way to know except to pass the mouse cursor across all the text and see if an underline appears.

**Additional context**
This would be nice because sometimes URLs can be encoded and so it can appear as normal text, eg

`echo -e '\e]8;;http://somehackingwebsitecoinminermalware.com\e\\innocent looking text\e]8;;\e\\'`

and you might click on it and accidentally open a URL without intending to. It also quickly informs you if you are able to open a browser for more information without having to read the text to see if you read a URL.

I guess the only concern here is performance, since I guess it would have to scan all text printed to the screen to look for URLs (not only the text underneath the mouse cursor). So probably it should be optional, so that it can be enabled by users with PCs which can handle the load/ disabled by users with slower PCs.

**Comment by kovidgoyal** [comment]
Not a fan of this idea. URLs that are URLs in text are already pretty
obvious given they have URL scheme prefixes such as https://

URLs using OSC 8 are only marked if the application producing them
wants them to be marked. The terminal should not be second guessing what
the application wants, it makes it impossible to design applications
that rely on certain behavior. For example, an application might want to
use an OSC 8 hyperlink that is not an actual hyperlink but instead
performs some action, r that is already underlined or otherwise
highlighted in a way that matches the application design. If the
terminal were to override that, it would be confusing and look bad.

As for seeing where a URL will lead when you click it before clicking it
there is already the show_hyperlink_target option for that.

And yes, performance will absolutely suck haivng to detect URLs in all
text and mark them.

**Comment by pallaswept** [comment]
> URLs in text are already pretty
> obvious given they have URL scheme prefixes such as https://

Yes but that presumes reading the text, and there may be a lot of it. If the underline is there, you don't have to check for the text, because you can see the underline.



> The terminal should not be second guessing what the application wants

And if the application wants to be malicious, now it can. It should be up to the user, not the application. If the user sees it making their application look bad, they could turn it off.


> As for seeing where a URL will lead when you click it before clicking it there is already the show_hyperlink_target option for that.

But what if it isn't underlined, so you don't know it's a URL, and then you click on it, thinking it's normal text and clicking it does nothing, but it actually is a link to www.malware.com?



> And yes, performance will absolutely suck havng to detect URLs in all text and mark them.

My PC handles it pretty well in the browser I think it can handle it in the terminal, too. It doesn't have to be on by default.... and it doesn't have to scan all text, just what's visible right now.

**Comment by kovidgoyal** [comment]
Except that kitty underlines URLs on hover and also optionally shows hyperlink targets.  So accidental clicks on URLs dont happen unless you blindly click things without looking at the screen in which case it being pre-underlined is not going to help. Not to mention that if simply opening URLs is dabgerous on your machine you have FAR bigger problems to worry about.

**Comment by pallaswept** [comment]
> accidental clicks on URLs dont happen unless you blindly click things without looking at the screen

Except you're assuming that users hover _and then pause to check for an underline_ and then click. If there's a wall of text and it all looks like text, clicking on some random part of it to activate the window or begin a selection or something, without pausing to check if it underlines, is normal behaviour....

> in which case it being pre-underlined is not going to help. 

....Which is why it being pre-underlined would help, which is why I asked for it. I understand that you're not personally a fan of the idea and don't have a need for it, but not everyone uses their PC just like you. If you wanted this feature, I'm sure it would already be here; I'm not asking for it for *your* use-case, I'm asking for it for *mine*.

> Not to mention that if simply opening URLs is dabgerous on your machine you have FAR bigger problems to worry about.

Agreed but it'd still be nicer to not accidentally click a URL that you didn't know was a URL, and it'd still be nice to quickly locate URLs in walls of text at a glance because they're underlined. There are reasons browsers do it that way. Is the terminal really any exception to those same reasons?

**Comment by kovidgoyal** [comment]
Many if not most of the features in kitty, I don't use, they are there because someone asked for them and I agreed they were a good idea. You want me to implement a feature for your use case, you need to convince *me* that it is worth both *my time* and whatever overhead it adds to the codebase in terms of complexity and performance. You havent met that bar.

No, browsers, *do not* override application specific hyperlink styles. Indeed in HTML you can make any random element clickable by adding an onclick handler that can have no style at all. Hell you can make the entire document clickable.

And kitty already has allow_hyperlinks=ask if you want confirmation when clicking hyperlinks.

**Comment by pallaswept** [comment]
Hi @kovidgoyal

**Comment by kovidgoyal** [comment]
Again, you can add onclick to any element in HTML and no amount of CSS overrides is going to style it differently. 

And again, terminals overriding hyperlink styling prevents applications from relying on their own styling. 

You have no clue what implementing this would involve and what performance costs it would have even when turned off. I do, and I deem it not worth it. You repeating the same things endlessly is not going to change my mind.
