### ISSUE TITLE
The diff kitten changes the cursor from block to beam under tmux

### ISSUE THREAD

**Issue by gabebw** [kovidgoyal/kitty#677]
* tmux version: 2.7 (with empty configuration file)
* kitty version: 0.11.1
* OS: macOS 10.13.4
* Kitty configuration: none, this happens even after removing `~/.config/kitty/kitty.conf`

Hi, thanks for making kitty! I've found some weird behavior and I hope you can help.

To reproduce:

1. Open a new shell under tmux. (This bug only occurs when running under tmux.)
1. Notice that the cursor is block.
1. Run `kitty +kitten diff` on any 2 files: `kitty +kitten diff foo bar`.
1. Press `q` to exit the diff kitten
1. The cursor is now a beam.

Block cursor:
<img width="50" alt="zsh 2018-06-23 23-07-26" src="https://user-images.githubusercontent.com/257678/41816439-368b1bfa-773a-11e8-8447-23420c0cd26a.png">

Beam cursor:
<img width="27" alt="zsh 2018-06-23 23-08-45" src="https://user-images.githubusercontent.com/257678/41816448-644e44c2-773a-11e8-8b54-a90b51884cbd.png">

**Comment by kovidgoyal** [comment]
Actually I suppose I can have the kitten detect if it is running under tmux and if so, not change the cursor. Though really, this should be fixed in tmux.

**Comment by kovidgoyal** [comment]
I tried it out and as far as I can see, tmux completely breaks the diff kitten. Scrolling does not work, colors are wrong, etc. So I dont think it is worth working around this particular issue. The fundamental premise of tmux is a bit of a hack, it needs to parse and change all the various terminal escape codes it sees, and it mangles escape codes it does not know about. Since the diff kitten uses many kitty specific protocols, it is not surprising ti does not work with tmux.
