### ISSUE TITLE
Terminal selection remains highlighted after selecting something else.

### ISSUE THREAD

**Issue by dagbdagb** [kovidgoyal/kitty#6903]
**Is your feature request related to a problem? Please describe.**
With kitty 0.30.0 , under Wayland 1.22 / Wayfire 0.7.5 / glfw 3.3.8:

When selecting text in a terminal, previously selected text in a different terminal (in the same or different process) remains highlighted. Selecting text in the same terminal unhighlights the previously selected text.

**Describe the solution you'd like**
I would like previously selected text to be 'un-highlighted' whenever and wherever I select other text.

**Describe alternatives you've considered**
The current behavior does not align with what I am familiar with in the X11 world. So, one alternative would be to 'just get used to it'. I live with it now. I find it ever so slightly messy.

I believe there is a Wayland signal to catch for selections. But even if there isn't one, the kitty client should be able to catch the situation (selecting text when another terminal in the same client, split window) also does a select. Then I would not have multiple selects per workspace, the way I use kitty.

It may also be the case that this behaviour depends on functionality in glfw, in which case I hope to be informed so I can bring it up in their tracker. 

And finally, it may be the case that this should be configurable in kitty. I am not truly convinced this is a useful feature for anyone?

**Additional context**
Thank you for kitty.

**Comment by kovidgoyal** [comment]
In no OS I have ever used, including X11, does creating a selection in one window clear the selection in another. kitty certainly has no such feature. Indeed I cant see why I would ever want to lose the selection in window A just because I made a selection in window B. That would break, for example, copying text, pasting it into something else to process it somehow, then copying it back to replace the previously selected text.

So I dont know what you are talking about, there is certainly no such feature in kitty code. If your X11 system behaves that way it will be via some global config/hack. Look for an equivalent one in wayland (though given this is wayland, I highly doubt one would exist).

**Comment by dagbdagb** [comment]
Thank you for clear_selection_on_clipboard_loss. Much appreciated.
