### ISSUE TITLE
Window border

### ISSUE THREAD

**Issue by emprovements** [kovidgoyal/kitty#699]
Hi, I am just thinking if it would be possible to draw border lines only between kitty windows, not on the actual terminal window border side. Something like tmux does this. Often when I create 3 windows, their borders does not align to each other.

**Comment by kovidgoyal** [comment]
I'm afraid I dont like this idea, not drawing borders on some sides means that you dont know where the actual terminal area starts/ends, so it can look like there are blank cells when there are not.

I'm not sure what you mean by window borders dont align with each other. As long as the windows are all the same ize in the layout, they will align, if they are not the same size they cannot align.

**Comment by emprovements** [comment]
I understand. Well I ment this and it looks quite ugly. [https://imgur.com/a/eB5xkGK](url)

**Comment by kovidgoyal** [comment]
If you use the tall/fat/grid layouts then windows will be differently sized depending on the number of windows, since window sizes have to be multiples of the cell size. Use the horizontal/vertical layouts and they wont be differently sized. As for it looking ugly, I'm not sure what is so ugly about it? How would you rather have it look? Assuming that there have to be borders so that you know where the terminal area is, then I dont see what alternative there is. You can of course turn off the border entirely in kitty.conf.

**Comment by emprovements** [comment]
Well, I have border of the window itself so I guess I know where the terminal area is. I like how the tmux has it for example. The only lines shown are the inner lines and outer border is the widow itself. By the window I mean window on OS level. I just found kitty the best and fastest terminal for Mac right now so I am trying to figure out how to make it really shine in terms of design. I tried to disable borders but than sometimes it is very confusing what is running where. So I made lines very thin and grey so it looks clean. I would also use tmux for this but I don't see the reason when kitty does it very well. Apart from this one "issue" :-D Maybe I am just too picky.

**Comment by emprovements** [comment]
Exactly 😉

**Comment by kovidgoyal** [comment]
Well, it should be possible to add a setting to generate only internal borders. I might get to it someday, in the meantime, patches are welcome (all relevant code is in layout.py)

**Comment by emprovements** [comment]
I will try to take a look. Thanks for a hint where to focus. I just never contribute to more complicated project like this 😁

**Comment by kovidgoyal** [comment]
You're welcome :) Feel free to ask if you cannot figure out something.

**Comment by kovidgoyal** [comment]
Oh and I forgot to mention another major reason that all around borders are required. The border color is used to indicate the active window and windows in which a bell has occurred. If you use only borders between windows, that indication no longer works, since there is now only one border for two windows.

**Comment by emprovements** [comment]
Understand. But I don't use a bell so I don't mind to have the bell disabled. But as you said before, to have it as a setting would be best.

**Comment by kovidgoyal** [comment]
Turns out it is possible to highlight the active/bell window while still collapsing neighboring borders.
