### ISSUE TITLE
X Error of BadRRCrtc on suspend

### ISSUE THREAD

**Issue by tarka** [kovidgoyal/kitty#700]
When suspending on my system I get the following error:
```
X Error of failed request:  BadRRCrtc (invalid Crtc parameter)
  Major opcode of failed request:  140 (RANDR)
  Minor opcode of failed request:  20 (RRGetCrtcInfo)
  Crtc id in failed request: 0x500
  Serial number of failed request:  50854
  Current serial number in output stream:  50854
```
Note that this is a Wayland desktop (Gnome 3.28.2), and Kitty doesn't show up in `xlsclients`.

Other details:
* Debian Testing
* Self-built Kitty (master, 4bf0e0ea23de28e0c7f80e2c88f6436cb4372494)
* Gnome Shell 3.28.2-0

**Comment by kovidgoyal** [comment]
kitty does not do X interaction itself, that is handled by glfw (https://github.com/glfw/glfw) you should report the error there. Also you can try the experimental wayland backed. Run kitty with KITTY_ENABLE_WAYLAND=1 (also needs the WAYLAND_DISPLAY env var set).

**Comment by kovidgoyal** [comment]
kitty's glfw fork already contains that commit. Indeed it contains all commits up to the head of glfw master. It's likely that the fix if 1147 disn't fix the issue completely. 

I suggest using wayland, since you are on a wayland desktop anyway. While wayland support is experimental, most things should work.

**Comment by kovidgoyal** [comment]
This commit might help as well: https://github.com/kovidgoyal/kitty/commit/ab7f3310c4f7982026a897155eabb097683658b2
