### ISSUE TITLE
'xterm-kitty': unknown terminal type

### ISSUE THREAD

**Issue by Nelyah** [kovidgoyal/kitty#713]
I'm having an issue when connecting to remote server (onto which kitty is not installed).
From kitty, if I ssh to the remote server, everything works well, however trying to run a program like `top` will leave me with this error message: `'xterm-kitty': unknown terminal type.` 

I have not been able to understand what it really boils down to, and if it is to be expected or not. Is there any way to circumvent this issue? I do not have root access on the remote server. Setting `export TERM=xterm` allows me to run the command as usual.

Does it mean I have to explicitly specify in my .bashrc the `TERM` value for those servers?

**Comment by kovidgoyal** [comment]
Read the FAQ https://sw.kovidgoyal.net/kitty/faq.html

**Comment by hanoii** [comment]
Read the FAQ, and also https://sw.kovidgoyal.net/kitty/conf.html?highlight=term#opt-kitty.term

> The value of the TERM environment variable to set. Changing this can break many terminal programs, only change it if you know what you are doing, not because you read some advice on Stack Overflow to change it.

Would you mind explaining slightly why would `XTERM=xterm` break? I work often with a containerized company that allows you to ssh to it but their container is read-only once it's built so I cannot copy .terminfo. I think I might be able to copy it to some of the writable paths and somehow make it read it from there, but I wonder what are the real implications of setting something like that.

Thanks and loving the terminal!

**Comment by kovidgoyal** [comment]
Basically, the TERM value controls how many programs interpret key strokes, output colors, and various other doodads. So depending on what programs you use and the incompatibilities between your chosed terminfo and kitty's terminfo you can experience breakage ranging from keystrokes being ignored/doing weird things/broken colors/ other random misbehavior. Or you could get lucky and be fine.

**Comment by pveentjer** [comment]
I checked the FAQ and it is pretty useless. Copying files to a remote to get ssh up and running is not a workable solution in many cases.

**Comment by thiderman** [comment]
@kovidgoyal What features do the `kitty-xterm` terminfo bring that cannot be fulfilled by the `xterm-256color` one? What terminal codes could be interpreted differently? And if there are any, why do `kitty` treat them differently?

Like the others, I'm in the situation where I cannot write anything to the machines I `ssh` to. To avoid having to specify a manual `TERM=xterm-256color` in scripts, I've been setting `TERM` to that in my shell, i.e. completely overriding the setting of `kitty-xterm`. And so far... nothing has changed.

As a whole, I don't understand the necessity of having `kitty-xterm`. Could you enlighten me please?

**Comment by kovidgoyal** [comment]
man infocmp

Use it to see the differences between terminfo databases. kitty is not
xterm, it is never going to be xterm. It does many things xterm does not
do and does not do many things xterm does.

**Comment by vdo** [comment]
Sorry @kovidgoyal  but I'm on the same page.

SSH is something we do too often to deal with this, is a no-go. I will try `xterm-256color` as mentioned above, and if it breaks too many things I will just change back to my compatible terminal.

**Comment by jnoortheen** [comment]
I use the fix mentioned here https://wiki.archlinux.org/index.php/Kitty#Terminal_issues_with_SSH

**Comment by nyurik** [comment]
@kovidgoyal I think the usability with this issue is still there, judging by the comments - reading FAQ sadly doesn't help/too confusing.  Ideal solutions:
* fully automatic -- users shouldn't be aware of the issue at all, and in the worst case automatic fallback into "just works" mode.
* less ideal but ok -- one magical command users should run `once`, i.e. some modification of their `/root/.bashrc` or remote `~/.bashrc`.

Please clarify how it could be done, and thank you for an absolutely awesome project!!!

**Comment by kovidgoyal** [comment]
On Wed, Dec 23, 2020 at 02:08:02PM -0800, Yuri Astrakhan wrote:
> * less ideal but ok -- one magical command users should run `once`, i.e. some modification of their `/root/.bashrc` or remote `~/.bashrc`.

This is mentioned in the FAQ, I dont see what is so confusing about it.

alias ssh="kitty +kitten ssh"

in your shell's rc files.

**Comment by arvindvjkumar** [comment]
> This is mentioned in the FAQ, I dont see what is so confusing about it. alias ssh="kitty +kitten ssh" in your shell's rc files.

I guess I can add my experience / issues with this here. TLDR, it seems like this issue is likely a blocker for me too.

My use case is using a python script that does some wrapper steps and calls ssh. I can't easily modify this python script. Without modifying the python script, the alias won't work (because it needs the `shell=True` option). 

Furthermore, even if I were able to change it, `kitty +kitten ssh` *doesn't work* with the same arguments created by the script (ie. a trailing `--` argument). (I did get it to call into the kitty ssh thing by creating a wrapper ssh script in `/usr/local/bin`)

I don't believe the infocmp command provided in the FAQ works either when using an empty trailing `--` argument (it hangs, no matter how I paired it down). FWIW, I might have missed something here since I don't understand it as well.

In-short, AFAIk the only option for me is to manually copy the file to each server and run TIC. Additionally, because we regularly cycle servers for dev environments, I need to copy a file every time I use a new staging cluster. The only option I see left is adding a keyboard shortcut to send a command to the terminal that writes the .terminfo files locally and runs tic. I'd then just need to run this command each time I ssh.

However, given the alternative of just using a terminal that uses xterm and not having to deal with any of this hackiness, it seems likely that I'll just do that.

**Comment by kovidgoyal** [comment]
Really?? You have a script you cant modify? So write another script that
copies the terminfo and then calls your immutable script, and use that. 

In any case, as I have explained before, if you want to perpetually
stagnate the terminal ecosystem by insisting every terminal be xterm
(the biggest boat anchor on the entire ecosystem), please just use
xterm. kitty is not for you.
