### ISSUE TITLE
Implement layout_action rotate for Grid layout

### ISSUE THREAD

**Issue by madblobfish** [kovidgoyal/kitty#7204]
**Is your feature request related to a problem? Please describe.**
Grid layout splits horizontally first. In cases with wide output it's causing line breaks and makes me "zoom in" on one of the two terminals.

**Describe the solution you'd like**
It would be nice to be able to rotate the grid layout by 90°. The first split would be vertical and use the full width.
For the `splits` layout there's already `layout_action rotate`, this could be implemented/reused for grid.

**Describe alternatives you've considered**
Using splits, but that would mean having to handle the subwindows manually.
Using my tiling window manager and OS windows, but that also means to handle the layouting manually and prevents using some kitty features (shortcuts, ...)

**Additional context**
I do not think this is required, but I can produce screenshots if it helps.

**Comment by kovidgoyal** [comment]
The first split is horizontal because terminal windows are typically
wide, so putting windows side by side makes sense.

I suggest you look into using an alternate layout like fat or vertical
if thats what you want.

As for changing the way grid lays out windows, not something I care
about, but patches welcome. You can add an option to the grid layout to
split vertically preferentially rather than horizontally. Relevant code
in grid.py
