### ISSUE TITLE
Kitten hints should ignore current shell prompt

### ISSUE THREAD

**Issue by Xadeck** [kovidgoyal/kitty#7224]
**Is your feature request related to a problem? Please describe.**

I'm using Fish + Tide. 
* prompt shows current directory path
* when you start typing a command, let's say "more -e", Fish proposes a potential completion from history, shown as a grayed text. 
* 
This doesn't play well with hints. Here is a simple scenario shown with screenshots:

![Screenshot from 2024-03-14 09-18-19](https://github.com/kovidgoyal/kitty/assets/475285/dffcfa71-80e2-4b60-ba95-ac58dd9e1908)
![Screenshot from 2024-03-14 09-18-46](https://github.com/kovidgoyal/kitty/assets/475285/d7d97945-4559-40ce-a071-402c70864671)

**Describe the solution you'd like**

There would be an option for Kitty hints to ignore the shell prompt. Naively, the shell integration seems to provide all the information so it feels like this shouldn't be too hard to achieve (but I haven't looked into it)!

**Describe alternatives you've considered**

I can't think of anything to workaround, apart from [completely customizing](https://sw.kovidgoyal.net/kitty/kittens/hints/#completely-customizing-the-matching-and-actions-of-the-kitten) the matching, but that seems like duplicating existing logic, and I will anyway have to come up with a broken heuristic to filter out the prompt (for the current prompt, that's probably easy: just ignore last 2 lines).

**Comment by kovidgoyal** [comment]
Not worth it as far as I am concerned. All it means is that there are a
couple of extra matches found, which doesnt materially affect using the hints
kitten. If it bothers you a simple solution would be to use a prompt
style that replaces / as the path separator. For instance my personal
prompt style uses powerline segments, or you could use U+2215 (∕) instead of
/. 

Note that your proposed fix of using shell integration doesnt really
work, as shell integration tell you only while lines contain prompts not
where in the line is part of the prompt and where it is the command you
are typing.

**Comment by Xadeck** [comment]
The trick with a / like character in the prompt is a good idea. That should get rid of hints 5 and 2 in the screenshot. 

I would still like to get rid of 1, because it is *never* the one I want (otherwise I would not trigger the kitten, I would just accept fish suggestion). If I could ignore that line entirely, I would be happy (yes, it means I could not get path already on that line, that's fine in my case).

I understand it's not worth the effort for you, thanks for having considered the FR and thanks again for the work on Kitty!
