### ISSUE TITLE
Direct Unicode input

### ISSUE THREAD

**Issue by mdSlash** [kovidgoyal/kitty#7269]
**Is your feature request related to a problem? Please describe.**
I'm using different apps to control my keyboard layers, and I have non-English Unicode characters in my keyboard layers. I insert them using their Unicode. When I insert a non-English character by its Unicode, Kitty directly leaves the current window and turns me into its Unicode UI window. It inserts the character correctly and then returns me to the same window I was working on. The problem I am encountering is that I don't need that UI window to show, as I mentioned in the discussion #7223.

![ezgif-3-294989ac6b](https://github.com/kovidgoyal/kitty/assets/128622475/a2f6a40a-a575-4b85-9658-e9ae0b8d4922)

**Describe the solution you'd like**
Adding a config option that disables Kitty's Unicode UI, enabling users to insert Unicode directly by `code`, `name`, or `favorite` without leaving the current window.

**Comment by kovidgoyal** [comment]
Then get your input layer to not send ctrl+shift+u and only send the
actual unicode character.

**Comment by mdSlash** [comment]
> Then get your input layer to not send ctrl+shift+u and only send the actual unicode character.

You closed that issue quickly, and the app I use doesn't support inserting Unicode directly. My problem is still ongoing. Thanks for your help. I will find a solution eventually.

**Comment by kovidgoyal** [comment]
I'm afraid I have no idea what your issue is. Either your app sends
ctrl+shift+u to kitty in which case you use the kitty unicode picker. Or
get your app to do whatever it wants to do when you press ctrl+shift+u
and send the *resulting unicode* as a key event to kitty. If your app is
not capable of doing that, I suggest finding a better one. Typical
candidates are: XCompose, IME via obus or fcitx or similar.

**Comment by jrozhon** [comment]
Hi, just to add a very niche point of view. I have my qmk keyboard set to send ctrl+shift+u and the code which works fine in every application i have used so far, but kitty opens a menu to select the code instead of just accepting it. It would be nice to have an option to disable unicode input in kitty. I have tried to fiddle with mapping, but with no luck.

**Comment by Straffern** [comment]
Yeah, I have the same issue using a Glove 80, with this mapping:
https://github.com/sunaku/glove80-keymaps
It enables me to use en-us as default, but quickly input danish characters, for a few words.
When working in Neovim this unicode input causes trouble.
I can't create a filename with a danish character (work related). When I hit enter, it also sends 'enter' to the neovim window, creating the filename, without the character.

**Comment by Lege19** [comment]
I also have the same issue. Getting keyboards to input unicode directly isn't possible without getting your hands extremely dirty in XKB settings. There are only so many scancodes you can use, and your primary language uses all the usual ones. So no, I'm not getting better software because the limitation is the USB protocol.

**Comment by Lege19** [comment]
I'd also like to point out that you could just add behavior that pressing space in codepoint mode is the same as enter.

**Comment by Lege19** [comment]
You rebind ctrl+shift+u to this kitten to get most of the way to solving the issue. If it were possible to get character by character user input without having a UI, then I'd call this a completely satisfactory solution:
```python
from kitty.boss import Boss
import termios
import sys

def main(args: list[str]) -> str | None:
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    new = termios.tcgetattr(fd)
    new[3] = new[3] & ~termios.ICANON
    try:
        termios.tcsetattr(fd, termios.TCSADRAIN, new)
        inp = sys.stdin.read(4)
        sys.stdin.read(1) # space
        return chr(int(inp, 16))
    except:
        pass
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)

def handle_result(args: list[str], answer: str, target_window_id: int, boss: Boss) -> None:
    # get the kitty window into which to paste answer
    w = boss.window_id_map.get(target_window_id)
    if w is not None:
        w.paste_text(answer)
```
