### ISSUE TITLE
Inactive (non-OS) window styling

### ISSUE THREAD

**Issue by happenslol** [kovidgoyal/kitty#7301]
**Is your feature request related to a problem? Please describe.**
I'm a heavy user of windows (non-OS windows) and the splits-layout. When only 2 windows are open, it's hard to see which one is active, so I'm using the `inactive_text_alpha` option to make it more obvious which window is currently focused.

The problem is that `inactive_text_alpha` will apply to *all* windows if the os window itself is not focused. This makes it impossible to see which window is focused while I have my browser focused, for example.

Additionally, while `inactive_text_alpha` works to some extent, I've recently switched back to kitty from wezterm, and the only thing I really miss is the [option to set the hue/saturation/brightness for inactive panes](https://wezfurlong.org/wezterm/config/appearance.html#styling-inactive-panes). This really makes focus visually clear and doesn't rely on setting the background (which could fail, as pointed out in #1775, for example).

**Describe the solution you'd like**
1. It would be great if there was a separate option that would let me control whether `inactive_text_alpha`, or any inactive styling for that matter, applies when the os window is unfocused, or only when the windows inside kitty is unfocused. Alternatively, having 2 separate options for this would work just as well (i.e. `os_window_inactive_text_alpha` and `inactive_text_alpha`)
2. Being able to adjust hue/saturation/brightness for inactive windows would be a nice-to-have.

**Describe alternatives you've considered**
The only possible solution I could come up with was to remote-control kitty and set the `inactive_text_alpha` option to `1.0` whenever the os window is unfocused, and back to my own value whenever it is focused. This seems a little too hacky for my taste though.

**Additional context**
I'm aware that what I'm asking for is largely based on personal preference, so I'd be open to implement this myself.

**Comment by kovidgoyal** [comment]
On Wed, Apr 03, 2024 at 05:33:49AM -0700, Hilmar Wiegand wrote:
> **Is your feature request related to a problem? Please describe.**
> I'm a heavy user of windows (non-OS windows) and the splits-layout. When only 2 windows are open, it's hard to see which one is active, so I'm using the `inactive_text_alpha` option to make it more obvious which window is currently focused.
>
> The problem is that `inactive_text_alpha` will apply to *all* windows if the os window itself is not focused. This makes it impossible to see which window is focused while I have my browser focused, for example.
>
> Additionally, while `inactive_text_alpha` works to some extent, I've recently switched back to kitty from wezterm, and the only thing I really miss is the [option to set the hue/saturation/brightness for inactive panes](https://wezfurlong.org/wezterm/config/appearance.html#styling-inactive-panes). This really makes focus visually clear and doesn't rely on setting the background (which could fail, as pointed out in #1775, for example).

Inactive text alpha does not work by changing background colors, it
doesnt change colors at all. It causes the text to be rendered with
lower opacity visually giving the text in the window a faded effect
by blending with whatever the background color is.

>
> **Describe the solution you'd like**
> 1. It would be great if there was a separate option that would let me control whether `inactive_text_alpha`, or any inactive styling for that matter, applies when the os window is unfocused, or only when the windows inside kitty is unfocused. Alternatively, having 2 separate options for this would work just as well (i.e. `os_window_inactive_text_alpha` and `inactive_text_alpha`)

I'm fine with a PR for this, in fact I dont think an option is needed at
all. The behavior should be
1) When there is a single visible kitty window:
   always apply styling
2) Otherwise apply styling to all but the active window in the inactive
os window.

If somebody complains about this behavior change an option can be added.

> 2. Being able to adjust hue/saturation/brightness for inactive windows would be a nice-to-have.

That's a pretty large performance cost. Every pixel would need to
re-calculated. While this probably wont cause any actual performance
impact it will cost more energy and since it has to be done on the GPU,
you cant even make it conditional (branches are expensive on GPUs), so everyone
would have to pay that cost regardless of whether they used the feature
or not.

So not a fan, unless it can be implemented without cost for the default
path.

>
> **Describe alternatives you've considered**
> The only possible solution I could come up with was to remote-control kitty and set the `inactive_text_alpha` option to `1.0` whenever the os window is unfocused, and back to my own value whenever it is focused. This seems a little too hacky for my taste though.

You can actually trivially implement this for yourself using the kitty watchers
feature. Setup a watcher in kitty.conf and react to on_focus_change. You
can check the os window focus state and adjust the opacity accordingly.
Of course this is a hack.

Closing feel free to follow up in a PR or ask for more clarification if
you need it.

**Comment by happenslol** [comment]
> I'm fine with a PR for this, in fact I dont think an option is needed at
> all. The behavior should be
> 1) When there is a single visible kitty window:
>    always apply styling
> 2) Otherwise apply styling to all but the active window in the inactive
> os window.

Thanks for your quick response.

Not 100% sure what you mean by this. Let's say I have `inactive_text_alpha = 0.5`. I see the following cases:
1. I have a kitty os window open, and inside of that a single window. The os window is not focused. Will the text alpha be 0.5 or 1.0 with what you are proposing?
2. I have a kitty os window, and inside of that 3 different windows. The os windows is not focused. From what I understand you're proposing that the 2 non-focused windows would be 0.5, but the focused one would be 1.0, even if the os window is not focused.

I basically never want `inactive_text_alpha` to apply because of the focus state of the os window - only because of the focus state of kitty internal windows.

**Comment by happenslol** [comment]
I understand. An option would then be needed for my usecase since. I'll first make a PR to accomplish (2), and then I can see about an option to never set text alpha on os window unfocus. Thank you!
