### ISSUE TITLE
scrollback pager showing shell integration characters with multi-line prompt

### ISSUE THREAD

**Issue by Tronchenbiais** [kovidgoyal/kitty#7306]
**Describe the bug**
When `PS1` spans several lines, showing the scrollback with the default program shows `;k=s` strings before the last line of the prompt. The same string is shown before `PS2` with continued  commands.

**To Reproduce**
1. Set `PS1` to `a\nb\nc`
2. Type commands
3. press `Ctrl+Shift+h` to show the scrollback buffer

**Screenshots**
shell output:
![shell](https://github.com/kovidgoyal/kitty/assets/9694516/4a6ad4ab-c74c-4c4c-9e72-e42384487ebd)

pager output:
![pager](https://github.com/kovidgoyal/kitty/assets/9694516/7f64081d-ea4c-4fbf-aecd-78e31448fcd6)

**Environment details**
```
kitty 0.32.2 created by Kovid Goyal
Linux tronchy-desktop 6.7.9-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.7.9-2 (2024-03-13) x86_64
Debian GNU/Linux trixie/sid tronchy-desktop /dev/tty

Running under: X11
Frozen: False
Paths:
  kitty: /usr/bin/kitty
  base dir: /usr/lib/kitty
  extensions dir: /usr/lib/kitty/kitty
  system shell: /bin/bash

Config options different from defaults:

Important environment variables seen by the kitty process:
	PATH                                /home/tronchy/.local/bin:/home/tronchy/software/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
	LANG                                en_US.UTF-8
	EDITOR                              nvim
	SHELL                               /bin/bash
	DISPLAY                             :0
	USER                                tronchy
	XDG_SEAT                            seat0
	XDG_SESSION_TYPE                    x11
	XDG_SEAT_PATH                       /org/freedesktop/DisplayManager/Seat0
	XDG_SESSION_CLASS                   user
	XDG_SESSION_ID                      158
	XDG_SESSION_PATH                    /org/freedesktop/DisplayManager/Session2
	XDG_RUNTIME_DIR                     /run/user/1000
	XDG_SESSION_DESKTOP                 lightdm-xsession
	XDG_GREETER_DATA_DIR                /var/lib/lightdm/data/tronchy
	XDG_VTNR                            7
```

**Additional context**

This was reproduced with no `.bashrc`, `.inputrc` or `kitty.conf`. I was also able to reproduce after upgrading to kitty v0.33.1

This may be `less` incorrectly escaping sequences.

```
>less -V
less 590 (GNU regular expressions)
Copyright (C) 1984-2021  Mark Nudelman

less comes with NO WARRANTY, to the extent permitted by law.
For information about the terms of redistribution,
see the file named README in the less distribution.
Home page: https://greenwoodsoftware.com/less
```

A related issue is that when using a multiline prompt, or when targeting continued commands, `Ctrl+Shift+RightClick` shows prompt lines in the pager (I can file a separate issue for this)

**Comment by Tronchenbiais** [comment]
I can currently work around this issue by setting:

```
scrollback_pager $SHELL -c "sed -e 's/;k=s//' /dev/stdin | less <options>"
```

in `kitty.conf`

**Comment by kovidgoyal** [comment]
Do not use newlines in bash prompts instead use \n the backslash and the
n character and you will be fine. Because of bash limitations shell
integration wont work with a multiline prompt unless the newlines are
encoded as \n not actual newline characters. Or use another shell that
does not have these limitations.

**Comment by Tronchenbiais** [comment]
I do use `\n` in my `PS1` setting, as shown in the "Steps to reproduce" and "Screenshot" section of the issue report. I have tried replacing that with `\\n` so that the new line is interpreted when the prompt is actually drawn, but I still see the issue. I think I'm missunderstanding your reply.

Shell integration does work for me (`Ctrl+Shift+G` shows what it should for example), but I keep getting spurious characters when I bring the scrollback buffer in `less`.

**Comment by kovidgoyal** [comment]
Ah yes, this is indeed a bug in less, report it there, it is failing to parse an escape code of the form: 

```
<ESC>]133;A;k=s<ESC>\
```

which is a perfectly valid OSC escape code that less should discard if it doesnt understand. Instead of writing a proper escape code parser it has apparently special cased 

```
<ESC>]133;A<ESC>\
```

which is why it doesnt show an issue with single like prompt. The former form appears only on lines after the first line of a prompt.

It's on my TODO list to write a replacement for less, when I get to that this will be automatically fixed. Or maybe I will detect when less is being used as a pager and sanitize these, though I am reluctant to do that as it means scanning the entire pager text before passing it on, which is a performance hit
