### ISSUE TITLE
When only r or c is specified, the behavior is still strange

### ISSUE THREAD

**Issue by sergei-grechanik** [kovidgoyal/kitty#7479]
This is related to https://github.com/kovidgoyal/kitty/issues/7380 and https://github.com/kovidgoyal/kitty/discussions/6979
Right now the aspect ratio of the image is preserved, but the missing dimension size in cells is not computed to fit the image. For example, using the mars image from #7380:
![image](https://github.com/kovidgoyal/kitty/assets/1084979/cdd7772f-9f51-49e6-ade6-d8536128aab0)

This is worse when the image is scaled up. When running the script from https://github.com/kovidgoyal/kitty/discussions/6979:
![image](https://github.com/kovidgoyal/kitty/assets/1084979/28718654-84e5-4f20-a8af-74165c4beabc)

I'm assuming this is not the intended behavior.

**Comment by kovidgoyal** [comment]
I dont understand. If you specify only c=50 then the image is displayed in the appropriate number of rows so that it takes 50 columns but preserves its aspect ratio. See screenshot. If the number of rows were computed ignoring the value of c, then the aspect ratio would not be preserved.  What are you expecting to happen?
![screenshot](https://github.com/kovidgoyal/kitty/assets/1308621/7ab4a326-d0b5-4591-8143-19060ab98813)
