### ISSUE TITLE
Naive image slicing is broken

### ISSUE THREAD

**Issue by sergei-grechanik** [kovidgoyal/kitty#7498]
It's another issue related to the change in scaling logic https://github.com/kovidgoyal/kitty/issues/7380
To reproduce cat this file: [naive-slicing.txt](https://github.com/user-attachments/files/15520149/naive-slicing.txt).
This file uploads an image and then displays it as 8 horizontal slices. Each slice has a height of 40 pixels and fits into 2 rows, with the number of columns calculated automatically:
```
^[_Ga=t,i=1,t=d,q=1,m=1,f=100;...^[\                                                
^[_Ga=p,i=1,q=1,r=2,y=0,h=40^[\                                                  
^[_Ga=p,i=1,q=1,r=2,y=40,h=40^[\                                                 
^[_Ga=p,i=1,q=1,r=2,y=80,h=40^[\                                                 
^[_Ga=p,i=1,q=1,r=2,y=120,h=40^[\                                                
^[_Ga=p,i=1,q=1,r=2,y=160,h=40^[\                                                
^[_Ga=p,i=1,q=1,r=2,y=200,h=40^[\                                                
^[_Ga=p,i=1,q=1,r=2,y=240,h=40^[\                                                
^[_Ga=p,i=1,q=1,r=2,y=280,h=40^[\ 
```
Currently this produces the following result:
![image](https://github.com/kovidgoyal/kitty/assets/1084979/038253fd-0553-409e-8ad1-20b5af4f39a3)
The problem is that the last slice is truncated because the total height of the image (314) is not divisible by 40. When the slice is stretched to fit 2 rows while preserving the aspect ratio, it results in a greater width comparing to the other slices.

This behavior is confusing, but I'm not sure if it should be fixed, I don't think this slicing technique is very common. I've seen something like this in hologram.nvim, but I didn't check if it's broken now.

**Comment by kovidgoyal** [comment]
I don't see the issue. As long as the semantics are clear and
consistent, that's what we need. The semantics of specifying only one of
r or c are quite clear in the spec. The implementation of the spec in
kitty had a bug, now fixed. I don't think the graphics protocol is
widespread enough that we need to maintain implementation bugs forever.

Preserving aspect ratio is the "intuitive" thing to do and as such I
believe it is best we keep that behavior. If hologram or some other
client implementation breaks because of this, I am more than happy to
help them fix the breakage. Worst case we can even add a new key that
specifies aspect ratio preserving behavior. Though personally I dont
think that's necessary.
