### ISSUE TITLE
Kitty shows a desktop notification every time a directory is entered

### ISSUE THREAD

**Issue by Schweber** [kovidgoyal/kitty#7518]
**Describe the bug**
nushell just released version 0.94.1 with the option to enable osc9_9. If i do that, kitty shows a desktop notification every time a directory is entered, so on startup of kitty and every time a command completes or the directory is changed. The notification is prefixed by `9;` and then prints the path to the directory.

Is this intentional or is there a misconfiguration in either `kitty` or `nushell`? I see no option to turn this off in either nushell or kitty.

**To Reproduce**
1. set `shell_integration: { osc9_9: true }` in config.nu
2. open nushell in kitty and change directories
3. See desktop notifications each time the directory is changed

**Screenshots**
![image](https://github.com/kovidgoyal/kitty/assets/64630479/b6d28d75-11f5-41e6-aa6c-3f1f29fb80d6)

**Environment details**
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead

Both not working.

**Additional context**
The problem is unchanged with `kitty --config NONE`.

I noticed that the kitty documentation about [Desktop notifications](https://sw.kovidgoyal.net/kitty/desktop-notifications/) is empty.

**Comment by kovidgoyal** [comment]
kitty shows a desktop notification only when the program running inside
it asks it too. So ask the nushell developers about it.

**Comment by devyn** [comment]
I think this might be a difference between how kitty and Windows Terminal treat OSC 9. Maybe kitty is using it for desktop notifications?

OSC 9;9 on Windows Terminal is used to set the current directory for the 'Duplicate Tab' function, and that's why we have it on by default, but it is configurable and users can turn it off if it causes a problem.

Maybe kitty should look for OSC 9 starting with `9;` and either ignore it, or use that to also set the current dir.

**Comment by kovidgoyal** [comment]
OSC 9 is not a kitty specific thing. kitty supports it because it is
somewhat widely used and was first pioneered by iTerm over a decade ago.
I dont know why Windows Terminal decided to stomp all over an existing
widely used and supported escape code but they should fix that.
Reference: https://iterm2.com/documentation-escape-codes.html kitty does
have a much more comprehensive and better designed escape code for
desktop notification, OSC 99:
https://sw.kovidgoyal.net/kitty/desktop-notifications/ but that's
irrelevant to this issue.

Reporting of working directories is done via OSC 7 not OSC 9. OSC 7 is
supported by all modern terminals, off the top of my head, kitty,
wezterm, gnome-terminal, iTerm, even Apple's extremely obsolete
Terminal.app supports it. Again for over a decade.

The correct thing to do here is for nushell to switch to using OSC 7 for
cwd notification and for windows terminal to do the same.

If for some reason windows terminal wants a new escape code for
reporting cwd, then they need to pick one that is not already used.

**Comment by kovidgoyal** [comment]
They aren't using osc99, they are using osc9 which is an escape code
meant for desktop notifications, first implemented by iTerm, a decade
ago, to implement reporting of cwd. Reporting of cwd is a completely different thing than desktop notifications.
OSC 9 is not meant for reporting of CWD.

They need to switch to using OSC 7. I explained all this in detail in my
previous post. If they want to dismiss the explanation as "different
terminal emulators behaving differently" when there is *one* terminal
emulator that implements OSC 9 incorrectly and out of all the rest they
chose to follow that one (Windows Terminal) that's their loss.

**Comment by devyn** [comment]
This is OSC 9;9 not 99 and it's there for support for Windows Terminal. These are configurable and this one isn't on by default. We provide those options with the understanding that they may not be compatible with all terminals.

I was just suggesting that kitty might decide to either support or ignore that for compatibility with applications that decide to use that, but it's definitely not necessary. If a user decides to turn this on and it behaves differently than it was intended to, that's on them.

Thanks
