### ISSUE TITLE
Processes launched through kitty do not inherit session ID

### ISSUE THREAD

**Issue by woaisthisgit** [kovidgoyal/kitty#7579]
I'm new to linux so sorry if I don't make a lot of sense here.

If I launch any application from the command line, and then run "loginctl session-status 1", the new process doesn't show up. If I repeat this with a different terminal emulator (in my case xterm) then I can see the new process.

This causes an issue when trying to run xss-lock from the terminal - I get a warning that the current PID does not belong to any known session, and when I activate the lock, xss-lock crashes.

The issue persists with the --config NONE option enabled.

I'm not sure what the underlying issue is but I can supply more information if needed!

**Comment by kovidgoyal** [comment]
This will be because kitty will run the shell in a new systemd scope.
Which it does so that systemd's stupid OOM killer doesn't kill the full
terminal if a program running in it uses a lot of RAM. Modern terminals
do the same thing, for example gnome-terminal. xterm doesnt. See #7427
for reference.

You can easily test this for yourself by commenting out the if block
starting at line 346 in child.py

You should anyway be running xss-lock in your desktop startup scripts
not from inside a terminal, as per its man page, and if you do want to
run it from the terminal, use -s 1 to get it to connect to the correct
session.

**Comment by woaisthisgit** [comment]
I see, maybe I should've tested in more than one alternate terminal 😅 Thank you!
