### ISSUE TITLE
A builtin menu action

### ISSUE THREAD

**Issue by roylez** [kovidgoyal/kitty#7649]
**Is your feature request related to a problem? Please describe.**

There are always some shortcuts that I do not use frequently enough to develop muscle memory, and my usual strategy for them is a menu or palette to group them together, so that there are fewer shortcuts to remember. I could do this in tmux or wezterm using built-in functionality, but kitty does not have this built-in. Yes, I could do the same thing with external tools, such as Keyboard Maestro or fzf, but it would be nicer if it is built-in.

**Describe the solution you'd like**

An action that brings up an overlay window containing a list of predefined actions.

**Additional context**

Screenshot of tmux menu
![screenshot 2024 07 20 0913](https://github.com/user-attachments/assets/9189f64d-b7cf-41d0-b107-6c9e7cb5661b)

Screenshot of wezterm menu
![screenshot 2024 07 20 0917](https://github.com/user-attachments/assets/ec545f3a-d600-437d-a360-f1ce4150bd9a)

**Comment by kovidgoyal** [comment]
You can trivially create one yourself in about 5 lines of bash script.
kitty provides you all the tools to do so. I will outline it for you:

```sh
cmd=$(echo "new_window\nnew_os_window\nnew_tab\n...." | fzf)
kitten @ action "$cmd"
```

chmod +x script

Then in kitty.conf
```
map f1 launch --allow-remote-control --type=overlay /path/to/the/script/from/above
```

You can make it more fancy by using command names and description in
your selector script. Or using whatever tool you like instead of fzf
to pick a selection. The list of all actions is at
https://sw.kovidgoyal.net/kitty/actions/

Choose the ones you want in your script.
You can actually be much more fancy and make up your own aliases for
complex sequences of actions or remote control commands. Way more
powerful and personalizable than a command palette.
