### ISSUE TITLE
Kitten theme 

### ISSUE THREAD

**Issue by alg4321** [kovidgoyal/kitty#7726]
**Describe the bug**
Having to reinstall kitten theme tool every time you close kitty.

**To Reproduce**
1. Install kitten theme
2. Change theme.  Choose Modify 
3. Close kitty
4. Type: kitten themes,  but it will not be installed anymore.

General problem:  Needing to reinstall kitten themes every instance of kitty.

**Comment by kovidgoyal** [comment]
I dont follow. What does "installed" mean? When you modify the theme the
colors of either the current terminal instance or all terminal instances
are changed, as expected, depending on hat option you chose. When you
rerun kitten themes it will show you all themes again, regardless of
what the current theme is, that is by design. What would be the point of
showing you the current theme when the kitten is meant for *changing*
themes.

And in the future please follow the issue template when reporting
issues.

**Comment by alg4321** [comment]
You don't follow? I did try to be clear.  "When you rerun kitten themes it
will show you all themes again,"  but it doesn't.  I had to make a curl
request to reinstall kitty using your shell script each time I wanted to
use kitten themes, trying to dial in my shell look, because, it's fun of
course.. Maybe the pic will be easier to track and more clear for you.
That was my first ticket, so I will follow the template in the future.
Kovid Goyal ***@***.***>
3:02 AM (11 hours ago)


to kovidgoyal/kitty, me, Author

**Comment by kovidgoyal** [comment]
In that case I have absolutely no clue what you are talking about. kitten is an actual executable file that comes as part of kitty. You dont need to install it. Just run it, it will already be there.

**Comment by alg4321** [comment]
I purged it, reinstalled it, and found the binaries in .local/kitty.app/bin/.
I ran them and they worked as expected from there.  I guess it's a
filesystem issue for me to solve. Idk the local where they go yet, but I
will figure it out.  I hope you forgive my fuss.  The problem could have
been my machines making directories, that the script was designed to put
files in, not remake??  Anyways thanks for your time and feedback.
