### ISSUE TITLE
Multi-chunk direct uploading doesn't work for animations

### ISSUE THREAD

**Issue by sergei-grechanik** [kovidgoyal/kitty#7742]
It looks like multi-chunk direct uploading of animation frames doesn't work (the animation is not looping).
This file uploads each frame in one command (cat it to run), the animation runs correctly:  
[animation-bird-onechunk.txt](https://github.com/user-attachments/files/16653303/animation-bird-onechunk.txt)
The commands look like this:
```
_Gq=2,a=T,f=100,U=1,i=110430338,c=59,r=17,t=d;<data>
_Ga=a,v=1,s=2,r=1,z=100,i=110430338
_Gq=2,a=f,f=100,i=110430338,z=100,t=d;<data>
_Gq=2,a=f,f=100,i=110430338,z=100,t=d;<data>
_Gq=2,a=f,f=100,i=110430338,z=100,t=d;<data>
_Ga=a,v=1,s=3,i=110430338
```

This files uploads them in several chunks using `m=1`/`m=0`, the image appears static: 
[animation-bird-multichunk.txt](https://github.com/user-attachments/files/16653306/animation-bird-multichunk.txt)
The commands look like this:
```
_Gq=2,a=T,f=100,U=1,i=2549395370,c=59,r=17,t=d,m=1
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=0
_Ga=a,v=1,s=2,r=1,z=100,i=2549395370
_Gq=2,a=f,f=100,i=2549395370,z=100,t=d,m=1
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=0
_Gq=2,a=f,f=100,i=2549395370,z=100,t=d,m=1
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=0
_Gq=2,a=f,f=100,i=2549395370,z=100,t=d,m=1
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=1;<data>
_Gi=2549395370,m=0
_Ga=a,v=1,s=3,i=2549395370
```

**Comment by kovidgoyal** [comment]
I dont see how that's possible, if it were the case no animated images would work over SSH, for example. And they definitely do. For example, the following works fine for me:

```sh
kitten icat --transfer-mode=stream --unicode-placeholders some-animation.gif
```

Not sure what's going on with your example, but if I had to guess, it would be that you should send the placeholder chars after transmitting the first frame data rather than after transmitting all frames. Otherwise, the actual image is not created when the animation is started. As an energy saving measure kitty stops scanning for animations if no actual animated images are present on screen. I dont think that scan is restarted when placeholder characters are found. Maybe it should be, not sure.

**Comment by sergei-grechanik** [comment]
Classic placements exhibit the same behavior: 
[animation-bird-multichunk-classic-placement.txt](https://github.com/user-attachments/files/16662298/animation-bird-multichunk-classic-placement.txt)

Actually I think I found the issue: the `a=f` is missing from subsequent chunks, so this works: 
[animation-bird-multichunk-classic-placement-explicit-action.txt](https://github.com/user-attachments/files/16662339/animation-bird-multichunk-classic-placement-explicit-action.txt)

I thought they were optional, but apparenty they are explicitly not optional for animations:
> When sending animation frame data, subsequent chunks must also specify the a=f key.

So it's not a bug.
