### ISSUE TITLE
Partial (buttons, not scrolling) mouse tracking mode

### ISSUE THREAD

**Issue by pianohacker** [kovidgoyal/kitty#7747]
**Is your feature request related to a problem? Please describe.**
I recently tried out [Stephane Chazelas' zsh mouse addon](https://github.com/stephane-chazelas/misc-scripts/blob/master/mouse.zsh) and immediately ran into a problem. While the script is very useful for moving around in a command line by clicking, it also breaks scrollback. Looking at [kitty's mouse code](https://github.com/kovidgoyal/kitty/blob/master/kitty/mouse.c), it seems like there is no mouse mode that can get click events but allow scroll events to be handled normally.

**Describe the solution you'd like**
A new mouse mode that forwards normal (left/middle/right) buttons as escape sequences, but scrolls through the scrollback for wheel events.

**Describe alternatives you've considered**
I've looked through the existing mouse modes, and [this line of code](https://github.com/kovidgoyal/kitty/blob/master/kitty/mouse.c#L949) seems to imply that if _any_ mouse mode is in use, scroll events will be intercepted.

I also tried to have the mouse event handler emulate scrollback using SU / SD (`CSI S` / `CSI + T`), but that's a pretty poor replacement.

**Additional context**
I'd be happy to take a crack at implementing this, given some guidance on what protocol is desired. i.e., should the new escape sequence allow arbitrary selection of buttons to forward/handle normally, what should the escape sequence be, etc.

My suggestion would be `CSI ? 1007 h`.

**Comment by kovidgoyal** [comment]
Clicking to move around the command line works out of the box
in zsh with kitty shell integration. It's not 100% robust, see below,
but works in most cases. As does middle click to paste and select to copy.

https://sw.kovidgoyal.net/kitty/shell-integration/

If you really want to implement a new protocol there is no need for a
new mouse mode. Simply add a field to the prompt marking protocol to
indicate that the shell supports click events. Then instead of sending
fake arrow key presses to move the cursor (which is not fully robust)
the terminal can send a click event instead, when it detects that the
cursor is at the current prompt line and the current prompt is marked to
support click events. The shell can handle the click however it likes,
including moving the cursor, or selecting a completion or whatever.

**Comment by kovidgoyal** [comment]
no followup

**Comment by pianohacker** [comment]
Apologies for the slow response.

Thanks for the link to that part of the shell integration docs, didn't realize this was supposed to be part of that! It's broken in my zsh and I'm not quite sure why.

When you mention the prompt-marking protocol, are you referring to [this](https://sw.kovidgoyal.net/kitty/shell-integration/#notes-for-shell-developers)? And the new field would be alongside `redraw`, `special_key`, and `k`? I think that makes sense. I'll see about tackling a PR.

**Comment by pianohacker** [comment]
https://github.com/kovidgoyal/kitty/pull/7828 submitted.

I didn't update the shell integration code. If [the relevant code in `mouse.zsh`](https://github.com/stephane-chazelas/misc-scripts/blob/master/mouse.zsh#L354-L486) is anything to go by, this is somewhat complicated. I have an SGR mouse event parser implemented for ZSH, but this and the click-event-to-prompt-position code need to be implemented for each shell.

Thoughts?

**Comment by kovidgoyal** [comment]
I suggest leaving the implementation of click event support to the
shells rather than trying to load it in the shell integration script.
I want the shell integration scripts to be minimal/fast.

Instead, have the click event support set some kind of global flag. The
shell integration script can check for that flag to determine if the
shell supports click events and if it does, it can send click_events=1
accordingly. That way, users that want this can turn it on in their
shell rc files by loading the click integration code and kitty's shell
integration will then automatically detect it. In the future if zsh ever
gains native support for click events, then it can be supported
seamlessly using the same mechanism.
