### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by net** [kovidgoyal/kitty#778]
Any chance you could cut a new release?

Thanks 🙂

**Comment by kovidgoyal** [comment]
Sadly I am a little swamped right now  (some stuff in my personal life). And because of the the changes in #469 I anticipate that things might well break for a number of people with the next release (see for example #742), so I dont want to make it while I dont have the bandwidth to deal with the issues. Hopefully things will settle down in a month or so.

**Comment by net** [comment]
Understood. Thank you for all you’ve done!
