### ISSUE TITLE
Remote control command behavior

### ISSUE THREAD

**Issue by net** [kovidgoyal/kitty#786]
We've run into a couple possible bugs integrating kitty and kakoune in mawww/kakoune#2266:

> Kitty starts application on @ new-window before the window size is available, resulting to the TIOCGWINSZ ioctl returning a 0,0 size. Additionally, when run from Kakoune, kitty @ new-window hangs, seemingly waiting on read syscall for an answer from the server, after the new window has been opened.

—@mawww

The behavior with the read syscall also seems to occur with the new kitty @ kitten remote command.

**Comment by kovidgoyal** [comment]
1) I dont see how that's a bug. In general it is not possible to know the window size until the window has been placed. As long as the SIGWNCH signal is delivered to the child when the window is placed, there is no bug. All kakoune needs to do is assume a default size and when it receives SIGWNCH redraw. Or it can wait for SIGWNCH on startup if it wants to avoid the redraw. If kitty held off launching children till the window size is available that would just mean a performance regression for the vast majority of programs that do not need a window size at startup.

2) Yes, new-window waits for a reply from kitty as it prints out the id of the newly created window. Why is that a problem? kakoune should not read/write to stdout/stdin until the kitty @ process has exit. As long as it does that, it will be fine. Or alternatively, if for some reason it does not want to do that, use the --listen-on and --to arguments to create a dedicated socket for remote control.

**Comment by kovidgoyal** [comment]
With regards to (1). In general a new window could startup hidden in which case it would not have a size at all, until the user decides to show it. What I can do, is give the window a default size in kitty itself which will change when the window is placed.

**Comment by kovidgoyal** [comment]
Well, i decided to implement the wait-for-sigwinch logic in kitty itself before execing the child process. The delay is minimal, so it is worth it.

**Comment by mawww** [comment]
Hello, regarding 2., `kitty @ new-window` is hanging on read on fd 3, and nothing is happening, even though the new window has opened. I am not sure why this behaviour is triggered when run from Kakoune instead of when run from the shell.

Which stdin/stdout should'nt Kakoune write to ? Its own tty stdin/stdout ? Do you mean kitty remote control protocol goes through terminal escape sequences and hence requires the client to have exclusive access to the tty when sending a request ? I guess that would explain the behaviour because Kakoune does read/write to the tty while it runs background shell commands (it stills parses input keys, as some will trigger immediate reactions, such a `<c-c>`, and sometime redraws to indicate we are waiting on a shell process).

Would'nt it be more robust for Kitty to have a separate channel for those remote calls (such as a unix socket), I dont know of any way to lock an fd to be the only process able to read/write from it, but maybe linux provides something to do that ?

**Comment by kovidgoyal** [comment]
Yes, it uses terminal escape codes, they have the advantage of working out-of-thebox, even across ssh.

And as I said, if that is not workable for kakoune, you can use the --listen-on and --to options to setup a dedicated socket for kitty remote control. See kitty --help and kitty @ --help

**Comment by kovidgoyal** [comment]
And let me re-iterate, the best thing to do is the run kitty @ and simply wait for it to quit before continuing the loop. kitty @ new-window is very fast all it does is send a message to kitty, which opens a new window and sends the response. 

That way your users wont have to bother with --listen-on and it will work even over ssh.

**Comment by mawww** [comment]
Ok, thanks for the precisions.

**Comment by kovidgoyal** [comment]
And I just added a --no-response argument to kitty @ new-window so it will not even wait for a response from kitty if you dont want it to.

**Comment by mawww** [comment]
That will do the trick, thanks.

**Comment by mawww** [comment]
Hum, wouldn't it make sense to have --no-response a general switch to `kitty @` (like `kitty @ --no-response new-window`) ? The same problem takes place with other commands, such as `focus-window`).
