### ISSUE TITLE
Stop ascribing meaning to codepoints

### ISSUE THREAD

**Issue by evertvp** [kovidgoyal/kitty#787]
Manish Goregaokar explains this better than I ever will: https://manishearth.github.io/blog/2017/01/14/stop-ascribing-meaning-to-unicode-code-points/. The issues described in his blog post also show up in kitty. For example, ZWJ's are rendered as <200d> on the prompt and ignored in the output. This is what `echo "👨‍👩‍👧‍👦"` looks like on the prompt: 
```
$ echo "👨<200d>👩<200d>👧<200d>👦"
👨👩👧👦
```
On the other hand 👩🏽 renders correctly but takes up 2 cell blocks (both in the prompt and the output) so this is consistent with https://github.com/kovidgoyal/kitty/issues/461#issuecomment-381441740.

For text in non-latin scripts there are also some weird things happening: 각 shows up in the prompt as `ᄀ<1161><11a8>` but correctly in the output (and it only takes up one cell, even though it is made up of three codepoints, so this is not consistent with https://github.com/kovidgoyal/kitty/issues/461#issuecomment-381441740).

All in all this is probably a (really) hard problem to solve, but it would be greatly appreciated if you could look into it.

**Comment by kovidgoyal** [comment]
zwj is not currently supported. This is something that can be
implemented, but is not something I am particularly keen to implement,
since it is a performance hit in general use for a pretty useless
feature (its only use is for combining emojis and arabic scripts). It
means that one now has to store a potentially unbounded number of unicode
codepoints per cell instead of the current three. This will have a
terrible impact on common case performance, which makes it not
worthwhile.

As for the skin tone combining char, that looks like a bug and will
probably be fixable. Feel free to open a separate issue for that.

Finally, for 각 it not showing up at the prompt is a bug in whatever
shell you are running, run cat instead of a shell and it will render
correctly although it will take up three cells, not one, which is a
fundamental limitation of kitty's design as a character grid. 
I should note that in general, kitty will never work well with th emore
complex scripts such as arabic/indic languages, since it is designed as
a character grid and those scripts do not fit into the character grid
paradigm. See #704

**Comment by kovidgoyal** [comment]
Emoji skin tone modifiers are now properly recognized as combining chars. https://github.com/kovidgoyal/kitty/commit/000c1cf306ddbb1a1465845aeb4f74d0f8e52071

**Comment by kovidgoyal** [comment]
Oh and your issue with zwj is also from your shell. Use cat or up-to-date bash and 👨‍👩‍👧‍👦 will render correctly.
