### ISSUE TITLE
terminfo file does not match reported keypress

### ISSUE THREAD

**Issue by alxdb** [kovidgoyal/kitty#796]
So, looking at the terminfo.py file for kitty, I see these lines:
```python
# Home                                                                                            
'khome': r'\EOH',                                                                                 
# End                                                                                             
'kend': r'\EOF', 
```
meaning the output of `showkey -a` should echo `^[OH` and `^[OF` on pressing home and end respectively. However, when testing this, `showkey` echos `^[[H` and `^[[F`. This means curses applications (e.g. vim), and other non readline applications (e.g. zsh) are not detecting the home and end key.

For example, if I do `bindkey "${terminfo[khome]}" beginning-of-line` in zsh, the binding does nothing. If I do `bindkey "^[[H" beginning-of-line` however, it works.

This is only an issue in kitty, urxvt for example works.

OS: Arch Linux (rolling release)
Kitty: 0.11.3
config changes: font and color scheme.

**Comment by kovidgoyal** [comment]
There are two terminal keyboard modes application mode and normal mode. https://vt100.net/docs/vt510-rm/DECCKM
and
http://invisible-island.net/xterm/manpage/xterm.html#h3-Special-Keys

The terminfo k* data refers to application mode. terminals start out in normal mode. If an application wants to make use of application mode, it needs to send the appropriate escape sequence first. For example, do this:

```
printf '\e[?1h'; showkey -a
```

and you will get [OH etc.

I have no idea why urxvt maps khome and friends to normal mode keys (probably because it does not support application mode), but it seems to be unique in doing so (well it and the linux kernel console). 

xterm, gnome-terminal, konsole, etc. all have the same, correct, behavior as kitty.

And as far as I know, all curses based applications work correctly with kitty. vim and zsh are both not curses based and so require special config to get around their broken keyboard handling. For zsh doing so is discussed in the link I posted above or you can simply add the switch to application mode escape code to your PS1. For vim, I dont recall what is necessary, but it should not be hard to google for it.
