### ISSUE TITLE
Cannot open kitty in MacOS 15.1

### ISSUE THREAD

**Issue by junereycasuga** [kovidgoyal/kitty#8002]
**Describe the bug**
I'm not sure if this is the right place to open this issue. But I'm getting `The application "Finder" does not have permission to open "kitty"` after upgrading MacOS 15.1. Kitty is the only application I'm facing this issue.

Although opening kitty using MacOS's default terminal works.

**To Reproduce**
1. Upgrade to the latest MacOS version (15.1)
2. Install kitty using nix-darwin
3. Open kitty using Finder

**Screenshots**
![Screenshot 2024-10-29 at 14 36 47](https://github.com/user-attachments/assets/dc2dcfa8-38d2-4696-8521-c8e486595be5)

**Environment details**
```
Press Ctrl+Shift+F6 (cmd+option+comma on macOS) in kitty, to copy debug output about kitty and its
configuration to the clipboard and paste it here. 

On older versions of kitty, run kitty --debug-config instead
```

**Additional context**
Try to reproduce the problem with `kitty --config NONE` if you cannot then post a minimal kitty.conf that reproduces the problem. If the problem involves interaction with some other terminal program post a minimal config for that program to reproduce the problem as well.

**Comment by kovidgoyal** [comment]
I'm afraid I dont support nix-darwin. I cant tell you the official kitty
binaries work fine in macOS 15.1

**Comment by kovidgoyal** [comment]
Actually, I was mistaken I was on 15.0.1 not 15.1, I'll check that the official kitty still opens in 15.1 later in the day.

**Comment by junereycasuga** [comment]
got it. will wait the results on your end. it was working fine until I upgraded to 15.1

**Comment by kovidgoyal** [comment]
Updated to 15.1 and official kitty binary launches from Finder just as before.

**Comment by benjasper** [comment]
Hi @junereycasuga, just to let you know I am having the same issue.
I am on nix-darwin as well, which makes it seem like this is somehow the cause of the issue. Also not really sure where to place this, but probably not an issue with kitty itself (although I don't have the issue with other packages).

I thought at first it was a skill issue on my end, but maybe not? Let me know if you figure something out :)

**Comment by junereycasuga** [comment]
@benjasper yea. same thing. all other packages on my machine installed using nix-darwin are working just fine except for kitty.

right now, i had to run kitty using MacOS's default terminal as a temporary solution.

**Comment by cthulhuz** [comment]
I am also having the same issue with kitty when running nix on MacOS 15.1. @junereycasuga @benjasper
Seems like we are not the only ones: https://github.com/DeterminateSystems/nix-installer/issues/1261

**Comment by derekschrock** [comment]
While only supporting official binaries is fine the other issue here is when you're building from source on macOS.  As the docs suggest:

`On macOS, you can use kitty/launcher/kitty.app to run kitty as well, but note that this is an unsigned kitty.app so some functionality such as notifications will not work as Apple disallows this. If you need this functionality, you can try signing the built kitty.app with a self signed certificate, see for example, here.
`

You can see that via the Note [here](https://sw.kovidgoyal.net/kitty/build/) for macOS with a link to how to sign the app.

With 15.1 it now seems be required to make the kitty.app launchable either by open(1) or double click.  

After creating a self signed certificate and running `codesign --deep -fs  "named cert" kitty/launcher/kitty.app/` allows kitty.app `open ...` or double clickable or executed via other means (Alfred, Spotlight).     

btw `kitty/laucher/kitty` while does work without signing has some oddities that I haven't identified yet so I've never used it.

@kovidgoyal  Would it be possible if an env var is set to the cert's name kitty's build will auto sign via:

  `codesign --deep -fs  "$CERTNAME" kitty/launcher/kitty.app/` if built via `./dev.sh build` 
or 
 `codesign --deep -fs  "$CERTNAME" kitty.app/` if built via `make app`

Otherwise just leave this as a post build manual process?

**Comment by derekschrock** [comment]
Ok. Nevermind.  I see there's already with bypy.

**Comment by yzx9** [comment]
In case anyone is still interested, NixOS/nixpkgs#352795 might be what you're looking for

**Comment by kovidgoyal** [comment]
open kitty/launcher/kitty.app works fine on my 15.1 system without
codesigning. I would be amazed if Apple broke the ability to run locally
compiled unsigned apps.

**Comment by derekschrock** [comment]
Do you have SIP turned off?

**Comment by kovidgoyal** [comment]
No, I dont.

**Comment by derekschrock** [comment]
Well that appears to be the case.

- https://hackaday.com/2024/11/01/apple-forces-the-signing-of-applications-in-macos-sequoia-15-1/
- https://lunduke.locals.com/post/6304352/apple-removes-ability-to-run-unsigned-apps-in-macos-15-1
- https://news.ycombinator.com/item?id=42032444

Works fine for some. 
Bug in System Settings UI to allow it (introduced in 15.0 - broken in 15.1).  
Apple A/B testing.
