### ISSUE TITLE
zooming and grapghics

### ISSUE THREAD

**Issue by mil-ad** [kovidgoyal/kitty#8014]
**Is your feature request related to a problem? Please describe.**
Zooming in and out does not affect the graphics (via Kitty's awesome graphic protocol).

**Describe the solution you'd like**
It might be more natural for graphics to also get larger or smaller with text zoom. This is how Wez has implemented it and would be nice to have this behavior at least as an option

**Comment by kovidgoyal** [comment]
I'm afraid not. This functionality belongs more properly in a program
running inside the terminal rather than the terminal itself. The
terminal doesn't really have enough context/information about the users'
intentions when they are increasing the font size. For example,
magnifying an image when doing this can cause all sorts of negative
effects such as pixelation, the image not fitting on the screen anymore,
etc. Therefore, I dont think it is a good idea.

**Comment by mil-ad** [comment]
@kovidgoyal fair enough. I made a small library that uses kitty graphics protocol: https://github.com/mil-ad/kitcat

Would be great if you could add it to the list of applications [here](https://sw.kovidgoyal.net/kitty/graphics-protocol/)

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/commit/97f26a8a757d10f3bea5253b027f24e9bed55604
