### ISSUE TITLE
Font being truncated in nvim

### ISSUE THREAD

**Issue by Anaritus** [kovidgoyal/kitty#8018]
**Describe the bug**

Hi! I am sorry if that is very common and has already been answered, but I couldn't find any solution from quick search.

I am using MesloLGL Nerd Font Mono, which is listed in kitten fonts. When previewing regular, bold etc variants it looks fine, but inside nvim italic symbols(mainly M,N) are truncated. 

I think this is related to https://sw.kovidgoyal.net/kitty/faq/#some-special-symbols-are-rendered-small-truncated-in-kitty and maybe https://sw.kovidgoyal.net/kitty/faq/#kitty-is-not-able-to-use-my-favorite-font, but I couldn't figure out what to actually do

**To Reproduce**
Use fresh install of kitty, use MesloLGL Nerd Font Mono, open up nvim (vim also works), use any way to display italic, type M,N and see the difference

**Screenshots**
![image](https://github.com/user-attachments/assets/6a413eaa-bdff-4298-a0ef-2d667c8e7381)
![image](https://github.com/user-attachments/assets/d7f47c1c-f13c-45b1-b82f-3f79d137b3ae)

**Comment by kovidgoyal** [comment]
The preview wont show truncation, because it doesn't do cell based
rendering. If you see truncation it is because the font does not have
matching metrics across all its faces. Use a better font or use the
modify_font setting in kitty.conf to broaden the cell size so it fits
the bold face as well. Also dont use patched NERD fonts they break
things and are not needed in kitty.
