### ISSUE TITLE
kitty.conf vim defaults

### ISSUE THREAD

**Issue by tostr7191** [kovidgoyal/kitty#8043]
Kitty has on of the best commented config files I have ever seen. I really like being able to look up things. However, I also like to see the changes I actually made.

By default kitty ships with this vim modeline: `# vim:fileencoding=utf-8:foldmethod=marker`. This works fine by folding along the markers `{{{` and `}}}`. However, for actually editing the file, referencing my own changes and similar, the markers actually do not correspond to what I care about at this moment.

I usually edit by copying the default value, uncommenting it and changing the setting like so:
```
# enable_audio_bell yes
enable_audio_bell no

#: The audio bell. Useful to disable it in environments that require
#: silence.
```

Now I would like to be able to easily fold by comments/not comments. I can achieve this in two ways:

Either set the modeline to:
```
# vim:fileencoding=utf-8:foldmethod=expr:foldexpr=getline(v\:lnum)=~'^\s*$\\\|^\\s*'.&commentstring[0]:foldminlines=0
```
which also requires something along these lines in your `.vimrc`:
```
autocmd BufReadPre */.config/kitty/kitty.conf setlocal modelineexpr
```

Alternatively one can also add the whole logic to the `.vimrc` like so (please note this is vim9script):
```
def KittyFold(lnum: number): any
  if getline(lnum) =~ $'^\s*$\|^\s*{&commentstring[0]}'    
    return 1
  else
    return 0
  endif
enddef

autocmd BufReadPre kitty.conf setlocal nomodeline foldmethod=expr foldexpr=KittyFold(v:lnum)
```

The effect is the same, it looks something like this:
<img width="929" alt="Screenshot 2024-11-12 at 00 56 42" src="https://github.com/user-attachments/assets/0fc7c334-ca32-492f-bea3-22736597c844">

I understand that neither of these can be easily included in the default config, but to me this change increases the value of the config file quite a bit, maybe there is a good place to put it in the documentation?

**Comment by kovidgoyal** [comment]
Personally I recommend that rather than uncommenting to change a value
put your changed values at the top of the file. Then in the future when
you want to read up what a setting does you can just move your cursor to
it and hit * to go to the next match of it and read its docs. And
similarly jump back to where you were with another press or two of n.
There are a few settings that are mentioned in multiple places in the
docs of related settings and this method shows you that extra context
easily as well.

I dont want to add editor specific documentation to the config as its
kind of unfair to users of other editors.
