### ISSUE TITLE
Pin cursor on top

### ISSUE THREAD

**Issue by pr4th4m** [kovidgoyal/kitty#8143]
I started a discussion in p10k repo to pin cursor at top, as per @romkatv this can only be done in terminals. So just wanted to check if this feature is already in kitty or would it be possible to add this feature.
Something similar to https://www.warp.dev/blog/configure-input-at-the-top-in-warp
Reason to request this feature is the neck pain I have looking at the bottom of screen most of the time

**Comment by romkatv** [comment]
> Reason to request this feature is the neck pain I have looking at the bottom of screen most of the time

I had the same until I moved my terminal window so that looking at the bottom of it is most comfortable. The most important info is at the bottom. Specifically, the prompt and the output of the last command. If you put prompt at the top, you'll still have to look at the bottom because that's where the output of the last command will be.

**Comment by pr4th4m** [comment]
Ya I agree with you if the output is large, however, for smaller output this feature can be useful.
I will try your suggestion to move terminal window, thanks for the tip 😄

**Comment by kovidgoyal** [comment]
:) As per me this should only be done in shells not terminals, or more
precisely shells in co-operation with terminals. For a
terminal to implement it alone, it would basically have to run the shell in its
own pty and display the output elsewhere which will cause all sorts of
breakage with more advanced things shells do like multiline prompts,
completion popus etc. Just browse the warp issue list for a taste.
