### ISSUE TITLE
Add ability to zoom a window

### ISSUE THREAD

**Issue by pehota** [kovidgoyal/kitty#870]
I really like Kitty but there are several things that keep me from abandoning iTerm and tmux. 
One of them is the ability to zoom a window (like tmux's `zoom pane`).
Unless I missed something in the documentation, there is no such functionality in Kitty currently.
It would really be a neat feature to have.

**Comment by kovidgoyal** [comment]
simply switch to the stack layout. That will effective zoom the currently focused layout. You can create a dedicated key binding for it in kitty.conf if you like using the goto_layout function.

**Comment by ptbrowne** [comment]
The zoom feature also allow to unzoom = go back to the previous layout.

Would you be open to a PR that implements this behavior ?

**Comment by kovidgoyal** [comment]
Switch back to the previosu layout and it is the same as unzoom.

**Comment by kovidgoyal** [comment]
If you mean you want an dedicated switch_to_previous layout function, sure, feel free to send a PR for that.

**Comment by ptbrowne** [comment]
@pehota At the moment to almost get this behavior I did : 

```
map `>z goto_layout stack
map `>a goto_layout tall
```

**Comment by pehota** [comment]
Thank you @ptbrowne and @kovidgoyal

**Comment by esn89** [comment]
with the "last_layout" implement, does that mean we now siwtch to stack, and then can toggle "last_layout" to get the zoom in/out effect?

**Comment by kovidgoyal** [comment]
yes

**Comment by ronjouch** [comment]
@kovidgoyal thanks for f0357b0 implementing `last_used_layout`.

Going one step further: because I typically switch between current layout and fullscreen ("stack"), it would be great to also have a `toggle_current_layout_with_layout <layout>` command, which would dispense having two keyboard shortcuts. I would `map f11 toggle_current_layout_with_layout stack`, and pressing <kbd>F11</kbd> would always toggle between the current/previous layout and the `stack` layout. So no need to have one mapping for stack, and another for tall. A real toggle.

Edge case: if no previous layout exists at initial invoke and layout is `stack`, it's a noop.

Does that makes sense? Would you accept a PR for that?

**Comment by kovidgoyal** [comment]
I dont think you need aa separate function for that. Just modify last_used_layout to switch to a random layout if there is no previous layout, then you can simply use it for your use case.

**Comment by ptbrowne** [comment]
> with the "last_layout" implement, does that mean we now siwtch to stack, and then can toggle "last_layout" to get the zoom in/out effect?

Is it possible to use the same key for zoom/unzoom ? Essentially having a conditional on the key ?

with the "last_layout" implement, does that mean we now siwtch to stack, and then can toggle "last_layout" to get the zoom in/out effect?

```
 map `>z goto_layout stack if current_layout() != 'stack' else last_layout
```

**Comment by ronjouch** [comment]
> *I don't think you need a separate function for that. Just modify `last_used_layout` to switch to a random layout if there is no previous layout, then you can simply use it for your use case.*

@kovidgoyal the need is at startup: if there's no previous layout, then I'd like to switch to stack. Not to a random layout.

1. I'm used to this behavior from various apps "F11" key, and also tmux `bind -n C-b resize-pane -Z`, which have this toggling behavior between current layout and maximized layout.
2. More importantly, it feels natural: I'm using a layout with multiple windows in it. At some point I want all the available space for one window. I maximize. Then I'm done and I unmaximize.

@ptbrowne 's suggestion about scripting in mappings would be neat too.

**Comment by kovidgoyal** [comment]
So instead of using a random layout, use the "next_layout" and set enabled_layouts to have stack as the number two layout, so that at startup it is the next_layout. 

As for scripting in mappings, I'm afraid that is not going to happen. What you can do is create your own kitten, to do arbitrary scripting, kittens have access to the full kitty environment (the boss object from which you can create windows/siwtch windows/tabs/etc). The downside, with kittens is currently they will cause a brief flash when a overlay window is opened to run the kitten. It should be easy to modify the kittens sub-system to create kittens that have to running component and instead can just be used to script kitty, seamlessly. See https://sw.kovidgoyal.net/kitty/kittens/custom.html

**Comment by ronjouch** [comment]
> *So instead of using a random layout, use `next_layout` and set `enabled_layouts` to have `stack` as the number two layout, so that at startup it is the `next_layout`.*

@kovidgoyal but then I still have to bind (and remember to use) _two_ keys: one to switch to `stack` at startup, and one to switch back. Instead I'd like a _single_ key to toggle between current layout and "maximized".

What I also tried was to remove all layouts but `tall` and `stack`. In this case, `next_layout` becomes a real toggle between the two since they're the only two, but I also use other layouts intermittently, so that doesn't work.

**Comment by kovidgoyal** [comment]
It should be trivial to to create a kitten to do that for yourself. It's a little too specialised a use case for me to bother with creating a dedicated endpoint in kitty for it. I will instead modify the kittens system to allow no-UI kittens, so there will be no flash either.

**Comment by ptbrowne** [comment]
>  I will instead modify the kittens system to allow no-UI kittens, so there will be no flash either.

Perfect, that was this that prevented me from using the kittens system. Thanks !

**Comment by kovidgoyal** [comment]
already done, https://github.com/kovidgoyal/kitty/commit/787100a4dcd3d9c338bfc15511e4a4824a865e6a

**Comment by Julian** [comment]
Anyone have a fuller-featured implementation of this (as a kitten it sounds like) to share?

E.g. 2 things I immediately miss after the basic `map kitty_mod+z        toggle_layout stack` is a way to:

* indicate in the tabbar that a tab is zoomed
* make `launch` while zoomed "work normally" -- i.e. not open the new window zoomed, it should now open the original zoomed window + the new one in a split window, but leave the other hidden windows hidden

**Comment by kovidgoyal** [comment]
If you want those semantic use detach-window instead and make thewindow
into a new tab.

**Comment by mtak** [comment]
> Hi, anyone knows why the shortcut `map ctrl+shift+z toggle_layout stack` doesn't work in the latin american keyboard. I tried some shortcuts but nothing. Only works `goto_layout stack`, and other layouts, but that is not cool to do "zoom in and zoom out", thank you very much.

Are you sure you are using Kitty >0.27.1? Ubuntu 22.04 has Kitty 0.21.2, which doesn't support this feature.
