### ISSUE TITLE
Support for blurred backgrounds

### ISSUE THREAD

**Issue by sergiocampama** [kovidgoyal/kitty#885]
I like to have the background with something like 0.75 opacity, but also with the contents behind the terminal to be blurred, so that the focus is not lost if I have multiple terminals stacked. Would this be possible in kitty?

**Comment by kovidgoyal** [comment]
Not easily, at least as far as I know. GLFW (the toolkit kitty uses) has no ready made setting for that (as far as I know), which means it would need to be implemented with per-platform code, since the blurring would have to be performed by the OS (on platforms other than X11 windows are not allowed access to the contents of other windows for security reasons).

As such this is not worth the effort to me. But, patches are welcome. If anyone wants to implement this and needs guidance, feel free to ask, I will be happy to provide it, if I can.

**Comment by RaitaroH** [comment]
@sergiocampama 

I have this in my zshrc. Found it on reddit [here](https://www.reddit.com/r/kde/comments/6jzuwu/konsole_and_yakuake_blur/). It is for plasma if you are using it.
```
# Blur {{{
if [[ $(ps --no-header -p $PPID -o comm) =~ '^yakuake|kitty$' ]]; then
        for wid in $(xdotool search --pid $PPID); do
            xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
# }}}
```

**Comment by wyuenho** [comment]
> on platforms other than X11 windows are not allowed access to the contents of other windows for security reasons

Is that still the case? [NSVisualEffectView](https://developer.apple.com/documentation/appkit/nsvisualeffectview)'s doesn't seem to suggest any additional entitlement requirements.

**Comment by MaximumMaxxx** [comment]
If you use bash this version worked in my .bashrc

```
# Blur {{{
if [[ $(ps --no-header -p $PPID -o comm) =~ yakuake|kitty ]]; then
        for wid in $(xdotool search --pid $PPID); do
            xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $wid; done
fi
# }}}

```

**Comment by jclsn** [comment]
How to do this for Wayland?
