### ISSUE TITLE
C-SPC/C-@ not registered

### ISSUE THREAD

**Issue by nochiel** [kovidgoyal/kitty#89]
Using `cat`, type `C-spc` or `C-@`
expected: `^@`
actual: no output.

**Comment by kovidgoyal** [comment]
I can fix c-spc to generate null bytes (that is what ^@ is in cat's output) but I dont agree that c-s-2 should also generate nullbytes.

**Comment by nochiel** [comment]
Thank you,  as usual.

> but I dont agree that c-s-2 should also generate nullbytes.

Because, `ctl` and `shift` clear out the 7th and 6th bits  respectively which results in `DC2` not `NUL`?

**Comment by kovidgoyal** [comment]
In theory sure, but the problem is that ctrl+shit as a modifier is fairly useless, since all the actual bytes it results in are ambiguous with other, shorter key combinations. That effectively means that it is pointless using the C-S- modifier for keyboard shortcuts in traditional terminal programs and that is why it is the default modifier for kitty's own keyboard shortcuts.

**Comment by nochiel** [comment]
> [...] all the actual bytes it results in are ambiguous with other, shorter key combinations. 

Aha. Got it.
