### ISSUE TITLE
Scrollback search

### ISSUE THREAD

**Issue by prawnsalad** [kovidgoyal/kitty#893]
Coming from iterm2 the biggest thing I'm missing is iterms buffer search.
![image](https://user-images.githubusercontent.com/725880/45170954-13aedc80-b1f9-11e8-9105-d3eb0efe1a11.png)

While any process is running in the shell, it highlights any occurrence of the search term so that we can easily find parts of text we are interested in in real-time without effecting the commands being run in the shell.

**Comment by spl** [comment]
I was also looking for this answer. It might help to reorganize this bit of documentation. Having it under the heading “The scrollback buffer” was not obvious to me. Perhaps it putting it as a FAQ with a title that included the (key-)words “search,” “find,” and “text” would help.

**Comment by kovidgoyal** [comment]
Feel free to send a PR with improvements, relevant file is docs/faq.rst

**Comment by spl** [comment]
@prawnsalad Oh right, that is a useful feature in iTerm. It's also helpful to have [triggers](https://www.iterm2.com/documentation-triggers.html). In particular, I use them to highlight words like “error” and ”warning” in the running output.

**Comment by kovidgoyal** [comment]
That's never going to happen. Searching for text live in program output is a huge performance killer. It means you have to re-run the search expression on every received byte. kitty prioritizes performance.

And if you really want to do it for an already running process, simply use a tool like https://github.com/jerome-pouiller/reredirect/

Though really, if you want to monitor a process you should pipe its output into a monitor program when you invoke it. The monitor program can do arbitrarily powerful things.

**Comment by kovidgoyal** [comment]
Thinking about it, one way to do this without impacting kitty performance at all is to create a live output kitten, which would work like the current scrollback viewing facility works but would have kitty tee the output it receives from the process into its stdin, so it would be live and you could configure it to run any program/script of your choice to search for things/highlight things whatever.

**Comment by felixfbecker** [comment]
So <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>H</kbd> opens the scrollback in the default pager, e.g. `less`. But what if I have a command running (like a watching compiler, or a server) that is streaming output? iTerm lets me easily search the output of those too, but it doesn't seem to work with Kitty.

**Comment by kovidgoyal** [comment]
You can search the current contents of the scrollback buffer and the
screen at anytime by pressing kitty_mod+h kitty does not care if the
output is live or not. You will simply get to search whatever the output
is at the moment you pressed the keys.

**Comment by s1341** [comment]
> Thinking about it, one way to do this without impacting kitty performance at all is to create a live output kitten, which would work like the current scrollback viewing facility works but would have kitty tee the output it receives from the process into its stdin, so it would be live and you could configure it to run any program/script of your choice to search for things/highlight things whatever.

Any chance of this happening?

**Comment by kovidgoyal** [comment]
Not something I am personally interested in, but pathes are welcome.

**Comment by s1341** [comment]
I'd be happy to take a crack at it, if you'd be willing to provide a little guidance as to where to begin/hpw tp go about it... I am not familiar with the kitty codebase and am not sure where to start.

**Comment by kovidgoyal** [comment]
Sure, basically the code that reads input from child processes is in
child-monitor.c (see the I/O thread section) 

To implement this you would need to be able to associate an optional
"tee" fd with every child. And have the I/O thread write the data it
reads into the tee fd. Since you cannot guarantee the process on the
other end will read the input fast, you will need to add some kind of
buffering, maybe even use a separate thread for tee output. 

Then in boss.py and child.py you would dd the plumbing to pass this fd
to children and to create kittens using this plumbing.

**Comment by s1341** [comment]
@kovidgoyal ok. I'll start looking at this tomorrow. Might ping you if I have questions

**Comment by s1341** [comment]
couldn't help myself... Is this (https://github.com/kovidgoyal/kitty/blob/master/kitty/child-monitor.c#L1258) about the right place to write the data to the 'tee' fd?

**Comment by kovidgoyal** [comment]
Sure will behappy to clear up any confusion.

**Comment by s1341** [comment]
@kovidgoyal are you available on IRC anywhere? It could be helpful to shorten the loop between us as I work on this tomorrow

**Comment by kovidgoyal** [comment]
No, that's where kitty sends input to the child process, you want to do
it after 1249, i.e. you want to send input received from the child to
the tee fd.

I'm afraid I am too busy to real time guide you, but if you post
questions here or in a PR I will usually respond fairly promptly.

**Comment by s1341** [comment]
ok. I'll see what I can do.

**Comment by s1341** [comment]
Ok. This is my plan:

1. I'm going to add a 'teefd' member to the Child struct in child-monitor.c
5. I'll add a new python-accessible function "set_child_teefd" to the child-monitor.c file. This function will look up the Child in the children array by id, and update its teefd member with the passed argument fd.
3. I'm going to add a teefd argument to the read_bytes function in child-monitor.c, and pass it from the child in the io_loop function.
4. I'm going to add code to the read_bytes function in child-monitor.c, so that if the teefd exists, it will write the data received from the child into that teefd. At first stab I'm going to do this without buffering at the sender side or a thread at the sender side.
5. I'm going to add a tee_fd_reader and tee_fd_writer to the Child class in child.py
6. I'm going to add code to _run_kitten in boss.py to add a new 'type_of_input' called "live", which can be specified on the handle_result function of the kitten.
7. I'll add code (a new elif) to _run_kitten in boss.py, such that if type_of_input == "live", it will:
  * check if the target window's child has a tee_fd_reader/tee_fd_writer, and if not it will create a new os.pipe and store its two sides as window.child.tee_fd_reader and window.child.tee_fd_writer
  * set the data variable to be the window.child.tee_fd_reader fd. This data will be passed to the new overlay as the stdin arg.
  * call self.child_monitor.set_child_teefd passing the window.id and window.child.tee_fd_writer
8. I'll add code to Boss.on_kitten_finish so that if the target window has a tee_fd_reader/tee_fd_writer not equal to -1, it will:
  * call self.child_monitor.set_child_teefd passing the window id and -1
  * close both window.child.tee_fd_writer and window.child.tee_fd_reader
8. I'll add code to Child.fork in child.py, such that if the self.stdin member is a number, it will set the stdin_reader_fd to the value of self.stdin, and stdin_writer_fd to -1. In addition, change the "if stdin is not None" after the spawn to also ignore numeric stdin values. 

Does this sound about right?

**Comment by kovidgoyal** [comment]
yeah sounds reasonable.

**Comment by s1341** [comment]
Ok. I'll get working on that.

**Comment by s1341** [comment]
@kovidgoyal Ok. I've implemented basic support in PR #1780.

I needed to use sys.__stdin__ in the kitten instead of sys.stdin, for some reason. Didn't go into why. 

In addition, I've made the read end of the pipe non-blocking, as this makes more sense to me. I've 
done that in boss.py. Maybe it should be left as a decision for the kitten author? Not sure.

My little demo kitten works as expected.

The next steps would be:
1. Add screen/scrollback to data sent to the kitten, perhaps with "live-screen", "live-screen-history".
2. I have not tested ANSI support... it should just work, as we're sending the data as binary.
3. Implement some kind of buffering on the write end of the pipe.

Another question would be if instead of creating an overlay, we could pass the actual input fd to the kitten, t

**Comment by kovidgoyal** [comment]
The pipe should remain blocking, as that is the default and expected
behavior. Individual kittens can always convert it to non-blocking with
fcntl is needed.

I need to think about changing the input specification scheme from a
list into a set, there are becoming too many entries otherwise.

Buffering is definitely required for robustness.

Not sure what you mean by pass the input fd to the kitten. Do you mean
have the kitten intercept and modify output from the child process? If
so, no that is not a good idea.

**Comment by s1341** [comment]
I'll make the pipe blocking and fcntl it in the demo.

I'll tackle buffering next week.

Ideally, I'd like to be able to e.g. highlight text in the screen/scrollback, while remaining with a fully functional terminal. In other words, I'd like to be able to continue interacting with the terminal while the 'highlight certain phrase' kitten is running, having it continue to highlight the phrase as I type it or it shows up in command output. This most closely matches the functionality in iterm2, which is kind of what I'd like to end up with. I don't know how to achieve this though... What do you think?

**Comment by kovidgoyal** [comment]
That's not really doable the only way to implement that is to continuously scan the input for the matching pattern, which is a huge waste of CPU cycles. That doesn't really fit with kitty's design goals.

**Comment by s1341** [comment]
Ok. Would it be doable in a kitten though? That way it could be optionally enabled by those willing to take the performance hit?

Meanwhile I've fixed the blocking and also added screen/history contents to the live content. For some reason when I add screen contents I get a gap between the old data and new data which is output to the screen. This seems to be because of the size of the window? How do I get the screen contents without the gap?

**Comment by kovidgoyal** [comment]
No, kittens cannot change what is drawn by kitty, they can only overlay. 

What do you mean by gap, a blank line?

**Comment by s1341** [comment]
Many blank lines. See the screenshot below, the hello at the bottom was typed into the overlay, the rest of the data is from the stdin.

![image](https://user-images.githubusercontent.com/5682183/60729774-2ba3d980-9f4c-11e9-9038-1159968474e4.png)

Also, because I'm using stdin as the pipe read point in the kitten, I can't ask the user for a search term, because input() uses the stdin... Doh! Any idea how I can work around this?

**Comment by kovidgoyal** [comment]
You open('/dev/tty') to interact with the terminal when stdin is
redirected. I'll look into the blanks later, when I hve some time to
review your code.

**Comment by s1341** [comment]
ok. I figured out the stdin/terminal interaction issue. Going to push one last commit and then call it a day. Please give me feedback on my code/etc.

**Comment by arkilho** [comment]
Has this feature been implemented?

**Comment by s1341** [comment]
@arkilho It has been implemented here https://github.com/kovidgoyal/kitty/pull/1809 as output filters. But not yet merged.

**Comment by brandon-fryslie** [comment]
I would really recommend @kovidgoyal try out iTerm 2's implementation of scrollback buffer search.  I simply don't believe anyone who has used it would find kitty's implementation comparable in any way.  I have looked through the entire chain of Github issues, PRs, and docs.

I struggled to come up with an analogy that would really express it, but I think this is somewhat close.  First, assume we are in a time when Google is high quality and useful, like 10-15 years ago.  iTerm 2's scrollback buffer search is like Google.  Fast, relevant, powerful.  kitty's would be like if Google made you download every page of results as HTML, open them in a separate text editor, grep them, copy the link yourself, and paste it back into your URL bar.  

Is it doable?  Of course.  And I'm sure over time people just learn to deal with it and it becomes normalized.  But coming from iTerm 2, really really unfortunate because everything else about kitty is just top notch so far.  I

 honestly figured I could just delete iterm2 because kitty does everything else so much better, I've started writing kittens, I was excited to play with multiple text sizes in a session, all the extensions, remote control, the fast rendering...the customizability.  So much great stuff.  I migrated fully to kitty and figured I'd just fix any issues as they came up until I was at parity.  I didn't think I used any advanced features of iTerm, and it absolutely never occurred to be that something as fundamental as search would just be non existent.  Yes I know it's technically possible to open a separate buffer and grep that, but Jesus.  It's like riding in a private jet until you need to use the bathroom, then being forced to pull over and use a random portopotty.  

I will give it an honest shot.  Maybe it's not as bad as it seems so far.  But I use this for work as well as for fun, and as much as I enjoy all the cool stuff in kitty, I just can't sacrifice basic usability to have interesting playthings.  

To make this more concrete here's something I do often in iTerm:

- Double click a word
- Press cmd+E
  - Now every occurrence of that word is highlighted in my unlimited scrollback (which magically seems to have 0 impact on performance)
- Press cmd+G / cmd+shift+G to navigate to each occurrence 

That's 1 click, 1 key to highlight every occurrence of any search string in the current buffer.  One more key navigates forward or back.  

I don't think this is possible at all today in kitty, with any amount of keypresses.  This isn't something you can write a kitten for, as far as I understand.  I'd love to be wrong, but from what I can tell there is simply nothing in kitty that would allow one to do this in kitty, period.  All the more impressive that the iterm2 dev managed to do it so efficiently that there is 0 performance penalty.  

That is just the feature I found that might be the dealbreaker.  But that's not anywhere near what iTerm 2 can do with search (I just don't use the advanced search stuff very much, only the basic search).  I know it doesn't really matter much if I use the tool you provided for free.  I am grateful you do provide it.  I'll ask around to see if there is some way to work around this deficiency.

In the meantime, I would encourage you to try iterm2's functionality.  I think it's important to distinguish between "I don't use this feature because I've solved the core issue in a better way" and "I don't use this feature because I haven't experienced how much better another solution can be".

Thanks for the great application, it's a wonderful tty.  

<img width="697" height="318" alt="Image" src="https://github.com/user-attachments/assets/8acf7bcf-3272-4306-aeff-425abc35c258" />

**Comment by kovidgoyal** [comment]
That's a whole load of text just to say that you haven't actually tried
this feature in kitty. You want to double click on a word and search for
it, do exactly the same with one line in kitty.conf

```conf
map ctrl+e launch --type overlay --stdin-source @screen_scrollback --stdin-add-formatting less --chop-long-lines --RAW-CONTROL-CHARS --pattern @selection
```

As for its "magical lack of performance cost", you base that on what
exactly? Though to be honest iTerm's overall performance is so poor the
additional overhead for infinite scrollback probably is indeed
negligible. Regardless if you want infinite scrollback in kitty use the
scrollback_pager_history_size setting in kitty.conf

Allowing you to examine the scrollback buffer in arbitrary programs of
your choice, is a strictly superior design to building it into the
terminal. Allowing for flexible, composable and modular solutions
adapted to individual workflows.

**Comment by brandon-fryslie** [comment]
Very fair point. 

> Allowing you to examine the scrollback buffer in arbitrary programs of
your choice, is a strictly superior design

I see the benefit in theory.  In practice I also value a tool that does everything I need, and behaves identically with the same kb shortcuts across the OS.  Not a complaint, just a comment.

Kitty provides me all the tools I need to do this, so in a real sense this is already resolved.

**Comment by xlab** [comment]
> do exactly the same with one line

Not exactly the same, since on iTerm2 the search happens with scrollbar available and it also shows amount of matches, etc. But at this moment it's obvious that the solution is to replace `less` with a custom made program that will extend this missing kitty functionality. There are great high-performance TUI libs that enable scrollbars and normal editor-like searches...

The only thing is that this sidecar process will look at a **snapshot** only. What we really need is something like `--stdin-source @screen_scrollback + @live_stdout` (notice live stdout) that will be piped into the viewer process.

This PR https://github.com/kovidgoyal/kitty/pull/1780 was implementing live stuff, but was closed "in favour" of unrelated feature, i.e. the feature that focuses on a small subset of use cases for live streaming, highlighting the pattern in live output.


UPD:
https://github.com/ynqa/sig/ - good example
