### ISSUE TITLE
There is already a terminal emulator named KiTTY. How will you differentiate your emulator from it?

### ISSUE THREAD

**Issue by anothermindbomb** [kovidgoyal/kitty#9]
KiTTY is a fork of PuTTY - you can find it at http://kitty.9bis.net/

You may want to differentiate your product from KiTTY so that google knows the difference...

**Comment by kovidgoyal** [comment]
As far as I can tell, the other kitty is windows only and this kitty does not run on windows, so the potential for name conflicts is low. As such, I am not particularly motivated to change the name. As for googlability -- hopefully this kitty will overtake the other kitty soon ;)

That said, I am not adamantly opposed to changing the name, it's just not something I see much need for at the moment, it's more important to get it working and bug free right now.

**Comment by Natanji** [comment]
Just wanna chime in to say that Kitty runs perfectly under Windows. Ubuntu for Windows exists and works great. ;)

**Comment by aperson** [comment]
That has nothing to do with the naming conflict.

**Comment by jaked122** [comment]
Just call it YAKitty, for yet another kitty

**Comment by ibrokemypie** [comment]
+1 the other kitty is all that comes up in google when looking for info, or if this one appears, the results are still swamped.

**Comment by bradens** [comment]
Naming conflicts are more problematic when doing searching for kitty related resources.  I think that it needs a name change unfortunately.

**Comment by lonjil** [comment]
I've been switching to Kitty, but it has been mostly impossible to find any resources by googling.

**Comment by dlong500** [comment]
Yeah, given that the other Kitty is still a terminal emulator it's really a bad choice to name it Kitty regardless of which operating systems either of the apps run on.  Aside from search engine problems it just creates confusion all around.

**Comment by GuiltyPixel** [comment]
I can't believe I'm suggesting this, but maybe **Nyaotty**, maybe said sort of like like 'naughty' with a [Meowth](https://en.wikipedia.org/wiki/Meowth) accent? I'm currently no longer using or interested in Kitty until this problem is resolved, either for the sake of clarity or professional courtesy. Note that KiTTY is the currently (actively) maintained fork of PuTTY which has been in use since 22-Jan-1999. I think this is a bit like calling a newly invented ice cream flavor '[rocky road](https://en.wikipedia.org/wiki/Rocky_road_(ice_cream))'. While that isn't a trademarked name, and isn't the most popular ice cream flavor, many people may believe they know what rocky road describes in the context of ice cream and may expect something other than the new product. That, and Google is confused apparently, but what else is new there? The glaring issue I see as far as clarity issues is that both are terminal emulators, kind of. One remote, one local, but probably confusing if I told a noob friend to go check out 'kitty terminal' and they put that in a search engine, don't you think? Issues such as those relating to 'kitty' and 'character encoding' or something are not going to be very clear. I'm not sure this issue should be closed.

**Comment by irth** [comment]
I wanted to look for some ready-to-use color schemes for Kitty and it's practically impossible

**Comment by notaduck** [comment]
@irth why not just use xresources colorcheme and remove the *. And = ?

**Comment by jtl999** [comment]
MeowKitty?

**Comment by spejamchr** [comment]
Witty?

**Comment by SolitudeSF** [comment]
@adbX just run a sed script. remove `*.` and `:`. the names are the same, except Xresources `cursorColor` is just `cursor` in kitty.

**Comment by anton-malakhov** [comment]
I guess people will keep coming and raise this issue. I'm not even sure I want to even try this one since the naming conflict will keep bugging me, so the conflict is not actually good for advertisement either

**Comment by hovissimo** [comment]
So even when this project overtakes the other KiTTY in Google's search results there's still a problem.  Now when people are trying to find results for the Windows SSH client they'll find this project instead.  

@kovidgoyal  "As for googlability -- hopefully this kitty will overtake the other kitty soon ;)"  This attitude is rude and selfish.
