### ISSUE TITLE
Reassigning code points in symbol mapping

### ISSUE THREAD

**Issue by michaelmior** [kovidgoyal/kitty#919]
Instead of using a patched font, I tried using `symbol_map`. However, I need to map some glyphs to different code points in the source font. It seems like this is not currently possible in kitty. For example, I whenever glyph `0xF000` would be displayed, I want to display glyph `0xF400` from another font.

**Comment by maximbaz** [comment]
This is quite unusual request, feels like your best bet is to look into fontconfig or keep using a patched font where `0xF000` has the glyph copied from `0xF400`, so that this replacement is respected by all apps.

**Comment by kovidgoyal** [comment]
Yeah,  I agree with @maximbaz symbol_map is not going to override the code point mapping of fonts, that's too niche a use case.

**Comment by michaelmior** [comment]
I would argue against the niche use case point since this is something done by the patched fonts from [nerd-fonts](https://github.com/ryanoasis/nerd-fonts) which has over 10K stars.

**Comment by michaelmior** [comment]
Also, using the patched font doesn't work correctly either for all glyphs. (I don't have any issues with gnome-terminal, alacritty, and others I've tried.)

**Comment by maximbaz** [comment]
Nerd fonts is doing something different from what you described. 

They take several fonts and want to combine all the glyphs from all the fonts into one big font. Problem is, in multiple fonts the same codepoints are used for different glyphs - suppose font A has a sun emoji at `0xF000` and font B has a flower emoji at `0xF000`. What they do is that in target font C they keep for example sun emoji at `0xF000`, but move flower emoji to `0xF400`.

So it's not like a mapping that instead of `0xF000` they always unconditionally display `0xF400`, they just have two codepoints, one is rendering sun emoji and another is rendering flower emoji.

**Comment by michaelmior** [comment]
Yes, I understand that. But if I want to emulate this using `symbol_map` instead of using patched font C, I would need to be able to map `0xF400` to `0xF000` in font B.

**Comment by kovidgoyal** [comment]
If you want to use the nerd font simply use it. As far as I know it works perfectly fine in kitty. If it isn't on your system, its probably because fontconfig is returning some other fallback font for the symbols that dont work, which you can override using symbol_map

**Comment by michaelmior** [comment]
Some symbols aren't working correctly with the patched font. Other terminals don't seem to have a problem. Any idea how to debug what's going on? It would be rather tedious to fix symbols one by one.
