### ISSUE TITLE
Unable to set constant title with session

### ISSUE THREAD

**Issue by ole-optiopay** [kovidgoyal/kitty#944]
When a session is used the `--title` option to the kitty command is ignored.
I can set titles for windows in the session file. So I can set the same title to all windows.

Unfortunately creating a new window (e.g. with `Ctrl`+`Shift`+`Enter`) creates a new, different title.

**Comment by kovidgoyal** [comment]
dup of #921 which is already fixed.

Although I should not that --title only applies to the first window (or
all the session windows) you create. it does not apply to any new
windows you might create later, this is by design. If you want to 
set titles in newly created windows, the best way to do that is to add a
window title setting escape code to the prompt definition of your shell.
