### ISSUE TITLE
alt+click to set cursor 

### ISSUE THREAD

**Issue by monouser7dig** [kovidgoyal/kitty#954]
on mac terminal you can set the position of the cursor by clicking+pressing alt

can this be added (as an option)?

thanks 

> I did a search through the docs and closed issues and could not find one.

**Comment by kovidgoyal** [comment]
As long as the terminal application you are running inside kitty supports the mouse simply clicking without needing to press alt is all you need to do. For example, in vim (with 'set mouse=a' in vimrc). 

I'm not sure what the point of alt+clicking to move the cursor in applications that dont support the mouse would be. Doing so would just confuse them, since the cursor would, from their paerspective, magically change positions.

**Comment by monouser7dig** [comment]
> As long as the terminal application you are running inside kitty supports the mouse simply clicking without needing to press alt is all you need to do.

Well I should have made the use case clearer, I used this feature in the standard bash command prompt where just clicking does not work in kitty.
This does not surprise users e.g. in Mac terminal you can only move the cursor by clicking into the same positions as the arrow keys can as well. Namely you can not klick the cursor into the prompt.

**Comment by kovidgoyal** [comment]
That might work with bash, since bash or rather readline doesn't do a lot of sophisticated processing with the cursor position) but I dont see how it could possibly work in general. Imagine you are writing a terminal application and you need to output some text at some point on the screen, to do so you move the cursor to that point and then output the text. Now if the user happens to alt+click in between those two actions (which can easily happen over an ssh connection, for exmaple, the txt will go to the wrong place and you wont even know that it has.

I also dont see how mac terminal could prevent the cursor from being moved into the prompt -- I'm not disbelieving you, I just know of no way to robustly implement that with out-of-band cursor movements such as you propose.

**Comment by monouser7dig** [comment]
Ok so this might not be easy,
the motivation for bringing this up was that 90% of the time I might be typing rather simple things in bash, so it seemed worth mentioning as a primary use case of (most?) terminals.
Having the alt modifier would only enable the user to make a conscious decision to use this feature so I'd argue the user would figure out where it works and only use it in those cases.

**Comment by kovidgoyal** [comment]
The proper solution for this is for readline to add mouse support. I'm guessing that what iterm does is similar to this: https://linux.die.net/man/1/urxvt-readline

**Comment by monouser7dig** [comment]
(actually I don't use iTerm but the bog standard Mac terminal but maybe iTerm works the same)

**Comment by kovidgoyal** [comment]
typo I meant to type mac terminal not iterm
