### ISSUE TITLE
Last line in window disappears after another window closes

### ISSUE THREAD

**Issue by cizra** [kovidgoyal/kitty#958]
I have this session file
```
$ cat kitty-line-disappears 
layout tall
launch bash -c "echo hi; sleep 3"
launch bash -c "echo hi;echo yo;echo hey ho; bash"
```

I launch it with:
```
$ kitty --session kitty-line-disappears 
```

After 3 seconds pass and the leftmost window shuts down, the last line `hey ho` disappears.

**Comment by kovidgoyal** [comment]
Does not happen for me. Typically when the bottom line disappears it is because the shell redrew its prompt over it, so its likely your bash config is involved as well.

**Comment by cizra** [comment]
You're right, this only seems to happen if my prompt is longer than fits on screen. 
```
export PS1='my rather long prompt $ '
```
That simple prompt without any colors or fancy cursor movement is enough to repro the issue if the window is small enough not to fit it.

Please feel free to close the issue if you consider it not a bug in Kitty.

**Comment by kovidgoyal** [comment]
Yeah, I dont see how this is a kitty bug. On resize, all kitty does is rewrap lines and position the cursor, which as far as I know it does correctly. In other words, the cursor should be on the line after hey ho after the resize. You can check that by running cat instead of bash at the end of the second launch command.

If the cursor is indeed on the correct line after the resize, then the bug is not in kitty. When I tried it, the cursor was on the correct line.
