### ISSUE TITLE
Fonts look significantly worse than in iTerm on high dpi displays

### ISSUE THREAD

**Issue by PapaCharlie** [kovidgoyal/kitty#963]
The screenshot below shows the difference in font rendering between iTerm and Kitty (above and below, respectively):
![image](https://user-images.githubusercontent.com/5124201/45456394-6f68e200-b69f-11e8-889d-9b8797e43901.png)

Both were configured with Fira Code Retina in 13pt. Am I missing some configuration somewhere?

**Comment by Luflosi** [comment]
This is because kitty does not support sub-pixel anti-aliasing. You can try setting the config option `macos_thicken_font` to something like 0.5 to 0.75 to make the font look slightly thicker and more similar to the font in iTerm.

**Comment by kovidgoyal** [comment]
The fonts in the screenshot look significantly better in kitty to me :) When it comes to fonts, better/worse is mostly a function of what you are used to looking at. As Luflosi said you can use th thicken fonts option that was just recently added to master to get th efonts in kitty to look more like those in iTerm.

**Comment by PapaCharlie** [comment]
Alright, I'll try playing around with that config. I guess it is a matter of preference. I just got used to they heavier font on iTerm.

@Luflosi Is sub-pixel anti-aliasing support on the roadmap?

**Comment by Luflosi** [comment]
Sub-pixel anti-aliasing is not on the road map and if nobody writes a patch to add it as an option without affecting the performance of kitty when that option is turned off, @kovidgoyal will not add it because it seems to be quite difficult to implement, would require a performance hit and he does not see a much of a point since many displays are high DPI nowadays (Just not mine :/ ). See #214 for more info. Apple is also dropping sub-pixel anti-aliasing in macOS Mojave, just FYI.

**Comment by 257** [comment]
> since many displays are high DPI nowadays.

i beg to differ.
