### ISSUE TITLE
kitty is quite slow via tigervnc, draws 50% CPU time of all 8 cores

### ISSUE THREAD

**Issue by michaeltraxler** [kovidgoyal/kitty#978]
Hi, if using kitty (great piece of software, by the way!) via vnc (tigervnc-server), the responsiveness experienced on a local X11-screen is completely gone.
When using a fast keyboard rate (xset r rate 200 120) and just pressing a key permanently, will draw 50% CPU of each of the 8 cores I have. This even happens if the vncserver is running locally on the same computer.
I also tried my best with the  input_delay, repaint_delay, sync_to_monitor, but no change.
opengl via tigervnc is also not really a problem, as I can run glxgears with 2000fps with the standard size.
The issue doesn't occur with xterm, urxvt, qterminal, konsole.
Any idea what can be done to use kitty also fast and with low CPU usage via vnc?
Thanks,
Michael

**Comment by kovidgoyal** [comment]
The way rendering in kitty works is by redrawing the entire window on every update. This si very cheap to do via the GPU. Much cheaper than doing things like calculating only what has changed and rendering that. That is probably why it is slow via VNC, since it has to do full screen updates for each frame. I'm afraid I dont see any practical way to change that.

Also more generally speaking, why do you need to vnc into a computer to run a terminal? Just ssh in instead. With regard to running kitty on remote computers, there is also #391
