### ISSUE TITLE
Tuchscreen Scrolling

### ISSUE THREAD

**Issue by GladOSkar** [kovidgoyal/kitty#984]
I would love to be able to scroll using my touchscreen.

I know no other terminal emulator does this, but i think it would be more useful than just marking text as the default mouse emulation mode does it.

I don't know how hard this would be, but i may look into it myself.

**Comment by maximbaz** [comment]
Are you suggesting that the fix should be on OS level? This would be cool, for example I remember Firefox struggling from this exact issue at some point, not sure if this is possible to configure though...

**Comment by kovidgoyal** [comment]
So if you do want to work on adding general touchscreen support to glfw so that it can be used in kitty, you can work off the embedded glfw in kitty (see glfw subdirectory). I dont know what platform you are using, look for files starting with cocoa_* for apple, x11_* for X11 and wl_* for wayland.

Feel free to ask if you have any questions, I will try to help as best I can. I'm closing this issue since I at least am not interested in doing the work for it. But feel free to continue using it to discuss. If someone starts working on this support I prefer to track it via a PR rather than an issue.

**Comment by al1-ce** [comment]
Leaving a note
From what I've gathered currently glfw has PRs implementing touch in win and wayland, plus cocoa in fork
https://github.com/elmindreda/glfw/tree/multitouch-input
Here is link to fork branch of glfw dev that implements all three
Sadly the dark horse here is x11 since there was no attempts in doing it whatsoever

I tried with my lack of knowlegde to combine and modify some those PRs and one PR adding tablet support, but to no avail
It seems that right now X sends touch input directly to mouse motion event and there might be a very hacky to add touch by polling touch deviceid somewhere and somehow checking event deviceid against it with xinput2 (x extensions) and then passing it as isTouch parameter

Ps:
Also worth noting in my reasearch I found several other terminals that support touchscreens, but support is either poor or terminal is bad, here's what I found:
Alacritty - best support for touch, not best terminal though yet. Touch scroll is done by moving single finger vertically and selection is moving horizontally. I think this is good way to do it here too
Tilix - scroll is insanely fast which is problem of outdated gnome toolkit, otherwise behaves same as gnome
Gnome - scroll is dependant on scrollbar, if it is hidden then no scroll
Konsole - it has touch support but I haven't tested it
Edex-UI and any web-based terminals - it's either hit or miss, still they're web based which isn't best

And so, there's only Alacritty with nice move up/down to scroll, move left/right to select which is good implementation

Now it's only left to wait for someone to add x11 glfw touch support or do it somehow

**Comment by al1-ce** [comment]
Also another hacky way would be to hotwire SDL2 library and poll touch events from it
