### ISSUE TITLE
Unicode Normalization

### ISSUE THREAD

**Issue by ramarnat** [kovidgoyal/kitty#987]
Is there a way to specify the Unicode normalization?

Currently on osx, under certain unicode situations, the command line gobbles up tabs and such. Similar to this issue - https://github.com/fish-shell/fish-shell/issues/474

**Comment by kovidgoyal** [comment]
IMO unicode normalization is not the province of the terminal emulator, but of the software running inside the terminal emulator. The problem is that unicode normalization is retroactive in that it affects previously sent bytes as well as the current byte. If trminal emulators were to implement it, it would mean that they were changing the bytes on the screen behind the back of the application running in the terminal emulator. Doing that is never a good design.

**Comment by ramarnat** [comment]
Would you know why the cursor gets eaten up in the attached example screencapture? I think it is due the normalization, but maybe not. 
![untitled](https://user-images.githubusercontent.com/88762/45959711-8933ee80-bfe8-11e8-9ba6-dd4579871982.jpeg)

**Comment by kovidgoyal** [comment]
Because whatever shell you are running has a different wcwidth() implementation than the on in kitty, which is based on the up-to-date unicode standard. shells often use outdated ones supplied by the host OS
